### PR TITLE
fix(forge): do not reset tx.origin during broadcast in forge script

### LINKED ISSUE #4434: tx.origin are overwritten in forge script
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c5dd9a6 2023-02-26T00:12:08.486636Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm using `forge script` to run transactions and deploy contracts. Usually everything works well but I'm running into an issue where the tx.origin seems to be changing in the middle of a script.
Here is my code:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.18;

import "forge-std/Script.sol";

import { console, Script } from "forge-std/Script.sol";

contract MyScript is Script {
    string network = "local";

    function setUp() public {
        vm.createSelectFork(network);
        uint256 pk = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(pk);
    }

    function run() public {
        ExternalContract ext = new ExternalContract();

        MyContract my = new MyContract();
        my.test(address(ext));

        vm.stopBroadcast();
    }
}

contract MyContract {
    function test(address _external) public {
        ExternalContract ext = ExternalContract(_external);

        console.log(tx.origin);
        ext.extFunc();
        console.log(tx.origin);
    }
}

contract ExternalContract {
    function extFunc() public {}
}
```

The first log shows the correct value: the address generated from the `PRIVATE_KEY` but the second log prints `0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38`

I have `anvil` running and the script is connecting to it.
The command i'm running is `forge script ./script/myscript.s.sol --tc MyScript`
And I have the networks setup in `foundry.toml`:
```
fs_permissions = [{ access = "read", path = ".env"}]

[rpc_endpoints]
local = "http://127.0.0.1:8545"
```

### PR DESCRIPTION
**Pull request by teddav**
This PR fixes #4434 
In `forge script` during a broadcast, from within a call, if a call is made to another contract, or if a contract is created, the `new_origin` is reset to the original `original_origin` which basically means that the `tx.origin` is not the "broadcaster" anymore.
This is because before resetting, the depth of the call was not checked.
This should fix it.

I wrote a test to go with it. It's pretty simple. Let me know if I should write more tests.  
The test is entirely written in the test file `script.rs`. I saw that there is a `Broadcast.t.sol` which seems to be used for test. I can also move it there if it's better.

### CODE REVIEW

File: evm/src/executor/inspector/cheatcodes/mod.rs [hunk 1]
```diff
@@ -727,7 +729,9 @@ where
 
         // Clean up broadcasts
         if let Some(broadcast) = &self.broadcast {
-            data.env.tx.caller = broadcast.original_origin;
+            if data.journaled_state.depth() == broadcast.depth {
+                data.env.tx.caller = broadcast.original_origin;
+            }
```
Comment (mattsse) [inline evm/src/executor/inspector/cheatcodes/mod.rs:734]: this looks correct

**Review by mattsse — APPROVED** [review]
awesome, tysm.

love the test

**Comment by SuperHero123123** [comment]
great work, thanks!

File: evm/src/executor/inspector/cheatcodes/mod.rs (hunk 1 above)
Comment (gatleas17) [reply evm/src/executor/inspector/cheatcodes/mod.rs:734]: thx

**Comment by olawale-york** [comment]
This doesn't seem to be the case only for scripts. I am experiencing the same issue with a test contract within the setup. 

If my test contracts setup looks like this:
contract AssurTest{
function setUp() public {
        insuree = vm.addr(0x123);
        insurer = vm.addr(0x456);
        arbitor = vm.addr(4);
        dispute = new Dispute();
        vault = new VaultTestable(address(dispute));
        vm.startPrank(address(this), address(this));
        vault.grantComptrollerRole(address(assurance));
        vm.stopPrank();
    }
    }
However, when the setup then becomes like this:
function setUp() public {
        insuree = vm.addr(0x123);
        insurer = vm.addr(0x456);
        arbitor = vm.addr(4);
        dispute = new Dispute();
        vault = new VaultTestable(address(dispute));
        assurance = new AssuranceTestable(address(vault), address(dispute));
        vm.startPrank(address(this), address(this));
        vault.grantComptrollerRole(address(assurance));
        vm.stopPrank();
    }
    
    The prank doesn't work and it reverts the tx.origin back to foundry's default sender. I don't understand what specific difference this line of code is making:  `assurance = new AssuranceTestable(address(vault), address(dispute));` but it makes it revert to the defaultSender. Is there anything I can do to fix tis issue
