### PR TITLE
fix(forge): handle error if etherscan identifier cannot resolve config

### LINKED ISSUE #11351: Scripting bug in foundry v1.3.1
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

1.3.1

### What version of Foundryup are you on?

1.3.0

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

To reproduce:
Do everything described in https://getfoundry.sh/guides/scripting-with-solidity
When I have in `foundry.toml`
```
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
```
and in `.env`
```
ETHERSCAN_API_KEY=<my key>
```
and run
```
forge script script/Counter.s.sol:CounterScript --fork-url http://localhost:8545 --broadcast --interactives 1
```

I'm getting error
```
forge script script/Counter.s.sol:CounterScript --fork-url http://localhost:8545 --broadcast --interactives 1

[⠊] Compiling...
No files changed, compilation skipped
Enter private key:
Error: No known Etherscan API URL for chain `anvil-hardhat`. To fix this, please:
1. Specify a `url` 
2. Verify the chain `anvil-hardhat` is correct
```

I think this PR caused the error: https://github.com/foundry-rs/foundry/pull/11194

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- regression introduced with https://github.com/foundry-rs/foundry/pull/11194
- closes #11351 

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by 0xrusowsky — DISMISSED** [review]
not familiar with the etherscan setup yet, but given the provided ctx, i think it makes sense

File: crates/evm/traces/src/identifier/etherscan.rs [hunk 1]
```diff
@@ -44,9 +44,11 @@ impl EtherscanIdentifier {
         if config.offline {
             return Ok(None);
         }
-        let Some(config) = config.get_etherscan_config_with_chain(chain)? else {
+
+        let Ok(Some(config)) = config.get_etherscan_config_with_chain(chain) else {
```
Comment (DaniPopes) [inline crates/evm/traces/src/identifier/etherscan.rs]: let's log the error to `warn!` at least

Comment (grandizzy) [reply crates/evm/traces/src/identifier/etherscan.rs]: added in https://github.com/foundry-rs/foundry/pull/11356/commits/7f767c5492253f5c721ffded408bc2dad5a76d44

**Review by DaniPopes — APPROVED** [review]
