### PR TITLE
fix: use network-specific BaseFeeParams for Optimism in Anvil

### LINKED ISSUE #12943: Anvil uses Ethereum base fee params for Optimism instead of Canyon params
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.5.0-stable Commit SHA: 1c57854462289b2e71ee7654cd6666217ed86ffd Build Timestamp: 2025-11-26T09:16:58.269730000Z (1764148618) Build Profile: maxperf

### What version of Foundryup are you on?

foundryup: 1.5.0

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

# Problem

Anvil currently hardcodes `BaseFeeParams::ethereum()` for all EIP-1559 base fee calculations, even when running in Optimism mode (`--optimism` flag). This causes incorrect base fee adjustments for Optimism networks.

# Expected Behavior

When running with `--optimism`, Anvil should use `BaseFeeParams::optimism_canyon()` which has different parameters.

# Current Behavior

Anvil always uses Ethereum's params (12.5% max change) regardless of the `--optimism` flag, resulting in base fee adjustments that don't match the actual Optimism network behavior.

### PR DESCRIPTION
**Pull request by haythemsellami**
## Motivation

fix: use network-specific BaseFeeParams for Optimism in Anvil.

Closes #12943.

## Solution

This PR fixes Anvil to use BaseFeeParams::optimism_canyon() when running in Optimism mode instead of always using Ethereum's parameters.

Changes:
  - crates/anvil/src/eth/fees.rs
    - Added base_fee_params field to FeeManager
    - Updated new() to accept network-specific BaseFeeParams
    - Added base_fee_params() getter
    - get_next_block_base_fee_per_gas() now uses stored params
    - Removed unused default_elasticity() function
    - Added doc comment to calculate_next_block_base_fee() clarifying it uses Ethereum params
  - crates/anvil/src/config.rs
    - Select BaseFeeParams::optimism_canyon() when is_optimism() is true
  - crates/anvil/src/eth/backend/mem/mod.rs
    - Use self.fees.base_fee_params() in block simulation instead of hardcoded Ethereum params
  - crates/anvil/tests/it/optimism.rs
    - Added test_optimism_base_fee_params() to verify correct params are used

## PR Checklist

- [x] Added Tests
- [x] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/anvil/src/config.rs [hunk 1]
```diff
@@ -1094,13 +1094,20 @@ impl NodeConfig {
             self.networks,
         );
 
+        let base_fee_params = if self.networks.is_optimism() {
```
Comment (grandizzy) [inline crates/anvil/src/config.rs]: I suggest to move this in `self.networks.base_fee_params()` fn

File: crates/anvil/src/config.rs [hunk 2]
```diff
@@ -1094,13 +1094,20 @@ impl NodeConfig {
...
+            BaseFeeParams::optimism_canyon()
```
Comment (grandizzy) [inline crates/anvil/src/config.rs]: should we try figuring out the optimisim hardfork in order to apply such? (not sure it has any value though but for backwards compatibility maybe) https://github.com/alloy-rs/hardforks/blob/bef91264a05e8a26711913a247cf9d6377fe80d8/crates/op-hardforks/src/lib.rs#L59

File: crates/anvil/src/config.rs (hunk 1 above)
Comment (haythemsellami) [reply crates/anvil/src/config.rs]: Updated.

File: crates/anvil/src/config.rs (hunk 2 above)
Comment (haythemsellami) [reply crates/anvil/src/config.rs]: Updated.

File: crates/evm/networks/src/lib.rs [hunk 3]
```diff
@@ -47,6 +49,23 @@ impl NetworkConfigs {
         self.optimism
     }
 
+    /// Returns the base fee parameters for the configured network.
+    ///
+    /// For Optimism networks, returns Canyon parameters if the Canyon hardfork is active
+    /// at the given timestamp, otherwise returns pre-Canyon parameters.
+    pub fn base_fee_params(&self, timestamp: u64) -> BaseFeeParams {
```
Comment (mattsse) [inline crates/evm/networks/src/lib.rs:56]: this makes sense

**Review by mattsse — APPROVED** [review]
makes sense, ty!

**Comment by mattsse** [comment]
there's perhaps one more thing which we could tackle here or in a followup pr.

for forked anvil, on opstack we should extract the basefeeparams from the header's extradata past holocene
