### PR TITLE
fix(cheatcode): expect revert only for calls with greater depth than test

### LINKED ISSUE #3437: Test function early returns after `vm.expectRevert`
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d7733ee 2022-10-03T00:06:06.841223Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

```solidity
pragma solidity 0.8.4;

import "forge-std/Test.sol";

contract ContractTest is Test {
    function setUp() public {}

    function rever() internal {
        revert();
    }

    function testExample() public {
        vm.expectRevert();
        rever();

        rever();
        console.log("Does not print");
    }
}
```
Running `forge test -vvv` passes this test and also doesn't print "Does not print" on console. In summary, after `vm.expectRevert()` the test just executes the call and does not run the remaining test.

### LINKED ISSUE #3723: Forge doesn't work with multiple "vm.expectRevert" when testing free functions
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cb925b1 2022-11-21T00:09:19.970948Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Given the following test:

```solidity
function testMultipleReverts() public {
    vm.expectRevert();
    revert();

    vm.expectRevert();
    console2.log("Do not revert");
}
```

Forge will consider the test to be passed, even if it should be failed, because there is no second revert.

### LINKED ISSUE #7238: feat(`cheatcodes`): V1 `expectRevert` behavior
## Motivation

`expect*` cheatcodes are ALL intended to function only for the _next call_. That means, if the next call does not fulfill the `expect*` set up before making it, tests should fail. However, this is not the case for `expectRevert` works right now.

See: #3723, #3437, #4832 .

`expectRevert`, since inception, works differently from intended: it matches reverts at the _test_ level, not at the _next call_ level. This means that reverting cheatcodes were being incorrectly catched by `expectRevert` (we're supposed to bypass checks for cheatcode calls) and also led users to use cheatcode incorrectly as illustrated in #3723, sometimes becoming actual accepted foundry patterns. It also meant that, if used to catch any revert without matching revert data, any revert at any point in the test after the `expectRevert` cheatcode was used could make the test pass. This is especially dangerous as it can hide actual code failures from intended reverts.

## New behavior

`expectRevert` now only works on the next `CALL`. Cheatcode calls are now ignored properly, _even if those cheatcode calls revert_. To illustrate, after introducing this new behavior, these are examples of now both passing and failing tests:

```solidity
// OK
function testExpectRevertString() public {
    Reverter reverter = new Reverter();
    cheats.expectRevert("revert");
    reverter.revertWithMessage("revert");
}

// FAIL
function testFailRevertNotOnImmediateNextCall() public {
    Reverter reverter = new Reverter();
    // expectRevert should only work for the next call. However,
    // we do not inmediately revert, so,
    // we fail.
    cheats.expectRevert("revert");
    reverter.doNotRevert();
    reverter.revertWithMessage("revert");
}

// FAIL
function testFailCheatcodeRevert() public {
  // This expectRevert is hanging, as the next cheatcode call is ignored.
  vm.expectRevert();
  vm.fsMetadata(fakePath) // try to go to some non-existent path to cause a revert
}
```

</p>
</details>

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #3723
Closes #7238 
Closes #3437 

Breaking change, should be merged after pinned version.

- record max depth of next call after `expectRevert`, compares with test depth (at which cheatcode was added). Does not apply for `_expectCheatcodeRevert` calls.
- add `allow_internal_expect_revert` config to enable expect reverts for internal calls. defaults to false
- fix and add tests

### CODE REVIEW

File: crates/cheatcodes/src/inspector.rs [hunk 1]
```diff
@@ -1175,6 +1177,11 @@ impl Inspector<&mut dyn DatabaseExt> for Cheatcodes {
         if self.gas_metering.paused {
             self.gas_metering.paused_frames.push(interpreter.gas);
         }
+
+        // `expectRevert`: track the max call depth during `expectRevert`
+        if let Some(ref mut expected) = self.expected_revert {
```
Comment (mattsse) [inline crates/cheatcodes/src/inspector.rs:1182]: make @DaniPopes happy hehe
```suggestion
        if let Some(expected) = &mut self.expected_revert {
```

File: testdata/default/cheats/AttachDelegation.t.sol [hunk 2]
```diff
@@ -86,6 +86,7 @@ contract AttachDelegationTest is DSTest {
         assertEq(token.balanceOf(bob), 200);
     }
 
+    /// forge-config: default.allow_internal_expect_revert = true
```
Comment (mattsse) [inline testdata/default/cheats/AttachDelegation.t.sol:89]: unrelated, pretty cool that this works

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by holic** [comment]
Just spotted some test failures in [MUD](https://github.com/latticexyz/mud) due to this change. (We intentionally use nightly in CI to make sure we're always ready for latest/upcoming foundry, to flag situations like this.)

MUD makes extensive use of internal libraries and free functions, but it's sort of unclear if the test failures we're seeing are intended. Wanted to check in before we enable the `allow_internal_expect_revert` config option across our repo + downstream user projects.

For example, this failing test:
https://github.com/latticexyz/mud/actions/runs/13013139151/job/36295534363
```
packages/schema-type test:ci: Encountered 1 failing test in test/solidity/SchemaType.t.sol:SchemaTypeTest
packages/schema-type test:ci: [FAIL: call didn't revert at a lower depth than cheatcode call depth] testSchemaTypeOverMaxLength() (gas: 3591)
```

Comes from a revert in this free function bound to a user type:
https://github.com/latticexyz/mud/blob/main/packages/schema-type/src/solidity/SchemaType.sol

Seems like any test that uses `expectRevert` for an operation that calls an internal/free function with a revert now fails with this new default. Maybe this is fine/expected, just want to know what the suggested best practice is going forward with these new defaults.

**Comment by grandizzy** [comment]
@holic yes, that's correct, free internal/free function with expect revert now fails. You can turn on the old behavior by setting `allow_internal_expect_revert = true` if you are aware that test stops executing after first expectRevert  (see https://github.com/foundry-rs/foundry/issues/3437)
