### PR TITLE
fix: `eth_feeHistory`

### LINKED ISSUE #7769: anvil: problems with estimate gas - max fee per gas less than block base fee
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-008922d5165c764859bc540d7298045eebf5bc60

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon) / Linux (x86)

### Describe the bug

I'm aware of https://github.com/foundry-rs/foundry/pull/7638 and the corresponding issues. I have a very similar problem, but when interacting with anvil. We use hardhat to manage contract deployment + sending txs. We use anvil as a drop in replacement for the hardhat node. this worked up until nightly-460319558e455611be1de64be8364c65c6896d15 (as mentioned in https://github.com/foundry-rs/foundry/issues/7620). the hardhat code also works with deployed evm chains (ie Arbitrum), therefore I think that recent anvil change has made eth_estimateGas lose parity w/ deployed chains. 

Perhaps: https://github.com/foundry-rs/foundry/pull/7515

This is the error message i get from hardhat:

```
ProviderError: max fee per gas less than block base fee
```

my current fix is using an older anvil version: nightly-2cb875799419c907cc3709e586ece2559e6b340e

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

Closes #7769 

Logic for determining pending block base fee is currently different in `eth_feeHistory` handler and miner itself. Thus, using value for pending block base fee returned by `feeHistory` will result in errors as it will be lower than actual base fee

This PR contains 2 changes:
1. Correctly process empty genesis block, thus base fee for 1st block is `87500000000` by default as genesis block is always empty.
2. Use alloy calculation fn in `eth_feeHistory`.

### CODE REVIEW

File: crates/anvil/src/eth/api.rs [hunk 1]
```diff
@@ -1317,25 +1319,14 @@ impl EthApi {
...
-                // same base gas
-                response.base_fee_per_gas.push(last_fee_per_gas as u128);
-            }
+        if let Some(block) = last_block {
+            let next_base_fee = calc_next_block_base_fee(
+                block.gas_used,
+                block.gas_limit,
+                block.base_fee,
+                BaseFeeParams::ethereum(),
+            );
```
Comment (mattsse) [inline crates/anvil/src/eth/api.rs:1328]: nice

File: crates/anvil/src/eth/fees.rs [hunk 2]
```diff
@@ -108,6 +109,7 @@ impl FeeManager {
     /// Returns the current base fee
     pub fn set_base_fee(&self, fee: u128) {
         trace!(target: "backend::fees", "updated base fee {:?}", fee);
+        println!("SETTINGS BASE FEE {:?}", fee);
```
Comment (mattsse) [inline crates/anvil/src/eth/fees.rs:112]:
```suggestion
```

**Review by mattsse — APPROVED** [review]
I see, nice find!

**Comment by klkvr** [comment]
@mattsse decided to go with a simpler fix and just push the `backend.fees().base_fee()` value to the response. don't think we should account for empty genesis as I believe users would expect block #1 base fee to be equal to the `--base-fee` flag value if provided, which is something we are breaking by accounting for genesis

File: crates/anvil/src/eth/backend/mem/mod.rs [hunk 3]
```diff
@@ -1055,12 +1055,12 @@ impl Backend {
...
 
-        // notify all listeners
-        self.notify_on_new_block(header, block_hash);
-
         // update next base fee
         self.fees.set_base_fee(next_block_base_fee);
 
+        // notify all listeners
+        self.notify_on_new_block(header, block_hash);
+
```
Comment (klkvr) [inline crates/anvil/src/eth/backend/mem/mod.rs:1063]: this was a subject to race condition anyway, but this just ensures that value in `fees` is always up to date

Comment (mattsse) [reply crates/anvil/src/eth/backend/mem/mod.rs:1063]: right, nice catch

**Review by mattsse — APPROVED** [review]
