### PR TITLE
fix(forge): trace identify by creation code with stripped args

### LINKED ISSUE #8465: bug(`forge script`): buffer overrun while deserializing
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (af97b2c 2024-07-18T00:22:15.301937000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I'm trying deploying the contract with `forge script`, it crashes.

Script is like: 
```
address constant ZERO = address(0xc0b0);
address dummy = new MyContract(ZERO, ZERO);
```

Error message:
```
[⠒] Compiling...
No files changed, compilation skipped
Enter keystore password:
Script ran successfully.

## Setting up 1 EVM.
2024-07-18T03:08:39.237259Z ERROR forge_script::transaction: Failed to decode constructor arguments contract=Some("MyContract") signature=constructor(address,address) is_create2=false constructor_args=0000000000000000000000c0b0000000000000000000000000000000000000000000000000000000000000c0b0
Error: 
buffer overrun while deserializing

Context:
- buffer overrun while deserializing
```

It looks like the `constructor_args`, which should be 64 bytes but 45 byte here, is incorrectly sliced.

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #8465 
- tested with https://github.com/worldcoin/world-chain/tree/osiris/buffer-overrun-poc/contracts (see https://github.com/foundry-rs/foundry/issues/8465#issuecomment-2766941472). Too large to include as a unit test
- similar with https://github.com/foundry-rs/foundry/pull/10270 but checking ctor args in trace identify code

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/evm/traces/src/identifier/local.rs [hunk 1]
```diff
@@ -53,6 +54,19 @@ impl<'a> LocalTraceIdentifier<'a> {
...
             if let Some(bytecode) = contract_bytecode {
+                let mut current_bytecode = current_bytecode;
+                if is_creation && current_bytecode.len() > bytecode.len() {
+                    // Try to decode ctor args with contract abi.
+                    if let Some(constructor) = contract.abi.constructor() {
+                        let constructor_args = &current_bytecode[bytecode.len()..];
+                        if constructor.abi_decode_input(constructor_args, false).is_ok() {
+                            // If we can decode args with current abi then remove args from
+                            // code to compare.
+                            current_bytecode = &current_bytecode[..bytecode.len()]
```
Comment (zerosnacks) [inline crates/evm/traces/src/identifier/local.rs:65]: this does assume that the metadata setting / output is the same for both cases but I think that is fair

**Review by zerosnacks — APPROVED** [review]

File: crates/evm/traces/src/identifier/local.rs (hunk 1 above)
Comment (grandizzy) [reply crates/evm/traces/src/identifier/local.rs:65]: yeah, there's a diff score computed next 
```
   let score = bytecode_diff_score(bytecode, current_bytecode);
```

which should catch this

Comment (grandizzy) [reply crates/evm/traces/src/identifier/local.rs:65]: @klkvr can you pls confirm above before merging? thank you!
