### PR TITLE
fix(forge): use etherscan verifier if key provided

### LINKED ISSUE #10056: verifier regression
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

_No response_

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

There seems to be a regression in contract verification.

We have this in our foundry toml
```
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_MAINNET}", chain = 1 }
```
and until recently this just worked with `--verify`.

Now i get a `Attempting to verify on Sourcify. Pass the --etherscan-api-key <API_KEY> to verify on Etherscan, or use the --verifier flag to verify on another provider.` error and it seems like i need to manually supply the key.

---

Perhaps with etherscan api v2 there is no longer any need to fix that, as ppl will use a single key for all chains. Very much looking forward to this.

That said there seems to be another bug in regard to etherscan. Even if I specify --verifier etherscan, on avalanche it will verify on routescan.

Idk if that helps but for our internal tooling at bgd we currently fetch explorer support via:
https://cdn-canary.routescan.io/api/evm/all/explorers and
https://api.etherscan.io/v2/chainlist

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #10056  : since Sourcify is default now it should check also if an API Key was provided. If so, then should not verify on Sourcify but continue checking and will eventually be set as etherscan
- the test suites (that deploy and verify contracts) are not performed by CI as they need private keys, so should be run locally (might look into running them with gh secrets as part of CI but would add additional time and effort to manage those accounts)

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/verify/src/etherscan/mod.rs [hunk 1]
```diff
@@ -278,8 +278,14 @@ impl EtherscanVerificationProvider {
         builder = if let Some(api_url) = api_url {
             // we don't want any trailing slashes because this can cause cloudflare issues: <https://github.com/foundry-rs/foundry/pull/6079>
             let api_url = api_url.trim_end_matches('/');
-            let base_url = if *verifier_type != VerificationProviderType::Etherscan {
-                // If verifier is not Etherscan then set base url as api url without trialing /api.
+
+            // Verifier is etherscan if explicitly set or if no verifier set (default sourcify) but
+            // API key passed.
+            let is_etherscan = matches!(verifier_type, VerificationProviderType::Etherscan) ||
+                (matches!(verifier_type, VerificationProviderType::Sourcify) &&
```
Comment (mattsse) [inline crates/verify/src/etherscan/mod.rs:285]: nit: can we replace this with `fn is_etherscan` and `is_sourcify` then this statement becomes easier

**Review by mattsse — APPROVED** [review]
checks out, smol style suggestion

File: crates/verify/src/etherscan/mod.rs (hunk 1 above)
Comment (grandizzy) [reply crates/verify/src/etherscan/mod.rs]: nice! added in https://github.com/foundry-rs/foundry/pull/10058/commits/22d45608cf12fc2e52fe73f006ad143a020090ec

**Review by mattsse — APPROVED** [review]

**Comment by kuzdogan** [comment]
Why turn off Sourcify and not verify on Sourcify in parallel regardless? 🙃

**Comment by grandizzy** [comment]
we don't have logic for running multiple verifiers at the same time but would be great to add such

**Comment by kuzdogan** [comment]
I'd very much like to see this happen, I've been shilling this idea for a while :) 

We already do this with the new Remix verification plugin 

https://x.com/SourcifyEth/status/1849450860600021229
https://remix-ide.readthedocs.io/en/latest/contract_verification.html
