### PR TITLE
fix(traces): Etherscan traces are only resolved for first instance of test run

### LINKED ISSUE #7558: Etherscan traces are only resolved for first instance of test run
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

_No response_

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

It appears that Etherscan traces are only applied once, on the first trace rather than across all.

Given the same test function ran twice:

```
[PASS] testForkGetPriceA() (gas: 27345)
Logs:
  Price A: 335172810074

Traces:
  [27345] ForkingTest::testForkGetPriceA()
    ├─ [15735] EACAggregatorProxy::latestRoundData() [staticcall]
    │   ├─ [7502] AccessControlledOffchainAggregator::latestRoundData() [staticcall]
    │   │   └─ ← [Return] 14720 [1.472e4], 335172810074 [3.351e11], 1712226143 [1.712e9], 1712226143 [1.712e9], 14720 [1.472e4]
    │   └─ ← [Return] 110680464442257324416 [1.106e20], 335172810074 [3.351e11], 1712226143 [1.712e9], 1712226143 [1.712e9], 110680464442257324416 [1.106e20]
    ├─ [0] console::log("Price A: %d", 335172810074 [3.351e11]) [staticcall]
    │   └─ ← [Stop] 
    └─ ← [Stop] 

[PASS] testForkGetPriceB() (gas: 27367)
Logs:
  Price B: 335172810074

Traces:
  [27367] ForkingTest::testForkGetPriceB()
    ├─ [15735] 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419::latestRoundData() [staticcall]
    │   ├─ [7502] 0xE62B71cf983019BFf55bC83B48601ce8419650CC::latestRoundData() [staticcall]
    │   │   └─ ← [Return] 14720 [1.472e4], 335172810074 [3.351e11], 1712226143 [1.712e9], 1712226143 [1.712e9], 14720 [1.472e4]
    │   └─ ← [Return] 110680464442257324416 [1.106e20], 335172810074 [3.351e11], 1712226143 [1.712e9], 1712226143 [1.712e9], 110680464442257324416 [1.106e20]
    ├─ [0] console::log("Price B: %d", 335172810074 [3.351e11]) [staticcall]
    │   └─ ← [Stop] 
    └─ ← [Stop] 
```

Notice it resolves `0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419` to `EACAggregatorProxy` and `0xE62B71cf983019BFf55bC83B48601ce8419650CC` to `AccessControlledOffchainAggregator` for the first test A but not for the second test B. The internals of the function are the exact same.

Minimal repro: https://github.com/zerosnacks/foundry-repro-7558

### PR DESCRIPTION
**Pull request by zerosnacks**
## Motivation

Closes #7558 

Currently the resolved Etherscan traces are only applied to the first occurrence of an address due to the resolved addresses not being captured and returned, see:

https://github.com/foundry-rs/foundry/blob/ee47bb01ee8aa042639cc9ae86a2a3cf6ab9d037/crates/evm/traces/src/identifier/etherscan.rs#L114-L118

## Solution

Reproducible by running minimal repro: https://github.com/zerosnacks/foundry-repro-7558

Implementation is largely pragmatic, emphasis on minimal changes - open to feedback

### CODE REVIEW

File: crates/evm/traces/src/identifier/etherscan.rs [hunk 1]
```diff
@@ -112,11 +113,30 @@ impl TraceIdentifier for EtherscanIdentifier {
...
+
+                AddressIdentity {
+                    address: addr,
+                    label: Some(label.clone()),
+                    contract: Some(label),
+                    abi,
+                    artifact_id: None,
+                }
+            })
+            .collect::<Vec<AddressIdentity<'_>>>();
```
Comment (mattsse) [inline crates/evm/traces/src/identifier/etherscan.rs:138]: this can be done in the for loop above?

so that we track `AddressIdentity` in resolved?

**Review by mattsse — CHANGES_REQUESTED** [review]
smol suggestion

File: crates/evm/traces/src/identifier/etherscan.rs (hunk 1 above)
Comment (zerosnacks) [reply crates/evm/traces/src/identifier/etherscan.rs]: Good point, updated

**Review by mattsse — APPROVED** [review]
