### PR TITLE
fix(forge): fix external call gas metering cheats

### LINKED ISSUE #3858: EvmError: OutOfGas with combination: vm.pauseGasMetering(), vm.rollFork()
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b1fe58 2022-12-08T00:15:07.729566Z)

### What command(s) is the bug in?

forge script scripts/GMXHistoricalJSON.s.sol

### Operating System

macOS (Intel)

### Describe the bug

After applying the `vm.pauseGasMetering()` and using together with `vm.rollFork()` I get error right after any contract call, example of the trace:

```
Traces:
  [2971690] → new GMXHistorical@0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
    ├─ [0] VM::envUint(START) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::envUint(END) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::envUint(INTERVAL) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::envString(NETWORK) [staticcall]
    │   └─ ← <env var value>
    └─ ← 14266 bytes of code

  [9223372036854775807] GMXHistorical::run()
    ├─ [0] VM::rpcUrl(avax) [staticcall]
    │   └─ ← https://api.avax.network/ext/bc/C/rpc
    ├─ [0] VM::createSelectFork(https://api.avax.network/ext/bc/C/rpc, 22968009)
    │   └─ ← 0
    ├─ [0] VM::rollFork(22968010)
    │   └─ ← ()
    ├─ [0] VM::pauseGasMetering()
    │   └─ ← ()
    ├─ [464448] 0x9ab2De34A33fB459b538c43f251eB825645e8595::allWhitelistedTokensLength() [staticcall]
    │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000007
    └─ ← "EvmError: OutOfGas"


Gas used: 9223372036854775807
Error:
Script failed.
```

### PR DESCRIPTION
**Pull request by brockelmore**
## Motivation
fix #3858
fix https://github.com/foundry-rs/forge-std/issues/257

## Solution
Due to this: https://github.com/bluealloy/revm/blob/2cb991091d32330cfe085320891737186947ce5a/crates/revm/src/evm_impl.rs#L190

when making external calls, there is a returned amount of gas that would cause an underflow when trying to return. This actually popped its head up as a `OutOfGas` overhead in some situations. So in the case that gas metering is off, and we are returning from an execution frame, we just set the gas to a `new` with 0 values for everything. This makes the above make no adjustments

### CODE REVIEW

File: evm/src/executor/inspector/cheatcodes/mod.rs [hunk 1]
```diff
@@ -278,8 +278,21 @@ where
...
             Some(Some(gas)) => {
-                // dont monitor gas changes, keep it constant
-                interpreter.gas = gas;
+                match interpreter.contract.bytecode.bytecode()[interpreter.program_counter()] {
+                    opcode::STOP | opcode::RETURN | opcode::SELFDESTRUCT | opcode::REVERT => {
+                        // If we are ending current execution frame, we want to just fully reset gas
+                        // otherwise weird things with returning gas from a call happen
+                        // ref: https://github.com/bluealloy/revm/blob/2cb991091d32330cfe085320891737186947ce5a/crates/revm/src/evm_impl.rs#L190
+                        //
+                        // It would be nice if we had access to the interpreter in `call_end`, as we
```
Comment (gakonst) [inline evm/src/executor/inspector/cheatcodes/mod.rs:287]: cc @rakita

**Review by gakonst — APPROVED** [review]
Looks good

**Comment by rakita** [comment]
There was bug report for underflow, it is fixed here: https://github.com/bluealloy/revm/commit/54e033355a80daa5863d503c8b05c486b1d18639

File: evm/src/executor/inspector/cheatcodes/mod.rs (hunk 1 above)
Comment (rakita) [reply evm/src/executor/inspector/cheatcodes/mod.rs:287]: This is maybe tricky to do, fn for `call_end` is inside Host trait, it does not have interpretor.

**Review by gakonst — APPROVED** [review]
