### PR TITLE
fix(`remappings`): Only append new lower-priority remappings if they do not exist

### LINKED ISSUE #5540: forge can prioritize autogenerated remappigns over the user ones
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2d87c0c 2023-08-04T00:24:28.478338727Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

If an import matches an autogenerated remapping and one provided by the user, the autogenerated one can take precedence, resulting in compilation errors.

I created [this repository](https://github.com/alcuadrado/foundry-custom-remappings-priority) to reproduce it.

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

Closes #5540 

As discussed in the issue, we were doing two things wrong:
- Sorting (therefore losing all priority)
- Inserting remappings that might conflict with other remappings that might not be "closer" but are higher priority.

## Solution

We now do not sort, and only insert if the remapping name has not been seen before.

### CODE REVIEW

File: config/src/providers/remappings.rs [hunk 1]
```diff
@@ -12,6 +12,35 @@ use std::{
 };
 use tracing::trace;
 
+/// Helper type for extendable remappings
+/// that can only be extended with remappings that don't overlap with existing ones.
+type Remappings = Vec<Remapping>;
```
Comment (mattsse) [inline config/src/providers/remappings.rs:17]: I really dislike these aliases, they just obfuscate things

File: config/src/providers/remappings.rs [hunk 2]
```diff
@@ -12,6 +12,35 @@ use std::{
...
+
+/// Helper trait for extendable remappings where the remappings can only be extended with
+/// remappings that don't overlap with existing ones.
+trait ExtendableRemappings {
+    fn extend_remappings<T>(&mut self, remappings: T)
+    where
+        T: IntoIterator<Item = Remapping>;
```
Comment (mattsse) [inline config/src/providers/remappings.rs:24]: the new type should just have a push function which only pushes if not contains, 

and then extend which calls push for each entry in the iter

**Review by mattsse — CHANGES_REQUESTED** [review]
I'd prefer a new type wrapper for this.

we also need to do this in the coreargs provider impl which also uses sort+dedup

File: config/src/providers/remappings.rs [hunk 3]
```diff
@@ -116,20 +152,24 @@ impl<'a> RemappingsProvider<'a> {
...
+                        })
+                    })
+                    .collect(),
+            );
         }
 
         // remove duplicates at this point
-        new_remappings.sort_by(|a, b| (&a.context, &a.name).cmp(&(&b.context, &b.name)));
-        new_remappings.dedup_by(|a, b| (&a.context, &a.name).eq(&(&b.context, &b.name)));
+        new_remappings.remappings.dedup_by(|a, b| (&a.context, &a.name).eq(&(&b.context, &b.name)));
```
Comment (Evalir) [inline config/src/providers/remappings.rs:170]: thought about wrapping `dedupy_by`, but decided against, happy to do so

File: config/src/providers/remappings.rs [hunk 4]
```diff
@@ -6,12 +6,46 @@ use figment::{
...
+    }
+
+    /// Create a new `Remappings` wrapper with a vector of remappings.
+    pub fn new_with_remappings(remappings: Vec<Remapping>) -> Self {
+        Self { remappings }
+    }
+
+    /// Push an element ot the remappings vector, but only if it's not already present.
+    pub fn push(&mut self, remapping: Remapping) {
+        if self.remappings.iter().any(|existing| existing.name.contains(&remapping.name)) {
```
Comment (mattsse) [inline config/src/providers/remappings.rs:35]: I don't think is matches the previous dedup behaviour which was dedup by context and path?

File: config/src/providers/remappings.rs [hunk 5]
```diff
@@ -116,20 +150,24 @@ impl<'a> RemappingsProvider<'a> {
...
+                        })
+                    })
+                    .collect(),
+            );
         }
 
         // remove duplicates at this point
-        new_remappings.sort_by(|a, b| (&a.context, &a.name).cmp(&(&b.context, &b.name)));
-        new_remappings.dedup_by(|a, b| (&a.context, &a.name).eq(&(&b.context, &b.name)));
+        new_remappings.remappings.dedup_by(|a, b| (&a.context, &a.name).eq(&(&b.context, &b.name)));
```
Comment (mattsse) [inline config/src/providers/remappings.rs:168]: why do we need to dedup here?
dedup will only work if sorted, which we're no longer doing.
the new type is supposed to handle this

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
