### PR TITLE
fix: cast find-block

### LINKED ISSUE #1286: cast find-block always returns 1
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (64087b5 2022-04-13T00:05:01.629608+00:00)

### What command(s) is the bug in?

cast find-block

### Operating System

_No response_

### Steps to reproduce

```
$ cast  find-block --rpc-url  $ETH_RPC_URL 1649503122
```

### Expected result

Block number closest to given Unix timestamp.

### Actual result

Always `1`

### PR DESCRIPTION
**Pull request by dcposch**
fixes #1286

## Motivation

Fixes `cast find-block`.

## Solution

Fixes broken `Cast::timestamp` function. See #1286 for an example.

## Test

There's already a unit test that could've caught this regression,`finds_block`. However, it requires `ETH_RPC_URL` and skips if that's missing.

Running `ETH_RPC_URL=<valid url> cargo test` fails before this PR, succeeds after.

### CODE REVIEW

File: cli/tests/it/cast.rs [hunk 1]
```diff
@@ -24,5 +24,8 @@ casttest!(finds_block, |_: TestProject, mut cmd: TestCommand| {
     println!("{}", output);
 
     // Expect successful block query
-    assert!(output.contains("6574364"), "{}", output);
```
Comment (dcposch) [inline cli/tests/it/cast.rs:27]: not sure where the old number came from. maybe a testnet?

File: cast/src/lib.rs [hunk 2]
```diff
@@ -340,8 +340,13 @@ where
             false,
         )
         .await?;
-        Ok(U256::from_str_radix(strip_0x(&block_field), 16)
-            .expect("Unable to convert hexadecimal to U256"))
+
+        let ret = if block_field.starts_with("0x") {
+            U256::from_str_radix(strip_0x(&block_field), 16).expect("Unable to convert hex to U256")
+        } else {
+            U256::from_str_radix(&block_field, 10).expect("Unable to convert decimal to U256")
```
Comment (dcposch) [inline cast/src/lib.rs:347]: this is the main fix. `cast` was previously parsing decimal block timestamps as hex, see #1286

**Review by mattsse — APPROVED** [review]
thanks, lgtm
needs nightly formatting `cargo +nightly fmt`
