### PR TITLE
fix(`forge`): catch faulty test constructors

### LINKED ISSUE #9903: Failures in constructor wrongly point to the setUp function
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.0.0-stable Commit SHA: e144b82070619b6e10485c38734b4d4d45aebe04 Build Timestamp: 2025-02-13T20:03:31.026474817Z (1739477011) Build Profile: maxperf

### What version of Foundryup are you on?

foundryup: 1.0.0

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Adding the following constructor to a just initiated Counter forge repository:
```solidity
    constructor() {
        require(false);
    }
```
and doing `forge test`
will ouput:
Image

This can be misleading as there is a `setUp` function, but the revert does not happen in it

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Closes #9903 

## Solution

- Catch contract deployment errors in setUp
- Display test suite failure accordingly
- Test

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/forge/tests/cli/test_cmd.rs [hunk 1]
```diff
@@ -3137,3 +3137,41 @@ Encountered a total of 1 failing tests, 1 tests succeeded
...
+    "#,
+    )
+    .unwrap();
+    prj.add_test(
+        "TestDeploymentFailure",
+        r#"
+import "src/FailingDeployment.sol";
+contract TestDeploymentFailure {
+
+    function setUp() public {
```
Comment (grandizzy) [inline crates/forge/tests/cli/test_cmd.rs:3159]: I *think* he meant adding require in test constructor, asked for clarification here https://github.com/foundry-rs/foundry/issues/9903#issuecomment-2664962152

Comment (yash-atreya) [reply crates/forge/tests/cli/test_cmd.rs:3159]: Got it. Should we keep this behavior as well? Seems useful to pinpoint which deployment failed in setUp when there are multiple.

Comment (grandizzy) [reply crates/forge/tests/cli/test_cmd.rs:3159]: I think that's shown already in traces so not sure if we should add more info here?

Comment (yash-atreya) [reply crates/forge/tests/cli/test_cmd.rs:3159]: Cool

File: crates/forge/src/runner.rs [hunk 2]
```diff
@@ -338,6 +343,23 @@ impl<'a> ContractRunner<'a> {
 
         self.executor.inspector_mut().tracer = prev_tracer;
 
+        // Check if test deployment failed due to reverting `constructor()`
```
Comment (grandizzy) [inline crates/forge/src/runner.rs:346]: IMO it's OK to keep the entire error message here, I suggest merging this one with the setUp() failure one, something like
```rust
        if let Some(setup_reason) = setup.reason.as_ref() {
            let function = if setup_reason.contains("contract deployment failed") {
                "constructor()"
            } else {
                "setUp()"
            };

            // Test contract deployment or setup failed, so we return a single test result
            return SuiteResult::new(
                start.elapsed(),
                [(function.to_string(), TestResult::setup_result(setup))].into(),
                warnings,
            )
        }
```

File: crates/forge/src/runner.rs [hunk 3]
```diff
@@ -158,6 +158,11 @@ impl<'a> ContractRunner<'a> {
             U256::ZERO,
             Some(&self.mcr.revert_decoder),
         );
+
+        if let Err(EvmError::Execution(err)) = &deploy_result {
+            return Ok(TestSetup::failed(format!("contract deployment failed: {err}")));
```
Comment (grandizzy) [inline crates/forge/src/runner.rs]: maybe rename `contract deployment failed` to `test contract deployment failed` for clarity?

**Review by grandizzy — COMMENTED** [review]
left some comments, please check

File: crates/forge/src/runner.rs [hunk 4]
```diff
@@ -158,6 +158,11 @@ impl<'a> ContractRunner<'a> {
             U256::ZERO,
             Some(&self.mcr.revert_decoder),
         );
+
+        if let Err(EvmError::Execution(err)) = &deploy_result {
+            return Ok(TestSetup::failed(format!("TestDeploymentFailed:{err}")));
+        }
```
Comment (DaniPopes) [inline crates/forge/src/runner.rs:164]: this is not right, i would just keep this fn as is

File: crates/forge/src/runner.rs (hunk 2 above)
Comment (DaniPopes) [reply crates/forge/src/runner.rs:346]: it should just be a bool flag on setup result, all we need to change here is the name of the displayed test result

Comment (grandizzy) [reply crates/forge/src/runner.rs:346]: ah, right, much better

File: crates/forge/src/runner.rs (hunk 4 above)
Comment (yash-atreya) [reply crates/forge/src/runner.rs]: [29ad127](https://github.com/foundry-rs/foundry/pull/9909/commits/29ad127d96aebce48adc8376e03a39d1774b9d26)

File: crates/forge/src/runner.rs (hunk 2 above)
Comment (yash-atreya) [reply crates/forge/src/runner.rs]: [29ad127](https://github.com/foundry-rs/foundry/pull/9909/commits/29ad127d96aebce48adc8376e03a39d1774b9d26)

**Review by grandizzy — APPROVED** [review]
lgtm

File: crates/forge/src/result.rs [hunk 5]
```diff
@@ -765,6 +765,8 @@ pub struct TestSetup {
     pub reason: Option<String>,
     /// Whether setup and entire test suite is skipped.
     pub skipped: bool,
+    /// Test Deployment Failure
+    pub deployment_failure: bool,
```
Comment (zerosnacks) [inline crates/forge/src/result.rs:769]:
```suggestion
    /// Whether the test failed to deploy.
    pub deployment_failure: bool,
```

**Review by zerosnacks — APPROVED** [review]
small doc nit - lgtm!

**Review by DaniPopes — APPROVED** [review]
