### PR TITLE
(fix): correctly redact private keys in traces #6995

### LINKED ISSUE #6995: forge script call traces should not print private key.
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (24abca6 2024-01-16T07:35:41.234348345Z)

### What command(s) is the bug in?

forge script

### Operating System

None

### Describe the bug

The call traces will print the private key param of `VM::startBroadcast` and `VM::broadcast`. It may lead to users inadvertently leaking sensitive information.

### PR DESCRIPTION
**Pull request by zerosnacks**
## Motivation

Fixes issue of private keys not being redacted in traces.

Previously there was a [logical error](https://github.com/foundry-rs/foundry/issues/6995#issuecomment-1932377769) causing inputs to not correctly be redacted.

Closes #6995 

## Solution

This change should cover all cheatcode cases where a `private key` is passed (directly or through the `Wallet` struct) or is returned.

This includes missing cases:
- `createWallet(...)`
- `getNonce(Wallet)`
- `signP256(uint256,bytes32)`
- `sign(Wallet,bytes32)`

I've added a parameterized test to verify all cases (incl. exceptions) and in a way so it is easy to maintain.

To be able to quickly check the proposed fixes I've created a minimal repo: https://github.com/zerosnacks/foundry-pr-6995

PS: dummy data included in the test was generated using the dummy private key of `0x90F79bf6EB2c4f870365E785982E1f101E93b906`, one of the Anvil defaults.

### CODE REVIEW

File: crates/evm/traces/src/decoder/mod.rs [hunk 1]
```diff
@@ -560,3 +573,83 @@ fn reconstruct_params(event: &Event, decoded: &DecodedEvent) -> Vec<DynSolValue>
...
+            ("broadcast()", vec![], None), // Ignore: `private key` is not passed.
+            ("startBroadcast(uint256)", vec![], Some(vec!["<pk>".to_string()])),
+            ("startBroadcast()", vec![], None), // Ignore: `private key` is not passed.
+            ("getNonce((address,uint256,uint256,uint256))", vec![], Some(vec!["<pk>".to_string()])),
+            ("getNonce(address)", vec![], None), // Ignore: `address` is public.
+            //
+            // Should redact private key and replace in trace in cases:
+            (
+                "sign(uint256,bytes32)",
+                vec![
```
Comment (DaniPopes) [inline crates/evm/traces/src/decoder/mod.rs:608]: FYI you can just use `alloy_primitives::hex!`

**Review by DaniPopes — APPROVED** [review]
lgtm

**Review by Evalir — APPROVED** [review]

File: crates/evm/traces/src/decoder/mod.rs (hunk 1 above)
Comment (zerosnacks) [reply crates/evm/traces/src/decoder/mod.rs]: Done, unfortunately still have to cast to a `Vec` to keep the test abstraction but should be more readable this way.

**Review by mattsse — APPROVED** [review]
