### PR TITLE
fix(forge): `vm.parseJson` and error while parsing powers of ten

### LINKED ISSUE #5038: vm.parseJson cannot parse powers of ten starting 1e20
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a26edce 2023-05-25T00:12:21.044857000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I was writing some tests using the vm.parseJson to load a dataset. However, I started to encounter errors when I tried to input power of ten in my JSON.

```
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e20)] test_parse_1e20() (gas: 3290)
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e21)] test_parse_1e21() (gas: 3355)
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e42)] test_parse_1e42() (gas: 3421)
```

For repro, I wrote the following test:

<details>
<summary>JsonUint256Test.sol</summary>

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import { Test } from "forge-std/test.sol";

struct Value {
  uint256 value;
}

contract JsonUint256Test is Test {
  /// pass
  function test_parse_maxUint64() public {
    string memory json = '{"value": 18446744073709551615}';
    bytes memory parsed = vm.parseJson(json);
    Value memory data = abi.decode(parsed, (Value));
    assertEq(data.value, 18446744073709551615);
  }

  /// pass
  function test_parse_18446744073709551616000() public {
    string memory json = '{"value": 18446744073709551616000}';
    bytes memory parsed = vm.parseJson(json);
    Value memory data = abi.decode(parsed, (Value));
    assertEq(data.value, 18446744073709551616000);
  }

  /// 1e19 pass
  function test_parse_1e19() public {
    string memory json = '{"value": 10000000000000000000}';
    bytes memory parsed = vm.parseJson(json);
    Value memory data = abi.decode(parsed, (Value));
    assertEq(data.value, 10000000000000000000);
  }

  /// 1e20 fails
  function test_parse_1e20() public {
    string memory json = '{"value": 100000000000000000000}';
    bytes memory parsed = vm.parseJson(json);
    Value memory data = abi.decode(parsed, (Value));
    assertEq(data.value, 1000000000000000000000);
  }

  /// 1e21 fails
  function test_parse_1e21() public {
    string memory json = '{"value": 1000000000000000000000}';
    bytes memory parsed = vm.parseJson(json);
    Value memory data = abi.decode(parsed, (Value));
    assertEq(data.value, 1000000000000000000000);
  }

  /// 1e42 fails
  function test_parse_1e42() public {
    string memory json = '{"value": 1000000000000000000000000000000000000000000}';
    bytes memory parsed = vm.parseJson(json);
    Value memory data = abi.decode(parsed, (Value));
    assertEq(data.value, 1000000000000000000000000000000000000000000);
  }

  /// 1e42+1 pass
  function test_parse_1e42plusOne() public {
    string memory json = '{"value": 1000000000000000000000000000000000000000001}';
    bytes memory parsed = vm.parseJson(json);
    Value memory data = abi.decode(parsed, (Value));
    assertEq(data.value, 1000000000000000000000000000000000000000001);
  }
}
```

</details>

<details>
<summary>forge test output</summary>

```
[⠒] Compiling...
[⠃] Compiling 1 files with 0.8.20
[⠊] Solc 0.8.20 finished in 657.24ms
Compiler run successful!

Running 7 tests for test/game/JsonUint256.t.sol:JsonUint256Test
[PASS] test_parse_18446744073709551616000() (gas: 4236)
[PASS] test_parse_1e19() (gas: 4101)
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e20)] test_parse_1e20() (gas: 3290)
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e21)] test_parse_1e21() (gas: 3355)
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e42)] test_parse_1e42() (gas: 3421)
[PASS] test_parse_1e42plusOne() (gas: 4169)
[PASS] test_parse_maxUint64() (gas: 4101)
Test result: FAILED. 4 passed; 3 failed; finished in 600.58µs

Failing tests:
Encountered 3 failing tests in test/game/JsonUint256.t.sol:JsonUint256Test
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e20)] test_parse_1e20() (gas: 3290)
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e21)] test_parse_1e21() (gas: 3355)
[FAIL. Reason: Failed to parse key "$": Unsupported value: Number(1e42)] test_parse_1e42() (gas: 3421)

Encountered a total of 3 failing tests, 4 tests succeeded
```

</details>

I made the following observations:

1. It seems that the first power of ten that triggers the error is 1e20 (1e19 works).
2. It seems that adding/subbing 1 to the number make it work again (e.g. `100000000000000000001` but not `100000000000000000000`)

### PR DESCRIPTION
**Pull request by xeno097**
Fixes #5038

## Motivation

Parsing powers of ten failed even if the number was a correct json value

## Solution

It seems that `Number::to_string` from `serde_json` formats big numbers powers of 10 to use the scientific notation. After parsing the number to a string and giving it to `U256::from_dec_str` or `U256::from_dec_str`, the conversion failed because the expected string should be in decimal format. 

In any other case, the conversion worked perfectly because `Number::to_string` is not trying to use scientific notation. In order to avoid a wrong string formatting I'm using the floating point representation of the number and then parsing it into string using the `format!` macro. Although this does work for powers of ten, it fails in other scenarios. Common shenanigans found while debugging were the following ones:
- `18446744073709551615` parsed to f64 was rounded up to `18446744073709552000`
- `10000000000000000000000000000000000000000005` parsed to f64 was rounded down to `10000000000000000000000000000000000000000000`
- Calling `Number::to_string` on any power of ten grater than `1e20` stringified it as `1e[number of 0 here]`
So in the end I implemented a hybrid approach that uses the existing logic to parse numbers and then falls back to using floats.

It feels a bit hacky so if someone has a better approach, it'd be very welcome.

### CODE REVIEW

File: evm/src/executor/inspector/cheatcodes/ext.rs [hunk 1]
```diff
@@ -176,16 +176,38 @@ fn value_to_token(value: &Value) -> Result<Token> {
...
+                    // Example: 18446744073709551615 becomes 18446744073709552000 after parsing it
+                    // to f64.
                     let s = number.to_string();
+
+                    // Calling Number::to_string with powers of ten formats the number using
+                    // scientific notation and causes from_dec_str to fail. Using format! with f64
+                    // keeps the full number representation.
+                    // Example: 100000000000000000000 becomes 1e20 when Number::to_string is
+                    // used.
+                    let fallback_s = format!("{f}");
```
Comment (mattsse) [inline evm/src/executor/inspector/cheatcodes/ext.rs:194]: TIL

**Review by mattsse — APPROVED** [review]
> It seems that Number::to_string from serde_json formats big numbers powers of 10 to use the scientific notation.

interesting, perhaps this is JS related.

lgtm, love the tests
