### PR TITLE
fix(providers): remove locks on requests

### LINKED ISSUE #7131: Performance regression between 2bcb4a1 and 293fad7
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (293fad7 2024-01-14T00:29:03.206718800Z)

### What command(s) is the bug in?

.\anvil.exe --fork-url "ws://127.0.0.1:8546" --auto-impersonate --no-storage-caching --no-mining

### Operating System

Windows

### Describe the bug

I encounter 2 performance issues between nightly builds 2bcb4a1 (2 Jan 2024) and 293fad7 (14 Jan 2024)

I also verified prior and post versions (Nov 2023-Feb 2024) to be certain the issues showed up sometime between the 2 builds and it's still present in the latest nightly (14 Feb 2024)

1. Establishing rpc websocket connections fail when opening 32 instances of anvil.exe and requires a wait time of about 6-7 seconds compared to 3 seconds on 2bcb4a1 and around 4-5 in some of the older ones. The behavior is consistent - I mean it's slower in the newer versions for some reason. Opening one instance for the human eye seems to be the same, but it's obviously not quite the same

2. Opening one instance in fork mode of geth node in the same network (I mean it's low latency) and trying to interact with some contracts takes up to 10x more time more. The environment, code, inputs and calls are the same, only the anvil.exe is different

In one instance eth_call execution time jumped from 19-21 seconds on the older versions to 193-200 seconds on the newer ones.
- the contract allows batch reading balances of an input array of tuples like [account address, erc20 token address]
- I'm sending 100 calls of 1000 tuples each
- the inner code does a simple for and calls balanceOf 1000 times and writes the balance in an output array
- the contract was compiled with solidity version 0.8.22 and I used both the non optimized and yul/inline assembly versions and they exhibit the same slow down in newer anvil versions
- to get the mentioned execution times (19 seconds/193 seconds) the accounts count is 50K and 11k erc20 tokens mixed to achieve 100k tuples

- each anvil version execution time stays roughly the same if I rerun the code - I mean it's consistent within the same version. The 10x it's not a one time thing, it's there all the time for the newer versions
- keep in mind the --no-storage-caching option so everything is in memory, but anvil starts from scratch in these tests so nothing is cached anyway
- anvil is forked on the latest live block - not using historical data

On the other hand erc20 transfer transactions seem to perform about the same, the performance seems slower on the newer versions but very slightly and I also perform evm_mine and anvil_reset after each transfer transaction so it's hard to reproduce reliably.

The eth_call is blatantly slower

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

Closes #7131 

We are basically blocking all async requests through provider rn by aquiring write lock before making a request.

## Solution

Use read lock

### CODE REVIEW

File: crates/common/src/provider/runtime_transport.rs [hunk 1]
```diff
@@ -216,14 +216,11 @@ impl RuntimeTransport {
...
 
-            let mut inner = this.inner.write().await;
             // SAFETY: We just checked that the inner transport exists.
-            let inner_mut = inner.as_mut().expect("We should have an inner transport.");
-
-            match inner_mut {
-                InnerTransport::Http(http) => http.call(req),
-                InnerTransport::Ws(ws) => ws.call(req),
-                InnerTransport::Ipc(ipc) => ipc.call(req),
+            match this.inner.read().await.as_ref().unwrap().clone() {
```
Comment (mattsse) [inline crates/common/src/provider/runtime_transport.rs:220]: we're acquiring this twice now we could do the this combined in an if let else 

by checking `this.inner.read().await.cloned()`

also the write check still has a race condition, so we also need to check for `is_none` there again

**Review by mattsse — CHANGES_REQUESTED** [review]
nit

File: crates/common/src/provider/runtime_transport.rs (hunk 1 above)
Comment (DaniPopes) [reply crates/common/src/provider/runtime_transport.rs:220]: I don't think we even need to clone since Service is implemented for `&Http` and `&Pubsub`

Comment (klkvr) [reply crates/common/src/provider/runtime_transport.rs:220]: ah right, it works as long as we can obtain &mut &T

```rust
match this.inner.read().await.as_ref().unwrap() {
    InnerTransport::Http(http) => {
        let mut http = http;
        http.call(req)
    },
}
```

is there a cleaner way to do this without that strange let?

Comment (DaniPopes) [reply crates/common/src/provider/runtime_transport.rs:220]: Don't think so

Comment (klkvr) [reply crates/common/src/provider/runtime_transport.rs]: refactored it, now we don't clone and check second time after aquiring write lock

we can't use if let some there anymore I believe because we don't clone

File: crates/common/src/provider/runtime_transport.rs [hunk 2]
```diff
@@ -211,19 +211,31 @@ impl RuntimeTransport {
...
-                let mut inner = this.inner.write().await;
-                *inner = Some(this.connect().await.map_err(TransportErrorKind::custom)?)
+            let mut inner = this.inner.read().await;
+            if inner.is_none() {
+                drop(inner);
+                let mut inner_mut = this.inner.write().await;
+                if inner_mut.is_none() {
+                    *inner_mut = Some(this.connect().await.map_err(TransportErrorKind::custom)?);
+                }
+                drop(inner_mut);
```
Comment (mattsse) [inline crates/common/src/provider/runtime_transport.rs:221]: pedantic style nit:

put this in its own scope {} so we don't need the manual drop

**Review by mattsse — APPROVED** [review]

File: crates/common/src/provider/runtime_transport.rs [hunk 3]
```diff
@@ -211,19 +211,31 @@ impl RuntimeTransport {
...
 
-            let mut inner = this.inner.write().await;
             // SAFETY: We just checked that the inner transport exists.
-            let inner_mut = inner.as_mut().expect("We should have an inner transport.");
-
-            match inner_mut {
-                InnerTransport::Http(http) => http.call(req),
-                InnerTransport::Ws(ws) => ws.call(req),
-                InnerTransport::Ipc(ipc) => ipc.call(req),
+            match inner.as_ref().unwrap() {
```
Comment (Evalir) [inline crates/common/src/provider/runtime_transport.rs:226]: Another pedantic style nit: I prefer having `expect()` with a message instead of a silent unwrap, just to make it super clear when an error happens

**Review by Evalir — APPROVED** [review]
Amazing catch

File: crates/common/src/provider/runtime_transport.rs (hunk 1 above)
Comment (gakonst) [reply crates/common/src/provider/runtime_transport.rs]: can do `InnerTransport::Http(mut http)`?

Comment (DaniPopes) [reply crates/common/src/provider/runtime_transport.rs]: > can do InnerTransport::Http(mut http)?

`mut http` removes the reference

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2278e1efe9c495f4ea5932f229a0a919
