### PR TITLE
fix: `cast --to-ascii` does not work if input has trailing whitespaces

### LINKED ISSUE #8652: `cast call` appends newline to output (breaks piping to cast --to-ascii)
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a0a0020 2024-08-12T00:25:05.209264900Z)

### What command(s) is the bug in?

cast call

### Operating System

Windows

### Describe the bug

```
$ cast --version
cast 0.2.0 (a0a0020 2024-08-12T00:24:56.205249700Z)

# pipe output into cast for conversion. 👎🏼
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com | cast --to-ascii
Error:
Invalid character '\n' at position 192

# Remove newlines before piping into --to-ascii. 👍🏼
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com | tr -d '\n' | cast --to-ascii
 USDT
```

### PR DESCRIPTION
**Pull request by leovct**
## Motivation

Closes #8652 

## Solution

This PR contains two things:

1. A fix of `cast --to-ascii` to remove any trailing whitespace before converting the value to ascii.

```bash
# before
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com | cast to-ascii
Error: 
Invalid character '\n' at position 192

# after
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com | cast to-ascii
 USDT
```

3. A fix of `cast call` to remove the additional break line.

```bash
# before: two additional break lines
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com
0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000045553445400000000000000000000000000000000000000000000000000000000


# after: only one additional break line
$ cast call 0xdAC17F958D2ee523a2206206994597C13D831ec7 "symbol()" --rpc-url https://eth.llamarpc.com
0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000045553445400000000000000000000000000000000000000000000000000000000

```

### CODE REVIEW

File: crates/cast/bin/main.rs [hunk 1]
```diff
@@ -66,7 +66,7 @@ async fn main() -> Result<()> {
         }
         CastSubcommand::ToAscii { hexdata } => {
             let value = stdin::unwrap(hexdata, false)?;
-            println!("{}", SimpleCast::to_ascii(&value)?);
+            println!("{}", SimpleCast::to_ascii(&value.trim_end())?);
```
Comment (mattsse) [inline crates/cast/bin/main.rs:69]: let's just do trim
```suggestion
            println!("{}", SimpleCast::to_ascii(&value.trim())?);
```

**Review by mattsse — CHANGES_REQUESTED** [review]
pedantic nit

**Review by mattsse — APPROVED** [review]
