### PR TITLE
Fix: Properly encode json path that returns array 

### LINKED ISSUE #4244: JSON: unable to decode arrays
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd7850b 2023-02-01T00:04:58.420758Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

`jsonParse` seems to be returning improperly encoded data.

```solidity
# this would fail
uint256 ids = jsonRoles.readUintArray(".roles[*].id");

# now this is what happens
bytes memory idBytes = jsonRoles.parseRaw(".roles[*].id");
console2.log("ids bytes:", vm.toString(idBytes));
```

The json looks more or less like this:
```json
{ "roles": [ { "id": 1 }, { "id": 2 } ] }
```

So we want to get an array of `[1, 2]`.

Encoded bytes we got look like this:

```
0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002
```

This is obviously not the right ABI-encoded version of that array.

I have the same issues with using `readStringArray` and `reaedAddressArray`.

### PR DESCRIPTION
**Pull request by odyslam**
## Motivation

fixes #4244 

## Solution 

The cheatcode incorrectly always assumed that the jsonPath would return a single value (an object, an array, etc.), but a jsonPath can return multiple values (as in the issue that this PR fixes). Now it will correctly encode the values as an Array if they are numerous.

## Breaking Change

Before, both notations ".key" and "key" would work because of the bug. The cheatcode adds internally `$.` in front of the passed key, so it's easier for users. That meant that `.key` would be translated to `$..key`, which returned **all values** in the JSON path, no matter their nested position. Due to the bug, it would take the first value of the array, so it worked virtually thew same.

Now that this is fixed, `.key` will not longer work properly, as it will be translated to `$..key` and `key` to `$.key`.  That means that apps that use `.key` need to migrate their keys to `key` notation.

### CODE REVIEW

File: evm/src/executor/inspector/cheatcodes/ext.rs [hunk 1]
```diff
@@ -409,8 +409,9 @@ fn parse_json(
     // values is an array of items. Depending on the JsonPath key, they
     // can be many or a single item. An item can be a single value or
     // an entire JSON object.
+    dbg!(&values);
     if let Some(coercion_type) = coerce {
-        if values.len() != 1 || values[0].is_object() {
+        if !values.iter().filter(|value| value.is_object()).collect::<Vec<&&Value>>().is_empty() {
```
Comment (mattsse) [inline evm/src/executor/inspector/cheatcodes/ext.rs:414]: you can use `any` here 
https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.any

**Review by mattsse — CHANGES_REQUESTED** [review]
ty, smol nit

**Review by mattsse — APPROVED** [review]

File: evm/src/executor/inspector/cheatcodes/ext.rs [hunk 2]
```diff
@@ -409,8 +409,9 @@ fn parse_json(
     // values is an array of items. Depending on the JsonPath key, they
     // can be many or a single item. An item can be a single value or
     // an entire JSON object.
+    dbg!(&values);
```
Comment (mds1) [inline evm/src/executor/inspector/cheatcodes/ext.rs:412]: Delete?

File: evm/src/executor/inspector/cheatcodes/ext.rs [hunk 3]
```diff
@@ -724,7 +729,9 @@ pub fn apply(
             serialize_json(state, &inner.0, &inner.1, &array_str_to_str(&inner.2))
         }
         HEVMCalls::WriteJson0(inner) => write_json(state, &inner.0, &inner.1, None),
-        HEVMCalls::WriteJson1(inner) => write_json(state, &inner.0, &inner.1, Some(&inner.2)),
+        HEVMCalls::WriteJson1(inner) => {
+            write_json(state, &inner.0, &inner.1, Some(&format!("$.{}", &inner.2)))
```
Comment (mds1) [inline evm/src/executor/inspector/cheatcodes/ext.rs:733]: I don't understand why we had to remove support for `.key` notation? Is this unavoidable? This is a pretty big breaking change and I think also means we're using a different syntax than standard `jq`/JSONPath syntax? My understanding is that you need the `.`, but I could be wrong. See below where `jq` fails to parse without it

image

Comment (odyslam) [reply evm/src/executor/inspector/cheatcodes/ext.rs:733]: The idea was to make it easier for users, but I guess you are right.

We could remove any formatting and force users to strictly abide (`$.key`), with $ meaning the root of the json object.

File: evm/src/executor/inspector/cheatcodes/ext.rs (hunk 2 above)
Comment (odyslam) [reply evm/src/executor/inspector/cheatcodes/ext.rs:412]: duh

File: evm/src/executor/inspector/cheatcodes/ext.rs (hunk 3 above)
Comment (mds1) [reply evm/src/executor/inspector/cheatcodes/ext.rs:733]: Sorry wdym exactly, would the breaking change instead be to force users to have the `$`? 

I think my current confusion is that my understanding is the issue was with ABI encoding the result when there are multiple returned values, so why does that affect the syntax used to specify keys?

I'd have though the only change needed here was this part:

```rust
let abi_encoded = if res.len() == 1 {
    abi::encode(&[Token::Bytes(abi::encode(&res))])
} else {
    abi::encode(&[Token::Bytes(abi::encode(&[Token::Array(res)]))])
};
```

Comment (odyslam) [reply evm/src/executor/inspector/cheatcodes/ext.rs:733]: With the bug, the code would *work* with both `.key` and `key,` due to the bug. 

Now, we have to make a choice. If we want to be strict with jsonPath, I **think** we should support `$.key` and not `.key`, even if it's breaking change, because `$` signifies the root of the json object. So, the cheatcode internally doesn't modify the key in any way. If we support `.key`, the cheatcode internally modifies it to `$.key`.

Comment (mds1) [reply evm/src/executor/inspector/cheatcodes/ext.rs:733]: Hmm, I see. Supporting `key` originally feels like a bug, cause I don't think that's really valid syntax anywhere else, so I'm ok with dropping that. Then changing `parseJson` to support both `$.key` AND `.key` (by automatically prepending a `$` in the latter case) seems ideal, that way we minimize breaking changes and people can use familiar jq-syntax.

Comment (odyslam) [reply evm/src/executor/inspector/cheatcodes/ext.rs:733]: I think I would prefer to go with `.key`,  assuming that there aren't cases where not starting from the root is preferable. From what I found on the internet, all examples start with `$`.

Comment (gakonst) [reply evm/src/executor/inspector/cheatcodes/ext.rs:733]: Just to be clear, did this PR break anyone using `.key` to access a field of a json object? If yes we should bring it back.

Comment (odyslam) [reply evm/src/executor/inspector/cheatcodes/ext.rs:733]: @gakonst it was fixed in #4288
