### PR TITLE
fix: debugger doesn't work with external libraries

### LINKED ISSUE #7038: Forge test debugger is unable to load sourcemaps for any ContractDefinition that contains references invoking external `library` functions
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge --version

### What command(s) is the bug in?

forge test --debug

### Operating System

macOS (Apple Silicon)

### Describe the bug

Sourcemaps in the Forge debugger have been flaky for a while now; see #5435 for an example.

I've finally come across a minimal reproduction – with the caveat that *the error displayed in this reproduction is different from the one I'm used to seeing*. The error displayed by this reproduction is `No PC-IC maps for contract <contract>`; I am [used to seeing](https://warpcast.com/emo.eth/0x20aacbb3) `No source map for contract <contract>`.

Currently, source maps break for *any* contract/library that contains any invocations of an external `library` method (of any nested depth). The source maps for the *library itself* are unaffected (as long as that library does not invoke any external library methods).

Since I never normally use external library methods, this is definitely not the issue I usually run into. 

(As a side note, I know coverage for libraries also has many issues; I can't help but wonder if this is related. See #2567 for discussion and other relevant linked issues).

Note that *internal library function invocations do not seem to break sourcemaps*, at least in this reproduction.

Reproduce with the following contracts by running `forge test --debug test_Increment`

### Counter.sol
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

/**
 * Sourcemaps for this ContractDefinition work because it does not invoke any
 * library functions.
 */
library Countable {
    function increment(uint256 number) public pure returns (uint256) {
        return ++number;
    }

    function setNumber(uint256, uint256 newNumber) public pure returns (uint256) {
        return newNumber;
    }
}

/**
 * Sourcemaps for this ContractDefinition *do not work* because it invokes
 * the above library functions.
 */
library NestedCountable {
    using Countable for uint256;

    function increment(uint256 number) public pure returns (uint256) {
        return number.increment();
    }

    function setNumber(uint256 number, uint256 newNumber) public pure returns (uint256) {
        return number.setNumber(newNumber);
    }
}

/**
 * Sourcemaps for this ContractDefinition do not work because it invokes
 * the NestedCountable library's functions
 */
contract Counter {
    uint256 public number;

    function setNumber(uint256 newNumber) public {
        number = NestedCountable.setNumber(number, newNumber);
    }

    function increment() public {
        number = NestedCountable.increment(number);
    }
}
```

### Counter.t.sol

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {Test, console} from "forge-std/Test.sol";
import {Counter} from "src/Counter.sol";

/**
 * Sourcemaps for this test ContractDefinition do not work because it contains
 * a reference to Counter, which invokes library functions.
 */
contract CounterTest is Test {
    Counter public counter;

    function setUp() public {
        counter = new Counter();
        counter.setNumber(0);
    }

    function test_Increment() public {
        counter.increment();
        assertEq(counter.number(), 1);
    }

    function testFuzz_SetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
}

```

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

Closes #7038

## Solution

Rewrite `Linker` a bit to use `CompactContractBytecodeCow` as there is actually no need for linker to own artifacts in most of the cases

Changes test runner flow to keep library addresses used for the test run and link contracts before running the debugger.

### CODE REVIEW

File: crates/forge/bin/cmd/test/mod.rs [hunk 1]
```diff
@@ -224,14 +224,20 @@ impl TestArgs {
...
 
         if should_debug {
-            // There is only one test.
-            let Some((_, test_result)) = outcome.tests().next() else {
+            // Get first non-empty suite result. We will have only one such entry
+            let Some((suite_result, test_result)) = outcome
+                .results
+                .iter()
+                .find(|(_, r)| !r.test_results.is_empty())
+                .map(|(_, r)| (r, r.test_results.values().next().unwrap()))
```
Comment (onbjerg) [inline crates/forge/bin/cmd/test/mod.rs:232]: is this unwrap safe?

Comment (klkvr) [reply crates/forge/bin/cmd/test/mod.rs:232]: we've just filtered by `is_empty` above

**Review by mattsse — APPROVED** [review]
great!
