### PR TITLE
fix(cast): try decoding custom errors when execution reverted in cast send

### LINKED ISSUE #9789: feat(cast): parse custom errors from `cast send` with local artifacts
### Component

Cast

### Describe the feature you would like

I noticed `cast call` and `cast run` can now be run with local artifacts (https://github.com/foundry-rs/foundry/pull/7359)

Is it possible to do the same thing for `cast send`? Right now I get a response like
```
Error: server returned an error response: error code 3: execution reverted: custom error 0xfdde54e2: 223429fa00000000000000000000000000000000000000000000000000000000, data: "0xfdde54e2223429fa00000000000000000000000000000000000000000000000000000000"
```

It'd be great if the custom error could be parsed via my local artifacts (which does have this selector).

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #9789 
- opened for visibility and initial feedback

## Solution

- try decode custom error with SignaturesIdentifier if code 3 and append to output e.g.
```
Error: server returned an error response: error code 3: execution reverted: custom error 0x6786ad34: ..., data: "...": AddressInsufficientBalance(0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266, 1000)
```

### CODE REVIEW

File: crates/cast/bin/tx.rs [hunk 1]
```diff
@@ -367,7 +369,51 @@ where
         }
 
         if self.tx.gas.is_none() {
-            self.tx.gas = Some(self.provider.estimate_gas(&self.tx).await?);
+            match self.provider.estimate_gas(&self.tx).await {
```
Comment (DaniPopes) [inline crates/cast/bin/tx.rs:372]: please move to a separate function that also uses let-else, this is too indented to make sense

Comment (grandizzy) [reply crates/cast/bin/tx.rs]: I reorganized code a little bit, please check https://github.com/foundry-rs/foundry/pull/9794/commits/6adb6a8adffd880dc4af82c58e931d1de6a31fe0

File: crates/cast/bin/tx.rs [hunk 2]
```diff
@@ -401,3 +429,32 @@ where
         Ok(self)
     }
 }
+
+/// Helper function that tries to decode custom error name and inputs from error payload data.
+async fn decode_execution_revert(data: &RawValue) -> Result<Option<String>> {
+    if let Some(err_data) = data.to_string().replace("\"", "").strip_prefix("0x") {
```
Comment (DaniPopes) [inline crates/cast/bin/tx.rs:435]: serde_json::from_value::<String is probably better

File: crates/cast/bin/tx.rs [hunk 3]
```diff
@@ -401,3 +429,32 @@ where
...
+        if let Some(known_error) = SignaturesIdentifier::new(Config::foundry_cache_dir(), false)?
+            .write()
+            .await
+            .identify_error(&hex::decode(selector)?)
+            .await
+        {
+            let mut decoded_error = known_error.name.clone();
+            if !known_error.inputs.is_empty() {
+                decoded_error.push('(');
+                let error = known_error.decode_error(&hex::decode(err_data)?)?;
```
Comment (DaniPopes) [inline crates/cast/bin/tx.rs:446]: you should be able to do write!("({})", ...) with itertools .format(", ")

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/cast/bin/tx.rs (hunk 2 above)
Comment (grandizzy) [reply crates/cast/bin/tx.rs]: changed to using `serde_json::from_str::<String>` in https://github.com/foundry-rs/foundry/pull/9794/commits/e9b5e66eb1af1ea3cc353da10427f12d7504ce94

File: crates/cast/bin/tx.rs (hunk 3 above)
Comment (grandizzy) [reply crates/cast/bin/tx.rs]: changed in https://github.com/foundry-rs/foundry/pull/9794/commits/e9b5e66eb1af1ea3cc353da10427f12d7504ce94

**Review by mattsse — APPROVED** [review]

**Review by DaniPopes — APPROVED** [review]

File: crates/cast/bin/tx.rs [hunk 4]
```diff
@@ -350,12 +356,36 @@ impl<P: Provider<AnyNetwork>> CastTxBuilder<P, InputState> {
...
 
+    /// Estimate tx gas from provider call. Tries to decode custom error if execution reverted.
+    async fn estimate_gas(&mut self) -> Result<()> {
+        match self.provider.estimate_gas(&self.tx).await {
+            Ok(estimated) => {
+                self.tx.gas = Some(estimated);
+                Ok(())
+            }
+            Err(err) => {
+                if let TransportError::ErrorResp(ref payload) = err {
```
Comment (DaniPopes) [inline crates/cast/bin/tx.rs:373]: please use `&` not `ref`

Comment (grandizzy) [reply crates/cast/bin/tx.rs]: oops, fixed

**Review by zerosnacks — APPROVED** [review]

**Comment by holic** [comment]
amazingggg, thank you!
