### PR TITLE
fix(fmt): do not add underscores on fractional part with exponent

### LINKED ISSUE #12194: bug(fmt): do not add underscores on fractional part with exponent
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

_No response_

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

_No response_

### Operating System

None

### Describe the bug

user reported diffs:
```
|-        uint128 expectedWithdrawableAmount = 5267.8268764263694426e18;
|+        uint128 expectedWithdrawableAmount = 5267.826_876_426_369_442_6e18;
```

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

closes #12194

## Solution

only add thousand underscores in the fractional part when there is no exponent

## PR Checklist

- [X] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/fmt/src/state/common.rs [hunk 1]
```diff
@@ -123,11 +123,11 @@ impl<'ast> State<'_, 'ast> {
...
             out.push('.');
-            if !fract.is_empty() {
-                add_underscores(&mut out, config, fract, is_dec, is_yul, true);
-            } else {
-                out.push('0');
-            }
+            match (fract.is_empty(), exp.is_empty()) {
+                (false, false) => out.push_str(fract),
+                (false, true) => add_underscores(&mut out, config, fract, is_dec, is_yul, true),
+                (true, _) => out.push('0'),
```
Comment (DaniPopes) [inline crates/fmt/src/state/common.rs:132]:
```suggestion
                // `X.YeZ`: keep as is
                (false, false) => out.push_str(fract),
                // `X.Y`
                (false, true) => add_underscores(&mut out, config, fract, is_dec, is_yul, true),
                // `X.` -> `X.0`
                (true, _) => out.push('0'),
```
