### PR TITLE
fix: eip7702 cheatcodes multiple auth

### LINKED ISSUE #10551: bug(forge): EIP-7702 cheatcodes cannot handle multiple auth
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

_No response_

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

_No response_

### Operating System

None

### Describe the bug

 we allow only one signed auth at a time https://github.com/foundry-rs/foundry/blob/477876a87fea0cd8e2c398f23f836189f2aad58c/crates/cheatcodes/src/inspector.rs#L393-L396, which means
```
vm.signAndAttach
performTx
```
works fine, but if one does
```
vm.signAndAttach
vm.signAndAttach
vm.signAndAttach
performTx
```
the tx authorizationList of next tx won't reflect all cheatcode calls.

We need to turn it into a vec add a fn like
```Rust
    pub fn add_delegation(&mut self, authorization: SignedAuthorization) {
        self.active_delegations.get_or_insert_with(|| vec![]).push(authorization);
    }
```
and use it when adding new delegations. Also when adding should keep the track of signers and properly increment nonces

### PR DESCRIPTION
**Pull request by zjesko**
fixes #10551

Add the ability to have multiple active delegations and signed auth. Also takes cares of correctly incrementing the nonce.

```
vm.signAndAttach
vm.signAndAttach
vm.signAndAttach
performTx
```
now works correctly

### CODE REVIEW

**Comment by zjesko** [comment]
@grandizzy @mattsse @DaniPopes
please review

**Review by grandizzy — CHANGES_REQUESTED** [review]
thank you! good start, couple of things wrt nonce management 

- here we need to handle the case when authority_acc is already in active delegations (hence nonce already incremented) 

https://github.com/foundry-rs/foundry/blob/3c0b3df8f8ef8800a10912ce5a9dcd9eb7e971ff/crates/cheatcodes/src/script.rs#L135-L136

so we need to walk through SignedAuthorization within `active_delegations` and increment the nonce of the last one for signer address (if any). For example if we have active delegations as
    - `alice` with nonce 1
    - `alice` with nonce 2
    - `bob` with nonce 1
if we add another delegation for `alice` it should have nonce 3

- the same thing should be done when we attach delegation / validate next nonce here
https://github.com/foundry-rs/foundry/blob/3c0b3df8f8ef8800a10912ce5a9dcd9eb7e971ff/crates/cheatcodes/src/script.rs#L161-L163

if authority_acc present in active delegation list then we need to compare with that incremented one

- since `return Err("invalid nonce".into()); ` it's quite useless, could you enhance this one to include expected / current nonce and authority address?

**Comment by zjesko** [comment]
alright, thanks for the feedback will patch this quickly

**Review by MrG9090 — APPROVED** [review]

**Review by grandizzy — APPROVED** [review]
thank you! lgtm, made couple of changes to reflect increment of sender nonce only (if also in auth list), fix fmt and test
waiting for other reviews before merging
CC @klkvr could you also pls check?

File: crates/cheatcodes/src/inspector.rs [hunk 1]
```diff
@@ -371,10 +371,10 @@ pub struct Cheatcodes {
     /// execution block environment.
     pub block: Option<BlockEnv>,
 
-    /// Currently active EIP-7702 delegation that will be consumed when building the next
+    /// Currently active EIP-7702 delegations that will be consumed when building the next
     /// transaction. Set by `vm.attachDelegation()` and consumed via `.take()` during
     /// transaction construction.
-    pub active_delegation: Option<SignedAuthorization>,
+    pub active_delegations: Option<Vec<SignedAuthorization>>,
```
Comment (klkvr) [inline crates/cheatcodes/src/inspector.rs]: let's just have `Vec` here, `None` is equivalent to `Some(Vec::new())` here

File: testdata/default/cheats/AttachDelegation.t.sol [hunk 2]
```diff
@@ -194,6 +194,29 @@ contract AttachDelegationTest is DSTest {
...
+        SimpleDelegateContract(alice).execute(calls);
+
+        assertEq(token.balanceOf(address(this)), 50);
+        assertEq(token.balanceOf(alice), 50);
+
+        vm._expectCheatcodeRevert("vm.signAndAttachDelegation: invalid nonce");
+        vm.signAndAttachDelegation(address(implementation), alice_pk, 0);
+        vm.signAndAttachDelegation(address(implementation), alice_pk, 1);
+        vm.signAndAttachDelegation(address(implementation2), bob_pk, 3);
+    }
```
Comment (klkvr) [inline testdata/default/cheats/AttachDelegation.t.sol]: Those are primarily script-related cheatcodes so I would like a test that would cover the full script flow with multiple delegations and assert that all transactions are getting hanlded correctly

File: crates/cheatcodes/src/script.rs [hunk 3]
```diff
@@ -155,11 +159,43 @@ fn sign_delegation(
...
+                .iter()
+                .filter_map(|auth| {
+                    auth.recover_authority()
+                        .ok()
+                        .filter(|&addr| addr == authority)
+                        .map(|_| auth.nonce)
+                })
+                .max()
+        })
+        .map_or(account_nonce + 1, |max_nonce| max_nonce + 1)
```
Comment (klkvr) [inline crates/cheatcodes/src/script.rs]: @grandizzy isn't this wrong for a case when `broadcast.new_origin != authority`? this +1 is only relevant when authority is the sender of transaction and will get its nonce increased

Comment (grandizzy) [reply crates/cheatcodes/src/script.rs]: @klkvr I think that's correct here as this logic applies when signed auths are created, so if sender is bob and we attach two signed auth for alice which has nonce 1 then auths should have nonce 2 and nonce 3, basically step 
```
6. Verify the nonce of authority is equal to nonce.
9. Increase the nonce of authority by one.
```
here https://eip7702.io/#behavior
For sender we increment here https://github.com/foundry-rs/foundry/pull/10623/files#diff-e6d620775172f55e7b3f7ee90c1504e58ad2148887baffc7bd6dc24959ff22b7R1161-R1165

File: crates/cheatcodes/src/inspector.rs (hunk 1 above)
Comment (grandizzy) [reply crates/cheatcodes/src/inspector.rs]: changed in https://github.com/foundry-rs/foundry/pull/10623/commits/7f62a4f9aaebcafb674874917b13efed35b483f5

File: crates/cheatcodes/src/script.rs (hunk 3 above)
Comment (pcaversaccio) [reply crates/cheatcodes/src/script.rs]: @grandizzy shared with me offline the following scenario:

> basically for bob with nonce 10 and alice with nonce 100, considering bob is sender and we attach 3 auths as
> - one for alice
> - one for bob
> - one more for alice
> what nonces should each auth have?

The first nonce is used for the tx broadcasting from bob, thus the auth nonce must be 11. And for Alice it's 2 tuples:
image

with the existing nonce and after this tuple is processed the nonce is increased by one. Thus the 2 auths must have nonce of 100 and 101.

Comment (grandizzy) [reply crates/cheatcodes/src/script.rs]: good catch, thanks both! implemented with https://github.com/foundry-rs/foundry/pull/10623/commits/fe37b425c96936340493e0764b152d43b095ffd3

**Review by cshein45 — APPROVED** [review]
Movement

File: crates/cheatcodes/src/inspector.rs [hunk 4]
```diff
@@ -1148,21 +1156,22 @@ impl Cheatcodes {
...
-                        (None, None) => {
-                            tx_req.sidecar = None;
-                            tx_req.authorization_list = None;
+                    // Apply active EIP-7702 delegations, if any.
+                    if !active_delegations.is_empty() {
+                        for auth in &active_delegations {
+                            let Ok(auth) = auth.recover_authority() else {
+                                continue;
+                            };
+                            if auth.eq(&broadcast.new_origin) {
```
Comment (klkvr) [inline crates/cheatcodes/src/inspector.rs]:
```suggestion
                            let Ok(authority) = auth.recover_authority() else {
                                continue;
                            };
                            if authority == broadcast.new_origin {
```

File: crates/cheatcodes/src/script.rs [hunk 5]
```diff
@@ -155,11 +160,49 @@ fn sign_delegation(
...
 }
 
+/// Returns the next valid nonce for a delegation, considering existing active delegations.
+fn next_delegation_nonce(
+    active_delegations: &[SignedAuthorization],
+    authority: Address,
+    broadcast: &Option<Broadcast>,
+    account_nonce: u64,
+) -> u64 {
+    match active_delegations.iter().rfind(|auth| auth.recover_authority().unwrap() == authority) {
```
Comment (klkvr) [inline crates/cheatcodes/src/script.rs]: I would prefer to avoid unwrap here as we have support for attaching arbitrary delegations and this might not be safe

**Review by klkvr — CHANGES_REQUESTED** [review]
only have nits

File: crates/cheatcodes/src/script.rs (hunk 5 above)
Comment (grandizzy) [reply crates/cheatcodes/src/script.rs]: changed in https://github.com/foundry-rs/foundry/pull/10623/commits/8e17fe85fa0804117024fc021f119f474153b0eb

**Review by klkvr — APPROVED** [review]
