### PR TITLE
fix(forge): preserve state of persisted accounts on rollFork(tx) / transact

### LINKED ISSUE #8006: vm.rollFork(tx) does not persist state when etch in test
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ea2eff9 2024-05-28T00:17:45.727606000Z)

### What command(s) is the bug in?

_No response_

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to replay transactions on a fork using different contract code but rollfork not persisting the contract bytecode from etch. Is this a bug or an invalid use case? From the docs for `rollFork` it seems to indicate this is a valid use case.

Sample code:
```
contract Mock {
    function totalSupply() external view returns (uint256 supply) {
        return 1;
    }
}

contract ReproTest is Test {
    // Vm constant vm = Vm(HEVM_ADDRESS);
    IERC20 dai;
    bytes32 transaction = 0x58e968fbaaf8495018a6d0ca0d13a08963359c9315967f24cb7be7373d857b7b; // Transaction inside block 19000001

    function setUp() public {
        vm.createSelectFork(vm.envString("FORK_URL_MAINNET"), 19000000);
        dai = IERC20(0x6B175474E89094C44Da98b954EedeAC495271d0F);
    }

    function testRollForkStateEtch() public {
        vm.etch(address(dai), address(new Mock()).code);
        assertEq(dai.totalSupply(), 1);
        // vm.rollFork(19000001);
        vm.rollFork(transaction);
        assertEq(dai.totalSupply(), 1);
    }

    function testRollForkStateEtchPersisted() public {
        vm.etch(address(dai), address(new Mock()).code);
        vm.makePersistent(address(dai));
        assertEq(dai.totalSupply(), 1);
        // vm.rollFork(19000001);
        vm.rollFork(transaction);
        assertEq(dai.totalSupply(), 1);
    }
}
```

Actual result:
```
[FAIL. Reason: assertion failed: 3723031040751006502480211083 != 1] testRollForkStateEtch() (gas: 68746)
[FAIL. Reason: assertion failed: 3723031040751006502480211083 != 1] testRollForkStateEtchPersisted() (gas: 69212)
```
Expected result: test should pass

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #8006 accounts state marked as persistent is overwritten in `rollFork(tx)` and `transact` calls

## Solution

- add `persistent_accounts` arg in `update_state` helper. Update state only if account is not marked as persistent
- `persistent_accounts` is some when called from `commit_transaction` (used by `rollFork` / transact)
- `persistent_accounts` is none when update state from stack

### CODE REVIEW

File: crates/evm/core/src/backend/mod.rs [hunk 1]
```diff
@@ -1894,16 +1906,26 @@ fn commit_transaction<I: InspectorExt<Backend>>(
...
+    state: &mut EvmState,
+    db: &mut DB,
+    persistent_accounts: Option<&HashSet<Address>>,
+) -> Result<(), DB::Error> {
     for (addr, acc) in state.iter_mut() {
-        acc.info = db.basic(*addr)?.unwrap_or_default();
-        for (key, val) in acc.storage.iter_mut() {
-            val.present_value = db.storage(*addr, *key)?;
+        let is_persistent =
+            if let Some(accounts) = persistent_accounts { accounts.contains(addr) } else { false };
```
Comment (mattsse) [inline crates/evm/core/src/backend/mod.rs:1922]: this looks a bit strange, 
I'd prefer persistent_accounts.and_then().unwrap_or(false)

**Review by mattsse — APPROVED** [review]
nice find!

lgtm, pedantic style suggestion

File: crates/evm/core/src/backend/mod.rs (hunk 1 above)
Comment (grandizzy) [reply crates/evm/core/src/backend/mod.rs]: went for `map_or` in https://github.com/foundry-rs/foundry/pull/8129/commits/777764d94b3918bda4ac70da9193337670fd190b, looks a little bit more cleaner

**Review by mattsse — APPROVED** [review]
