### PR TITLE
fix(invariant): ignore persisted failure if different test contract

### LINKED ISSUE #9965: bug(`forge`): invariant failures that persist on the cache are retried even if they should be excluded according to the configuration.
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.0.0-nightly Commit SHA: 9bcfbaa6e6066fb9f87ce07163f5479d4b124563 Build Timestamp: 2025-02-26T00:21:24.429838503Z (1740529284) Build Profile: maxperf

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

If a failed invariant test is cached, and then you change the target configuration (e.g., targetSenders, targetContracts, etc.), when you execute the tests again, this failing test will be reported as failed even if it should not be according to the new targets configuration.

### Code snippet
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console} from "forge-std/Test.sol";

contract Ownable {
    address public owner;
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    constructor(address _owner) {
        owner = _owner;
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "Ownable: caller is not the owner");
        _;
    }

    function changeOwner(address _owner) external onlyOwner {
        owner = _owner;
        emit OwnershipTransferred(msg.sender, _owner);
    }
}

contract OwnableTest is Test {
    Ownable public ownable;
    address initial_owner = makeAddr("initial_owner");
    address never_owner = makeAddr("never_owner");

    function setUp() public {
        ownable = new Ownable(initial_owner);
        // excludeSender(initial_owner);
    }

    function invariant_never_owner() public {
        assertNotEq(ownable.owner(), never_owner);
    }
}

```

### Reproduction
* init a new project and copy the given snippet.
* run `forge test --mc OwnableTest`, the test should fail and create a new cached failing invariant sequence in the cache folder.
Image
* uncomment the `excludeSender(initial_owner);` and execute the test again.
* Now, the test should not fail, as it is not possible with the current configuration, however, the failing sequence is still reported as a test failure. You need to clear the cache and run the test again to pass.

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #9965 

## Solution
- persist test driver bytecode together with generated counterexample
- when loading persisted failure, compare test bytecodes and ignore / warn user if doesn't match
- canonicalize failure path, remove invariant config clones

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/forge/src/runner.rs [hunk 1]
```diff
@@ -894,3 +916,50 @@ fn fuzzer_with_cases(
...
+/// Helper function to load failed call sequence from file.
+/// Ignores failure if generated with different test contract than the current one.
+fn persisted_call_sequence(path: &Path, bytecode: &Bytes) -> Option<Vec<BaseCounterExample>> {
+    foundry_common::fs::read_json_file::<InvariantPersistedFailure>(path).ok().and_then(
+        |persisted_failure| {
+            if let Some(persisted_bytecode) = &persisted_failure.driver_bytecode {
+                // Ignore persisted sequence if test bytecode doesn't match.
+                if !bytecode.eq(persisted_bytecode) {
+                    let _= sh_warn!("\
+                            Failure from {:?} file was ignored because test contract bytecode doesn't match.",
```
Comment (zerosnacks) [inline crates/forge/src/runner.rs:939]: nit: `because test contract bytecode doesn't match` could be worded differently, `because test contract bytecode has changed`.

**Review by zerosnacks — APPROVED** [review]
Makes sense! Small wording nit other than that lgtm!

File: crates/forge/src/runner.rs (hunk 1 above)
Comment (grandizzy) [reply crates/forge/src/runner.rs]: yep, better, changed in https://github.com/foundry-rs/foundry/pull/9981/commits/520c9cee1b681e150b9333a4785ceefec972f160
