### PR TITLE
fix(cast): Harden `cast send` and provide more accurate error messages

### LINKED ISSUE #4831: cast send is using eth_sendTransaction when it should use eth_sendRawTransaction
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (dedc31e 2023-04-26T00:13:24.012522000Z)

### What command(s) is the bug in?

cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am having difficulty calling `cast send` to send a tx via remote RPC. It appears that cast is using `eth_sendTransaction` when it should use `eth_sendRawTransaction`. 

## Details

1. The key I'm trying to use is in a local keystore file.
1. The error I receive from Alchemy is (I get something similar from Infura as well):

```
(code: -32600, message: Unsupported method: eth_sendTransaction. See available methods at https://docs.alchemy.com/alchemy/documentation/apis, data: None)
```

2. A minimum viable repro command is:

```
cast send 0x78339d822c23d943e4a2d4c3dd5408f66e6d662d --from 0x78339d822c23d943e4a2d4c3dd5408f66e6d662d
```

However I have also tried multiple variations, including: 
- with `--keystore ~/Library/Ethereum/keystore/UTC-... --password ...`
- with `--keystore ~/Library/Ethereum/keystore/UTC-...` (no --password`)
- various combinations with and without `--keystore`, `--password` and `--from`

I eventually got it working with `seth` using just the `--from` argument.

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

Closes #4831.

`cast send` right now assumes that if a signer can't be constructed, it must fall back to `eth_sendTransaction` in all cases. This is not exactly true, and will result in misleading error messages depending on the combination of flags passed in for the wanted signing method. Particular highlights were:

- If a path to a folder that contains a keystore was passed in, it would try and walk the directory to try and find it. However, keystores no longer contain the `address` field that was being used to identify the correct keystore, so they were never found. This caused `cast send` to fall back to `eth_sendTransaction` hoping the remote RPC had the unlocked account to sign the tx.
- If the ledger option was passed in but the ledger was not available or connected, `cast send` would again fall back to `eth_sendTransaction`. This would happen similarly with other available local signing methods.
- If a `--from` address is passed in and no other information is provided, `cast send` would again fall back to `eth_sendTransaction`. This is actually "correct" behavior, but the user is kept in the dark as to why this is and is not given enough context. 

## Solution

The send command was lightly refactored and commented for future reference. The main changes are:
- Defaulting to `eth_sendTransaction` is now only possible by passing the `--unlocked` flag, matching `forge script`'s behavior. This flag also requires the `--from` flag to be passed, to ensure enough information is passed in by the user.
- If not defaulting to `eth_sendTransaction`, we must now be able to construct a signer with the flags passed in, or we will bail and inform the user something is wrong.
- **THIS BREAKS COMPATIBILITY WITH DAPPTOOLS**: We now don't walk directories looking for keystores if only a directory is passed in with the `--keystore` flag, and instead bail and tell the user to provide the keystore file directly. This is because keystores are no longer generated with the `address` inside of them. (This is a big discussion point, and while I favor being more strict, we could also try and decrypt all the keystores found and use the first one to succeed, but this has edge cases that could lead to bad scenarios).
- If a ledger is not available for whatever reason, instead of defaulting to `eth_sendTransaction`, we bail and inform the user that they must only have the ledger unlocked and connected with no other conflicting wallet apps open.

EDIT: @DaniPopes @0xMelkor can't seem to be able to add you as reviewers, but as always, feel free to review!

### CODE REVIEW

File: cli/src/opts/wallet/mod.rs [hunk 1]
```diff
@@ -316,35 +322,18 @@ pub trait WalletTrait {
...
-    /// sender address
+    /// if the path is a directory, it bails and asks the user to specify the keystore file
+    /// directly.
     fn find_keystore_file(&self, path: impl AsRef<Path>) -> Result<PathBuf> {
         let path = path.as_ref();
         if !path.exists() {
             bail!("Keystore file `{path:?}` does not exist")
         }
 
         if path.is_dir() {
```
Comment (Evalir) [inline cli/src/opts/wallet/mod.rs:335]: Note that this is where compatibility with dapptools on this functionality is broken. Happy to accomodate suggestions on how we want to handle this as keystores do not have the expected `address` property.

**Comment by 0xMelkor** [comment]
> EDIT: @DaniPopes @0xMelkor can't seem to be able to add you as reviewers, but as always, feel free to review!

On it

File: cli/src/cmd/cast/send.rs [hunk 2]
```diff
@@ -50,6 +50,10 @@ pub struct SendTxArgs {
 
     #[clap(subcommand)]
     command: Option<SendTxSubcommands>,
+
+    /// Send via `eth_sendTransaction using the `--from` argument or $ETH_FROM as sender
+    #[clap(long, requires = "from")]
```
Comment (0xMelkor) [inline cli/src/cmd/cast/send.rs:55]: I guess `--from` fallbacks to `$ETH_FROM`...correct?

File: cli/src/cmd/cast/send.rs [hunk 3]
```diff
@@ -99,8 +148,7 @@ impl SendTxArgs {
                         The specified sender via CLI/env vars does not match the sender configured via\n\
                         the hardware wallet's HD Path.\n\
                         Please use the `--hd-path <PATH>` parameter to specify the BIP32 Path which\n\
-                        corresponds to the sender.\n\
-                        This will be automatically detected in the future: https://github.com/foundry-rs/foundry/issues/2289\
+                        corresponds to the sender, or let foundry automatically detect it by not specifying any sender address.\n\
```
Comment (0xMelkor) [inline cli/src/cmd/cast/send.rs:151]: Can we transform it in something like 
```rust
r#"
The specified sender via CLI/env vars does not match the sender configured via
the hardware wallet's HD Path.
Please use the `--hd-path <PATH>` parameter to specify the BIP32 Path which
corresponds to the sender, or let foundry automatically detect it by not specifying any sender address."#
```

File: cli/src/cmd/cast/send.rs [hunk 4]
```diff
@@ -81,14 +85,59 @@ impl SendTxArgs {
...
+        } else {
+            None
+        };
+
+        // Case 1:
+        // Default to sending via eth_sendTransaction if the --unlocked flag is passed.
+        // This should be the only way this RPC method is used as it requires a local node
+        // or remote RPC with unlocked accounts.
+        if unlocked {
+            // Checking if signer isn't the default value
```
Comment (0xMelkor) [inline cli/src/cmd/cast/send.rs:114]: We are updating the nonce, but it's not clear how the comment relates to the code:
```rust
  // Checking if signer isn't the default value
  // 00a329c0648769A73afAc7F9381E08FB43dBEA72.

```

File: cli/src/cmd/cast/send.rs [hunk 5]
```diff
@@ -81,14 +85,59 @@ impl SendTxArgs {
...
+            // 00a329c0648769A73afAc7F9381E08FB43dBEA72.
+            if resend {
+                tx.nonce = Some(provider.get_transaction_count(config.sender, None).await?);
+            }
+
+            cast_send(
```
Comment (0xMelkor) [inline cli/src/cmd/cast/send.rs:120]: `cast_send` is called twice. 
Since `cast_send` is our final intent, can we refactor to have just a call at the end of the fn block?

**Review by 0xMelkor — COMMENTED** [review]
@Evalir ty, this is my review

File: cli/src/cmd/cast/send.rs (hunk 5 above)
Comment (Evalir) [reply cli/src/cmd/cast/send.rs:120]: Yeah the reason this is written like so is that `provider` actually takes different types depending if you have a signer or not, which will also affect `from` and the `eth_*` method used. We want to clearly differentiate when we're falling back to `eth_sendTransaction` vs using a signer and using `eth_sendRawTransaction`, and so we have these two code paths. I actually think abstracting it all away so it looks like only one path could make this harder to reason about and could allow misleading error messages due to fall-through cases. Let me know what you think!

File: cli/src/cmd/cast/send.rs [hunk 6]
```diff
@@ -109,19 +157,6 @@ impl SendTxArgs {
                 tx.nonce = Some(provider.get_transaction_count(from, None).await?);
```
[the remark this answers is not in the document]
Comment (Evalir) [reply cli/src/cmd/cast/send.rs:157]: Answered in https://github.com/foundry-rs/foundry/pull/4874#discussion_r1185013668 — essentially want to keep these code paths simple instead of further abstracting them.

[the remark this answers is not in the document]
Comment (mattsse) [reply cli/src/cmd/cast/send.rs:157]: +1

**Review by mattsse — APPROVED** [review]
changes lgtm, haven't tested it though,

pending @0xMelkor for final approval

File: cli/src/cmd/cast/send.rs [hunk 7]
```diff
@@ -81,14 +85,59 @@ impl SendTxArgs {
...
+
+        // Case 1:
+        // Default to sending via eth_sendTransaction if the --unlocked flag is passed.
+        // This should be the only way this RPC method is used as it requires a local node
+        // or remote RPC with unlocked accounts.
+        if unlocked {
+            // Checking if signer isn't the default value
+            // 00a329c0648769A73afAc7F9381E08FB43dBEA72.
+            if resend {
+                tx.nonce = Some(provider.get_transaction_count(config.sender, None).await?);
```
[the remark this answers is not in the document]
Comment (Evalir) [reply cli/src/cmd/cast/send.rs:115]: see https://github.com/foundry-rs/foundry/pull/4874#discussion_r1185016531

File: cli/src/cmd/cast/send.rs [hunk 8]
```diff
@@ -138,29 +129,39 @@ impl SendTxArgs {
...
+            // user-specified --from
+            if let Some(specified_from) = eth.wallet.from {
+                if specified_from != from {
+                    eyre::bail!(
+                        r#"
+The specified sender via CLI/env vars does not match the sender configured via
+the hardware wallet's HD Path.
+Please use the `--hd-path <PATH>` parameter to specify the BIP32 Path which
+corresponds to the sender, or let foundry automatically detect it by not specifying any sender address.
+"#
```
Comment (DaniPopes) [inline cli/src/cmd/cast/send.rs:151]: Same for all the other strings. Either escape newlines or remove them

```rust
r#"
a
"# == "\na\n"

"\
a\
" == "a"

"\
a" == "a"
```

```suggestion
                        "\
The specified sender via CLI/env vars does not match the sender configured via
the hardware wallet's HD Path.
Please use the `--hd-path <PATH>` parameter to specify the BIP32 Path which
corresponds to the sender, or let foundry automatically detect it by not specifying any sender address.\
"
```

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: cli/src/cmd/cast/send.rs (hunk 8 above)
Comment (Evalir) [reply cli/src/cmd/cast/send.rs:151]: Hey @DaniPopes this was done after a previous review by @0xMelkor — happy to accommodate whatever style you prefer, would just like alignment on which one we all prefer 😅  (and the current style is already used across the codebase)

Comment (DaniPopes) [reply cli/src/cmd/cast/send.rs:151]: The message as is now will be printed with trailing newlines as I was trying to highlight in the first code block, and you don't need raw strings to allow newlines in literals: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9652a8796a70c06b62941ce502bec872
I saw that each line ended with `"\n\"`, which is superfluous, but this suggestion is not a style choice

Comment (Evalir) [reply cli/src/cmd/cast/send.rs:151]: Ahh I see what you mean now, my bad! Awesome will incorporate it then

Comment (Evalir) [reply cli/src/cmd/cast/send.rs]: done in https://github.com/foundry-rs/foundry/pull/4874/commits/7da515ee9756a8c46b6656bbec910b25980e9a0b

**Review by DaniPopes — APPROVED** [review]

**Review by mattsse — APPROVED** [review]
