### PR TITLE
fix(chisel): Windows prompt

### LINKED ISSUE #4503: The position of chisel command line prompt on windows is displayed incorrectly
### Component

Chisel

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1d9a34e 2023-03-07T00:06:14.4107988Z)

### What command(s) is the bug in?

_No response_

### Operating System

Windows

### Describe the bug

The position of the cursor is wrong

I analyzed the code, the problem lies in the dispatcher.get_prompt function

This can be modified chisel.rs main function
`
let prompt = if cfg!(windows) { format!(">") }else {dispatcher.get_prompt()};
`

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Closes #4503

Refs https://github.com/kkawakam/rustyline/pull/215

## Solution

Move syntax highlighting to `SolidityHelper`

### CODE REVIEW

File: chisel/src/solidity_helper.rs [hunk 1]
```diff
@@ -207,6 +236,41 @@ impl Highlighter for SolidityHelper {
     fn highlight_char(&self, line: &str, pos: usize) -> bool {
         pos == line.len()
     }
+
+    fn highlight_prompt<'b, 's: 'b, 'p: 'b>(
```
Comment (mattsse) [inline chisel/src/solidity_helper.rs:240]: :)

**Review by mattsse — APPROVED** [review]
lgtm
