### PR TITLE
fix(anvil): ensure typed tx supported based on hardfork

### LINKED ISSUE #4386: Return error when processing tx type not supported by hardfork
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.1.0 (e2fa2b5 2023-02-19T00:12:20.195646276Z)

### What command(s) is the bug in?

anvil --prune-history --steps-tracing --hardfork berlin

### Operating System

Linux

### Describe the bug

When sending a transaction with the type that should not be supported by the current hardfork, Anvil still happily accepts it. I am not sure if this is an intended behavior (a kind of "cheat code") or a bug.

This is what returns Hardhat when sending a type 2 tx and running the hardfork `berlin` or earlier:
```
{'code': -32602, 'message': "EIP-1559 style fee params (maxFeePerGas or maxPriorityFeePerGas) received but they are not supported by 
the current hardfork. \n\nYou can use them by running Hardhat Network with 'hardfork' london or later.", 'data': {'message': "EIP-1559 style fee 
params (maxFeePerGas or maxPriorityFeePerGas) received but they are not supported by the current hardfork. \n\nYou can use them by running Hardhat 
Network with 'hardfork' london or later."}}
```

And this is the error message when sending a type 1 tx to the `muirGlacier` hardfork or earlier on Hardhat:
```
{'code': -32602, 'message': "Access list received but is not supported by the current hardfork. \n      \nYou can use them by running 
Hardhat Network with 'hardfork' berlin or later.", 'data': {'message': "Access list received but is not supported by the current hardfork. \n      
\nYou can use them by running Hardhat Network with 'hardfork' berlin or later."}}
```

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #4386

ensures current hardfork supports typed transactions.

## Solution
add check to eth_sendRawTransaction.

wdyt @michprev

### CODE REVIEW

File: anvil/src/eth/backend/mem/mod.rs [hunk 1]
```diff
@@ -453,9 +453,35 @@ impl Backend {
...
+        self.env.read().cfg.spec_id
+    }
+
     /// Returns true for post London
     pub fn is_eip1559(&self) -> bool {
-        (self.env().read().cfg.spec_id as u8) >= (SpecId::LONDON as u8)
+        (self.spec_id() as u8) >= (SpecId::LONDON as u8)
+    }
+
+    /// Returns true for post muirGlacier
```
Comment (michprev) [inline anvil/src/eth/backend/mem/mod.rs:466]: Should return true for berlin or later.

File: anvil/src/eth/backend/mem/mod.rs [hunk 2]
```diff
@@ -453,9 +453,35 @@ impl Backend {
...
+    pub fn ensure_eip1559_active(&self) -> Result<(), BlockchainError> {
+        if self.is_eip1559() {
+            return Ok(())
+        }
+        Err(BlockchainError::EIP1559TransactionUnsupportedAtHardfork)
+    }
+
+    /// Returns an error if EIP1559 is not active (pre muirGlacier)
+    pub fn ensure_eip2930_active(&self) -> Result<(), BlockchainError> {
+        if self.is_eip1559() {
```
Comment (michprev) [inline anvil/src/eth/backend/mem/mod.rs:481]: Should call `self.is_eip2930()`. Also the comment above should mention EIP2930 instead of EIP1559

File: anvil/src/eth/backend/mem/mod.rs [hunk 3]
```diff
@@ -453,9 +453,35 @@ impl Backend {
...
+            return Ok(())
+        }
+        Err(BlockchainError::EIP1559TransactionUnsupportedAtHardfork)
```
Comment (michprev) [inline anvil/src/eth/backend/mem/mod.rs:484]: Should return `BlockchainError::EIP2930TransactionUnsupportedAtHardfork`

File: anvil/src/eth/error.rs [hunk 4]
```diff
@@ -72,6 +72,8 @@ pub enum BlockchainError {
     TimestampError(String),
     #[error(transparent)]
     DatabaseError(#[from] DatabaseError),
+    #[error("EIP-1559 style fee params (maxFeePerGas or maxPriorityFeePerGas) received but they are not supported by the current hardfork.\n\nYou can use them by running anvil with '--hardfork londong' or later.")]
+    EIP1559TransactionUnsupportedAtHardfork,
 }
```
Comment (michprev) [inline anvil/src/eth/error.rs:77]: Missing `EIP2930TransactionUnsupportedAtHardfork`. The error message can be something like 
```
Access list received but is not supported by the current hardfork.\n\nYou can use it by running 
anvil with '--hardfork berlin' or later.
```

File: anvil/src/eth/api.rs [hunk 5]
```diff
@@ -792,10 +792,14 @@ impl EthApi {
...
             // version byte
             let extend = rlp::encode(&data);
-            match rlp::decode::<TypedTransaction>(&extend[..]) {
+            let tx = match rlp::decode::<TypedTransaction>(&extend[..]) {
                 Ok(transaction) => transaction,
                 Err(_) => return Err(BlockchainError::FailedToDecodeSignedTransaction),
-            }
+            };
+
+            self.ensure_typed_transaction_supported(&tx)?;
```
Comment (michprev) [inline anvil/src/eth/api.rs:800]: How about other JSON-RPC requests for sending transactions? Namely `eth_sendTransaction` and `eth_sendUnsignedTransaction`?

File: anvil/src/eth/error.rs [hunk 6]
```diff
@@ -281,6 +283,9 @@ impl<T: Serialize> ToRpcResponseResult for Result<T> {
                 BlockchainError::DatabaseError(err) => {
                     RpcError::internal_error_with(err.to_string())
                 }
+                err @ BlockchainError::EIP1559TransactionUnsupportedAtHardfork => {
+                    RpcError::invalid_params(err.to_string())
+                }
```
Comment (michprev) [inline anvil/src/eth/error.rs:288]: Add `EIP2930TransactionUnsupportedAtHardfork`

**Comment by mattsse** [comment]
thanks for the review.

fixed eip2930 issues and integrated in other `eth_send` calls

**Comment by michprev** [comment]
Please also address this one:
`is_eip2930` should return `true` for `berlin` or later.
https://github.com/mattsse/foundry/blob/581e059216b36c3e93d70504b0bf3725e25b3ca7/anvil/src/eth/backend/mem/mod.rs#L466-L469

So it should be:
```rust
    /// Returns true for post berlin
    pub fn is_eip2930(&self) -> bool {
        (self.spec_id() as u8) >= (SpecId::BERLIN as u8)
    }
```

Also the comment https://github.com/mattsse/foundry/blob/581e059216b36c3e93d70504b0bf3725e25b3ca7/anvil/src/eth/backend/mem/mod.rs#L479
should be:
```
/// Returns an error if EIP2930 is not active (pre berlin)
```

**Comment by mattsse** [comment]
fixed
