### PR TITLE
fix(`config`): properly sanitize evm and solc version if both are set

### LINKED ISSUE #4954: bug(forge): incompatible evm version & solc versions are accepted
### Component

Forge

### Describe the bug

Right now, we have no validation regarding the combination of EVM version and solc version set. And if we auto detect the solidity version, it seems we don't take into account the EVM version as well. While this wasn't an issue for quite a while, this is bound to cause an incredible amount of headaches going forward with 2 different EVM versions being released in the span of a year (Paris and Shanghai).

If the solc version is specified, we should:
- If the EVM version is also set, validate that the combination is compatible.
- If the EVM version is not set, then use an appropiate evm version.

If the solc version is autodetected:
- We should ensure that the EVM version set is compatible with the autodetected version, and if not, use a compatible one (I'm open to erroring here @mattsse but i think the whole point of autodetection is for people to not have to care about this)

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

Closes #4954. Note that this does not handle the case when the solc version is autodetected—I think this might need a change in ethers-solc?

If both solc and evm version are set in the foundry config, we should ensure both are compatible. A solc/evm version combo is compatible when using an specific solc version won't introduce invalid opcodes that the EVM version can't handle. In the solc versions currently supported by forge, this only really happens with using `>=0.8.20` on evm versions less than Shanghai.*

* Technically, different evm chains also could have problems with newer specs, but handling this at a multi-chain level is another conversation in itself.

## Solution

Sanitize the EVM version / solc combo if both are set.

### CODE REVIEW

**Review by Un4G173N — COMMENTED** [review]
""

File: config/src/lib.rs [hunk 1]
```diff
@@ -558,6 +559,27 @@ impl Config {
...
     }
 
+    /// Sanitizes the EVM version and solc version combination used in the config if both are set.
+    pub fn sanitize_evm_version(&mut self) -> Result<(), ExtractConfigError> {
+        if let Some(SolcReq::Version(version)) = &self.solc {
+            // Users should not be able to both specify a solc version equal or higher to
+            // 0.8.20 and an EVM version lower than Shanghai, as this
+            // could introduce PUSH0 opcodes into the code that would be
+            // considered invalid in a chain that does not support EIP 3855.
+            if version >= &Version::new(0, 8, 20) && self.evm_version < EvmVersion::Shanghai {
```
Comment (mattsse) [inline config/src/lib.rs:569]: this looks correct

**Review by mattsse — APPROVED** [review]
this is a side-effect of the introduced evm_version config, 
makes sense to check that they are compatible past shanghai.

Isn't the new opcode a breaking compiler change? not sure what the motivation was to release this as patch release.
