### PR TITLE
fix: error handling with retries when waiting for receipt

### LINKED ISSUE #9636: bug(`forge script`): `Failure on receiving a receipt, server returned a null response when a non-null response was expected`
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

uses: foundry-rs/foundry-toolchain@v1

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

I run workflow on ubuntu-22.04
there're like 100+ txs in script
```
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

          forge script script/deploy.s.sol:DeployScript \
            --slow \
            --rpc-url ${{ env.RPC }} \
            --private-key ${{ secrets.PRIVATE_KEY }} \
            --broadcast \
```

always got error: 
```
Error: Failure on receiving a receipt for 0x37949a9954e1....d679f0a8601879c5bc314bceee8:
server returned a null response when a non-null response was expected

 Add `--resume` to your command to try and continue broadcasting
        the transactions.
```

but tx has been comfirmed onchain, also I tried serval rpcs and failed

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
closes #9636 

## Solution
- use `Retry` utility. add `Continue` variant to preserve number of retries (without decrementing)
- use `Continue` on watcher timeout err if tx is still known to the node (won't count as a retry). For all other errs use `Retry`
- tested with 100 txes on base sepolia

### CODE REVIEW

**Comment by grandizzy** [comment]
@klkvr do you think this makes sense in context of https://github.com/foundry-rs/foundry/issues/9636#issuecomment-2576908064 ?

**Comment by klkvr** [comment]
I don't think this will address the issue as we're hitting error in different arm https://github.com/foundry-rs/foundry/issues/9636#issuecomment-2579603513

we could consider retrying several fatal errors instead of immidiately returning here https://github.com/foundry-rs/foundry/blob/b4a47336038cd4d1342eedb3f9555772585e745f/crates/script/src/receipts.rs#L51-L52

**Comment by grandizzy** [comment]
> I don't think this will address the issue as we're hitting error in different arm [#9636 (comment)](https://github.com/foundry-rs/foundry/issues/9636#issuecomment-2579603513)
> 
> we could consider retrying several fatal errors instead of immidiately returning here
> 
> https://github.com/foundry-rs/foundry/blob/b4a47336038cd4d1342eedb3f9555772585e745f/crates/script/src/receipts.rs#L51-L52

yeah, that's what I wanted with https://github.com/foundry-rs/foundry/pull/9650/files#diff-40b142bf1cc0e034c56533fad30c71161b2cc0b4dd4d6a72468e0649e3c7002dR61-R66 what do I miss? thank you!

**Comment by klkvr** [comment]
ah missed that second branch has changed too

lgtm but I'd keep `provider.get_transaction_by_hash` below so it runs for both cases

File: crates/script/src/receipts.rs [hunk 1]
```diff
@@ -39,6 +39,7 @@ pub async fn check_tx_status(
             return Ok(receipt.into());
         }
 
+        let mut retries = 0;
```
Comment (DaniPopes) [inline crates/script/src/receipts.rs:42]: can we use the retry utility here

Comment (grandizzy) [reply crates/script/src/receipts.rs:42]: I am not sure we can since `retries` within `Retry` utility applies for all errors (while in this case we want to apply retry only for fatal errors while for timeout error we want to loop until receipt is available). does this make sense?

Comment (DaniPopes) [reply crates/script/src/receipts.rs:42]: That's what the "until_break" variant is for. I would prefer using the Retry struct because it also emits a warning when retrying.

File: crates/script/src/receipts.rs [hunk 2]
```diff
@@ -48,8 +49,13 @@ pub async fn check_tx_status(
...
                 // do nothing on timeout, we will check whether tx is dropped below
                 Err(PendingTransactionError::TxWatcher(WatchTxError::Timeout)) => {}
-                // treat other errors as fatal
-                Err(e) => return Err(e.into()),
+                // treat other errors as fatal, with retries
+                Err(e) => {
+                    if retries == 3 {
+                        return Err(e.into())
+                    }
+                    retries += 1;
```
[the remark this answers is not in the document]
Comment (DaniPopes) [reply crates/script/src/receipts.rs:57]: This is what `Retry` is for.

File: crates/script/src/receipts.rs (hunk 1 above)
Comment (grandizzy) [reply crates/script/src/receipts.rs]: @DaniPopes pls check https://github.com/foundry-rs/foundry/pull/9650/commits/c35a798669670848853aac05ee9d29dbab7f085e with `Continue` variant. I have tested it on base sepolia with 100 txes but granted it doesn't cover all potential scenarios. One thing to notice is that progress bar becomes flaky now when a retry as `Retry` utility prints warning

**Review by DaniPopes — APPROVED** [review]
