### PR TITLE
Fix single broadcast/prank nonce setting

### LINKED ISSUE #5635: `vm.broadcast()` sets incorrect nonce for txs
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a0a31c3 2023-08-12T00:23:12.943797000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

```solidity
contract NonceBug is Script {
    function run() public payable {
        vm.broadcast(1);
        IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48).approve(
            address(1), 1000
        );

        vm.broadcast(1);
        IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48).approve(
            address(1), 1000
        );
    }
}
```
Dry-running following script on mainnet will generate two transactions with the same nonce for the same sender:
```
{
  "transactions": [
    {
        ...
        "nonce": "0x661",
        "accessList": []
      },
      ...
    },
    {
        ...
        "nonce": "0x661",
        "accessList": []
      },
      ...
    }
  ],
...
}
```

When adding --broadcast flag, script will fail with error `EOA nonce changed unexpectedly while sending transactions`

I have tracked the issue down to this line of code: https://github.com/foundry-rs/foundry/blob/410c8173e76b9fa42864e2d63309cd7cc4b6cfd9/crates/evm/src/executor/inspector/cheatcodes/mod.rs#L727
And it seems to be actually increasing nonce to correct next value. But somehow on the next broadcast it becomes the old value again.

Another interesting thing here is that following script would generate correct nonces:
```solidity
contract NonceBug is Script {
    function run() public payable {
        vm.broadcast(1);
        address(0).call("");

        vm.broadcast(1);
        address(0).call("");
    }
}

```
```
{
  "transactions": [
    {
        ...
        "nonce": "0x661",
        "accessList": []
      },
      ...
    },
    {
        ...
        "nonce": "0x662",
        "accessList": []
      },
      ...
    }
  ],
...
}
```

Also, using `vm.startBroadcast()/vm.stopBroadcast()` instead of `vm.broadcast()` solves the issue too.

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation
Closes #5635

## Solution

Remove single call broadcast/prank from cheatcodes inspector only when we have came back to the broadcast/prank initialization depth

I think this should get a careful review from someone with deep knowledge of evm crate architecture

### CODE REVIEW

**Comment by nhtyy** [comment]
Nice! This makes sense to me wrt the delegatecall issue. 

but i don't think this will fix the issue of the flag being cleared if there is two `broadcast` calls in the same script 

maybe @Evalir can clear up semantics here

**Comment by klkvr** [comment]
The issue actualy happens not only with delegatecalls, but with any broadcasted calls which result in subsequent calls to other contracts.

For me it solved the issue with two broadcasts in the same script which I explained in the issue

**Comment by nhtyy** [comment]
oh yeah @klkvr just tested and you're totally right my bad

while it is true that `broadcast` is set to None, on the next `vm.broadcast`, which is a call to the HEVM address, theres a "hook" in the cheatcode inspector that leads to this function

https://github.com/foundry-rs/foundry/blob/95a93cd397f25f3f8d49d2851eb52bc2d52dd983/crates/evm/src/executor/inspector/cheatcodes/env.rs#L110-L128

So ya great find and great fix!

File: crates/evm/src/executor/inspector/cheatcodes/mod.rs [hunk 1]
```diff
@@ -758,20 +758,21 @@ impl<DB: DatabaseExt> Inspector<DB> for Cheatcodes {
         if let Some(prank) = &self.prank {
             if data.journaled_state.depth() == prank.depth {
                 data.env.tx.caller = h160_to_b160(prank.prank_origin);
-            }
-            if prank.single_call {
-                std::mem::take(&mut self.prank);
+
+                if prank.single_call {
+                    std::mem::take(&mut self.prank);
+                }
```
Comment (Evalir) [inline crates/evm/src/executor/inspector/cheatcodes/mod.rs:764]: Let's add docs on the rationale as to why this is applied iff the outer `if` runs—it's a change on the previous behavior and I'm a bit apprehensive it might "fix" (or break) behavior that has come to be expected. Will test this locally

File: crates/evm/src/executor/inspector/cheatcodes/mod.rs [hunk 2]
```diff
@@ -758,20 +758,21 @@ impl<DB: DatabaseExt> Inspector<DB> for Cheatcodes {
...
 
         // Clean up broadcast
         if let Some(broadcast) = &self.broadcast {
             if data.journaled_state.depth() == broadcast.depth {
                 data.env.tx.caller = h160_to_b160(broadcast.original_origin);
-            }
 
-            if broadcast.single_call {
-                std::mem::take(&mut self.broadcast);
+                if broadcast.single_call {
```
Comment (Evalir) [inline crates/evm/src/executor/inspector/cheatcodes/mod.rs:773]: ditto here and the others

**Comment by klkvr** [comment]
Hey @evalir, I have added some comments. However, IMO, the previous behavior was slightly less intuitive. I'm not entirely sure if we actually need an explanation here. The broadcast cleaning outside of the `if data.journaled_state.depth() == broadcast.depth` condition resulted in the logic inside that `if` statement not being executed in certain cases. So, the current implementation looks more suspicious to me. But yes, it really needs review and should be documented if we decide to keep the current behavior
