### PR TITLE
fix: fuzz console log

### LINKED ISSUE #7928: Logs are not displayed when for functions that take fuzzing varilables
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

string memory greet = hello.greet(); forge 0.2.0 (4aa17bc 2024-05-14T00:18:17.189981000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Test methods that utilize fuzzing arguments don't generate logs. For instance, I have two test methods that should emit logs. The first method, test2, doesn't use fuzzing and logs correctly. However, the second method, test3, which accepts fuzzing variables, fails to emit logs for some reason.

The example is below.

The test code:
```solidity
contract HelloWorldTest is Test {
    HelloWorld hello;
    function setUp() public {
      hello = new HelloWorld("Foundry is fast!");
    }

    function test2() public {
        assertEq(hello.version(), 0);
        hello.updateGreeting("Hello World");
        assertEq(hello.version(), 1);
        string memory greet = hello.greet();
        emit log(greet);
        assertEq(
            hello.greet(),
            "Hello World"
        );
    }


    function test3(string memory __greeting) public {
        assertEq(hello.version(), 0);
        hello.updateGreeting(__greeting);
        assertEq(hello.version(), 1);
        string memory greet = hello.greet();
        emit log(greet);
        assertEq(
            hello.greet(),
            __greeting
        );
    }
}
```

Testing command:
`forge test -vv`

Expected output:
```
[⠊] Compiling...
No files changed, compilation skipped

Ran 2 tests for test/HelloWorld.t.sol:HelloWorldTest
[PASS] test2() (gas: 45690)
Logs:
  Hello World

[PASS] test3(string) (runs: 256, μ: 68326, ~: 46301)
Logs:
  dfghjhghjhghjkjh
Suite result: ok. 2 passed; 0 failed; 0 skipped; finished in 20.23ms (19.85ms CPU time)

Ran 1 test suite in 160.79ms (20.23ms CPU time): 2 tests passed, 0 failed, 0 skipped (2 total tests)
```

Actual output:
```
[⠊] Compiling...
No files changed, compilation skipped

Ran 2 tests for test/HelloWorld.t.sol:HelloWorldTest
[PASS] test2() (gas: 45690)
Logs:
  Hello World

[PASS] test3(string) (runs: 256, μ: 68326, ~: 46301)
Suite result: ok. 2 passed; 0 failed; 0 skipped; finished in 20.23ms (19.85ms CPU time)

Ran 1 test suite in 160.79ms (20.23ms CPU time): 2 tests passed, 0 failed, 0 skipped (2 total tests)
```

There are no logs for `test3`.

### PR DESCRIPTION
**Pull request by Azleal**
## Motivation

**Closes #7928  #3843 **
when using fuzz test, `console.log` doesn't work as expected(display console log info). this PR is to fix `console.log` in fuzz test

## Solution
current version of foundry only keep the logs for failed fuzz test case. so in this PR, added `logs` to keep logs in every `CaseOutcome` and display logs for every run case in a fuzz test.

### CODE REVIEW

**Comment by Azleal** [comment]
I tried to figure out how to add a test as instructed [here](https://github.com/foundry-rs/foundry/blob/master/CONTRIBUTING.md), but I didn't figure it out. appreciate if anyone could kindly point out how to add one, i'll recommit this PR. thanks

**Review by mattsse — COMMENTED** [review]
wdyt @grandizzy ?

**Comment by grandizzy** [comment]
> I tried to figure out how to add a test as instructed [here](https://github.com/foundry-rs/foundry/blob/master/CONTRIBUTING.md), but I didn't figure it out. appreciate if anyone could kindly point out how to add one, i'll recommit this PR. thanks

I think a test for this could be done similar to https://github.com/foundry-rs/foundry/pull/7544/files#diff-815e5f4f8a07901e1a8da4960e8334a0ba54a5bbd94ce5c620a7bd24ec1f36e9R530-R578 where it basically runs forge test -vv and then make sure it prints logs properly

```solidity
function testConsoleLogFromFunction() public {
    console.log("logging from function");
}
```
and make sure you get in output the 
```
Logs:
  logging from function
```
sequence

**Comment by Azleal** [comment]
> > I tried to figure out how to add a test as instructed [here](https://github.com/foundry-rs/foundry/blob/master/CONTRIBUTING.md), but I didn't figure it out. appreciate if anyone could kindly point out how to add one, i'll recommit this PR. thanks
> 
> I think a test for this could be done similar to https://github.com/foundry-rs/foundry/pull/7544/files#diff-815e5f4f8a07901e1a8da4960e8334a0ba54a5bbd94ce5c620a7bd24ec1f36e9R530-R578 where it basically runs forge test -vv
> 
> ```solidity
> /// forge-config: default.fuzz.runs = 1
> function testConsoleLogFromFunction(uint256 x) public {
>     console.log("logging from function");
> }
> ```
> 
> and then make sure it prints logs properly by checking output for
> 
> ```
> Logs:
>   logging from function
> ```
> 
> sequence

@grandizzy Thank you for your reference. I added a test for fuzz test console log.

**Comment by Azleal** [comment]
Hi @mattsse @grandizzy , I'm wondering if my updated PR meets the requirements for testing. If not, I'd like to discuss further and make improvements. hope to see this feature included in the next release soon.

File: crates/evm/evm/src/executors/fuzz/mod.rs [hunk 1]
```diff
@@ -127,7 +131,9 @@ impl FuzzedExecutor {
                     // to run at least one more case to find a minimal failure
                     // case.
                     let call_res = _counterexample.1.result.clone();
+                    let _logs = _counterexample.1.logs.clone();
```
Comment (grandizzy) [inline crates/evm/evm/src/executors/fuzz/mod.rs:134]: I think this can be one liner as `logs.borrow_mut().extend(_counterexample.1.logs.clone());`

**Comment by grandizzy** [comment]
> Hi @mattsse @grandizzy , I'm wondering if my updated PR meets the requirements for testing. If not, I'd like to discuss further and make improvements. hope to see this feature included in the next release soon.

I think that's a really cool addition, would be nice to have such for invariant tests as well, but out of the scope of this PR. @mattsse @DaniPopes pls have a look :pray:

File: crates/evm/evm/src/executors/fuzz/mod.rs (hunk 1 above)
Comment (Azleal) [reply crates/evm/evm/src/executors/fuzz/mod.rs]: @grandizzy thank you for pointing it out, one liner is much cleaner.

**Comment by Azleal** [comment]
> > Hi @mattsse @grandizzy , I'm wondering if my updated PR meets the requirements for testing. If not, I'd like to discuss further and make improvements. hope to see this feature included in the next release soon.
> 
> I think that's a really cool addition, would be nice to have such for invariant tests as well, but out of the scope of this PR. @mattsse @DaniPopes pls have a look 🙏

I'll dig into invariant tests console logging after this PR closed

**Comment by Azleal** [comment]
> > Hi @mattsse @grandizzy , I'm wondering if my updated PR meets the requirements for testing. If not, I'd like to discuss further and make improvements. hope to see this feature included in the next release soon.
> 
> I think that's a really cool addition, would be nice to have such for invariant tests as well, but out of the scope of this PR. @mattsse @DaniPopes pls have a look 🙏

hi @grandizzy @mattsse @DaniPopes , it's been a while since this PR was committed. i'm using this feature by building foundry locally. and i noticed many others need this feature too. so i wonder if there's anything that i can do to push this forward? please don't hesitate to comment if anything that i can do. thanks for your time.

File: crates/evm/evm/src/executors/fuzz/mod.rs [hunk 2]
```diff
@@ -146,8 +151,8 @@ impl FuzzedExecutor {
             success: run_result.is_ok(),
             reason: None,
             counterexample: None,
-            decoded_logs: decode_console_logs(&call.logs),
-            logs: call.logs,
+            decoded_logs: decode_console_logs(&logs.clone().into_inner()),
+            logs: logs.into_inner(),
```
Comment (mattsse) [inline crates/evm/evm/src/executors/fuzz/mod.rs:155]: this clone can be avoided by tmp converting into_inner and borrow from there.

**Review by mattsse — CHANGES_REQUESTED** [review]
sgtm,

only have one smol nit, ptal @grandizzy

**Comment by grandizzy** [comment]
lgtm, pls address the nit above

File: crates/evm/evm/src/executors/fuzz/mod.rs (hunk 2 above)
Comment (Azleal) [reply crates/evm/evm/src/executors/fuzz/mod.rs]: > this clone can be avoided by tmp converting into_inner and borrow from there.

how about this? @mattsse

**Comment by j-vp** [comment]
I believe this commit causes the more verbose test runs to have extremely large outputs, especially on high-fuzz github actions (ie: 2000 runs, 500 tests, 2-3 bounds/test = a lot of logging).

Even on local tests, using -vvv to get failing test traces, this now becomes unworkable.

**Comment by grandizzy** [comment]
that's correct, it is because bounds are logged in forge std
https://github.com/foundry-rs/forge-std/blob/d44c4fbbb9ff054fb334babbdd34f9b6e899b3d6/src/StdUtils.sol#L62
https://github.com/foundry-rs/forge-std/blob/d44c4fbbb9ff054fb334babbdd34f9b6e899b3d6/src/StdUtils.sol#L87

@mattsse I am going to revert this commit for now as it looks it needs some more work
@mds1 do you know any reason for Result bound to be logged in forge-std while others are not?

**Comment by grandizzy** [comment]
> So this PR now print console logs for every iteration of a fuzz set? I think previously we only printed them for the last successful run? Printing for every run feels extremely noisy
> 
> But the reason we log the `bound` result is to make debugging failed fuzz tests easier to reason about, and to simplify creating test cases to reproduce the failure with

gotcha, we have to re evaluate the proper way to implement such to avoid all the noise
