### PR TITLE
fix(verify): cached artifacts by version

### LINKED ISSUE #9510: Error: No matching artifact found
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e520767 2024-12-06T00:23:08.381567000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Intel)

### Describe the bug

```
forge verify-contract --num-of-optimizations 400 --watch --constructor-args 0x --compiler-version 0.8.20+commit.a1b79de6 0x6df7bf308ABaf673f38Db316ECc97b988CE1Ca78 src/mixins/Create3Factory.sol:Create3Factory [...]

Error: No matching artifact found for Create3Factory
```

foundryup to an older version like `foundryup -v nightly-f3376a6e45ffacd45125e639e5f50bec0c0900be` and now it works.

see repo here:
https://github.com/0xCalibur/foundry-issue

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #9510 

Similarly with https://github.com/foundry-rs/foundry/pull/9483
Try to retrieve artifacts from cache by version without build metadata too if cached artifacts and artifact not found by version arg.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]

File: crates/verify/src/verify.rs [hunk 1]
```diff
@@ -321,7 +322,14 @@ impl VerifyArgs {
...
                     .artifacts
                     .get(&contract.name)
-                    .and_then(|artifacts| artifacts.get(&version))
+                    .and_then(|artifacts| {
+                        let mut cached_artifacts = artifacts.get(&version);
+                        if cached_artifacts.is_none() && version.build != BuildMetadata::EMPTY {
+                            version.build = BuildMetadata::EMPTY;
+                            cached_artifacts = artifacts.get(&version);
+                        }
+                        cached_artifacts
```
Comment (zerosnacks) [inline crates/verify/src/verify.rs:331]: would you mind adding a clarifying comment here explaining under what circumstances this could happen?

**Review by zerosnacks — APPROVED** [review]

File: crates/verify/src/verify.rs (hunk 1 above)
Comment (zerosnacks) [reply crates/verify/src/verify.rs]: Thanks!
