### PR TITLE
fix(anvil): Otterscan searchTransactions behavior

### LINKED ISSUE #7516: Otterscan ots_searchTransactionsBefore, ots_searchTransactionsAfter: incorrect firstPage lastPage and ordering
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9881e7d 2024-03-28T00:18:02.827635071Z)

### What command(s) is the bug in?

_No response_

### Operating System

Linux

### Describe the bug

After running anvil:
```
./anvil
```

* `ots_searchTransactionsBefore` on an account with no activity (0 transactions) yields `lastPage: false` when it should be `lastPage: true`:
```
curl http://localhost:8545 -X POST -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"ots_searchTransactionsBefore","params":["0x0000000000000000000000000000000000000000", 0, 25],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"txs":[],"receipts":[],"firstPage":true,"lastPage":false}}
```

* `ots_searchTransactionsAfter` (equivalent to starting from the last page) on an account with no activity (0 transactions) yields `firstPage: false` and `lastPage: false` when it should be `firstPage: true` and `lastPage: true`:
```
curl http://localhost:8545 -X POST -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"ots_searchTransactionsAfter","params":["0x0000000000000000000000000000000000000000", 0, 25],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"txs":[],"receipts":[],"firstPage":false,"lastPage":false}}
```

~* `ots_searchTransactionsAfter` returns `firstPage: false` when the first page is reached. (After sending 27 transactions)~ (actually I think this is just Otterscan re-trying the same request due to the next point)

* Results returned by `ots_searchTransactionsAfter` are not in reverse order (newest to oldest)

Suggestions for fixing:
* For both RPC methods, `firstPage` and `lastPage`, handle the case where the address has zero transactions.
* For `ots_searchTransactionsAfter`, make sure the results are in reverse order.

### PR DESCRIPTION
**Pull request by sealer3**
Fixes #7516.

## Motivation

Anvil's `ots_searchTransactionsBefore` and `ots_searchTransactionsAfter` are not compliant to the specification, making transaction navigation in Otterscan buggy when using an Anvil backend.

## Solution

This PR fixes multiple bugs in the `ots_searchTransactionsBefore` and `ots_searchTransactionsAfter` implementations, namely fulfilling that

* Results must be given in reverse chronological order for both functions
* `firstPage` indicates that the results include the most recent transaction
* `lastPage` indicates that the results include the oldest transaction
* Scanning must continue even after the page of results is filled in order to check whether this is the first/last page
* Results should only include transactions before/after the block number provided as a parameter, rather than including transactions inside that block
* Results may include more than `pageSize` transactions if the final block searched extends the list by more than the page size
* Results should include contract creation transactions if the address is the creator
* Results should include the contract creation transaction if the address is the created contract

These changes follow the intricacies of the method as outlined here: https://github.com/otterscan/otterscan/blob/develop/docs/custom-jsonrpc.md#ots_searchtransactionsbefore-and-ots_searchtransactionsafter

### CODE REVIEW

File: crates/anvil/src/eth/otterscan/api.rs [hunk 1]
```diff
@@ -183,51 +174,41 @@ impl EthApi {
...
-        } else {
-            block_number
-        };
+        let first_block = self.get_fork().map(|f| f.block_number() + 1).unwrap_or(1);
+        let from = if block_number == 0 { first_block } else { block_number + 1 };
         let to = best;
 
-        let first_page = from == best;
+        let mut first_page = from >= best;
         let mut last_page = false;
```
Comment (DaniPopes) [inline crates/anvil/src/eth/otterscan/api.rs:182]: nit: I believe you can use [`Itertools::with_position`](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.with_position) to not calculate `first`/`last` variables manually

Comment (sealer3) [reply crates/anvil/src/eth/otterscan/api.rs:182]: I suppose in both methods I can replace `n == to` with `pos == Position::Last` (lmk if you want this change and I will be happy to do it). However, the `first_page` and `last_page` booleans in the response refer to the entire list of transactions (does the response include the most recent transaction that ever touches this address? does it include the oldest one?), whereas the range of blocks in this loop might just be a subset of that complete range.

Comment (sealer3) [reply crates/anvil/src/eth/otterscan/api.rs:182]: Looking at this again, since we can't determine both `first_page` and `last_page` from the iterator, I think it would be clearer to keep the code as is.

Comment (DaniPopes) [reply crates/anvil/src/eth/otterscan/api.rs:182]: OK with this

**Comment by DaniPopes** [comment]
@mattsse ptal

**Review by mattsse — APPROVED** [review]
thx, this looks correct
