### PR TITLE
fix(anvil): include total difficulty

### LINKED ISSUE #3154: Anvil missing block totalDifficulty information
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f540aa9 2022-09-09T00:09:51.262286Z)

### What command(s) is the bug in?

_No response_

### Operating System

macOS (Intel)

### Describe the bug

Anvil does not appear to track `totalDifficulty` when mining blocks.

### Reproduction steps
1. Fork ethereum mainnet using default Anvil settings:
```
% anvil --fork-url https://some-forkable-url
```

2. The last recorded block shows a `totalDifficulty`:
```
% cast block 15504216

...
timestamp            1662747868
totalDifficulty      58344397744196789300626
transactions:        [
...
```

3. Perform a payment using the provided accounts:
```
% cast send 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 --value 1 --from 0x70997970c51812dc3a010c7d01b50e0d17dc79c8
```

7. The produced block does not show a `totalDifficulty`:
```
% cast block 15504217

...
timestamp            1662747957
totalDifficulty      
transactions:        [
...
```

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #3154

include total difficulty in the `Block` response

## Solution
the total difficulty will be either 0, or will have the value of the forked block in forking mode, this is rather a hotfix to provide compatibility for tools that require this info

wdyt @mootz12

### CODE REVIEW

**Comment by mootz12** [comment]
```
the total difficulty will be either 0, or will have the value of the forked block in forking mode
```
seems perfectly reasonable to me. Thanks for the quick response 😄

File: anvil/src/config.rs [hunk 1]
```diff
@@ -715,7 +715,7 @@ impl NodeConfig {
                 env.block = BlockEnv {
                     number: fork_block_number.into(),
                     timestamp: block.timestamp,
-                    difficulty: block.difficulty,
+                    difficulty: Default::default(),
```
Comment (gakonst) [inline anvil/src/config.rs:718]: should this remain as `block.difficulty`?

Comment (mattsse) [reply anvil/src/config.rs:718]: oh right, this is not a good change since this affects the `block.difficulty` var, 

my thinking here was if we remove it here, it will essentially freeze the `totalDifficulty`.

what should we do with the difficulty after the first block "mined" by anvil itself, should we just continue to use the `difficulty` of the block we forked off or `0`.

if we continue to use the difficulty of the forked block, or something else non zero then this PR needs a bit more work because then we need to track the totalDifficulty on a per block basis.

Comment (gakonst) [reply anvil/src/config.rs:718]: i see. let's give the 'simpler' approach a try and see if anybody complains..

**Comment by mattsse** [comment]
we now set the difficulty for new blocks to `0` while also accounting for the difficulty of the forked block.

**Review by rkrasiuk — APPROVED** [review]
