### PR TITLE
fix(`invariant`): support assertions on handlers

### LINKED ISSUE #4718: Function-level assertions don't work when using invariants.
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (388c3c0 2023-04-10T00:15:22.461433000Z)

### What command(s) is the bug in?

forge test -m invariant

### Operating System

macOS (Apple Silicon)

### Describe the bug

According to the [invariant testing documentation](https://book.getfoundry.sh/forge/invariant-testing#function-level-assertions) in the foundry book it is possible to use function-level assertions in a handler. However, this doesn't seem to work. Minimal working example:

**Counter.sol**
```solidity
contract Counter {
    uint256 public number;

    function setNumber(uint256 newNumber) public {
        if(newNumber != 100) {
            number = newNumber;
        } 
    }
}
````

**CounterHandler.sol**
```solidity
contract CounterHandler is Test {
    Counter counter;

    constructor(Counter _counter) {
        counter = _counter;
    }

    function setNumber(uint256 newNumber) public {
        counter.setNumber(newNumber);
        assertEq(uint(0), uint(1));
        assertTrue(false);
    }
}
````

**CounterInvariants**
```solidity
contract CounterInvariants is Test {
    Counter counter;
    CounterHandler handler;

    function setUp() public {
        counter = new Counter();
        handler = new CounterHandler(counter);
        targetContract(address(handler));
    }

    function invariant_numberNotZero() public {
        assertEq(counter.number() != 100, true);
    }
}
```

As shown in the CounterHandler contract I've introduced some assertions that should fail such as `assertTrue(false)` and `assertEq(uint(0), uint(1))`. However, when running the invariant test it will succeed.
image

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

Closes #4718.

## Solution

The targeted contracts were not being checked for `DSTest` assertions—which means assertions were never going to work. We now check for these when checking if the depth runs can continue. This should not be an issue if the targeted contracts do not inherit `DSTest`.

### CODE REVIEW

File: evm/src/fuzz/invariant/executor.rs [hunk 1]
```diff
@@ -551,17 +554,28 @@ fn collect_data(
 
 /// Verifies that the invariant run execution can continue.
 /// Returns the mapping of (Invariant Function Name -> Call Result) if invariants were asserted.
+#[allow(clippy::too_many_arguments)]
```
Comment (Evalir) [inline evm/src/fuzz/invariant/executor.rs:557]: sign that invariants need to be refactored... they took a while to understand 😅

File: evm/src/fuzz/invariant/executor.rs [hunk 2]
```diff
@@ -551,17 +554,28 @@ fn collect_data(
...
     shrink_sequence: bool,
 ) -> (bool, Option<BTreeMap<String, RawCallResult>>) {
     let mut call_results = None;
-    if !call_result.reverted {
+
+    // Detect handler assertion failures first.
+    let handlers_failed = targeted_contracts
+        .lock()
+        .iter()
+        .any(|contract| !executor.is_success(*contract.0, false, state_changeset.clone(), false));
```
Comment (Evalir) [inline evm/src/fuzz/invariant/executor.rs:575]: even if the contract does not inherit from DSTest this seems to work well (it should be a noop essentially).

File: evm/src/fuzz/invariant/executor.rs [hunk 3]
```diff
@@ -551,17 +554,28 @@ fn collect_data(
...
 /// Returns the mapping of (Invariant Function Name -> Call Result) if invariants were asserted.
+#[allow(clippy::too_many_arguments)]
 fn can_continue(
     invariant_contract: &InvariantContract,
     call_result: RawCallResult,
     executor: &Executor,
     calldata: &[BasicTxDetails],
     failures: &mut InvariantFailures,
+    targeted_contracts: &FuzzRunIdentifiedContracts,
+    state_changeset: StateChangeset,
```
Comment (mattsse) [inline evm/src/fuzz/invariant/executor.rs:565]: why do we need them here?

looks expensive

Comment (Evalir) [reply evm/src/fuzz/invariant/executor.rs:565]: Right, to support handler assertion on invariants, we need to check if they've failed after execution is done, by checking DSTest's `failed()` func. So we need to check the targeted contracts which will have the handlers. And the fresh state is on the state changeset, so we also need it.

Comment (Evalir) [reply evm/src/fuzz/invariant/executor.rs:565]: Been also briefly testing this for any performance regression, doesn't seem to have any significant impact. On average a whole invariant campaign seems to take around 300ms-400ms more.

**Review by mattsse — APPROVED** [review]
