### PR TITLE
fix(forge/script): deployment size check

### LINKED ISSUE #2923: "Max code size exceeded" still remains
In response to @gakonst in https://github.com/foundry-rs/foundry/issues/2619#issuecomment-1226088429_

Reproducible setup:
https://github.com/0xPhaze/foundry-max-code-size

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Deployment sizes check introduced in #2619 would not work for arbitrary bytecode deployed without an artifact and thus pass without errors.

## Solution

Check against bytecodes from both artifacts and traces

Tested with, closes #2923:

Before: https://mumbai.polygonscan.com/tx/0xcf74fcecf15120bcf703598b4f47411f46210a5b6ffcef46a3e3919fd04f629b
(max codesize exceeded revert)

After: 
image

### CODE REVIEW

File: cli/src/cmd/forge/script/mod.rs [hunk 1]
```diff
@@ -451,10 +453,47 @@ impl ScriptArgs {
...
+        // From traces, only push if it was not present already
+        let create_nodes = result.traces.iter().flat_map(|(_, traces)| {
+            traces
+                .arena
+                .iter()
+                .filter(|node| matches!(node.kind(), CallKind::Create | CallKind::Create2))
+        });
+
+        let mut i = 0usize;
+        for node in create_nodes {
```
Comment (mattsse) [inline cli/src/cmd/forge/script/mod.rs:482]: Why do we need the index here?

File: cli/src/cmd/forge/script/mod.rs [hunk 2]
```diff
@@ -451,10 +453,47 @@ impl ScriptArgs {
...
+            if let RawOrDecodedCall::Raw(ref init_code) = node.trace.data {
+                if let RawOrDecodedReturnData::Raw(ref deployed_code) = node.trace.output {
+                    if !bytecodes.iter().any(|(_, b, _)| b == init_code) {
+                        bytecodes.push((format!("Unknown{}", i), init_code, deployed_code));
+                        i += 1;
+                    }
+                    continue
+                }
```
Comment (mattsse) [inline cli/src/cmd/forge/script/mod.rs:490]: could explain this step

**Review by mattsse — COMMENTED** [review]
ty, test look good.

just need some clarification on the added check

File: cli/src/cmd/forge/script/mod.rs (hunk 1 above)
Comment (DaniPopes) [reply cli/src/cmd/forge/script/mod.rs:482]: would be to differentiate multiple unnamed contracts, should be in the same order that the traces are displayed

**Review by mattsse — COMMENTED** [review]
I see, that makes sense

File: cli/src/cmd/forge/script/mod.rs [hunk 3]
```diff
@@ -451,10 +453,50 @@ impl ScriptArgs {
...
+                    // Only push if it was not present already
+                    if !bytecodes.iter().any(|(_, b, _)| b == init_code) {
+                        bytecodes.push((format!("Unknown{}", unknown_c), init_code, deployed_code));
+                        unknown_c += 1;
+                    }
+                    continue
+                }
+            }
+            // Both should be raw and not decoded since it's just bytecode
+            unreachable!("Create data was not raw");
```
Comment (mattsse) [inline cli/src/cmd/forge/script/mod.rs:495]: since this function returns a "result", I would rather return this as an error, even if we assume that it is unreachable

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
