### PR TITLE
fix(cheatcodes): Fix `expectCall` behavior

### LINKED ISSUE #4879: `vm.expectCall` unexpected behavior
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e807429 2023-05-04T00:03:45.171389475Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

`vm.expectCall` is giving contradictory errors when used within a helper function and a loop.

To reproduce:
1. `git clone git@github.com:ScopeLift/umbra-protocol.git`
2. `git checkout expect-call-issue`
3. `cd contracts-periphery/ && cp .env.example .env` and fill in `ETH_RPC_URL` in `.env`
4. `forge test --mc UniswapWithdrawHookTest`

**Relevant lines of codes are at 71-83 and 151-153.**

In this case:
`vm.expectCall(
      address(withdrawHook), abi.encodeWithSelector(withdrawHook.tokensWithdrawn.selector)
    );
`

When you run the test command at step 4. You'll see this error:

```
Failing tests:
Encountered 2 failing tests in test/UniswapWithdrawHook.fork.1.t.sol:UniswapWithdrawHookTest
[FAIL. Reason: Expected at least one call to 0x5991a2df15a8f6a256d3ec51e99254cd3fb576a9 with data 0x579073de, but got **none** Counterexample: calldata=0x3d93c91a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, args=[0, 0, 0, 0]] testFuzz_HookTest_withdrawTokenAndCall(uint256,uint256,uint256,uint256) (runs: 0, μ: 0, ~: 0)
[FAIL. Reason: Expected at least one call to 0x5991a2df15a8f6a256d3ec51e99254cd3fb576a9 with data 0x579073de, but got **none** Counterexample: calldata=0xc410223f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, args=[0, 0, 0, 0]] testFuzz_HookTest_withdrawTokenAndCallOnBehalf(uint256,uint256,uint256,uint256) (runs: 0, μ: 0, ~: 0)
```

If you change the code to:
`vm.expectCall(
      address(withdrawHook), abi.encodeWithSelector(withdrawHook.tokensWithdrawn.selector), **0**
    );
`
and then run the test, you'll see:
```
Failing tests:
Encountered 2 failing tests in test/UniswapWithdrawHook.fork.1.t.sol:UniswapWithdrawHookTest
[FAIL. Reason: Expected call to 0x5991a2df15a8f6a256d3ec51e99254cd3fb576a9 with data 0x579073de to be made 0 time(s), but was called 10 time(s) Counterexample: calldata=0x3d93c91a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, args=[0, 0, 0, 0]] testFuzz_HookTest_withdrawTokenAndCall(uint256,uint256,uint256,uint256) (runs: 0, μ: 0, ~: 0)
[FAIL. Reason: Expected call to 0x5991a2df15a8f6a256d3ec51e99254cd3fb576a9 with data 0x579073de to be made 0 time(s), but was called 10 time(s) Counterexample: calldata=0xc410223f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, args=[0, 0, 0, 0]] testFuzz_HookTest_withdrawTokenAndCallOnBehalf(uint256,uint256,uint256,uint256) (runs: 0, μ: 0, ~: 0)
```

If you change the code to:
`vm.expectCall(
      address(withdrawHook), abi.encodeWithSelector(withdrawHook.tokensWithdrawn.selector), **10**
    );
`
and then run the test, you'll see:
```
Failing tests:
Encountered 2 failing tests in test/UniswapWithdrawHook.fork.1.t.sol:UniswapWithdrawHookTest
[FAIL. Reason: Expected call to 0x5991a2df15a8f6a256d3ec51e99254cd3fb576a9 with data 0x579073de to be made 10 time(s), but was called 0 time(s) Counterexample: calldata=0x3d93c91a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, args=[0, 0, 0, 0]] testFuzz_HookTest_withdrawTokenAndCall(uint256,uint256,uint256,uint256) (runs: 0, μ: 0, ~: 0)
[FAIL. Reason: Expected call to 0x5991a2df15a8f6a256d3ec51e99254cd3fb576a9 with data 0x579073de to be made 10 time(s), but was called 0 time(s) Counterexample: calldata=0xc410223f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, args=[0, 0, 0, 0]] testFuzz_HookTest_withdrawTokenAndCallOnBehalf(uint256,uint256,uint256,uint256) (runs: 0, μ: 0, ~: 0)
```

The expected number of calls should actually be 1:
`vm.expectCall( address(withdrawHook), abi.encodeWithSelector(withdrawHook.tokensWithdrawn.selector), **1**); ` 
But this also fails with the error saying it was called 10 times.

### PR DESCRIPTION
**Pull request by Evalir**
**This is a breaking change.**

Closes #4879.

Implements the intended behavior for the `expectCall` cheatcode, with and without count.

# Behavior

`expectCall` will be invoked in two different modes depending on how the cheatcode was used:
- If no count was provided, the mode will be `NonCount`. The behavior of this mode is:
  - It is **additive**. Calling `expectCall(...)` `N` times, will set a lower bound of expected calls of `N`, but will _not_ revert if more than `N` calls are matched. This is the legacy `expectCall` behavior.
  - For the same calldata, **cannot** be overwritten with a `Count` `expectCall` cheatcode call.

Example of `NonCount` additive behavior:

```
// this will PASS
cheats.expectCall(address(target), abi.encodeWithSelector(target.add.selector, 1, 2));
cheats.expectCall(address(target), abi.encodeWithSelector(target.add.selector, 1, 2));
target.add(1, 2);
target.add(1, 2);
target.add(1, 2);
```

Example of how it cannot be overwritten:
```
// this will FAIL
cheats.expectCall(address(target), abi.encodeWithSelector(target.add.selector, 1, 2));
// Cannot overwrite a non-count expectCall cheatcode call with a count one.
cheats.expectCall(address(target), abi.encodeWithSelector(target.add.selector, 1, 2), 2);
target.add(1, 2);
target.add(1, 2);
target.add(1, 2);
```

- If a count is provided, the mode will be `Count`. The behavior of this mode is:
  - It will match exactly **N** calls and revert if more are found, `N` being the amount of calls to match specified.
  - It is **NOT** additive. Calling `expectCall(..., N)` `M` times will fail. It can only be called **once** if it has a count, even if it is 0.
  - For the same calldata, it cannot be overwritten with any other `expectCall` cheatcode call, with or without count.

This essentially means that for any different calldata, there is only one `expectCall` cheatcode "mode" active. It is either `NonCount` and additive, or `Count` and non-additive. Note that a partial match and a full match is considered different calldata, so you could additively match partial-matches and strictly match full-matches. Tests have been added for each of these cases.

### CODE REVIEW

**Comment by Evalir** [comment]
cc @PaulRBerg — you might be interested in nitpicking this to make sure we are happy with how this is implemented now!

File: evm/src/executor/inspector/cheatcodes/mod.rs [hunk 1]
```diff
@@ -772,43 +786,57 @@ where
 
         // If the depth is 0, then this is the root call terminating
         if data.journaled_state.depth() == 0 {
-            for (address, expecteds) in &self.expected_calls {
-                for (expected, actual_count) in expecteds {
-                    let ExpectedCallData { calldata, gas, min_gas, value, count } = expected;
+            for (address, calldatas) in &self.expected_calls {
```
Comment (Evalir) [inline evm/src/executor/inspector/cheatcodes/mod.rs:789]: As a note-to-self, this and all other "handlers" on the different hooks should probably be abstracted into their own function and properly documented for easy modification later.

File: evm/src/executor/inspector/cheatcodes/mod.rs [hunk 2]
```diff
@@ -126,7 +126,7 @@ pub struct Cheatcodes {
     pub mocked_calls: BTreeMap<Address, BTreeMap<MockCallDataContext, MockCallReturnData>>,
 
     /// Expected calls
-    pub expected_calls: BTreeMap<Address, Vec<(ExpectedCallData, u64)>>,
+    pub expected_calls: BTreeMap<Address, BTreeMap<Bytes, (ExpectedCallData, u64)>>,
```
Comment (Evalir) [inline evm/src/executor/inspector/cheatcodes/mod.rs:129]: This is now storing this information

```
BTreeMap<Address, // -> Target
    BTreeMap<Bytes, // -> Calldata. Selectors are NOT deduped, so partial matches and full matches can be applied.
        (ExpectedCallData, // -> The expected call data to match. Note that the calldata is now held as the key instead of inside this struct.
        u64) // -> The actual amount of times this call was seen
    >
>
````

File: evm/src/executor/inspector/cheatcodes/mod.rs [hunk 3]
```diff
@@ -565,15 +565,29 @@ where
...
+                            .value
+                            .map_or(true, |value| value == call.transfer.value.into()) &&
+                        // The gas matches, if provided
                         expected.gas.map_or(true, |gas| gas == call.gas_limit) &&
+                        // The minimum gas matches, if provided
                         expected.min_gas.map_or(true, |min_gas| min_gas <= call.gas_limit)
-                }) {
-                    *count += 1;
+                    {
+                        *actual_count += 1;
```
Comment (Evalir) [inline evm/src/executor/inspector/cheatcodes/mod.rs:589]: For any of the two modes, the discrimination of how to interpret the actual count is done later—our only job here is detecting if all values properly match for the current call.

File: evm/src/executor/inspector/cheatcodes/mod.rs [hunk 4]
```diff
@@ -772,43 +786,57 @@ where
...
-                    .into_iter()
-                    .flatten()
-                    .join(" and ");
-                    if count.is_none() {
-                        if *actual_count == 0 {
-                            return (
-                                InstructionResult::Revert,
-                                remaining_gas,
-                                format!("Expected at least one call to {address:?} with {expected_values}, but got none")
+                    match call_type {
```
Comment (Evalir) [inline evm/src/executor/inspector/cheatcodes/mod.rs:793]: Match depending of mode:
- `Count`: `count` Must be **strictly** `actual_count`, if not we should fail.
- `NonCount`: `actual_count` must be **at least equal to** `count` (therefore, if we see that `count` is bigger than `actual_count`, we should fail as we didn't see enough calls).

For reference:
- `count`: Amount of times a call must be seen.
- `actual_count` Amount of times a call was actually seen.

**Review by Evalir — COMMENTED** [review]
Some helpful comments for reviewing (I will add more docs to the code nevertheless)

My hope is that we can use this same structure & adapt it for the other `expect*` cheatcodes with count.

File: evm/src/executor/inspector/cheatcodes/expect.rs [hunk 5]
```diff
@@ -220,6 +230,54 @@ fn expect_safe_memory(state: &mut Cheatcodes, start: u64, end: u64, depth: u64)
     Ok(Bytes::new())
 }
 
+#[allow(clippy::too_many_arguments)]
```
Comment (Evalir) [inline evm/src/executor/inspector/cheatcodes/expect.rs:233]: [Cmon, it ain't that bad :)](https://www.youtube.com/watch?v=dRHetRTOD1Q)

**Comment by PaulRBerg** [comment]
Hey @Evalir, thanks very much for this PR, as well as the helpful clarifications.

The proposal looks great; it is a good idea to have two separate modes for `expectCall`. I only have one question about this:

> For the same calldata, cannot be overwritten with a `Count` `expectCall` cheatcode call.

By "cannot", do you mean Foundry will revert, or will it silently ignore the attempt to override the calldata's expect?

**Comment by Evalir** [comment]
Hey @PaulRBerg — Foundry will revert.

File: evm/src/executor/inspector/cheatcodes/expect.rs [hunk 6]
```diff
@@ -220,6 +230,54 @@ fn expect_safe_memory(state: &mut Cheatcodes, start: u64, end: u64, depth: u64)
     Ok(Bytes::new())
 }
```
Comment (mattsse) [inline evm/src/executor/inspector/cheatcodes/expect.rs:232]: can we please add a few docs here what this checks exactly checks and when this is supposed to return a revert

**Review by mattsse — CHANGES_REQUESTED** [review]
few nits.

test lgtm.
seems like this fixes a few issues @PaulRBerg 

@mds1 wdyt?

File: evm/src/executor/inspector/cheatcodes/mod.rs [hunk 7]
```diff
@@ -126,7 +126,7 @@ pub struct Cheatcodes {
     pub mocked_calls: BTreeMap<Address, BTreeMap<MockCallDataContext, MockCallReturnData>>,
 
     /// Expected calls
-    pub expected_calls: BTreeMap<Address, Vec<(ExpectedCallData, u64)>>,
+    pub expected_calls: BTreeMap<Address, BTreeMap<Vec<u8>, (ExpectedCallData, u64)>>,
```
[the remark this answers is not in the document]
Comment (Evalir) [reply evm/src/executor/inspector/cheatcodes/mod.rs]: done in https://github.com/foundry-rs/foundry/pull/4912/commits/ce54d4b4c820e385e539d4371e6a2367498a8790

File: evm/src/executor/inspector/cheatcodes/expect.rs (hunk 6 above)
Comment (Evalir) [reply evm/src/executor/inspector/cheatcodes/expect.rs:232]: done in https://github.com/foundry-rs/foundry/pull/4912/commits/ce54d4b4c820e385e539d4371e6a2367498a8790

**Comment by mds1** [comment]
This is great, thanks a lot @Evalir! Let's also get the book updated with the info from the PR description which is really thorough and helpful 💯

**Review by mattsse — APPROVED** [review]
lgtm, holding off on book changes so we have these before we publish.
