### PR TITLE
respect silent argument in script command

### LINKED ISSUE #4009: Respect --silent argument in script command
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

_No response_

### What command(s) is the bug in?

_No response_

### Operating System

None

### Describe the bug

ref #3981

the `--silent` option is not respected throughout the script command.

printlns should make use of the `shell` when printing output

https://github.com/foundry-rs/foundry/blob/master/common/src/shell.rs

see `forge test` for example:

https://github.com/foundry-rs/foundry/blob/a44159a5c23d2699d3a390e6d4889b89a0e5a5e0/cli/src/cmd/forge/test/mod.rs#L286

### PR DESCRIPTION
**Pull request by i-m-aditya**
## Motivation

Respect --silent argument in forge script command

## Solution

Fixes #4009

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
the command is still using regular `println!`, right?

we'd need to refactor them as well and go trough `shell`

File: cli/src/cmd/forge/script/sequence.rs [hunk 1]
```diff
@@ -110,8 +110,8 @@ impl ScriptSequence {
                 )?),
                 &self,
             )?;
-
-            println!("\nTransactions saved to: {path}\n");
+            shell::println(format!("\nTransactionsdffs saved to: {path}\n"))?;
+            // println!("\nTransactions saved to: {path}\n");
```
Comment (mattsse) [inline cli/src/cmd/forge/script/sequence.rs:114]:
```suggestion
```

File: cli/src/cmd/forge/script/cmd.rs [hunk 2]
```diff
@@ -30,6 +30,10 @@ impl ScriptArgs {
 
         self.maybe_load_private_key(&mut script_config)?;
 
+        if self.opts.args.silent {
+            shell::set_shell(shell::Shell::from_args(true, false))?;
```
Comment (mattsse) [inline cli/src/cmd/forge/script/cmd.rs:34]: can be combined by using `self.opts.args.silent` as argument

**Review by mattsse — CHANGES_REQUESTED** [review]
few nits, otherwise lgtm

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
the failing script tests indicate that something's not behaving as expected
