### PR TITLE
fix: use both indexed and unindexed params when decoding logs

### LINKED ISSUE #6121: Contract events logs are empty
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9fd44a7 2023-10-26T00:16:42.293111408Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Forge stopped returning the transaction logs in one of the releases from the last few days.

Example test:

```solidity
contract DummyTest is Test {
    event DummyEvent(uint256 indexed number);

    function test_expectEventEmit() public {
        vm.expectEmit(true, false, false, false);

       emit DummyEvent(1);

       emit DummyEvent(1);
    }
}
```

With `forge 0.2.0 (9fd44a7 2023-10-26T00:16:42.293111408Z)`:

```
❯ forge test -vvvv
[⠆] Compiling...
No files changed, compilation skipped

Running 1 test for test/Counter.t.sol:DummyTest
[PASS] test_expectEventEmit() (gas: 5442)
Traces:
  [5442] DummyTest::test_expectEventEmit()
    ├─ [0] VM::expectEmit(true, false, false, false)
    │   └─ ← ()
    ├─ emit DummyEvent()   <------- Notice how it doesn't include the number
    ├─ emit DummyEvent()
    └─ ← ()

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 601.15µs

Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

With `forge 0.2.0 (1a1d653 2023-06-14T00:06:40.452758373Z)`:

```
Running 1 test for test/Counter.t.sol:DummyTest
[PASS] test_expectEventEmit() (gas: 5442)
Traces:
  [5442] DummyTest::test_expectEventEmit() 
    ├─ [0] VM::expectEmit(true, false, false, false) 
    │   └─ ← ()
    ├─ emit DummyEvent(number: 1)     <------- But this old version includes the number
    ├─ emit DummyEvent(number: 1)
    └─ ← ()

Test result: ok. 1 passed; 0 failed; finished in 450.80µs
```

### PR DESCRIPTION
**Pull request by Evalir**
Fixes #6121.

This bug happened because we were only adding labels for unindexed params. We now need to restore the order of the indexed and unindexed params as alloy returns them separately, to be able to assign the labels properly.

### CODE REVIEW

File: crates/evm/traces/src/decoder.rs [hunk 1]
```diff
@@ -347,6 +347,7 @@ impl CallTraceDecoder {
                             })
                             .collect(),
                     );
+                    println!("got log {log:?}");
```
Comment (mattsse) [inline crates/evm/traces/src/decoder.rs:350]:
```suggestion
```

File: crates/evm/traces/src/decoder.rs [hunk 2]
```diff
@@ -358,6 +359,25 @@ impl CallTraceDecoder {
...
+            inputs.push(decoded.indexed[indexed].clone());
+            indexed += 1;
+        } else {
+            inputs.push(decoded.body[unindexed].clone());
+            unindexed += 1;
+        }
+    }
+
+    inputs
+}
```
Comment (mattsse) [inline crates/evm/traces/src/decoder.rs:379]: I feel like this should be supported by DecodedEvent perhaps

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
error unrelated?

**Comment by Evalir** [comment]
Yeah? Seems unrelated, from an external integration test that probably changed
