### PR TITLE
fix(forge): fix stack overflow when the lib path is absolute.

### LINKED ISSUE #9127: Stack overflow caused by `FOUNDRY_LIBS` or `DAPP_LIBS` containing absolute paths
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cc8e430 2024-10-16T00:22:08.572482504Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

## Steps to reproduce

1. Push a temporary directory onto the stack

```sh
pushd "$(mktemp -d)" 
```

2. Create a forge project

```sh
forge init
```

3. Build the project with the environment variable `FOUNDRY_LIBS` set to an array that contains an absolute path to a directory. In this case, we use the absolute path to the `lib` folder just created by the `forge init` command.

```sh
FOUNDRY_LIBS=["$(pwd)/lib"] forge build
```

4. This last command will exit with status code 134 and print the following error message.

```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by l1nxy**
## Motivation
Close #9127
The crash is caused by the recursive call of `get_mapping` in the config crate:
https://github.com/foundry-rs/foundry/blob/c6d59b32fad4b78453354b92acfef5a95013b17f/crates/config/src/providers/remappings.rs#L101-L161
The `get_mapping` function calls the `lib_foundry_toml_remappings` function:
https://github.com/foundry-rs/foundry/blob/c6d59b32fad4b78453354b92acfef5a95013b17f/crates/config/src/providers/remappings.rs#L196-L211
In the `lib_foundry_toml_remappings`, it reads config from a nested lib folder. However, when the lib path in `self.lib_paths` is absolute, it uses `self.root.join(lib_path)`, it will produce wrong path if lib_path is absolute.
The join function is described as follows:
> pub fn [join](https://doc.rust-lang.org/std/path/struct.Path.html#method.join)<P: [AsRef](https://doc.rust-lang.org/std/convert/trait.AsRef.html)<[Path](https://doc.rust-lang.org/std/path/struct.Path.html)>>(&self, path: P) -> [PathBuf](https://doc.rust-lang.org/std/path/struct.PathBuf.html)
> Creates an owned [PathBuf](https://doc.rust-lang.org/std/path/struct.PathBuf.html) with path adjoined to self.
> **If the path is absolute, it replaces the current path.**

Therefore, if the lib paths are absolute, they will only return the setting path and recursively search for nested libs.

## Solution
I propose adding a check to determine whether the `lib` path is absolute or not. If it is absolute, we should return the root folder joined by `lib`. Otherwise, we should return just the new path based on lib's relative path.
By the way, I am not sure if setting an absolute path for the `lib` option in config is allowed. If we need to disable it, we can do so and print a warning message to inform users.

### CODE REVIEW

**Comment by zerosnacks** [comment]
Hi @l1nxy thanks for your PR!

Would you mind adding a test case for this?

We have some tests for remappings here: https://github.com/foundry-rs/foundry/blob/ab8ebf667d04eaeb0826adf17cc238c5a6719936/crates/forge/tests/cli/config.rs#L494-L594

File: crates/config/src/providers/remappings.rs [hunk 1]
```diff
@@ -196,7 +196,7 @@ impl RemappingsProvider<'_> {
     fn lib_foundry_toml_remappings(&self) -> impl Iterator<Item = Remapping> + '_ {
         self.lib_paths
             .iter()
-            .map(|p| self.root.join(p))
+            .map(|p| if p.is_absolute() { self.root.join("lib") } else { self.root.join(p) })
```
Comment (mattsse) [inline crates/config/src/providers/remappings.rs:199]: if this is absolute, should we just use `p`? because if absolute this would exclude p entirely?

Comment (l1nxy) [reply crates/config/src/providers/remappings.rs:199]: This is an optional solution because we don't know the actual library path in the current directory, so we need to provide a default path.
My question is: Should we allow setting an absolute library path? If yes, there should be a default library path.

Comment (mattsse) [reply crates/config/src/providers/remappings.rs:199]: I see, I'm leaning towards not allowing/supporting absolute lib paths, so I think the current default to using lib makes sense

Comment (l1nxy) [reply crates/config/src/providers/remappings.rs:199]: Agree, using the default library path can make most libraries work effectively.
If the solution is acceptable, I will add some tests for it.

**Comment by l1nxy** [comment]
@mattsse Any problem?

**Review by mattsse — APPROVED** [review]
makes sense, imo absolute paths should be discouraged
