### PR TITLE
fix(build): use output graph/artifacts rather than sources

### LINKED ISSUE #12018: bug(build): lack of analysis capabilities on cached runs
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

_No response_

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

_No response_

### Operating System

None

### Describe the bug

`fn configure_pcx_from_compile_output` relies on `ProjectCompileOutput.sources()` to figure out the sources that solar should ingest. However, when the source code doesn't change between compiler runs, compilation is skipped and sources is empty.

This behavior wasn't caught by unit tests, and causes solar analysis capabilities to only be available on the first test run.

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

closes #12018 

## Solution

use `ProjectCompilerOutput.graph().source_files()` and `ProjectCompilerOutput.artifact_ids()` rather than `.sources()`

## PR Checklist

- [X] Added Tests
- [X] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/forge/tests/cli/json.rs [hunk 1]
```diff
@@ -56,9 +51,21 @@ contract SimpleJsonCheatsTest is Test {
...
-    );
+"#;
+
+// tests enhanced `vm.parseJson` and `vm.serializeJson` cheatcodes, which are not constrained to
+// alphabetical ordering of struct keys, but rather respect the Solidity struct definition.
+forgetest_init!(test_parse_json, |prj, cmd| {
+    prj.add_test("JsonCheats", TEST_CONTRACT);
 
     // Directly run the test. No `bind-json` or type schemas are needed.
     cmd.forge_fuse().args(["test"]).assert_success();
```
Comment (DaniPopes) [inline crates/forge/tests/cli/json.rs:63]: can we not have it in one test
