### PR TITLE
fix: put metadata in artifact instead separate file

### LINKED ISSUE #2969: Output of Metadata by default "broke" compatibility with typechain tool
### Component

Forge

### Describe the feature you would like

As of https://github.com/foundry-rs/foundry/pull/2798, typechain can no longer process the "out" abi folder: "Error occured: Not a valid ABI". 

If there is no simple way around this, I would suggest adding a flag/option to disable its output. Alternatively, keep this data in a separate folder, so that it doesn't get mixed with the ABI files in the "glob" typechain parameter.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #2969

@rkrasiuk do we have a sourcify test?

## Solution
instead of emitting the metadata as separate file, we put it in the artifact itself

sourcify verification is then still possible by extracting the metadata from the artifact

### CODE REVIEW

**Comment by rkrasiuk** [comment]
@mattsse we have tests covering sourcify on `create --verify`
https://github.com/foundry-rs/foundry/blob/f8fe940277323c83794b17a93312f9085b560165/cli/tests/it/verify.rs#L156

File: cli/src/cmd/forge/verify/sourcify.rs [hunk 1]
```diff
@@ -51,19 +31,37 @@ impl VerificationProvider for SourcifyVerificationProvider {
...
+        }
 
-        let mut files = HashMap::new();
+        let mut files = HashMap::with_capacity(2 + entry.imports.len());
 
-        let filename = path.file_name().unwrap().to_str().unwrap().to_owned();
-        let metadata_path =
-            config.out.join(&filename).join(format!("{}.metadata.json", args.contract.name));
+        let artifact_path = args.contract.path.map_or(path, PathBuf::from);
+        let artifact: ConfigurableContractArtifact = fs::read_json_file(&artifact_path)?;
```
Comment (rkrasiuk) [inline cli/src/cmd/forge/verify/sourcify.rs:46]: this is not the contract path rather than artifact path. currently, it tries reading `.sol` file as json

File: config/src/lib.rs [hunk 2]
```diff
@@ -798,15 +798,16 @@ impl Config {
...
     pub fn configured_artifacts_handler(&self) -> ConfigurableArtifacts {
-        let mut extra_output_files = self.extra_output_files.clone();
+        let mut extra_output = self.extra_output.clone();
         // Sourcify verification requires solc metadata output. Since, it doesn't
         // affect the UX & performance of the compiler, output the metadata files
         // by default.
         // For more info see: https://github.com/foundry-rs/foundry/issues/2795
-        if !extra_output_files.contains(&ContractOutputSelection::Metadata) {
-            extra_output_files.push(ContractOutputSelection::Metadata);
+        if !extra_output.contains(&ContractOutputSelection::Metadata) {
```
Comment (rkrasiuk) [inline config/src/lib.rs:806]: nit: maybe add a comment here to reference this PR or the corresponding issue

**Review by rkrasiuk — CHANGES_REQUESTED** [review]

File: cli/src/cmd/forge/verify/sourcify.rs (hunk 1 above)
Comment (mattsse) [reply cli/src/cmd/forge/verify/sourcify.rs]: right, fixed

Comment (rkrasiuk) [reply cli/src/cmd/forge/verify/sourcify.rs]: gg, testing now

**Comment by mattsse** [comment]
ran tests, sourcify works:

https://repo.sourcify.dev/contracts/full_match/5/0x224486cda72DeFfE45d379D4DCeBA36947d6fB84/

**Review by rkrasiuk — APPROVED** [review]
confirmed working as well. sidenote: it didn't work with `via_ir` set to `true`

**Comment by mattsse** [comment]
interesting, perhaps this a sourcify thing
