### PR TITLE
fix(lint): lint only files that we build

### LINKED ISSUE #11234: forge lint should default to src/
### Component

Forge

### Describe the feature you would like

`forge lint`, by default, will complain about lib/, test/, script/ 

### Additional context

N/A

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #11234 
- if `forge build path` then lint only path that we build

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by 0xrusowsky — COMMENTED** [review]
the changes look good, but i am wondering if it is desirable to have this behavior? we already exclude gas and codesize lints from tests and scripts.

if we think its desirable (i am not against it), imo it would be better to configure it via a flag in `foundry.toml`, rather than users having to explicitly include tests and scripts.

this way users would easily know the behavior that they have configured

**Comment by grandizzy** [comment]
> the changes look good, but i am wondering if it is desirable to have this behavior? we already 
> 
> this way users would easily know the behavior that they have configured.. having to pass the `script/` and `test/` paths every time, is more tedious than simply changing a config flag.

yep, agree, this makes sense, so we will lint src, test and scripts by default but not libs. Also lint only files we build if they're specified Cc @aviggiano

**Comment by aviggiano** [comment]
Makes sense! Good feature

File: crates/forge/src/cmd/build.rs [hunk 1]
```diff
@@ -118,13 +118,13 @@ impl BuildArgs {
...
         if !output.output().errors.iter().any(|e| e.is_error()) {
-            self.lint(&project, &config).map_err(|err| eyre!("Lint failed: {err}"))?;
+            self.lint(&project, &config, &self.paths).map_err(|err| eyre!("Lint failed: {err}"))?;
         }
 
         Ok(output)
     }
 
-    fn lint(&self, project: &Project, config: &Config) -> Result<()> {
+    fn lint(&self, project: &Project, config: &Config, files: &Option<Vec<PathBuf>>) -> Result<()> {
```
Comment (DaniPopes) [inline crates/forge/src/cmd/build.rs]:
```suggestion
    fn lint(&self, project: &Project, config: &Config, files: Option<&[PathBuf]>) -> Result<()> {
```

File: crates/forge/src/cmd/build.rs [hunk 2]
```diff
@@ -118,13 +118,13 @@ impl BuildArgs {
 
         // Only run the `SolidityLinter` if there are no compilation errors
         if !output.output().errors.iter().any(|e| e.is_error()) {
-            self.lint(&project, &config).map_err(|err| eyre!("Lint failed: {err}"))?;
+            self.lint(&project, &config, &self.paths).map_err(|err| eyre!("Lint failed: {err}"))?;
```
Comment (DaniPopes) [inline crates/forge/src/cmd/build.rs]:
```suggestion
            self.lint(&project, &config, self.paths.as_deref()).map_err(|err| eyre!("Lint failed: {err}"))?;
```

Comment (DaniPopes) [inline crates/forge/src/cmd/build.rs]: can we not get the paths from the compiler output instead?

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/forge/src/cmd/build.rs (hunk 2 above)
Comment (grandizzy) [reply crates/forge/src/cmd/build.rs]: I am not sure we want this as will mean that we won't lint contracts that are already built, e.g. we will show lint errors only first time for `forge build src/utils/BaseVault.sol` but not on subsequent `forge build src/utils/BaseVault.sol` (same with `forge build` entire project). I think we want to always lint the files, wdyt?

Comment (DaniPopes) [reply crates/forge/src/cmd/build.rs]: that's true for `output`, however we can check the paths from `artifacts_with_files()`.

Comment (DaniPopes) [reply crates/forge/src/cmd/build.rs]: with that we can simply pass the paths from `artifacts_with_files()` to `lint` and avoid having to `input_files_iter`

File: crates/forge/src/cmd/build.rs [hunk 3]
```diff
@@ -118,13 +118,14 @@ impl BuildArgs {
 
         // Only run the `SolidityLinter` if there are no compilation errors
         if !output.output().errors.iter().any(|e| e.is_error()) {
```
Comment (DaniPopes) [inline crates/forge/src/cmd/build.rs]: the condition above can be merged with this one: config.lint.lint_on_build &&

File: crates/forge/src/cmd/build.rs (hunk 2 above)
Comment (grandizzy) [reply crates/forge/src/cmd/build.rs]: hm, isn't this the same, `artifacts_with_files()` returns cached and compiled artifacts, so if we call `forge build src/utils/BaseVault.sol` again (and `BaseVault.sol` is not recompiled) then we won't know to lint `BaseVault.sol` only, maybe I am missing something?

File: crates/forge/src/cmd/build.rs (hunk 3 above)
Comment (grandizzy) [reply crates/forge/src/cmd/build.rs]: yep, simplified in https://github.com/foundry-rs/foundry/pull/11247/commits/7722419146ee3f92ba7b72927e8f3dee25a7216a

File: crates/forge/src/cmd/build.rs (hunk 2 above)
Comment (DaniPopes) [reply crates/forge/src/cmd/build.rs]: we can do both

Comment (grandizzy) [reply crates/forge/src/cmd/build.rs]: @DaniPopes `artifacts_with_files` returns all artifacts including artifacts from deps while `input_files_iter` returns only src, test and scripts that we want to lint. Could use `artifacts_with_files` but then have to filter out deps artifacts - IMO is cleaner by `input_files_iter` but happy to change if you strongly think we should use `artifacts_with_files`. thank you!

Comment (DaniPopes) [reply crates/forge/src/cmd/build.rs]: I see, that is fine then
