### PR TITLE
fix(anvil): respect existing accounts on fork

### LINKED ISSUE #1623: Respect on chain nonces for dev accounts in fork mode
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

_No response_

### What command(s) is the bug in?

_No response_

### Operating System

_No response_

### Describe the bug

since we're using known dev accounts by default it's common that they're used on dev chains: https://rinkeby.etherscan.io/address/0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 

when we initialising the genesis account they should fetch the dev accounts and only update the balance but keep the on chain nonce

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #1623

## Solution
fetch dev accounts from fork and only set genesis balance,

### CODE REVIEW

File: anvil/tests/it/fork.rs [hunk 1]
```diff
@@ -101,17 +109,19 @@ async fn test_fork_reset() {
...
     assert_eq!(tx.transaction_index, 0u64.into());
 
     let nonce = provider.get_transaction_count(from, None).await.unwrap();
 
-    assert_eq!(nonce, 1u64.into());
+    assert_eq!(nonce, initial_nonce + 1);
     let to_balance = provider.get_balance(to, None).await.unwrap();
     assert_eq!(balance_before.saturating_add(amount), to_balance);
-
+    dbg!(block_number);
```
Comment (gakonst) [inline anvil/tests/it/fork.rs:124]:
```suggestion
```

**Review by gakonst — APPROVED** [review]
