### PR TITLE
fix(`linker`): Use correct compiler version appended when there are multiple

### LINKED ISSUE #5396: Forge crashes with message `No target contract named <path>:<name>`.
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6c0fce3 2023-07-14T02:45:24.569798838Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hello, my name is Guilherme. I am one of the core contributors of [`cartesi/rollups`](https://github.com/cartesi/rollups). Our [test workflow](https://github.com/cartesi/rollups/actions/runs/5554303929) started failing since earlier today (10 a.m. BRT), because `forge test` is crashing. I managed to replicate the error locally, and this is the error message. The back trace is not very helpful, so I omitted it.

```
The application panicked (crashed).
Message:  No target contract named ../node_modules/@cartesi/util/contracts/CartesiMathV2.sol:CartesiMathV2
Location: utils/src/lib.rs:269
```

I easily managed to pinpoint the line that raised the error: [here](https://github.com/foundry-rs/foundry/blob/master/utils/src/lib.rs#L269).
Also, it seems that this section of code was last updated by this PR: [here](https://github.com/foundry-rs/foundry/pull/5364).

You can replicate the error yourself by following these steps:

1. Start the latest Ubuntu machine
2. Install `jq`, `yarn` and `docker`
3. Clone `https://github.com/cartesi/rollups.git`
4. Initialize the submodules (`git submodule update --init --recursive`)
5. Go to `onchain/rollups`
6. Run `yarn` (installs contract dependencies)
7. Run `./test/foundry/dapp/helper/update-proofs.sh --setup`
8. Run `forge test`

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

Closes #5396 

The problem here is that versioned linking introduces a problem when the same artifact is compiled with several compiler. versions: Its identifier will have the compiler version appended, e.g `contracts/libraries/SafeDecimalMath.sol:SafeDecimalMath.0.8.21` . In this case, the identifier we were using won't match, as we're not appending the version used.

## Solution

We need to make sure to use the _requested_ compiler version instead of using the incorrect one when linking. Therefore, we'll track the version used to compile the dep in the `ArtifactDependency` struct, to later append it and use it if the naked identifier can't be found

### CODE REVIEW

File: utils/src/lib.rs [hunk 1]
```diff
@@ -145,11 +149,18 @@ pub fn link_with_nonce_or_address<T, U>(
         .iter()
         .map(|(id, contract)| {
             let key = id.identifier();
+            let version = id.version.to_string();
+            let version =
+                &version[..version.find("+").expect("Should have compiler version")].to_string();
```
Comment (mattsse) [inline utils/src/lib.rs:154]: is this always guaranteed to have metadata?

**Review by mattsse — APPROVED** [review]
since the version is always set in the artifact, this should work for all cases

File: utils/src/lib.rs (hunk 1 above)
Comment (Evalir) [reply utils/src/lib.rs]: Yep, all solidity compiler versions have the metadata appended to them, but we can avoid this panic

**Comment by tommyrharper** [comment]
Awesome, thanks for the super fast response, this fixed it 🙌 🤩 💫
