### PR TITLE
fix(anvil): implement impersonateAccount correctly

### LINKED ISSUE #1910: Improve impersonating accounts
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

_No response_

### What command(s) is the bug in?

_No response_

### Operating System

_No response_

### Describe the bug

currently `anvil_impersonatingAccount` is not implemented like `hardhat_impersonatingAccount`, instead of setting the sender to the impersonated account, `anvil_impersonatingAccount` rather is a list of "unlocked" accounts that can allow fake tx signing if the transaction's sender is an impersonated account

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #1910
* mimic hardhat's behavior in anvil_impersonateAccount 

## Solution
* use a list for impersonated/unlocked accounts rather a single account that is used for transactions without from field

### CODE REVIEW

**Comment by banteg** [comment]
Can confirm it works with https://github.com/ApeWorX/ape-foundry/pull/5

File: cli/src/cmd/utils.rs [hunk 1]
```diff
@@ -169,14 +169,17 @@ pub fn unwrap_contracts(
...
             } else {
-                c.bytecode.clone().object.into_bytes().expect("not bytecode").to_vec()
+                c.bytecode.clone().object.into_bytes()
             };
 
-            (id.clone(), (c.abi.clone(), bytecode))
+            if let Some(bytecode) = bytecode {
+                return Some((id.clone(), (c.abi.clone(), bytecode.to_vec())))
+            }
+            None
```
Comment (gakonst) [inline cli/src/cmd/utils.rs:182]: is this a separate fix?

**Review by gakonst — APPROVED** [review]
