### PR TITLE
fix(`linking`): handle workspace setups by adding a fallback for artifacts

### LINKED ISSUE #5396: Forge crashes with message `No target contract named <path>:<name>`.
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6c0fce3 2023-07-14T02:45:24.569798838Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hello, my name is Guilherme. I am one of the core contributors of [`cartesi/rollups`](https://github.com/cartesi/rollups). Our [test workflow](https://github.com/cartesi/rollups/actions/runs/5554303929) started failing since earlier today (10 a.m. BRT), because `forge test` is crashing. I managed to replicate the error locally, and this is the error message. The back trace is not very helpful, so I omitted it.

```
The application panicked (crashed).
Message:  No target contract named ../node_modules/@cartesi/util/contracts/CartesiMathV2.sol:CartesiMathV2
Location: utils/src/lib.rs:269
```

I easily managed to pinpoint the line that raised the error: [here](https://github.com/foundry-rs/foundry/blob/master/utils/src/lib.rs#L269).
Also, it seems that this section of code was last updated by this PR: [here](https://github.com/foundry-rs/foundry/pull/5364).

You can replicate the error yourself by following these steps:

1. Start the latest Ubuntu machine
2. Install `jq`, `yarn` and `docker`
3. Clone `https://github.com/cartesi/rollups.git`
4. Initialize the submodules (`git submodule update --init --recursive`)
5. Go to `onchain/rollups`
6. Run `yarn` (installs contract dependencies)
7. Run `./test/foundry/dapp/helper/update-proofs.sh --setup`
8. Run `forge test`

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

Closes #5396.

The new linking fixes broke workspace setups that have files imported from outside the project root.

## Solution

Add a fallback that is composed of the project root + the relative path obtained.

### CODE REVIEW

File: utils/src/lib.rs [hunk 1]
```diff
@@ -262,12 +266,23 @@ fn recurse_link<'a>(
         dependencies.dependencies.iter().for_each(|dep| {
             let ArtifactDependency {  file, key, .. } = dep;
             let next_target = format!("{file}:{key}");
+            let root = PathBuf::from(root.as_ref().to_str().unwrap());
+            // In some project setups, like JS-style workspaces, you might not have node_modules available at the root of the foundry project.
+            // In this case, imported dependencies from outside the root might not have their paths tripped correctly.
+            // Therefore, we fall back to a manual path join to locate the file.
+            let fallback_path =  dunce::canonicalize(root.join(file)).unwrap_or_else(|_| panic!("No file named {file}"));
```
Comment (mattsse) [inline utils/src/lib.rs:273]: I don't like that we panic here,

when does this return None?

**Review by mattsse — CHANGES_REQUESTED** [review]
this fallback should only be used when canonicalize works

and this entire thing should really be rewritten from scratch -.-

File: utils/src/lib.rs (hunk 1 above)
Comment (Evalir) [reply utils/src/lib.rs]: It returns none if the path doesn't exist or is not a directory (and other OS related errors in the case of windows, probably): https://doc.rust-lang.org/std/fs/fn.canonicalize.html

moved all the fallback code on the error case if the artifact is not found—if we're gonna panic anyway there's no way to stop it at this point (as it's an unhandled case / project setup). And yeah we need to rewrite this 😅

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
pending clippy

**Comment by guidanoli** [comment]
Thanks for the fix!
