### PR TITLE
fix(coverage): do not account abstract contract items

### LINKED ISSUE #12204: bug(`forge coverage`): empty virtual function in abstract contract should be excluded from coverage report
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

1.4.2-stable

### What version of Foundryup are you on?

0.3.1

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

When getting the coverage report of a test of the `deposit()` function from `contract B`, the coverage report flags the function `_deposit()` from `contract A` as not covered.

This prevents the coverage report from reaching 100%

```js
abstract contract A {
  function _deposit() internal virtual;
}

contract B is A {
  function deposit() external {
    _deposit();
  }

  function _deposit() internal override {
    // Some logic
  }
}
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- ref https://t.me/foundry_support/65227
- Closes #12204 
- do not include abstract contracts coverage items

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by DaniPopes — APPROVED** [review]

File: crates/evm/coverage/src/analysis.rs [hunk 1]
```diff
@@ -483,8 +483,9 @@ impl SourceAnalysis {
                         // Visit only top-level contracts.
                         let ItemKind::Contract(contract) = &item.kind else { continue };
 
-                        // Skip interfaces which have no function implementations.
-                        if contract.kind.is_interface() {
+                        // Skip interfaces and abstract contracts which have no function
+                        // implementations.
```
Comment (DaniPopes) [inline crates/evm/coverage/src/analysis.rs:487]: abstract contracts *can* have implementations, which can be overridden. so do normal contracts. I don't know how we should handle this tbh but this is fine for now since I assume they're mostly unimplemented
