### PR TITLE
fix(forge): Optionally use create2 factory in tests and non-broadcasting scripts

### LINKED ISSUE #5529: bug: tests do not deploy via create2 the same as scripts
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ca67d15 2023-08-02T00:22:03.700607000Z)

### What command(s) is the bug in?

forge test

### Operating System

None

### Describe the bug

1. `forge init` a new repo
2. Add the below test
```solidity
function test1() public {
    address a = computeCreate2Address(0, hashInitCode(type(Counter).creationCode), address(this));
    address b = address(new Counter{salt: 0}());
    require(a == b, "create2 address mismatch");
}
```
3. Run `forge test --mt test1 -vvvv`, the test passes and deploys to `new Counter@0xBE03C2aFB559A5Ce6926b01A813F37584476c95f`
4. Update the default script to run:
```solidity
function run() public {
    vm.broadcast();
    new Counter{salt: 0}();
}
```
5. Run `forge script script/Counter.s.sol -vvvv` and you'll see it deploys to `new Counter@0xE414be17fD7aa8Ee7194000dc622AdEF3c81aFCd`

This shows that scripts (as expected) route create2 deploys through the default create2 deployer. But tests (unexpectedly) deploy directly from the test contract.

I think the two behaviors should be consistent, especially since it's ideal to test scripts, and this behavior means we get different addresses depending on which command you invoke the script with (directly, or indirectly trough a test) which is confusing behavior

cc @zobront

### PR DESCRIPTION
**Pull request by RPate97**
## Motivation
#5529 

## Solution
Resolves #5529 by adding logic to allow the default create2 factory to be used in tests and non-broadcasting scripts. I chose to make this change non-breaking by introducing a new config option / CLI flag `always_use_create_2_factory`, which must be set to `true` to enable this behavior.

In the future, this option could be removed or changed relatively easily to make using the create2 factory the default behavior if a breaking change is acceptable.

### CODE REVIEW

**Comment by mds1** [comment]
Thanks for opening this! I agree this needs to be introduced in a way that avoids breaking changes, since it's likely users have assertions with hardcoded expected create2 addresses.

What do you think about doing this as a config option / CLI flag instead? My rationale is that users are unlikely to only need this feature in a subset of tests, making a global flag simpler than a cheatcode, since a cheat might need to be declared in multiple places. And declaring a cheat in multiple places (since not all tests share the same setup) makes it more error prone / hard to be consistent everywhere. 

And we should remove this in v1 and make this the default for simplicity, cc @Evalir to document this wherever v1 breaking changes are being tracked

Also cc @zobront who originally pointed out this issue

**Comment by RPate97** [comment]
> What do you think about doing this as a config option / CLI flag instead? 
I think that's a good idea, will update this.

File: crates/cheatcodes/src/inspector.rs [hunk 1]
```diff
@@ -1419,7 +1422,23 @@ fn process_create<DB: DatabaseExt>(
             }
 
             call.caller = DEFAULT_CREATE2_DEPLOYER;
+        }
+    }
+    Ok(())
+}
 
+fn process_create<DB: DatabaseExt>(
```
Comment (Evalir) [inline crates/cheatcodes/src/inspector.rs:1430]: Could we add some docs on what the two functions do now? as we have `apply_create2_deployer` and `process_create`, and previously `process_create` was fallible, but now it will always succeed and update state in case of scripts.

**Review by Evalir — CHANGES_REQUESTED** [review]
a smol nit:

File: crates/cheatcodes/src/inspector.rs (hunk 1 above)
Comment (RPate97) [reply crates/cheatcodes/src/inspector.rs]: @Evalir Just bumping since this is ready for review. Thanks.

**Comment by sam-goldman** [comment]
Hey @Evalir, this continues to be an issue for us. The PR has been ready for a month, so I just wanted to bump it. Totally understand you've got a lot on your plate, but I just want to make sure that this doesn't get buried into oblivion :)

**Comment by Evalir** [comment]
Understood @sam-goldman — let's fix this :)

File: crates/cheatcodes/src/inspector.rs [hunk 2]
```diff
@@ -1241,6 +1235,14 @@ impl<DB: DatabaseExt> Inspector<DB> for Cheatcodes {
             }
         }
 
+        // Apply the Create2 deployer
+        if self.broadcast.is_some() || self.config.always_use_create_2_factory {
+            match apply_create2_deployer(data, call, &self.prank, &self.broadcast) {
+                Ok(_val) => {}
```
Comment (Evalir) [inline crates/cheatcodes/src/inspector.rs:1241]:
```suggestion
                Ok(_) => {}
```

**Review by Evalir — CHANGES_REQUESTED** [review]
this lgtm, just a nit—cc @mattsse / @onbjerg would love extra eyes

**Review by onbjerg — CHANGES_REQUESTED** [review]

File: crates/cheatcodes/src/inspector.rs [hunk 3]
```diff
@@ -1416,18 +1418,31 @@ fn mstore_revert_string(interpreter: &mut Interpreter<'_>, bytes: &[u8]) {
...
+fn apply_create2_deployer<DB: DatabaseExt>(
     data: &mut EVMData<'_, DB>,
     call: &mut CreateInputs,
-) -> Result<(Bytes, Option<Address>, u64), DB::Error> {
-    match call.scheme {
-        CreateScheme::Create => {
-            call.caller = broadcast_sender;
-            Ok((bytecode, None, data.journaled_state.account(broadcast_sender).info.nonce))
+    prank: &Option<Prank>,
+    broadcast: &Option<Broadcast>,
```
Comment (mattsse) [inline crates/cheatcodes/src/inspector.rs:1434]:
```suggestion
    prank: Option<&Prank>,
    broadcast: Option<&Broadcast>,
```

**Review by mattsse — CHANGES_REQUESTED** [review]
as @mds1 said, I think this makes sense and this looks like an appropriate solution imo

any concerns @DaniPopes 
I only have nits

sorry for the delayed review

File: crates/cheatcodes/src/inspector.rs [hunk 4]
```diff
@@ -1241,6 +1235,14 @@ impl<DB: DatabaseExt> Inspector<DB> for Cheatcodes {
             }
         }
 
+        // Apply the Create2 deployer
+        if self.broadcast.is_some() || self.config.always_use_create_2_factory {
```
[the remark this answers is not in the document]
Comment (RPate97) [reply crates/cheatcodes/src/inspector.rs:1239]: This is intended to cause the create2 deployer to be applied in a broadcasting script, as is the current behavior. If the `always_use_create_2_factory` is true, then the create2 deployer should also be used in tests and non-broadcasting scripts. This should be the default behavior in my opinion, but using an option ensures this change is backward compatible.

I believe this PR correctly implements that behavior, but I am new to Rust, so let me know if you think I'm misunderstanding something about the implementation.

[the remark this answers is not in the document]
Comment (onbjerg) [reply crates/cheatcodes/src/inspector.rs:1239]: gotcha

**Review by Evalir — APPROVED** [review]
excited to get this in! cc @mds1

**Review by klkvr — APPROVED** [review]
lgtm
