### PR TITLE
fix(forge): ensure contract managing fork is  persistent

### LINKED ISSUE #8004: `forge test` crashes with `Message:  called Option::unwrap() on a None value`
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ea2eff9 2024-05-28T00:17:45.727606000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

The bug lies in the updated Foundry version. 

**Steps to reproduce:**

1. Clone the repository
```sh
git clone https://github.com/exp-table/pigeon
``` 

2. Add your RPC URLs to the `.env` file
```sh
ETH_MAINNET_RPC_URL=
POLYGON_MAINNET_RPC_URL=
ARBITRUM_MAINNET_RPC_URL=

# Optional
ENABLE_CELER_ESTIMATES=true
ENABLE_HYPERLANE_ESTIMATES=false
ENABLE_LZ_ESTIMATES=true
```

3. Run the tests using `forge test`

**Logs:**

```sh
[⠊] Compiling...
No files changed, compilation skipped

Ran 5 tests for test/Celer.t.sol:CelerHelperTest
[PASS] testCustomOrderingCeler() (gas: 108685)
[PASS] testFancyCeler() (gas: 123722)
[PASS] testMultiDstCeler() (gas: 151884)
[PASS] testSimpleCeler() (gas: 72229)
[PASS] testSimpleCelerWithEstimates() (gas: 77270)
Suite result: ok. 5 passed; 0 failed; 0 skipped; finished in 7.69s (1.91s CPU time)

Ran 4 tests for test/Axelar.t.sol:AxelarHelperTest
[PASS] testCustomOrderingAxelar() (gas: 341805)
[PASS] testFancyAxelar() (gas: 236169)
[PASS] testMultiDstAxelar() (gas: 391397)
[PASS] testSimpleAxelar() (gas: 189999)
Suite result: ok. 4 passed; 0 failed; 0 skipped; finished in 11.48s (3.90s CPU time)
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-9.0.0/src/journaled_state.rs:641

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 8 frames hidden ⋮                               
   9: core::panicking::panic::hc59c8a709a9b37ae
      at <unknown source file>:<unknown line>
  10: core::option::unwrap_failed::h64934fbe08d33633
      at <unknown source file>:<unknown line>
  11: revm::journaled_state::JournaledState::sload::hb292ab2772e652cb
      at <unknown source file>:<unknown line>
  12: <revm::context::Context<EXT,DB> as revm_interpreter::host::Host>::sload::h7c2eadaa276e2317
      at <unknown source file>:<unknown line>
  13: revm_interpreter::instructions::host::sload::h1c9497870d645e6c
      at <unknown source file>:<unknown line>
  14: revm::inspector::handler_register::inspector_instruction::{{closure}}::h03e2dc73635a341d
      at <unknown source file>:<unknown line>
  15: revm::handler::mainnet::execution::execute_frame::h026fc75de773d06f
      at <unknown source file>:<unknown line>
  16: revm::evm::Evm<EXT,DB>::transact::h235456cda0c49183
      at <unknown source file>:<unknown line>
  17: foundry_evm::executors::Executor::call_raw_with_env::he2005afc97600e72
      at <unknown source file>:<unknown line>
  18: foundry_evm::executors::Executor::execute_test::h9cc3b93e2c860177
      at <unknown source file>:<unknown line>
  19: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h44e499dd908e19bc
      at <unknown source file>:<unknown line>
  20: rayon::iter::plumbing::bridge_producer_consumer::helper::h2693959307ecc7a2
      at <unknown source file>:<unknown line>
  21: rayon_core::join::join_context::{{closure}}::h6ffee74b42c8d4bf
      at <unknown source file>:<unknown line>
  22: rayon::iter::plumbing::bridge_producer_consumer::helper::h2693959307ecc7a2
      at <unknown source file>:<unknown line>
  23: rayon_core::join::join_context::{{closure}}::h6ffee74b42c8d4bf
      at <unknown source file>:<unknown line>
  24: rayon::iter::plumbing::bridge_producer_consumer::helper::h2693959307ecc7a2
      at <unknown source file>:<unknown line>
  25: rayon_core::join::join_context::{{closure}}::h6ffee74b42c8d4bf
      at <unknown source file>:<unknown line>
  26: rayon::iter::plumbing::bridge_producer_consumer::helper::h2693959307ecc7a2
      at <unknown source file>:<unknown line>
  27: forge::runner::ContractRunner::run_tests::h1f32def75e6f25bf
      at <unknown source file>:<unknown line>
  28: forge::multi_runner::MultiContractRunner::run_tests::hac520a5a0e7c1729
      at <unknown source file>:<unknown line>
  29: rayon::iter::plumbing::bridge_producer_consumer::helper::h16cdcbd0a900c75f
      at <unknown source file>:<unknown line>
  30: rayon_core::join::join_context::{{closure}}::h3308bff5d566a6dc
      at <unknown source file>:<unknown line>
  31: rayon::iter::plumbing::bridge_producer_consumer::helper::h16cdcbd0a900c75f
      at <unknown source file>:<unknown line>
  32: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hbcf434872e4b1d95
      at <unknown source file>:<unknown line>
  33: rayon_core::registry::WorkerThread::wait_until_cold::hc2f2f5c5d2ac906c
      at <unknown source file>:<unknown line>
  34: std::sys_common::backtrace::__rust_begin_short_backtrace::h26c5ce7ae435c375
      at <unknown source file>:<unknown line>
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}::h7359e7db922f9b5d
      at <unknown source file>:<unknown line>
  36: std::sys::pal::unix::thread::Thread::new::thread_start::h9266fbbdd0c3d8be
      at <unknown source file>:<unknown line>
  37: __pthread_joiner_wake<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
zsh: abort      forge test
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation

Fixes #8004 

Test contract that manage forks (create / select / roll) should be made persistent, otherwise their state can be lost

## Solution

- ensure caller is persistent for create, select and roll fork cheatcodes

### CODE REVIEW

**Review by klkvr — CHANGES_REQUESTED** [review]
I think we can do this in `Backend::select_fork` instead? It already has some similar logic

Also important to note that this does not resolve this issue for some weird cases when forks are switched deep in call stack

File: crates/cheatcodes/src/evm/fork.rs [hunk 1]
```diff
@@ -355,3 +362,13 @@ fn check_broadcast(state: &Cheatcodes) -> Result<()> {
         Err(fmt_err!("cannot select forks during a broadcast"))
     }
 }
+
+// Helper to ensure that the caller managing the fork is persistent.
+// Applies to create, select and roll forks actions.
+// https://github.com/foundry-rs/foundry/issues/8004
+#[inline]
+fn ensure_persistent_caller<DB: DatabaseExt>(ccx: &mut CheatsCtxt<DB>) {
```
Comment (mattsse) [inline crates/cheatcodes/src/evm/fork.rs:370]: I think we can replace this function entirely and always call add which is more efficient because it only does one lookup

but I can see the value in this function for doc purposes, but would like to drop the `ensure_` prefix because this is commonly used by functions that check a condition and return an error if that condition is violated which is not the case here

**Review by mattsse — CHANGES_REQUESTED** [review]
nice repro!

only have a naming nit and suggestion

**Comment by grandizzy** [comment]
> I think we can do this in `Backend::select_fork` instead? It already has some similar logic
> 

The problem with this approach is that we don't have the original `msg.sender` from cheat context available in `Backend::select_fork/roll_fork` - we can add it as an additional param but I don't think we should mix them, wdyt?

File: crates/cheatcodes/src/evm/fork.rs (hunk 1 above)
Comment (grandizzy) [reply crates/cheatcodes/src/evm/fork.rs]: changed with https://github.com/foundry-rs/foundry/pull/8041/commits/4a6fae0ee51a3bd6b0281b0832f25f58f86f8869

**Comment by grandizzy** [comment]
> I think we can do this in `Backend::select_fork` instead? It already has some similar logic
> 

The problem with this approach is that we don't have the original msg.sender from cheat context available in Backend::select_fork/roll_fork - we can add it as an additional param but I don't think we should mix them, wdyt?

> Also important to note that this does not resolve this issue for some weird cases when forks are switched deep in call stack, but I don't think this can be solved without separately tracking call stack

Yep, the scope of this PR is to make sure test contracts that use fork cheatcodes are persistent, see https://github.com/foundry-rs/foundry/issues/8004#issuecomment-2135568075

**Review by mattsse — APPROVED** [review]

**Comment by klkvr** [comment]
>  I think we can do this in Backend::select_fork instead? It already has some similar logic
>
>   The problem with this approach is that we don't have the original msg.sender from cheat context available in 
>   Backend::select_fork/roll_fork - we can add it as an additional param but I don't think we should mix them, wdyt?

Right, I think we can keep it as is for now

I just don't want `persist_caller` to become the new [correct_sender_nonce](https://github.com/foundry-rs/foundry/pull/7907) which ended up in many random places and caused weird bugs. But `persist_caller` usecase seem pretty narrow so it's probably fine

**Review by klkvr — APPROVED** [review]
