### PR TITLE
fix(forge): custom verifiers should not throw on unknown etherscan chains

### LINKED ISSUE #11430: bug(forge verify-contract): Etherscan API URL Error when using blockscout
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.3.2-stable

### What version of Foundryup are you on?

foundryup: 1.3.0

### What command(s) is the bug in?

forge verify-contract & forge script --verify

### Operating System

macOS (Apple Silicon)

### Describe the bug

I get this error while trying to deploy on lisk, a chain that has no Etherscan support:
Error: No known Etherscan API URL for chain `4202`. To fix this, please:
1. Specify a `url` 
2. Verify the chain `4202` is correct

Image

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #11430 
- config should not throw on non etherscan verifiers when chain not known by etherscan - issue introduced in https://github.com/foundry-rs/foundry/pull/11194/files#diff-0f348074359029c2930eb72b52f482c2e0f4495dc61b95bc919f155a8d2fd82cR1437-R1444. Instead should just continue as unknown etherscan chains could be supported by other verifiers like blockscout and sourcify.

## Solution
- in place fix, needs a broader refactoring to reflect same code is used by etherscan-like verifiers and more tests for non-etherscan supported verifiers 
- consider backport to v1.3.3

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/verify/src/provider.rs [hunk 1]
```diff
@@ -179,10 +183,16 @@ impl VerificationProviderType {
...
+        // enforce the API key requirement.
         if self.is_etherscan() {
+            if let Some(chain) = chain
+                && chain.etherscan_urls().is_none()
+            {
+                eyre::bail!(EtherscanConfigError::UnknownChain(String::new(), chain,))
+            }
             if !has_key {
-                eyre::bail!("ETHERSCAN_API_KEY must be set to use Etherscan as a verifier")
+                eyre::bail!("ETHERSCAN_API_KEY12 must be set to use Etherscan as a verifier")
```
Comment (zerosnacks) [inline crates/verify/src/provider.rs]:
```suggestion
                eyre::bail!("ETHERSCAN_API_KEY must be set to use Etherscan as a verifier")
```

File: crates/verify/src/provider.rs [hunk 2]
```diff
@@ -179,10 +183,16 @@ impl VerificationProviderType {
...
         }
 
-        // 2. If `--verifier etherscan` is explicitly set, enforce the API key requirement.
+        // 2. If `--verifier etherscan` is explicitly set, check if chain is supported and
+        // enforce the API key requirement.
         if self.is_etherscan() {
+            if let Some(chain) = chain
+                && chain.etherscan_urls().is_none()
+            {
+                eyre::bail!(EtherscanConfigError::UnknownChain(String::new(), chain,))
```
Comment (zerosnacks) [inline crates/verify/src/provider.rs]:
```suggestion
                eyre::bail!(EtherscanConfigError::UnknownChain(String::new(), chain))
```
