### PR TITLE
fix(anvil): set blob fields in genesis

### LINKED ISSUE #7841: Blob fields missing from anvil genesis
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d495216 2024-05-03T00:21:54.426103000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

```shell
> anvil --hardfork cancun

> cast rpc eth_getBlockByNumber 0 false | jq .blobGasUsed
null

> cast rpc eth_getBlockByNumber 1 false | jq .blobGasUsed
"0x0"
```

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Fixes #7841

## Solution

Set blob fields in `BlockchainStorage::new()` and `ClientForkConfig`

### CODE REVIEW

**Review by DaniPopes — APPROVED** [review]
@mattsse

File: crates/anvil/src/eth/backend/mem/storage.rs [hunk 1]
```diff
@@ -233,6 +234,8 @@ impl BlockchainStorage {
             gas_limit: env.block.gas_limit.to::<u128>(),
             beneficiary: env.block.coinbase,
             difficulty: env.block.difficulty,
+            blob_gas_used: Some(env.tx.blob_hashes.len() as u128 * DATA_GAS_PER_BLOB as u128),
```
Comment (mattsse) [inline crates/anvil/src/eth/backend/mem/storage.rs:237]: this is not quite right because this uses the txenv.

this function is not very clean because initializing this with the env is a bit weird.

what this should do here is `env.block.blob_excess_gas_and_price.as_ref().map(|_| 0)`

**Review by mattsse — CHANGES_REQUESTED** [review]
nice,

smol nit
