### PR TITLE
script refactoring

### LINKED ISSUE #4476: `forge script --watch` is not watching anything
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28b2ae6 2023-03-04T00:10:50.272293Z)

### What command(s) is the bug in?

forg escript

### Operating System

macOS (Intel)

### Describe the bug

Greetings folks!
Have a specific use-case where I need to watch-on-file changes and redeploy the script to the anvil (trying to make recompile on-watch along with `@wagmi/cli` hooks work), but it just looks like the --watch mode does ... nothing?

https://user-images.githubusercontent.com/35642018/222925341-260a0c3b-4d34-4e76-84cc-38b27d37e361.mp4

### LINKED ISSUE #7244: Misleading Error Message: Could not find target contract
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ac80261 2024-02-24T00:17:06.154246094Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Running `forge script MyDeployment.sol` fails with the message `Error: Could not find target contract MyDeployment` even though the file is clearly present and the script contract name is correct.

In my case, the real bug was calling an external library method which had been accidentally marked public/external instead of internal, causing a dynamic linkage failure, and the message "Error: Could not find target contract"

You should be able to reproduce using a `library Foo { function foo() public {} }` along with a contract which calls `Foo.foo()` and finally a deployment script which constructs the contract that uses the external lib.  If you change the visibility to `internal`, the static binding / inlining causes the "Could not find target contract" message to go away.

This is the same error message as reported in #3076 but presumably with a different cause/solution.

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

The idea is to refactor script to be more like a state-machine, so its easier to navigate/update and we are able to debug each state transition separately.

## Solution

I've started with `build` module, it now returns and operates on `BuildData` and `LinkedBuildData` structs which contain all build artifacts and solc-related data and allow us to use them through script execution instead of passing `Linker` everywhere.

Closes #7244 
Closes #4476

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
I like this approach a lot.

structuring this in compile+link steps makes a lot of sense

**Comment by klkvr** [comment]
Refactoring goals were mostly increasing readability and safety of the code.

Readability right now should be better because the logic overall became more flat. If earlier we had `handle_broadcastable_transactions` going up to 4-5 functions deep, it's now split across several states which are invoked sequentially and don't go deeper than 2 small functions.

Safety isn't great because we have a lot of `Option`s which are _assumed_ to be `Some` after some point. It is not really easy to know where this point is and it does not help both reading existing code and extending it. I've tried to reduce such practicies as well. Example of those is ScriptConfig`: https://github.com/foundry-rs/foundry/blob/c24933da985419ea143de7e8636d5b0a48d2fab7/crates/forge/bin/cmd/script/mod.rs#L619-L625

All of those parameters are initialized with default values and populated later, accessing those in the wrong place might result in panic or unintended behavior.

I've also simplified logic where it was possible, however, we still have several pretty long functions which would be nice in the shorter form, but this can be fixed a bit later, esp considering that all of the state transaction functions are normally readable

**Comment by klkvr** [comment]
We should also be able to remove onchain simulation step once we have isolation mode enabled by default

File: crates/forge/bin/cmd/script/cmd.rs [hunk 1]
```diff
@@ -1,376 +1,99 @@
...
+            .preprocess()
+            .await?
+            .compile()?
+            .link()?
+            .prepare_execution()
+            .await?
+            .execute()
+            .await?
+            .prepare_simulation()
             .await?;
```
Comment (mattsse) [inline crates/forge/bin/cmd/script/cmd.rs:39]: this is great!

I'd like a few more function docs that cover the workflow

**Review by mattsse — CHANGES_REQUESTED** [review]
this looks great, this is a lot easier to navigate

I'd like to see a few more docs on functions,types,fields

**Review by mattsse — APPROVED** [review]
the individual states are very easy to follow now.

@DaniPopes would appreciate a closer look

File: crates/forge/bin/cmd/script/sequence.rs [hunk 2]
```diff
@@ -16,16 +16,91 @@ use foundry_common::{
...
+
+impl ScriptSequenceKind {
+    pub fn save(&mut self, silent: bool, save_ts: bool) -> Result<()> {
+        match self {
+            ScriptSequenceKind::Single(sequence) => sequence.save(silent, save_ts),
+            ScriptSequenceKind::Multi(sequence) => sequence.save(silent, save_ts),
+        }
+    }
+
+    pub fn iter_sequences(&self) -> impl Iterator<Item = &ScriptSequence> {
```
Comment (DaniPopes) [inline crates/forge/bin/cmd/script/sequence.rs:42]: `fn sequences{_mut}(&self) -> &[ScriptSequence]` rather than iter IMO

File: crates/forge/bin/cmd/script/mod.rs [hunk 3]
```diff
@@ -1,64 +1,59 @@
+use crate::cmd::script::runner::ScriptRunner;
+
+use self::transaction::AdditionalContract;
+
 use super::{build::BuildArgs, retry::RetryArgs};
-use alloy_dyn_abi::FunctionExt;
-use alloy_json_abi::{Function, InternalType, JsonAbi};
-use alloy_primitives::{Address, Bytes, Log, U256, U64};
-use alloy_rpc_types::request::TransactionRequest;
+
```
Comment (DaniPopes) [inline crates/forge/bin/cmd/script/mod.rs:6]: no spaces in between imports

**Review by DaniPopes — CHANGES_REQUESTED** [review]
Can we extract this into a separate crate?

**Comment by mattsse** [comment]
> Can we extract this into a separate crate?

oh yeah, totally forgot about this, I'd like that, yes

**Comment by klkvr** [comment]
@DaniPopes @mattsse I fthink it makes sense to avoid having `clap` dependency in the separate crate. A reasonable way to do this might be to move some of `ScriptArgs` methods to `ScriptConfig` and populate them in `ScriptArgs::preprocess`. But we'd duplicate half of `ScriptArgs` fields that way.

Do you see any cleaner solution here?

**Comment by klkvr** [comment]
ah, we'd still need clap for `VerifyArgs`, so we can either line up verification extraction and get rid of clap where it will be possible then, or divide `ScriptArgs` and `ScriptConfig` now anyway

**Comment by klkvr** [comment]
Extracted scripting code to separate crate and also removed `ScriptArgs` dependency on `BuildArgs`. It now uses `CoreBuildArgs` + separate `--skip` parameter. Removed params are `--names`, `--sizes`, `--watch*` and `--format-json`. All of those were not used and had not effect. This change should close #4476

File: crates/script/src/build.rs [hunk 4]
```diff
@@ -0,0 +1,231 @@
...
+            Ok::<_, eyre::Report>(Some(path))
+        } else {
+            let contract = ContractInfo::from_str(&args.path)?;
+            target_name = Some(contract.name.clone());
+            if let Some(path) = contract.path {
+                Ok(Some(dunce::canonicalize(path)?))
+            } else {
+                Ok(None)
+            }
+        }?;
```
Comment (mattsse) [inline crates/script/src/build.rs:141]: is the additional Ok wrapper required here?
I dont think we have an err, hence the `Ok<_, eyre>`

File: crates/script/src/cmd.rs [hunk 5]
```diff
@@ -0,0 +1,111 @@
+use super::{states::PreprocessedState, ScriptArgs, ScriptConfig};
+use alloy_primitives::Address;
+use ethers_signers::Signer;
+use eyre::Result;
+use foundry_cheatcodes::ScriptWallets;
+use foundry_cli::utils::LoadConfig;
+use foundry_common::{shell, types::ToAlloy};
+
+impl ScriptArgs {
```
Comment (mattsse) [inline crates/script/src/cmd.rs:9]: this should be below scriptargs type def

File: crates/script/src/execute.rs [hunk 6]
```diff
@@ -0,0 +1,493 @@
...
+    pub func: Function,
+    /// Calldata to pass to the target contract.
+    pub calldata: Bytes,
+    /// Bytecode of the target contract.
+    pub bytecode: Bytes,
+    /// ABI of the target contract.
+    pub abi: JsonAbi,
+}
+
+impl LinkedState {
```
Comment (mattsse) [inline crates/script/src/execute.rs:47]: this should be below type def

**Review by mattsse — CHANGES_REQUESTED** [review]
amazing.

I see that a few `impl` blocks are not colocated with thir struct def, this is probably because the previous ScriptArgs impl was scattered across multiple files, but this makes it a lot harder to navigate.

impl blocks should go under their respective struct def

File: crates/script/src/execute.rs (hunk 6 above)
Comment (klkvr) [reply crates/script/src/execute.rs:47]: yeah, I've placed it like this as we had it split across several files before, should I get rid of `states.rs` at all and keep impls of all states along with their definitions?

Comment (mattsse) [reply crates/script/src/execute.rs:47]: that'd be great, I prefer that style because then you don't need to jump across multiple files when looking at a type:

```rust
struct A

impl A

impl Trait for A

```

although @DaniPopes prefers `impl Trait` above the `impl A` block, I'm indifferent about the order of these two

**Review by mattsse — APPROVED** [review]
lgtm

pending @DaniPopes

File: crates/script/src/sequence.rs [hunk 7]
```diff
@@ -26,6 +23,86 @@ use std::{
...
+    }
+
+    pub fn sequences_len(&self) -> usize {
+        match self {
+            ScriptSequenceKind::Single(_) => 1,
+            ScriptSequenceKind::Multi(sequence) => sequence.deployments.len(),
+        }
+    }
+
+    pub fn get_sequence_mut(&mut self, index: usize) -> Option<&mut ScriptSequence> {
```
Comment (DaniPopes) [inline crates/script/src/sequence.rs:65]: I think all these methods are redundant if we can just use `fn sequences() -> &[ScriptSequence]`

File: crates/script/src/sequence.rs [hunk 8]
```diff
@@ -26,6 +23,86 @@ use std::{
...
+            }
+        };
+
+        Ok(())
+    }
+}
+
+impl Drop for ScriptSequenceKind {
+    fn drop(&mut self) {
+        self.save(false, true).expect("could not save deployment sequence");
```
Comment (DaniPopes) [inline crates/script/src/sequence.rs:102]: Should probably be `if let Err(e) = { error!() }` rather than panicking on IO errors

File: crates/script/src/multi_sequence.rs [hunk 9]
```diff
@@ -0,0 +1,152 @@
...
+    pub timestamp: u64,
+}
+
+/// Sensitive values from script sequences.
+#[derive(Clone, Default, Serialize, Deserialize)]
+pub struct SensitiveMultiChainSequence {
+    pub deployments: Vec<SensitiveScriptSequence>,
+}
+
+fn to_sensitive(sequence: &mut MultiChainSequence) -> SensitiveMultiChainSequence {
```
Comment (DaniPopes) [inline crates/script/src/multi_sequence.rs:30]: Does this need `&mut`? Also I'd prefer this be like `SensitiveMultiChainSequence::from_multi_sequence` or a From impl

File: crates/script/src/broadcast.rs [hunk 10]
```diff
@@ -0,0 +1,429 @@
...
+            .sequeneces_mut()
+            .map(|sequence| async move {
+                let rpc_url = sequence.rpc_url();
+                let provider = Arc::new(get_http_provider(rpc_url));
+                receipts::wait_for_pending(provider, sequence).await
+            })
+            .collect::<Vec<_>>();
+
+        let errors =
+            join_all(futs).await.into_iter().filter(|res| res.is_err()).collect::<Vec<_>>();
```
Comment (DaniPopes) [inline crates/script/src/broadcast.rs:190]: we can `filter_map(Result::err)` and format the list using itertools `eyre!("{}", errors.iter().format("\n"))`

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/script/src/sequence.rs (hunk 7 above)
Comment (klkvr) [reply crates/script/src/sequence.rs:65]: The need for `get_sequence_mut` and `sequences_len` is from the `BundledState::broadcast` where we need mutable access to separate sequences to populate pending txes and receipts, but we also sometimes need mutable access to the parent `ScriptSequenceKind` to do checkpoint save of all sequences to the file. so not sure what's the best approach to reduce redundancy here

**Review by DaniPopes — APPROVED** [review]

File: crates/script/src/sequence.rs (hunk 7 above)
Comment (DaniPopes) [reply crates/script/src/sequence.rs:65]: right I mean this
```rust
    pub fn sequences(&self) -> &[ScriptSequence] {
        match self {
            ScriptSequenceKind::Single(sequence) => std::slice::from_ref(sequence),
            ScriptSequenceKind::Multi(sequence) => &sequence.deployments,
        }
    }

    pub fn sequences_mut(&mut self) -> &mut [ScriptSequence] {
        match self {
            ScriptSequenceKind::Single(sequence) => std::slice::from_mut(sequence),
            ScriptSequenceKind::Multi(sequence) => sequence.deployments,
        }
    }
```

Then all the other functions (`get_sequence_mut`, `sequences_len`) can just call the corresponding methods on the slices returned by these methods

Comment (klkvr) [reply crates/script/src/sequence.rs]: ah got it, updated in 5bd705d3ca951b6b0828fa7e4e74ed58c90b9814
