### PR TITLE
fix(cli): redirect tracing logs to stderr

### LINKED ISSUE #13034: bug(forge): verify-contract --show-standard-input-json logs errors to stdout
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.5.1-stable Commit SHA: b0a9dd9ceda36f63e2326ce530c10e6916f4b8a2 Build Timestamp: 2025-12-22T11:39:01.425730780Z (1766403541) Build Profile: maxperf

### What version of Foundryup are you on?

foundryup: 1.5.0

### What command(s) is the bug in?

`forge verify-contract`

### Operating System

Linux

### Describe the bug

When you don't have a `cache` directory in your foundry project and run:

```
forge verify-contract --show-standard-input-json 0x0000000000000000000000000000000000000000 <your-contract> > input.json
```

You'll see something like this in the first line of `input.json`:
```
[2m2026-01-09T14:03:54.003279Z[0m [31mERROR[0m [2mfoundry_compilers::cache[0m[2m:[0m [3merror[0m[2m=[0m"/app/cache/solidity-files-cache.json": No such file or directory (os error 2)
```

While the second line will contain the expected JSON.

Running this instead:
```
forge verify-contract --show-standard-input-json 0x0000000000000000000000000000000000000000 <your-contract> 2>/dev/null > input.json
```
doesn't help either.

### PR DESCRIPTION
**Pull request by MarkFizz77**
Fixes #13034
Tracing logs were going to stdout and breaking  `--show-standard-json-input` output, redirected them to stderr where they belong.

### CODE REVIEW

**Review by onbjerg — DISMISSED** [review]

**Comment by zerosnacks** [comment]
I think this makes sense; @DaniPopes, any opinions on this?

**Review by DaniPopes — APPROVED** [review]

File: crates/cli/src/utils/mod.rs [hunk 1]
```diff
@@ -87,7 +87,9 @@ pub fn subscriber() {
     let registry = tracing_subscriber::Registry::default().with(env_filter());
     #[cfg(feature = "tracy")]
     let registry = registry.with(tracing_tracy::TracyLayer::default());
-    registry.with(tracing_subscriber::fmt::layer()).init()
+    registry
+        .with(tracing_subscriber::fmt::layer().with_writer(std::io::stderr))
+        .init()
```
Comment (zerosnacks) [inline crates/cli/src/utils/mod.rs]:
```suggestion
    registry.with(tracing_subscriber::fmt::layer().with_writer(std::io::stderr)).init()
```
