### PR TITLE
fix: ensure caller exists

### LINKED ISSUE #3192: Accessing Cheatcodes Fails when Running Multiple Forks
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63c71b4 2022-09-12T00:05:14.033477Z)

### What command(s) is the bug in?

make test match=test_optimism_relay

### Operating System

macOS (Apple Silicon)

### Describe the bug

A nondescript crash occurs at this line: https://github.com/makerdao/dss-test/blob/add-bridges/src/tests/IntegrationTest.t.sol#L137

This test creates 2 network forks - one for mainnet and one for optimism. I set both the `OptimismDomain` and `MainnetDomain` to be persistent so they can be called from either fork.

High level description of what's going on:

1. It will deposit DAI through an existing bridge on mainnet, switch to optimism and relay the message.
2. It will then withdraw the DAI back to mainnet.
3. Queues up another message to do the same thing again.
4. The second call to `optimism.relayL1ToL2()` fails. When inspecting it appears that switching back to the Optimism fork followed by any call to `vm` will cause the crash. I'm able to call into `vm` just fine in the test contract. It's only when I call into it from the `OptimismDomain` contract it crashes.

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #3192

revm will panic if the `caller` account does not exist in the final journaled state.
There was another edge case where this could have happened.

## Solution
Ensure that the caller account always exists in the fork's journaled state when selecting another fork.

### CODE REVIEW

File: forge/tests/it/repros.rs [hunk 1]
```diff
@@ -179,6 +179,27 @@ fn test_issue_3055() {
         }
     }
 }
+// <https://github.com/foundry-rs/foundry/issues/3192>
+#[test]
+fn test_issue_3192() {
+    let mut runner = runner();
+    let suite_result =
+        runner.test(&Filter::new(".*", ".*", ".*repros/Issue3192"), None, TEST_OPTS).unwrap();
+    assert!(!suite_result.is_empty());
```
Comment (gakonst) [inline forge/tests/it/repros.rs:188]: We have a lot of this boilerplate at this point, should we convert this into a function `test_issue(num: u64, expected: bool)`?

**Review by gakonst — APPROVED** [review]

File: forge/tests/it/repros.rs (hunk 1 above)
Comment (mattsse) [reply forge/tests/it/repros.rs:188]: yeh we definitely want this, will write additional helpers to make this nicer
