### PR TITLE
fix(cheatcodes): improve fork cheatcodes messages

### LINKED ISSUE #8908: bug: logs emitted on RPC failures when forking are not descriptive enough
### Component

Forge

### Describe the feature you would like

It's quite common in our codebase to experience CI failures related to RPC errors. For example:

```Could not instantiate forked environment with fork url: ***```

 or
```
[FAIL. Reason: backend: failed while inspecting] 
````

Here are some logs for more context
https://github.com/moonwell-fi/moonwell-contracts-v2/actions/runs/10927647686/job/30334305230?pr=350
https://github.com/moonwell-fi/moonwell-contracts-v2/actions/runs/10944099346/job/30385149157

It would be really great if the error messages from Forge could give us more details. We are not Rust engineers, so it's tough for us to figure out what's causing the issue.

Thank you!

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #8908 

follow up on https://github.com/foundry-rs/foundry/pull/8936#pullrequestreview-2321724224 not sure what's the best solution here but I hit this while doing some tests, the issue is with wrapped errors that are not displaying entirely when failed from cheatcodes and propagated to test result, https://github.com/foundry-rs/foundry/pull/8936 could be a better solution as will handle all other cases if any...

- with this approach:
image

- with https://github.com/foundry-rs/foundry/pull/8936 approach
image

- current
image

@yash-atreya @mattsse @klkvr

### CODE REVIEW

**Review by mattsse — APPROVED** [review]

File: crates/cheatcodes/src/evm/fork.rs [hunk 1]
```diff
@@ -278,14 +278,18 @@ fn create_select_fork(ccx: &mut CheatsCtxt, url_or_alias: &str, block: Option<u6
     check_broadcast(ccx.state)?;
 
     let fork = create_fork_request(ccx, url_or_alias, block)?;
-    let id = ccx.ecx.db.create_select_fork(fork, &mut ccx.ecx.env, &mut ccx.ecx.journaled_state)?;
+    let id = ccx
+        .ecx
+        .db
+        .create_select_fork(fork, &mut ccx.ecx.env, &mut ccx.ecx.journaled_state)
+        .map_err(|err| fmt_err!("{err:?}"))?;
```
Comment (DaniPopes) [inline crates/cheatcodes/src/evm/fork.rs:285]: If these are for eyre errors then i would revert these changes and update the implementation of `From<eyre::Error>` https://github.com/foundry-rs/foundry/blob/8bdcbfa4d65408b75c4038bd5ee67ce7f6dbd3bb/crates/cheatcodes/src/error.rs#L296

**Comment by DaniPopes** [comment]
I'm not a fan of multi-line errors because it skews formatting for the whole line, it would be better if it was flattened into one line

File: crates/cheatcodes/src/evm/fork.rs (hunk 1 above)
Comment (grandizzy) [reply crates/cheatcodes/src/evm/fork.rs:285]: Makes sense, this would be also fixing same issue for non vm errors like here https://github.com/foundry-rs/foundry/issues/8908#issuecomment-2422931839 if I get this right?

**Comment by grandizzy** [comment]
> I'm not a fan of multi-line errors because it skews formatting for the whole test report, it would be better if it was flattened into one line

Agree, multi line looks good for cli reports but not for tests.

File: crates/cheatcodes/src/evm/fork.rs (hunk 1 above)
Comment (DaniPopes) [reply crates/cheatcodes/src/evm/fork.rs:285]: yes

**Comment by DaniPopes** [comment]
You can get an iterator over the error messages with [`.chain()`](https://docs.rs/eyre/latest/eyre/struct.Report.html#method.chain)

**Review by yash-atreya — APPROVED** [review]

File: crates/cheatcodes/src/evm/fork.rs (hunk 1 above)
Comment (grandizzy) [reply crates/cheatcodes/src/evm/fork.rs]: @DaniPopes pls check https://github.com/foundry-rs/foundry/pull/9141/commits/c0ea8503db90f1bb9554f9ab9336422c54191d4b

**Review by zerosnacks — APPROVED** [review]
Much better :+1:

**Review by DaniPopes — APPROVED** [review]
