### PR TITLE
fix(forge): fix `verify-contract` etherscan cloudflare bug

### LINKED ISSUE #4865: Failed to deserialize response: expected value at line 1 column 1
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8307d6d 2023-04-20T00:05:51.425008000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

Linux

### Describe the bug

I am running forge in an AWS EC2 instance and on verification keep getting a 403 error from Etherscan which results in the `Failed to deserialize response: expected value at line 1 column 1` error as it returns html with a captcha rather than json. 

I've reached out to Etherscan and this was their response:

> We are aware of our CloudFlare protections being particularly sensitive to unknown automated scripts, and returning 403 responses as a result. 
> We're looking into whitelisting this at the moment, however a quick workaround for this would be to make your request more identifiable by attaching a User Agent string

My understanding is that reqwest doesn't set a default User-Agent header and so CloudFlare decides to block my request.

Does anyone know of a way to add a User-Agent header to outgoing requests on forge?

This seems like it currently affects just a small subset of users, although it would future proof everyone if a default user agent was set by forge/foundry. For example, curl automatically applies a default user agent so it would make sense for forge/foundry to do the same.

### PR DESCRIPTION
**Pull request by tsite**
Etherscan verification for non-mainnet chains requires a question mark at the end of the verifier url in order to prevent a forward slash from being added to the url which trips a cloudflare rule on requests from ec2 boxes.

Verification on both Goerli and Sepolia fails without this character present.

Hardhat-verify does not add the extra forward slash to the verifier url and has no issues verifying contracts on etherscan.

Fixes #4865, #5251, #5741

## Motivation

Fix etherscan contract verification on non-mainnet chains.

## Solution

Add a question mark to the end of the verifier url.

### CODE REVIEW

File: crates/forge/bin/cmd/verify/etherscan/mod.rs [hunk 1]
```diff
@@ -263,9 +263,9 @@ impl EtherscanVerificationProvider {
         config: &Config,
     ) -> Result<Client> {
         let etherscan_config = config.get_etherscan_config_with_chain(Some(chain))?;
+        let etherscan_api_url = etherscan_config.as_ref().map(|c| c.api_url.clone() + "?");
```
Comment (mattsse) [inline crates/forge/bin/cmd/verify/etherscan/mod.rs:266]: oh interesting.

this should check if api_url already ends with `?`

**Review by mattsse — CHANGES_REQUESTED** [review]
oh wow very nice find

**Review by Evalir — APPROVED** [review]
super nice find—I think I had seen this on the foundry chat for people running non-conventional setups

pending mattsse's nit!

**Review by mattsse — APPROVED** [review]
