### PR TITLE
fix(forge): do not revert if event with count 0 not emitted

### LINKED ISSUE #10527: bug: `expectEmit(count)` is inconsistent
> @grandizzy As I detailed above, I personally think the `expectEmit(count)` implementation is
> 1. not serving its initial purpose: that is, to assert a particular event is not emitted (similar to `expectCall(count)`). Rather, `expectEmit(count)` when `count=0` applies generally, for all events
> 2. inconsistent: when `count > 0` it applies for a single event (the one you emit just after `expectEmit`), while `count=0` applies for all events (as highlighted in point 1) 

 _Originally posted by @avniculae in [#509](https://github.com/foundry-rs/foundry/issues/509#issuecomment-2883449864)_

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #10527 

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/forge/tests/it/repros.rs [hunk 1]
```diff
@@ -404,3 +404,6 @@ test_repro!(10302);
 
 // https://github.com/foundry-rs/foundry/issues/10477
 test_repro!(10477);
+
+// https://github.com/foundry-rs/foundry/issues/10527
+test_repro!(10527);
```
Comment (mattsse) [inline crates/forge/tests/it/repros.rs:409]: still pretty cool to me that this is all it takes to write a sol repro

**Review by mattsse — APPROVED** [review]
I see, makes sense
