### PR TITLE
fix(`anvil`): latest evm version should be prague

### LINKED ISSUE #10652: hardfork --latest option doesn't leat to Prague being selected as hardfork
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

1.2.1-stable

### What version of Foundryup are you on?

1.0.1

### What command(s) is the bug in?

anvil --hardfork prague --block-time 10

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I run `anvil --hardfork prague --block-time 10` I'd expect to get `Prague` so I can test 7702 tx types for example.

Instead, I get Cancun, which makes sense as per: 
https://github.com/foundry-rs/foundry/blob/65650a6fca64dbd17c093c106b1c61b1982f5469/crates/anvil/src/config.rs#L536
And also because `latest` is the default option as seen in:
https://github.com/foundry-rs/foundry/blob/65650a6fca64dbd17c093c106b1c61b1982f5469/crates/anvil/src/cmd.rs#L82-L83

This should be updated to deliver the latest hardfork when using `--latest`.

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Closes #10652 

## Solution

Return `Prague` as the default/latest hardfork in `get_hardfork` 

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
yep, this should be prague

File: crates/anvil/src/config.rs [hunk 1]
```diff
@@ -525,15 +525,15 @@ impl NodeConfig {
     /// Returns the hardfork to use
     pub fn get_hardfork(&self) -> ChainHardfork {
         if self.odyssey {
-            return ChainHardfork::Ethereum(EthereumHardfork::Prague);
+            return ChainHardfork::Ethereum(EthereumHardfork::default());
```
Comment (zerosnacks) [inline crates/anvil/src/config.rs:528]: I think this is a fair assumption that Odyssey will continue to at least be the latest hardfork
