### PR TITLE
fix(forge): debugger should load sourcemaps by file_id

### LINKED ISSUE #7043: Forge test debugger does not show sourcemaps for inherited contracts
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2cf84d9 2024-02-07T00:15:49.638525000Z)

### What command(s) is the bug in?

forge test --debug

### Operating System

None

### Describe the bug

Sourcemaps for inherited contracts are not found/shown by the Forge test debugger.

In this case, the call to the inheriting contract is displayed correctly with sourcemap:
Screenshot 2024-02-07 at 4 54 49 PM

But once the function is dispatched to the inherited contract (`JUMPI` -> `JUMPDEST`), the debugger reports no sourcemap:
Screenshot 2024-02-07 at 4 55 27 PM

Code for minimal repro; run with `forge clean; forge test --debug test_Increment.` Tested with solc `0.8.13` and `0.8.23`.

### Counter.sol
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

contract Counter {
    uint256 internal _number;

    event SetNumber(uint256 newNumber);
    event Increment();

    function setNumber(uint256 newNumber) public {
        emit SetNumber(newNumber);
        _number = newNumber;
    }

    function increment() public {
        emit Increment();
        ++_number;
    }

    function number() public view returns (uint256) {
        return _number;
    }

    function name() public view virtual returns (string memory) {
        return "Counter";
    }
}
```

### AltCounter.sol (inheriting contract)
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {Counter} from "src/Counter.sol";

contract AltCounter is Counter {
    function name() public view virtual override returns (string memory) {
        return "AltCounter";
    }
}
```

### Counter.t.sol
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";
import {Counter} from "src/Counter.sol";
import {AltCounter} from "src/AltCounter.sol";

contract CounterTest is Test {
    Counter public counter;

    function setUp() public {
        counter = new AltCounter();
        counter.setNumber(0);
    }

    function test_Increment() public {
        counter.increment();
        assertEq(counter.number(), 1);
    }

    function testFuzz_SetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
}
```

### PR DESCRIPTION
**Pull request by emo-eth**
## Motivation

Summary from #7043:

> [ContractSources](https://github.com/foundry-rs/foundry/blob/725c9a95b1331c67b55facd4da1598cbc8e03112/crates/common/src/compile.rs#L276) is a mapping of name -> id -> (source code, bytecode)
> 
> In src_map, the source for the contract is [looked up by name](https://github.com/foundry-rs/foundry/blob/3344e2ceeb68fd77d6be001ce7990742debc2e9a/crates/debugger/src/tui/draw.rs#L331). Since this may return multiple contracts with the same name, the entries are iterated over and the SourceElement's index is compared to the file_id of the current contract source. [If they match, the source code is returned](https://github.com/foundry-rs/foundry/blob/3344e2ceeb68fd77d6be001ce7990742debc2e9a/crates/debugger/src/tui/draw.rs#L353).
> 
> The problem is that this will never return source code for inherited contracts, because it is only loading source code for (contracts with the same name as) the contract being invoked; if the SourceElement points to a different index (aka file_id), it will never match any of the contract sources loaded from ContractSources.
> 
> ContractSources should maintain an index both of name -> id -> (source, bytecode) and id -> (source, bytecode) for looking up cross-source sourcemaps.

## Solution

`ContractSources` now also maintains a mapping of `file_id/index -> (source code, bytecode)`. When the loaded `file_id` does not match `source_element.index`, it looks up the contract source using the `source_element`'s `index`.

I could use some help testing this – it looks to me like the [`debug.rs` test](https://github.com/foundry-rs/foundry/blob/bacacceb97da35ccd03b955aab2a6642ccfedd37/crates/forge/tests/cli/debug.rs#L6) doesn't actually make any assertions, so I don't have much to go off of. 

Closes #7043

Before:
Screenshot 2024-02-08 at 6 40 40 PM

After: 
Screenshot 2024-02-08 at 6 41 06 PM

### CODE REVIEW

File: crates/debugger/src/tui/draw.rs [hunk 1]
```diff
@@ -350,7 +352,20 @@ impl DebuggerContext<'_> {
                 let pc_ic_map = if is_create { create_map } else { rt_map };
                 let ic = pc_ic_map.get(pc)?;
                 let source_element = source_map.swap_remove(ic);
```
Comment (emo-eth) [inline crates/debugger/src/tui/draw.rs:354]: I have a suspicion that if two contracts share the same name, this could retrieve a `source_element` that doesn't actually belong to the contract being called – but fixing that case probably involves a lot of upstream changes. Just noting here.

Comment (onbjerg) [reply crates/debugger/src/tui/draw.rs:354]: that might be right

File: crates/debugger/src/tui/draw.rs [hunk 2]
```diff
@@ -350,7 +352,20 @@ impl DebuggerContext<'_> {
...
+                        || {
+                            // otherwise find the source code for the element's index
+                            self.debugger
+                                .contracts_sources
+                                .sources_by_id
+                                .get(&index)
+                                .map(|(source_code, _)| (source_element.clone(), source_code))
+                        },
+                    )
+                })
```
Comment (onbjerg) [inline crates/debugger/src/tui/draw.rs:368]: this suggestion is poorly formatted, but in essence I think you should be able to remove one layer of nesting by pulling the `or_else` out

```suggestion
                 // if index matches current file_id, return current source code
                source_element.index.and_then(|index| (index == *file_id).then_some((source_element.clone(), source_code))).or_else(
                        || {
                            // otherwise find the source code for the element's index
                            self.debugger
                                .contracts_sources
                                .sources_by_id
                                .get(&index)
                                .map(|(source_code, _)| (source_element.clone(), source_code))
                        },
                    );
```

**Review by onbjerg — CHANGES_REQUESTED** [review]
hyped for this

File: crates/common/src/compile.rs [hunk 3]
```diff
@@ -271,9 +271,41 @@ impl ProjectCompiler {
     }
 }
 
-/// Map over artifacts contract sources name -> file_id -> (source, contract)
+/// Contract source code and bytecode.
 #[derive(Clone, Debug, Default)]
-pub struct ContractSources(pub HashMap<String, HashMap<u32, (String, ContractBytecodeSome)>>);
+pub struct ContractSources {
+    /// Map over artifacts contract sources name -> file_id -> (source, contract)
+    pub sources_by_name: HashMap<String, HashMap<u32, (String, ContractBytecodeSome)>>,
```
Comment (DaniPopes) [inline crates/common/src/compile.rs:278]: Can this be `String -> Vec<u32>` to not duplicate `sources_by_id`?

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/common/src/compile.rs (hunk 3 above)
Comment (emo-eth) [reply crates/common/src/compile.rs:278]: Good call!

File: crates/debugger/src/tui/draw.rs (hunk 2 above)
Comment (emo-eth) [reply crates/debugger/src/tui/draw.rs:368]: Cool – implemented; need to unwrap the `source_element.index` again since I was using the closure value originally.

File: crates/common/src/compile.rs [hunk 4]
```diff
@@ -271,9 +271,51 @@ impl ProjectCompiler {
...
+
+    /// Returns all (name, source) pairs.
+    pub fn entries(&self) -> Vec<(String, &(String, ContractBytecodeSome))> {
+        self.ids_by_name
+            .iter()
+            .flat_map(|(name, ids)| {
+                ids.iter()
+                    .filter_map(move |id| self.sources_by_id.get(id).map(|s| (name.clone(), s)))
+            })
+            .collect()
```
Comment (DaniPopes) [inline crates/common/src/compile.rs:316]: Can return `impl Iterator` instead of collecting

File: crates/common/src/compile.rs [hunk 5]
```diff
@@ -271,9 +271,51 @@ impl ProjectCompiler {
     }
 }
 
-/// Map over artifacts contract sources name -> file_id -> (source, contract)
+/// Contract source code and bytecode.
 #[derive(Clone, Debug, Default)]
-pub struct ContractSources(pub HashMap<String, HashMap<u32, (String, ContractBytecodeSome)>>);
+pub struct ContractSources {
+    /// Map over artifacts contract sources name -> file_id -> (source, contract)
```
Comment (DaniPopes) [inline crates/common/src/compile.rs:277]: Doc needs update

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/common/src/compile.rs (hunk 4 above)
Comment (emo-eth) [reply crates/common/src/compile.rs:316]: Was wrestling with types before, but think I got it now!

File: crates/common/src/compile.rs (hunk 5 above)
Comment (emo-eth) [reply crates/common/src/compile.rs:277]: Fixed

File: crates/common/src/compile.rs (hunk 4 above)
Comment (emo-eth) [reply crates/common/src/compile.rs:316]: Also made get_sources return an `impl Iterator`

File: crates/debugger/src/tui/draw.rs [hunk 6]
```diff
@@ -356,7 +358,20 @@ impl DebuggerContext<'_> {
                 let pc_ic_map = if is_create { create_map } else { rt_map };
                 let ic = pc_ic_map.get(pc)?;
                 let source_element = source_map.swap_remove(ic);
-                (*file_id == source_element.index?).then_some((source_element, source_code))
+                // if the source element has an index, find the sourcemap for that index
+                source_element
+                    .index
+                    .and_then(|index| 
+                    // if index matches current file_id, return current source code
+                    (index == file_id).then_some((source_element.clone(), source_code)))
```
Comment (DaniPopes) [inline crates/debugger/src/tui/draw.rs:366]:
```suggestion
                    (index == file_id).then(|| (source_element.clone(), source_code)))
```

**Review by DaniPopes — CHANGES_REQUESTED** [review]
Needs `cargo +nightly fmt`

File: crates/debugger/src/tui/draw.rs (hunk 6 above)
Comment (emo-eth) [reply crates/debugger/src/tui/draw.rs]: Changed – curious, is there a functional difference between the two?

**Review by DaniPopes — APPROVED** [review]
LGTM, thanks! Pending @onbjerg

**Review by mattsse — APPROVED** [review]
ty!
lgtm
