### PR TITLE
fix(fmt): always return formatted when source read from stdin

### LINKED ISSUE #11871: Formatter integration in VS Code is broken (with latest nightly)
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.3.5-stable

### What version of Foundryup are you on?

foundryup: 1.3.0

### What command(s) is the bug in?

_No response_

### Operating System

macOS (Apple Silicon)

### Describe the bug

Latest nightly build doesn't work well with VS Code: the option "format on save" (using Forge as the formatter) will empty the file before saving it. This behavior is not present in the latest stable.

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #11871
- always return formatted when source read from stdin (and no other args `check` or `raw` passed)
- vscode plugin use stdin and replace content with `forge fmt` output

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/forge/src/cmd/fmt.rs [hunk 1]
```diff
@@ -157,30 +157,31 @@ impl FmtArgs {
...
+                        if self.check {
+                            let name = path
+                                .strip_prefix(&config.root)
+                                .unwrap_or(path)
+                                .display()
+                                .to_string();
+                            let summary = format_diff_summary(&name, &diff);
+                            Some(Ok(summary))
+                        } else {
+                            match fs::locked_write(path, formatted) {
```
Comment (DaniPopes) [inline crates/forge/src/cmd/fmt.rs]: why are we locking? this implies that readers also lock but i dont think that is the case

File: crates/forge/src/cmd/fmt.rs [hunk 2]
```diff
@@ -157,30 +157,31 @@ impl FmtArgs {
...
-                            &TextDiff::from_lines(original.as_str(), &formatted),
-                        );
-                        Some(Ok(summary))
-                    } else {
-                        match fs::write(path, formatted) {
-                            Ok(_) => {
-                                let _ = sh_println!("Formatted {}", path.display());
-                                None
+                    let diff = TextDiff::from_lines(original.as_str(), &formatted);
+                    if diff.ratio() < 1.0 {
```
Comment (DaniPopes) [inline crates/forge/src/cmd/fmt.rs]: is this not the same as original == formatted ?

Comment (grandizzy) [reply crates/forge/src/cmd/fmt.rs]: tbh I have to check this more and find a way to repro first, I guess they're the same ... moving in wip

Comment (grandizzy) [reply crates/forge/src/cmd/fmt.rs]: brain fart, pls ignore

File: crates/forge/src/cmd/fmt.rs (hunk 1 above)
Comment (grandizzy) [reply crates/forge/src/cmd/fmt.rs]: brain fart, pls ignore

File: crates/forge/src/cmd/fmt.rs [hunk 3]
```diff
@@ -127,12 +127,15 @@ impl FmtArgs {
                     let path = source_unit.file.name.as_real();
                     let original = source_unit.file.src.as_str();
                     let formatted = forge_fmt::format_ast(gcx, source_unit, fmt_config.clone())?;
+                    let from_stdin = path.is_none();
 
                     if original == formatted {
-                        return None;
+                        // Return original code if read from stdin.
+                        // <https://github.com/foundry-rs/foundry/issues/11871>
+                        return (from_stdin && !self.check && !self.raw).then_some(Ok(formatted));
```
Comment (0xrusowsky) [inline crates/forge/src/cmd/fmt.rs]: maybe we could enhance the cmnt with something like:
```
if user passes the `--check` or `--raw` flag they are performing
a check and only want to get an output if there is an actual diff
```

but its implicit in the flags, so no need if u don't want to

**Review by DaniPopes — APPROVED** [review]
