### PR TITLE
fix(`anvil`): arb fork mining

### LINKED ISSUE #9152: bug(`anvil`): arbitrum and anvil block mining inconsistency
There's a deeper issue with how we handle Arbitrum in anvil, which is causing the `test_arbitrum_fork_block_number` to fail.

On arbitrum `env.block.number` is `l1BlockNumber`. See https://github.com/foundry-rs/foundry/blob/09824ad0cdb4d20e280e1698ca9097b869b2a4da/crates/evm/core/src/utils.rs#L54 

So when we fork off of arbitrum the `env.block.number` is set to `l1BlockNumber` that we get from `get_block(fork_block_number)`. 

However, upon mining a new block we increment`env.block.number`. See https://github.com/foundry-rs/foundry/blob/09824ad0cdb4d20e280e1698ca9097b869b2a4da/crates/anvil/src/eth/backend/mem/mod.rs#L1102. 

This `BlockEnv` is then used in the `TransactionExecutor` which results in the block being mined with the incorrect block number (i.e `l1BlockNumber + 1`), instead of `fork_block_number + 1`. 

Fix for this is a bit hacky:

In `do_mine_block`, for Arb specific chain_id's; temporarily set the `env.block.number` to `storage.best_number` (which is being correctly maintained). Use this modified `BlockEnv` in `TransactionExecutor`. After tx execution is complete and block is mined. Flip `env.block.number` back to maintain `l1BlockNumber` consistency. 

@mattsse wdyt?

_Originally posted by @yash-atreya in https://github.com/foundry-rs/foundry/issues/9151#issuecomment-2426143383_

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Closes #9152 

## Solution

While mining blocks on arbitrum forks set the `env.block.number` using `storage.best_number` as `env.block.number` actually represents `l1BlockNumber` and not the arbitrum block number.

### CODE REVIEW

File: crates/anvil/src/eth/backend/mem/mod.rs [hunk 1]
```diff
@@ -2952,3 +2953,17 @@ pub fn prove_storage(storage: &HashMap<U256, U256>, keys: &[B256]) -> Vec<Vec<By
...
 }
+
+pub fn is_arbitrum(chain_id: u64) -> bool {
+    if let Ok(
+        NamedChain::Arbitrum |
+        NamedChain::ArbitrumGoerli |
+        NamedChain::ArbitrumNova |
+        NamedChain::ArbitrumTestnet,
+    ) = NamedChain::try_from(chain_id)
+    {
```
Comment (mattsse) [inline crates/anvil/src/eth/backend/mem/mod.rs:2964]: we could upstream this to alloy-chains as well

**Review by mattsse — CHANGES_REQUESTED** [review]
makes sense, can we add a simple test for this?

**Review by mattsse — APPROVED** [review]
