### PR TITLE
fix(primitives): track both 4844/7594 sidecars presence in `FoundryTransactionRequest::build_typed_tx`

### LINKED ISSUE #13217: bug(anvil): tx request sent with eip7594 blob format doesn't result in `TxEip4844WithSidecar`
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

master (e125369c21f0fe284b3e3a9bbf07955823b899f3)

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

./target/debug/anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

Sending a simple blob tx : 
```bash
./target/debug/cast send 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 --from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --unlocked --blob --path ./a_lil_blob
```

triggers this error on Anvil:  
```
RPC request failed:
    Request: EthSendTransaction(WithOtherFields { inner: TransactionRequest { from: Some(0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266), to: Some(Call(0x70997970c51812dc3a010c7d01b50e0d17dc79c8)), gas_price: None, max_fee_per_gas: Some(2000000001), max_priority_fee_per_gas: Some(1), max_fee_per_blob_gas: Some(1), gas: Some(21001), value: None, input: TransactionInput { input: Some(0x), data: Some(0x) }, nonce: Some(0), chain_id: Some(31337), access_list: None, transaction_type: Some(3), blob_versioned_hashes: Some([0x01a915545ed9da7598c52136719cf9ef55d0e5c7eaddc0bbc9971ac9397a48f0]), sidecar: Some(Eip7594(BlobTransactionSidecarEip7594 { blobs: 1, commitments: [0xae5088865bc940945214d90d95411d3fd9b1a7f5b2aa66aa0ca2cd0ea0166ffc39842f6eaa101e3bb4dc67d99283b387], cell_proofs: [0x82fa16dee8692a1eae26f5e2cac7fc97711dbd42f47a49624557e0c9ba2cb844454d325bc3a38f14602bcdc78d4e62dd, 0xb15ca34f9b84d393673df3cdd724c70b7996d7bb68a681e8b8705050a3803259f1103df36856c404e9074760b0a48776, 0x81e8889d3cfe5f63572f53f5ddf6a57543a2d8fd8d092c163afc433c6c1798673f25f7eda595f4668fb3389f21b377dc, 0xa2183f28043e2aa6b4b72501913be8bd8cf6cdda9b90d3965d1e6b13d0feddd6f88f53b34cc7cb6296ecb7cee74aa0d7, 0xb92f90305ea57b89cee604d7e9699ec48dbb24c0e26a6079978f588d57a14d488997cdf9667d17c9f050bbf14002a002, 0x8a16f0044ed0471811efa39e54d010eaa9970044251d5a06642a249acff83b420749521deb766a74350f4fe2c340b999, 0xac558b8eb3e06cce54ad74eafe6830787ccc32d8f613d664a371873a41055fc42619b9953e8bf73431ed76bf7469e037, 0x8cdef73ee9cb4d462381abc87eeccabdd173984b32bb0a343116dcbfe599889c2d5fa5b4c0ea44685f428c1666999d06, 0x979dd7e8b93dd590e8762e3bd6629fb076990c669ab227887d4ec6880a68c6ee1a27be385d32475272a42af9d2863722, 0xa5aeb9cab0c47bf9a802a9426f0d496cd7103eda73159cafbf6bc159d0270795e9abfb143c242ae093cfa7669c38aa10, 0xb529d4036d7ba52b72e03f9d4994e5d63acbd6a734d6490845bc930a636da7897ed17102177032a3e37ac858f6d0f423, 0x8923a373b5e3a8ac180f0a3c71aab97e7476ba23f238fbb99a952ddd075718393e16c0797df3a30fd27a27b49e1f5ae7, 0xb3d97a7d205c6c116689078a081f84c3ee84f2f4db02042571f45dcaee90721087e5c799d2b706a57e39a4db5c4488cd, 0xa89dfc885bed7b38a0a0c0dc55e946eeaae52bfd7d0eb20842301874c6bd2ea089650fa84629fe6b57acd6c50594cf21, 0xb907e369ba282b9068d796e3fe03fd8cbbbd9d7213d94ffe10249009ff0e9238cea59d9919c30362b3417d3112468c2d, 0xb1b578be842b4f0fbf4b00a975d7610bac48aacbe25307dfeac17b52655ec6b446de04f0201dfdd2e97fa8d41dd0826a, 0x846bb42eaece153fc3e9b927294a2a485c32547cb03e1dcea25cd21448e8f99f7d922192f71138703c1aa2fdb3a82673, 0xb8113703358f889917513323363a6d9b4dbab3908d0eb0f9f048bb11093bfae3e77a4ac0831a58e06b71f3a127b65681, 0x899fc090495dbeaf4bf81063303c3bcce94127ce343065679e22bb23fed839c2cd5f02469c8dd5c33b2e15716c35e4c0, 0xb7a00a2ee55c48672709248e05c8c0085e6e082e8515f744232b8dde35902a055ac949e4a112b76ccf212b530808a023, 0x872b0e652dcebce87daa7858b3071fd27f33128d1a006f75439de42b1492ab1fd5d706f012a5fb7d7467d38c71e00d0f, 0xb56651fdcffd487c37972665c03f1d33295d826391eb5479d5b14534e323ecc3617cc4c65514321a60d4f4e263678a2d, 0xa7cc44d5fb8f9300949bc3a906fe8095348ce9a451475d78679eb56fa6903f055079e74dcf4968577ed3ae97a14b3ddf, 0x93445f4c997667a670579d64a11d740f870087bc4314de9b385b554ac49160cf1c5c12e2ccd6c8de6c23a8d1fc560849, 0xa6f78bf0ada4ae6d24e4da37b5fd19681ceebd0bab143ceeb86f2c05ce413edbdc80847106a936ae9e65001b973e85b6, 0xacc584ef190386fce20e61ef537493fb2c157a74f27082d49f2ee7b8b53c4023cba9aa625828e4b70e18b953ae703935, 0x884ac13c696525a726ee5a3f5cfe1e513bc01b9d7e017e04a3a523942f27d6b682e31131b2fd7c3bd6c1c830309ac706, 0x8abadf582ac43faca4ae4570a9c7d4cd8f112a6d9e19af931c4523d7284814254a913b98948d66a170e227f7445afe79, 0xa63052f67c4087946fb4ffcd4dd826f1bf52e84c4151461b27bcba023ed17e4d46393fead0ebb37dc00bbf9366cc1b7e, 0x92a4ca79eb82c6ff936c7738fa14774d97fec539b6efea60f9d7ba92e6f01b6ad21c09aa9785fc4bcd11127ce089d55e, 0xaad0255b7e855d7f62f72eed16c453284a176e8498d4c18338d174fe6aee5ca8dc2b4b91040ae13bbda19ad9c251377f, 0x8e87b9f7dfaaa7219eddad5ce65c66302b1a46abce8c46c2fe7437a46ccd241e26da2d54f1817088f715325a80ca6ea2, 0x8875d0362a83f0bb7125d83b6dde35fc32143b44cb7e125b81b52664560f281701244f48436b0cccdd75dfaf207e6d35, 0xb07ddba4afa53c25cf6c5cf956f865895d79fcbce1cfd6f2f66a9ef5279e27544e07773ebda39ebcd3eb4a337e41c64f, 0xb918d15706e48938364c4c60f71207e47504d7102d37dfaa75a3613f5604eb61ce53dd3753b2cf7b6a7d049caab22399, 0xa8b1d0f9222a8a2ccc6820ff51f1f6c136c719219cefbbf78017c3bea6b9b66bb8cd5bcafb11af71f44046bfbec82c97, 0xa27dcc42462372c3ee3945fac07b0bbe0c6c400cbea726160ac1a299f0cf544dc48eae9a4f83325bd301ea574451ad53, 0x967c1ac5c30ec347eb021d72bf7b03194842e4f912cd03488eb49efe45e4b926d966154a00f2d59969d8b21874e63626, 0xb30db1291ad308ad5e8bf1d55cc96db29420e2a9a0175ce753d2ee7986f21d560ce210dfbd49c74cc6648bb6ed588eb6, 0xb15cce16f538458d54666d480acc7fd1332f81689fefa8c79e2168df2ff7bb293c4617aab8fa5d82a4b521a10891f031, 0xa3d39552d58ec14e5263ba75ef670f823085f13ebc850e80326e861ca440cf5351407f9a0abb8b3a47a4d27cee08ed57, 0xa725e6e52ded2b0b1947d4448cdb8e5369dc23f2e59d54639d5f53d0cb6f38491bba486ffae358f36dd9537916120899, 0x8ed68f77a58978fe774eac59b90d2f3cbf32813f68c7ef437e7db0552cb1470ffed1b36dda948c4de11df44ec78c534e, 0xb6155d5c58dc56e65f44a66d9732837b05162ee559a65dcc902afb818b2f01fd93e02ac4f47045aed19470bd1f72344c, 0x8ab9eb28a6314874c2b08c52742664ccc13504a1fa3f48394d9859f102e8b538a90cbadfcadc5125058ad84dab567ff9, 0xa78cbf98bae0530fb4fd250787caabfbfc01d2992361a489471ef16943abbb1abbb81786035c57e482c51ac444d2735f, 0xa23b5da0d5185face17c5bb72d9af27a68688bfd46441c07ae54efff488372b0343e0d6b6ed8418f07c4ebb1dd8adb25, 0x88de083bf17ff6bdcf23f705ee32485c5b7930c8406374494c77121cf0b0ebdbf0505984ab22bdcc3e1cfeae5cb2ddbf, 0xb4bed2de7eb4c40e572ee3f94f97b71e69b91f9eae386a95977d67bbc23c4809996d0401c0dd5007b1370478dec57795, 0xb2f6369b8b3e865799ed2abe6c89d5e86a52e4f3ee51b26bb2b03674b4f65d6e3d57ab32ce5853740db8559ab2d2e6fa, 0x99ceb0176d193599369c8a42bd628f49705d05e5cb5275cfea2fb910f258e1b29114d78b0f26a5afb6663377c55e3853, 0xb5eb1f90a0b9e33f7a9eb7e6775bddb38f8e6c62a34885834233d0bbf25c05239e82a46b49542c860312923f57f33217, 0x90229c787ace8d9b74f6717bf5b2ea66fc5cec2080beecdddafaeb09997c1f74f5c98ee6ef4ab2719782f4160e406c52, 0xa34ba6dd15db7379e558bbea0092224ed7c8470bc0c0aff6616635e26eb9dc9b09cf5dddfca70f6e87777687451e6378, 0xb32eae9436a1ef3342f046010be81266abaa4d792ee0ab7d9359e56c4f91b6a31e7ca99f5454294c6e236da5fa96a870, 0xa7c17e0488477fbad4056401d0fb5bd272795fb3849c4dde7f85c4dd68987aeec9fcec125873f564c79fc6a1c351e9ea, 0x8fe639d69f7949ffda483606c7ebedf853b19b8d34d46daea439388e1f8998b49515af8a3650127388583340ed5b0abe, 0xa7fd2d093bb985529d01caefe58ab2a586f3a7b6c0e23b89201590477c26a6bf6a9e92b044467f22be0a40a14e0a42f9, 0x912d75975633f26e2a6200b96ca3e87eb86814328719be4b4daed692fee0b5eb672450219697299ab96d7f34306b8cf6, 0xac867e83c8b6d202c9e1c1c6680461d86803c87b7da9c803949a1ca670166f01e0923a35e07a541fe4a7c7a52e44b9e8, 0xb5fc08e4b725f36ff55ce4df100ffbde9a28e0d3cfcfa924fecbbd97423729335f1838f04560695815d250a214f81f3d, 0xb846bf4c63897d33e3fd8d7edc2887310727fb4b92187b84eb00ef620d284d257bcdfa27825f396e780f6f3996a5a606, 0xb445aa300ddd58bb729903665e311c968982722207ddf24fa09b0895d2522150f0ff04b66aa3fb4753e283543f68066c, 0x930245650810c58d823874e8a67d3c1da6d44b8a08ec60ca7ddaf0ce8ce2642953fc3a6c30db40e35938e763f1a67c62, 0x96fdcca0c56b8a46215520d5dd02ffb6b84536c9aed0afa04c8087b5089eb9d5dafdd3dd00d9d2129d47a9aa360e84da, 0xad49375d338f26b104ce0dd4c724d97a673ace57035c46d9a0033331fe21c0a6de7d112f309ae3f78f382fdc78261e45, 0xa2e613f94128693346075d20d287fb73ad59c321c68b309f2dd7d4e095d4669b2d9b1f92cacdcc87a612edcea7509f4d, 0x81bfcddedabfce4becf47d13b705e26f3a223ba6dce6541e59f6a5057a06a8a93f4a0c492dc8d41569fc70ba65503d31, 0x8317b7aabf17cf4e4ff0925ce3ecc8ceb604ed899687d6dbc459529664ea4f8e057deee7ce74299e00952b43da01fb8c, 0xb5253634a6b42508baf4240142740b81c83713263bbae609f1065c07d15a7c26b75e1314e1d930ff853885511a366572, 0x943b59bbe6678b3d717af9edf0270e15b27341d71b0551e9baad7d15ef65d7e7ef11ed17a040eb0b2f214e5b5154b367, 0xa7c23ff3216fa6046e41f2c60e1bcf04978cd3a8f7550b091a950f0d03ad1155f82efcae2d0e344011003924c58be998, 0xa1faf2f8c6b8876af1b0cfa0895c1e87a4b2da26a89c4854b4043b08a4983e861fd7f9e60309046bfc68aca13a3a986f, 0xa00a43c4373c41d7e519d5995ad999994f9554219afe6b741d53c8c5608981deca119512a976a8cce546124720b0d102, 0xa5ea792fb2f2acbdb5918bf40084ebcca05ea3afb12206560ac02ec804df3d59cbcb81d6aaa1f0e536f8fc7f0b44d2c8, 0x85a57a6af5c1d2bf52991d17d0f67262d0f01625b8c8c60f9e2f352a6c8961e06bed35ecc89f5fec8c76e02b87a660e0, 0xa48abe70765c6513194c9d60c939dd7b6822dbccc21877cb3a72386e23721b9a074a59e99f78dcc295feaefb7654126d, 0x90d1eab203076ddf5d23df6008151dc5a9eb32126bad1e3a1b664bb8af37a74ec582779e5f5fba6540abc776ff31e3a2, 0x92a0c0cc7b3eb569f0587795b52b318bff3c7be5812468db0b0c0f15ed46ccd4ec27bbb1afdca5caa0132b6c69ca29e0, 0xa935c33ba42aa9fc1157c182d14dcd8010f46608d96448a062336bcf9f79216ec1a30700ba1c5db0d5ce4350b10efc94, 0x829e57eeb2b6f58913903996131140cf10b2cf939da595f6601e5c568e4b57e320355baf8bb007d6816f67debd584613, 0x9121cea0aaa64a9b3fd6d8a1c9ab914fe92868506a7be2a7ac9fca8d18a23bc5d4ef6a06943d65aee4fc3d59a8d0317e, 0xa7b6ebddada0ea226657068f068719c8a7123588409c2d1b3cd6a6d7b926d8a602adda615a3ed9520d874a54e6418358, 0xa091bb4ba1eecad96170aeb5aa87ef1e2be4b2d6355a5f4e1b6acb6fae3a244b28566e1a8029aff0b0dfc38c64aa323d, 0x969519df6f789c8120b72ad9b35f202854b4fae3851b03a35620a03bc9b315bcf51ddadbdb85b0b235169dde914b7f85, 0x8aa469bb17bddfc3ec0794f5a5b6e27c918944f583da1b0fc12664c2835e960d8341033254f384715542dc2c520f06f2, 0x8e148de84478a723173bc33c08c68bd13a7bd4028671b5177f71a225a9cfe7f3243f318b5f1ca572a8ea9a7fbd93f540, 0xa55468472645a19d816d384c738448fa432601c8a2e5c0a18c2446767b9bd17184faca47082f1dbb1eea173fa04a22e3, 0x940c80004d0e2c65e75be82d44f8099fac7701133c362d6229f9a8b18d35a387762c07d028c84ad24e609a02eaf0214f, 0x94332517ca0d72920820604cc2b16cb0bb4a9be3cf9b71e7f02817f26dbb99443432bf186e80c8f8922be40ab1b20fa6, 0x86e831a4d012e3981186b6e269ee8f07d1072207494e77c238b2943cbffe640b261552bcd4d05d3d6009c29e687da425, 0xa124c3a5957a9e48ded9562cfe53fbb81166620b97f624126ac952aaf16f4a10ee31f91bfb591adcdaab17e43bb69fbf, 0xaeffe5359e2360334b0c789f5c07b38303276f75a46a652aa158b14d06645a119aef8dc9b03b1a6c19ae7d43854e60e8, 0x9947626f65e1c5a0bb7aa587758dccb72ae429161086616c1c726b4b0752c36ac5da3161c735e721c49e9c09b7a22c6d, 0xa96cb35983431f008d506a591a573d8be08a7db223a083b50d1f266836d52163ea395f5985e0064eb5ed14bdc0e44786, 0xa55f30832ce39c5a9d0ad99434085c6288ab61899643639ce937aa4d0ff9a3fe076eea150221fd746cfed3ab27a11a2b, 0xb2cae22ebc1c4cd4c84e11bd8ddb1c7d6a3ce7bd50328db1828ea9cd40c7b01d9c4f6d8bf3662df0ecdeb210334de89a, 0x92a0daf30c5f6994e50cedb240504d397e711ff6d2be24a2f6bea5f440dea6b8a706ff9056d654d758e06fdcddc87166, 0xaa103686914a1cfea9be17ae217a14ad92a80d11405232daeec3462c60abdc214ed74d7dbaf76f3d3cdf6d442700d075, 0xafa38213052d9e1ee40a1aee62e8013bfe957d92e36466c9ea338f9e65c4ac79cd1930ba70496db785f1cf511a374a58, 0xaf27ba769d97be333648bbfcfccb1f35edf0efa666b347c0495c4d415e0d7eb883c7ba9149b5c87a7897a6d36b1a94e6, 0x8be862871b2fa9f25283b2aa893b454ac5e472dc9e92374c02376caf77219112a82a76073b68491e0a0b13823c920440, 0xad8528601b77947c3e6682e86b315edb9b001f7235096f3e470a5990854195a7e9290184a5cc3f8b28fd1b51ab3531cc, 0x8b0f60b5e7827032af5a26b78f456d8d96c398af7819947486dc5153ed70c073b17d5a136688a7c5eeef852b23df1a98, 0xb66901ff7a1b3a64d0fbf16a93af08703d0397f939d6153964a1ea4c7b750eda80618f69960f5e092c4b02d6f1f56471, 0xb9edd4807e1b7eb6b19623d312cf5bd888b1773ede6d37cf1f35a43dbe745386f1ad2015b45c84e78cf1d0cfcafedf8b, 0xae3920de0c44f086b8e8fa2e485afdbc3453844c29360b718428e5437ec4ff1f7d66f8344771529b12e23d28dbed4058, 0x807fa7d6e93c641a9205b736f962451e8f9e833dfc0a2a337faebb21e9c94ba56b07be3a5927ef69551ba59f7c9d55a7, 0xb32125bb002cb2c728537ec02c25a4e7c46fda01464df661a9b93b8c4ce470b9ce7c88303edf95596cce8490defd3460, 0x9832adc23656fd73b5388cb96b58d494f0c07c399b1bf5fb48c0d15ec22e9e8fb8246321f81153364c79e004e4ef80a6, 0x929d7f6190b8da2745f730684ec1d15f49cf62b06550c8b13397e748cbf21d7957fccad95eb9615c72cd4f56d5d6016d, 0xb95c5f4c6ff5e8273cab10a816892c409fc3abfbdc796bbb668f43788a0e73b2e201a8a35be858727837b0f912feb230, 0x8dc553da928e00471965e76b4afce436c3b7a6cb12dfe34c737c2e26620e6a750c090e553b70a9c3ca9cfe8487ea4e61, 0x9131e845d51b48ed187e80aaee30e60cab366a05d73573d419680024cc0e15e64c8421b04dab8286b9b65c0ac477a76e, 0x83193b77c5a63bf1e580627821199b328f2c6350f7c172842c935ef05a84dadcca867127927e70b7945719b3fd6c13c8, 0x94428cb1c3d73f8ef51e4dbdbdbbc36d69b006d32e7493203aadbe17c2bb3ae034679f6e6af29376e5f1e71c77425eee, 0x98b2cd8c0469d20704d6d55721b39e4c3da720be7370fbfc4fb963fe4bc7262b3ee9b6bf93252f80b7539f18237d8fe2, 0xad9150da50e15844f6e6b128e4c2686e58b5f95f7eeb1817b754a08ab6e09e4e0c44c095adbcbb41ca31edcf69d89d52, 0x96454dc354b11b2279e27ebc409660ff334db9499a0317fbf88ee859535476f621f9bf800ea4b80d46793ee032e97b08, 0xa78e8fed8bc44e1622e2c54c0c6e7c58c1cb6288146832616d4720358a1c9b39d42e711bae5f7819695aa48aa1c98407, 0x87cc95fba787f72a85e92075aac01a90e4f0889185e3aedc934e687355a56682a6046a522172542335ce4384f3c0a3d1, 0xab35d96db0f9becfaf6c69c34d8110472b6cffe59e2c52d84baa7c812d408fdc1bd85d430ff6f9bd0c902c4466df1a11, 0x84d2a26abe4b122cfe8626c119a3ce1c0f908df38e0a155cd8165f87374d0ac057c57ffb8cf309c81004982742f55e64, 0x93cf5a62078fad1408b2baee04562c33808550cc93422b4b85aeedc480c82ac9228996b1e94621003934e7db84d68493, 0xb9def8336bd3606a9b5bda77ad1ed3b3e02290810f3112d967eee27792211d1ffe6e667d1663ed83f8cdf8511588a3e0, 0xac31edbcf4ace8f881c69e0df76a2e3da1c7bfa0976738fd0607d88d1836f2c7e467ba840a69fa8942c95a892bff7c7e, 0x8577d4d560d90b1f90105bcbde2716c1dd9fc1c2308f02226e55430477e15605415cd19de96d5013cb5220515f2058ed, 0x836b40008cc14a87c3ef9f2bd6495149cd1171bc718573adaff74ff1bdd3cbba6f7442bd33ff7b06d461298ec210a5e4] })), authorization_list: None }, other: OtherFields {} })
    Error: Invalid params: Failed to decode transaction
```

This is probably because the eip7594 blob is not properly handled somewhere, so Anvil builds a `TxEip4844` instead of `TxEip4844WithSidecar`. Indeed when I relaunch anvil with `--auto-impersonate` to skip blob validation the problem disappears.

### PR DESCRIPTION
**Pull request by mablr**
## Motivation

Closes #13217

## Solution

Check for both 4844/7594 sidecars before building without sidecars
 
## PR Checklist

- [x] Added Tests
- [x] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/primitives/src/transaction/request.rs [hunk 1]
```diff
@@ -216,9 +216,12 @@ impl FoundryTransactionRequest {
                 access_list: self.access_list().cloned().unwrap_or_default(),
                 ..Default::default()
             }))
-        } else if self.as_ref().has_eip4844_fields() && self.as_ref().blob_sidecar().is_none() {
-            // if request has eip4844 fields but no blob sidecar, try to build to eip4844 without
-            // sidecar
+        } else if self.as_ref().has_eip4844_fields()
+            && alloy_network::TransactionBuilder4844::blob_sidecar(self.as_ref()).is_none()
+            && self.as_ref().blob_sidecar_7594().is_none()
```
Comment (mablr) [inline crates/primitives/src/transaction/request.rs]: This is not pretty because the traits have conflicting methods.

I guess a nice (but breaking) follow-up could be to unify/refactor alloy-network's `TransactionBuilder4844`, `TransactionBuilder7594` traits to avoid this kind of problems and make it more elegant.
