### PR TITLE
fix(coverage): use first opcode for if block with statements

### LINKED ISSUE #8604: bug(`coverage`): if/else branches are evaluated incorrectly inside for-loop
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0b73b42 2024-08-05T00:19:50.130854000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

None

### Describe the bug

Inside a for-loop 1/2 branches are evaluated, L11 shows `#/+` despite L12 and L14 showing coverage. Without a for-loop both branches are evaluated as expected.

Screenshot 2024-08-05 at 13 10 51 copy
Screenshot 2024-08-05 at 13 10 51

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.25;

contract POC {
    event IsTrue(bool isTrue);
    event IsFalse(bool isFalse);

    function coverageIsPartial(bool[] calldata isTrue) external {
        for (uint256 i = 0; i < isTrue.length; i++) {
            // shows partial coverage
            if (isTrue[i]) {
                emit IsTrue(isTrue[i]);
            } else {
                emit IsFalse(!isTrue[i]);
            }
        }
    }

    function coverageIsFull(bool isTrue) external {
        // shows full coverage
        if (isTrue) {
            emit IsTrue(isTrue);
        }
        else {
            emit IsFalse(!isTrue);
        }
    }
}

contract POC_Test {
    POC internal poc;

    function setUp() public {
        poc = new POC();
    }

    function test_coverageIsPartial() public {
        bool[] memory isTrue = new bool[](2);
        isTrue[0] = true;
        isTrue[1] = false;
        poc.coverageIsPartial(isTrue);

        bool[] memory isFalse = new bool[](2);
        isFalse[0] = false;
        isFalse[1] = true;
        poc.coverageIsPartial(isFalse);
    }

    function test_coverageIsFull() public {
        poc.coverageIsFull(true);
        poc.coverageIsFull(false);
    }
}
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #8604 

Atm for branches we determine instruction anchors for both if / else statements. This works OK but in some edge cases like https://github.com/foundry-rs/foundry/issues/8604#issuecomment-2270443031 where last JUMPI instruction within if block triggers replacement of anchor properly / previously identified. 

## Solution

- for if blocks with statements the anchor is always the opcode of first statement: introduce `is_first_opcode` flag for `Branch` coverage item kind. Set flag to true for if with statements and test flag when finding branch anchors. If set as first opcode then find instruction from source map /  ic-pc map (`find_anchor_simple`), otherwise by looking up last JUMPI instruction (`find_anchor_branch`). 
- tests (fixed test for single statement coverage false path where all lines were shown as hit)

### CODE REVIEW

File: crates/evm/coverage/src/analysis.rs [hunk 1]
```diff
@@ -424,12 +425,20 @@ impl<'a> ContractVisitor<'a> {
...
+                                    branch_id,
+                                    path_id: 0,
+                                    is_first_opcode: false,
+                                },
                                 loc: self.source_location_for(&node.src),
                                 hits: 0,
                             });
                             self.push_item(CoverageItem {
-                                kind: CoverageItemKind::Branch { branch_id, path_id: 1 },
+                                kind: CoverageItemKind::Branch {
```
Comment (DaniPopes) [inline crates/evm/coverage/src/analysis.rs:437]: realized that most (all?) calls to `push_item` set `loc: self.source_location_for(src), hits: 0`. Do you mind making a PR that adds `push_item_kind` that accepts `kind` and `src` to dedup this?

Comment (grandizzy) [reply crates/evm/coverage/src/analysis.rs:437]: pls check https://github.com/foundry-rs/foundry/pull/8616

**Review by mattsse — APPROVED** [review]
nice,

pending rebase

**Review by DaniPopes — APPROVED** [review]
