### PR TITLE
fix(cast): improve handling of `mktx --raw-unsigned` with runtime validation

### LINKED ISSUE #11110: When creating raw unsigned transaction the `from` parameter is required
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.3.0-nightly Commit SHA: b57f7c15b1c19b65057ffeff799c76eed3f283b0 Build Timestamp: 2025-07-26T06:04:01.741775000Z (1753509841) Build Profile: maxperf

### What version of Foundryup are you on?

foundryup: installed - forge Version: 1.3.0-nightly Commit SHA: b57f7c15b1c19b65057ffeff799c76eed3f283b0 Build Timestamp: 2025-07-26T06:04:01.741775000Z (1753509841) Build Profile: maxperf foundryup: installed - cast Version: 1.3.0-nightly Commit SHA: b57f7c15b1c19b65057ffeff799c76eed3f283b0 Build Timestamp: 2025-07-26T06:04:01.741775000Z (1753509841) Build Profile: maxperf foundryup: installed - anvil Version: 1.3.0-nightly Commit SHA: b57f7c15b1c19b65057ffeff799c76eed3f283b0 Build Timestamp: 2025-07-26T06:04:01.741775000Z (1753509841) Build Profile: maxperf foundryup: installed - chisel Version: 1.3.0-nightly Commit SHA: b57f7c15b1c19b65057ffeff799c76eed3f283b0 Build Timestamp: 2025-07-26T06:04:01.741775000Z (1753509841) Build Profile: maxperf foundryup: done!

### What command(s) is the bug in?

cast mktx

### Operating System

macOS (Apple Silicon)

### Describe the bug

When creating an unsigned transaction via `--raw-unsigned` parameter `cast` requires the `from` parameter, even though that is irrelevant for the creation of the raw unsigned transaction.

```
❯ cast mktx --raw-unsigned --from 0x0000000000000000000000000000000000000001 --nonce 0 --chain 1 --gas-limit 1 --gas-price 1 --priority-gas-price 1 0x0000000000000000000000000000000000000001
Warning: This is a nightly build of Foundry. It is recommended to use the latest stable version. To mute this warning set `FOUNDRY_DISABLE_NIGHTLY_WARNING` in your environment.

0x02dd01800101019400000000000000000000000000000000000000018080c0

❯ cast mktx --raw-unsigned --from 0x0000000000000000000000000000000000000002 --nonce 0 --chain 1 --gas-limit 1 --gas-price 1 --priority-gas-price 1 0x0000000000000000000000000000000000000001
Warning: This is a nightly build of Foundry. It is recommended to use the latest stable version. To mute this warning set `FOUNDRY_DISABLE_NIGHTLY_WARNING` in your environment.

0x02dd01800101019400000000000000000000000000000000000000018080c0

❯ cast mktx --raw-unsigned --nonce 0 --chain 1 --gas-limit 1 --gas-price 1 --priority-gas-price 1 0x0000000000000000000000000000000000000001
error: the following required arguments were not provided:
  --from <ADDRESS>

Usage: cast mktx --from <ADDRESS> --raw-unsigned --nonce <NONCE> --chain <CHAIN> --gas-limit <GAS_LIMIT> --gas-price <PRICE> --priority-gas-price <PRICE> <TO> [SIG] [ARGS]...

For more information, try '--help'.

❯ cast --version
cast Version: 1.3.0-nightly
Commit SHA: b57f7c15b1c19b65057ffeff799c76eed3f283b0
Build Timestamp: 2025-07-26T06:04:01.741775000Z (1753509841)
Build Profile: maxperf
```

### PR DESCRIPTION
**Pull request by mablr**
## Motivation

Resolve #11110 with a quick fix.

A deeper refactor of the `CastTxBuilder` for building raw unsigned tx may be relevant in the future.

## Solution

- Added validation for required parameters when `--from` is not provided, ensuring necessary transaction details are specified.
- Used `Address::ZERO` as a placeholder when there is no need to query provider
- Unit tests (may be a bit too much ;))

## PR Checklist

- [x] Added Tests
- [x] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/cast/src/cmd/mktx.rs [hunk 1]
```diff
@@ -106,7 +106,36 @@ impl MakeTxArgs {
...
+                    && tx.gas_limit.is_some()
+                    && gas_pricing_ok
+                    && (!tx.blob || tx.blob_gas_price.is_some());
+
+                if !has_required_params {
+                    let gas_msg =
+                        if tx.legacy { "--gas-price" } else { "--gas-price, --priority-gas-price" };
+                    let blob_msg = if tx.blob { ", --blob-gas-price" } else { "" };
+                    eyre::bail!(
+                        "Missing required parameters for raw unsigned transaction. When --from is not provided, you must specify: --chain, --nonce, --gas-limit, {}{}",
```
Comment (Neurone) [inline crates/cast/src/cmd/mktx.rs]: As a note, without a `from` parameter you are only forced to define a `nonce` manually, the rest of the parameters can still be derived from the provider if developers want to.

Comment (mablr) [reply crates/cast/src/cmd/mktx.rs]: oh yes that's right

Comment (mablr) [reply crates/cast/src/cmd/mktx.rs]: it is actually way simpler like this 4abbb30

File: crates/cast/src/cmd/mktx.rs [hunk 2]
```diff
@@ -106,7 +106,17 @@ impl MakeTxArgs {
 
         if raw_unsigned {
             // Build unsigned raw tx
-            let from = eth.wallet.from.ok_or_eyre("missing `--from` address")?;
+            // Check if nonce is provided when --from is not specified
+            // See: <https://github.com/foundry-rs/foundry/issues/11110>
+            if eth.wallet.from.is_none() && tx.nonce.is_none() {
```
Comment (mattsse) [inline crates/cast/src/cmd/mktx.rs:111]: ah yeah, that makes sense, the api is a bit weird like that because this basically reuses the regular signing function just with an optional value for returning unsigned

File: crates/cast/src/cmd/mktx.rs [hunk 3]
```diff
@@ -96,7 +96,7 @@ impl MakeTxArgs {
 
         let provider = get_provider(&config)?;
 
-        let tx_builder = CastTxBuilder::new(&provider, tx, &config)
+        let tx_builder = CastTxBuilder::new(&provider, tx.clone(), &config)
```
Comment (mattsse) [inline crates/cast/src/cmd/mktx.rs:99]: we could copy the nonce first, but this would just introduce another variable and doesnt really matter for this command
