### PR TITLE
fix(`anvil`): reset from fork to another fork

### LINKED ISSUE #8684: bug(`anvil`): `anvil_reset` seems to not reset the addresses contract code
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

_No response_

### What command(s) is the bug in?

anvil -f "FORK_URL" --port PORT --fork-block-number BLOCK_NUMBER

### Operating System

Linux

### Describe the bug

Running `anvil_reset` doesn't seem to reset the addresses contract code.

For example say that I ran `anvil -f "FORK_URL" --port PORT --fork-block-number BLOCK_NUMBER` where the `FORK_URL` is some eth mainnet endpoint and then running

```sh
curl -X POST \
      -H "Content-Type: application/json" \
      --data '{"jsonrpc":"2.0","method":"eth_call","params": [{"to": "0x16Fc5058F25648194471939df75CF27A2fdC48BC", "data": "0x54fd4d50"}, "latest"],"id":69}' \
      "http://localhost:6969/"
```

This results is `{"jsonrpc":"2.0","id":69,"result":"0x"}`

This is expected since `0x16Fc5058F25648194471939df75CF27A2fdC48BC` is the portalAddress contract on Mainnet Sepolia.

However when running `anvil_reset` and then running the above `curl` command the result is the same `{"jsonrpc":"2.0","id":69,"result":"0x"}`

```sh
curl -X POST \
            -H "Content-Type: application/json" \
            --data '{"jsonrpc": "2.0", "id": 31337, "method": "anvil_reset", "params": [{"forking": {"jsonRpcUrl": "MAIN_NET_SEPOLIA_URL", "blockNumber":"6511079" }}]}' \
            "http://localhost:6969/"
```

This seems to be working as expected with **Hardhat** when using `hardhat_reset` where the result is instead
`{"jsonrpc":"2.0","id":69,"result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000006332e31302e300000000000000000000000000000000000000000000000000000"}` as it's the expected outcome when querying the contract on sepolia.

 The address `0x16Fc5058F25648194471939df75CF27A2fdC48BC` on mainnet doesn't contain contract code but then on Sepolia it does and I believe that this code is not being updated on the `reset` call.
 
 This can be check with 
 
 ```sh
 curl -X POST \
            -H "Content-Type: application/json" \
            --data '{"jsonrpc": "2.0", "id": 31337, "method": "eth_getCode", "params": ["0x16Fc5058F25648194471939df75CF27A2fdC48BC", "latest"]}' \
            "http://localhost:6969"/
 ```
 
 This results is `{"jsonrpc":"2.0","id":31337,"result":"0x"}`
 
 I believe it might be because the fork creates a [default storage](https://github.com/foundry-rs/foundry/blob/62def0d68897aae7c2172eabed8085f631625003/crates/anvil/src/eth/backend/fork.rs#L51) but not entirely sure.
 
 Not sure this is the intended behavior, but it would be great to have a similar behavior as `hardhat_reset`

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation
Fixes #8684 

Resetting from an existing fork to another fork would not update underlying `ForkedDatabase`, resulting in an invalid state for the new fork. 

## Solution

reset the underlying the `ForkedDatabase` using `node_config.setup_fork_db_and_config`

### CODE REVIEW

File: crates/anvil/src/eth/backend/mem/mod.rs [hunk 1]
```diff
@@ -426,45 +426,59 @@ impl Backend {
...
-
             // reset storage
             *self.blockchain.storage.write() = BlockchainStorage::forked(
                 fork.block_number(),
                 fork.block_hash(),
                 fork.total_difficulty(),
             );
             self.states.write().clear();
-            self.db.write().await.clear();
+            // self.db.write().await.clear();
```
Comment (mattsse) [inline crates/anvil/src/eth/backend/mem/mod.rs:481]: why do we no longer need this?

**Comment by grandizzy** [comment]
hey @yash-atreya, wonder if you got the chance to test it with arbitrum forks too, there's a special case with block L1/L2 Not sure if it needs to be addressed here too but think it worth flagging https://github.com/foundry-rs/foundry/blob/d1271376d36e4cb24015bc6cde272468158e7c8d/crates/anvil/src/eth/backend/mem/mod.rs#L1734-L1746

File: crates/anvil/src/eth/backend/mem/mod.rs (hunk 1 above)
Comment (yash-atreya) [reply crates/anvil/src/eth/backend/mem/mod.rs:481]: Correct me if I'm wrong but we no longer need this because when we reset to a new forked state from a non-fork/old-fork state, we use `self.db`(`Backend.db`) as an intermediate step to set the `database` in `ClientFork`, [here](https://github.com/foundry-rs/foundry/blob/e613c1ab79f297ff46607fecf3066a0c958fc44c/crates/anvil/src/eth/backend/mem/mod.rs#L403-L405) and [here](https://github.com/foundry-rs/foundry/blob/e613c1ab79f297ff46607fecf3066a0c958fc44c/crates/anvil/src/eth/backend/mem/mod.rs#L438). 

So even when we clear - `self.db.write().await.clear();`, RPC calls work because they refer to the database in the fork + `foundry_fork_db::SharedBackend`. 

Ideally we should maintain this db in the `Backend` until we support resetting from forked state to non-forked (genesis) state.

**Review by mattsse — APPROVED** [review]
