### PR TITLE
fix(invariant): weight invariant selectors by number of selectors

### LINKED ISSUE #2986: feat: weight invariant selectors by number of selectors, not number of contracts.
### Component

Forge

### Describe the feature you would like

Let's say right now my invariant test is setup with two contracts:
- Contract A has 1 function selector, `fn0`.
- Contract B has 20 function selectors, `fn1` through `fn20`.

As I understand it, right now the process is:
1. First Contract A or Contract B will be chosen randomly
2. Then we look at the available selectors for each and randomly choose one.

This means `fn0` will be chosen ~50% of the time, and `fn1` through `fn20` are each only chosen 50 / 20 = 2.5% of the time. Ideally, each of the 21 functions would be chosen 100 / 21 = ~4.76% of the time

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation

Closes #2986 

In addition to [issue explanation](https://github.com/foundry-rs/foundry/issues/2986#issue-1353388549) we're using `proptest::sample::Selector` strategy which according to docs `Initially, the selection is roughly uniform, with a very slight bias towards items earlier in the iterator.`

Note: test is a little bit flaky in CI (locally it gives the same results for same seed constantly) might consider to ignore if failures start to pop up

Test with 3 handlers / 10 selectors (per handler: 1 selector, 5 selectors and 4 selectors), 1 run and depth of 500, result of hits / selector:
| | s1 | s2 | s3 | s4 | s5 | s6 | s7 | s8 | s9 | s10 |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| master | 167 | 37 | 28 | 31 | 30 | 32 | 39 | 35 | 41 | 60 |
| PR | 52 | 51 | 60 | 61 | 45 | 40 | 45 | 38 | 58 | 50 |

## Solution

- Consolidate `FuzzRunIdentifiedContracts` logic
  - move logic to update collect / clear invariant run contracts
  - add function to flatten contracts function in order to be used by strategy, return vector of (targeted address, function)
- use `proptest::sample::Index` strategy to randomly pick a (targeted address, function) pair
- test

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
pending @DaniPopes

File: crates/evm/fuzz/src/strategies/invariants.rs [hunk 1]
```diff
@@ -64,27 +68,17 @@ pub fn invariant_strat(
...
-            let fuzz_state = fuzz_state.clone();
-            let fuzz_fixtures = fuzz_fixtures.clone();
-            func.prop_flat_map(move |func| {
-                let sender = select_random_sender(&fuzz_state, senders.clone(), dictionary_weight);
-                let contract =
-                    fuzz_contract_with_calldata(&fuzz_state, &fuzz_fixtures, contract, func);
-                (sender, contract)
-            })
+    any::<prop::sample::Index>()
+        .prop_map(move |index| index.get(&contracts.fuzzed_functions()).clone())
```
Comment (DaniPopes) [inline crates/evm/fuzz/src/strategies/invariants.rs:72]: move `contracts.fuzzed_functions()` outside and merge the two prop* calls

**Review by DaniPopes — APPROVED** [review]
makes sense

File: crates/evm/fuzz/src/strategies/invariants.rs (hunk 1 above)
Comment (grandizzy) [reply crates/evm/fuzz/src/strategies/invariants.rs:72]: > move `contracts.fuzzed_functions()` outside and merge the two prop* calls

makes sense, though I think contracts.fuzzed_functions() should remain inside so new collected contracts / functions to be included?

**Review by klkvr — APPROVED** [review]
