### PR TITLE
fix(anvil): clean up `eth_estimateGas`

### LINKED ISSUE #7490: anvil: EVM error MemoryLimitOOG
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f9da73d 2024-03-23T00:16:29.636127000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

I opened #7478 that I hoped would fix this issue for me, but even when running a locally built anvil version with a much higher memory limit (128 mb -> 2 or 4gb) I'm still getting `EVM error MemoryLimitOOG` so I feel like this a bug more internal to the evm or its setup.

For reproduction:

1. Run anvil with:
`anvil --host 0.0.0.0 --fork-url=$ETHEREUM_RPC_URL --chain-id=1`
1. Download the requests to anvil: [Request_Body_03-25-2024-10-55-20.folder.zip](https://github.com/foundry-rs/foundry/files/14747860/Request_Body_03-25-2024-10-55-20.folder.zip)
2. Unzip the folder and cd into it with a terminal. Run: 
    ```
    while IFS= read -r file; do
        curl -X POST -H "Content-Type: application/json" -d @"$file" http://localhost:8545
    done < <(ls | sort -V)
    ```
3. Observe that the last lines returned are:
    ```
    {"jsonrpc":"2.0","id":51,"error":{"code":-32603,"message":"EVM error MemoryLimitOOG"}} 
    {"jsonrpc":"2.0","id":975548868,"result":null}
    ```

To summarize what the requests are doing, they are from our integration test suite that sets up an address with ETH and WETH, mints some items and grants approvals, then uses [SeaportRouter](https://etherscan.io/address/0x9069f84Ee64BE4EB008700EE004200006ac38e00) to fulfill. This problem is not inherent to SeaportRouter since we are running into the same `MemoryLimitOOG` testing other Seaport contracts.

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

Closes #7490 and changes code to avoid duplication of error handling logic between initial estimation vs binary search steps.

## Solution

Adds `GasEstimationCallResult` which takes care of matching errors occured during call and fully covers all potential `InstructionResult`s to distinguish between out of gas errors, reverts and unexpected failures.

### CODE REVIEW

File: crates/anvil/src/eth/api.rs [hunk 1]
```diff
@@ -2214,10 +2214,10 @@ impl EthApi {
         // configured gas limit
         let mut highest_gas_limit = request.gas.unwrap_or(block_env.gas_limit);
 
-        // check with the funds of the sender
-        if let Some(from) = request.from {
-            let gas_price = fees.gas_price.unwrap_or_default();
-            if gas_price > U256::ZERO {
+        let gas_price = fees.gas_price.unwrap_or_default();
+        // If we have non-zero gas price, cap gas limit by sender balance
+        if gas_price > U256::ZERO {
```
Comment (mattsse) [inline crates/anvil/src/eth/api.rs:2219]:
```suggestion
        if !gas_price.is_zero() {
```

File: crates/anvil/src/eth/api.rs [hunk 2]
```diff
@@ -2698,3 +2594,57 @@ fn determine_base_gas_by_kind(request: &TransactionRequest) -> U256 {
...
+/// Keeps result of a call to revm EVM used for gas estimation
+enum GasEstimationCallResult {
+    Success(u64),
+    OutOfGas,
+    Revert(Option<Bytes>),
+    EvmError(InstructionResult),
+}
+
+/// Converts the result of a call to revm EVM into a [GasEstimationCallRes].
+impl TryFrom<Result<(InstructionResult, Option<Output>, u64, State)>> for GasEstimationCallResult {
```
Comment (mattsse) [inline crates/anvil/src/eth/api.rs:2607]: we can keep this,
I think we can clean this up with a helper type after the larger alloy pr is through

File: crates/anvil/src/eth/api.rs [hunk 3]
```diff
@@ -2230,84 +2230,43 @@ impl EthApi {
                 let allowance = available_funds.checked_div(gas_price).unwrap_or_default();
                 if highest_gas_limit > allowance {
                     trace!(target: "node", "eth_estimateGas capped by limited user funds");
-                    highest_gas_limit = allowance;
+                    highest_gas_limit = std::cmp::min(highest_gas_limit, allowance);
```
Comment (mattsse) [inline crates/anvil/src/eth/api.rs:2233]: this min is redundant because allowance is smaller here,
we could replace the entire if with this and remove the trace, not that useful

File: crates/anvil/src/eth/api.rs [hunk 4]
```diff
@@ -2321,52 +2280,25 @@ impl EthApi {
...
-                        highest_gas_limit = mid_gas_limit;
-                    }
-                    // If the transaction failed due to lack of gas, we can set a floor for the
-                    // lowest gas limit at the current midpoint, as spending any
-                    // less gas would make no sense (as the TX would still revert due to lack of
-                    // gas).
-                    InstructionResult::Revert |
-                    InstructionResult::OutOfGas |
-                    InstructionResult::OutOfFunds |
-                    // we're also checking for InvalidFEOpcode here because this can be used to trigger an error <https://github.com/foundry-rs/foundry/issues/6138> common usage in openzeppelin <https://github.com/OpenZeppelin/openzeppelin-contracts/blob/94697be8a3f0dfcd95dfb13ffbd39b5973f5c65d/contracts/metatx/ERC2771Forwarder.sol#L360-L367>
```
Comment (mattsse) [inline crates/anvil/src/eth/api.rs:2353]: can we keep this in the tryfrom impl

File: crates/anvil/src/eth/api.rs [hunk 5]
```diff
@@ -2230,84 +2230,43 @@ impl EthApi {
...
-                        fees,
-                        gas_limit,
-                    ))
-                } else {
-                    // the transaction did fail due to lack of gas from the user
-                    Err(InvalidTransactionError::Revert(Some(convert_transact_out(&out).0.into()))
-                        .into())
-                };
+            GasEstimationCallResult::Revert(output) => {
+                Err(InvalidTransactionError::Revert(output).into())
```
Comment (mattsse) [inline crates/anvil/src/eth/api.rs:2251]: I think we want to keep mapping the output here: `convert_transact_out`?

**Review by mattsse — CHANGES_REQUESTED** [review]
this is great!

only have a few suggestions

File: crates/anvil/src/eth/api.rs (hunk 5 above)
Comment (klkvr) [reply crates/anvil/src/eth/api.rs:2251]: We handle conversion to bytes in `TryFrom` impl and it's basically the only thing `convert_transact_out` is doing

File: crates/anvil/src/eth/api.rs (hunk 4 above)
Comment (klkvr) [reply crates/anvil/src/eth/api.rs:2353]: With this PR overall logic changes and now any EVM error is ignored just as `InvalidFEOpcode`

Earlier we would throw a error on any revm error if it's not `Revert`, `OutOfGas` or `InvalidFEOpcode`, so the comment made sense, but I think now [this](https://github.com/foundry-rs/foundry/pull/7515/files#diff-a76a82dc700c0415fcd07ec10cde2ad56234e41af0ea3c07f8d1a8383b8b0913R2297-R2298) comment is enough to explain what's going on

Comment (mattsse) [reply crates/anvil/src/eth/api.rs:2353]: I see, then the comment is no longer useful, gotcha

**Review by mattsse — APPROVED** [review]
lgtm
