### PR TITLE
fix(`cheatcodes`): disallow using `vm.prank` after `vm.startPrank`

### LINKED ISSUE #5515: bug(forge): `tx.origin` set using `startPrank` is not reset to `DefaultSender` after calling a `prank`-ed call
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (25d3ce7 2023-08-01T00:20:16.462585000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

When the following test

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, Vm} from "forge-std/Test.sol";

contract ContractTest is Test {
    function test() public {
        address player = makeAddr("player");
        SenderLogger senderLogger = new SenderLogger();
        Contract c = new Contract();

        senderLogger.log(); // Log(ContractTest, DefaultSender)
        vm.startPrank(player, player);
        senderLogger.log(); // Log(player, player)
        c.f(); // vm.prank(player, player)
        senderLogger.log(); // Log(ContractTest, player) <- ContractTest should be player
        senderLogger.log(); // Log(ContractTest, player) <- player should be DefaultSender
        vm.stopPrank(); // FAIL. Reason: No prank in progress to stop
    }
}

contract Contract {
    Vm public constant vm = Vm(address(bytes20(uint160(uint256(keccak256("hevm cheat code"))))));

    function f() public {
        vm.prank(msg.sender, msg.sender);
    }
}

contract SenderLogger {
    event Log(address, address);

    function log() public {
        emit Log(msg.sender, tx.origin);
    }
}

```

is run, the following output is printed.

```sh
$ forge test -vvvvv
[⠒] Compiling...
[⠃] Compiling 1 files with 0.8.21
[⠊] Solc 0.8.21 finished in 1.75s
Compiler run successful!

Running 1 test for test/Counter.t.sol:ContractTest
[FAIL. Reason: No prank in progress to stop] test() (gas: 166169)
Traces:
  [166169] ContractTest::test() 
    ├─ [0] VM::addr(<pk>) [staticcall]
    │   └─ ← player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C]
    ├─ [0] VM::label(player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C], player) 
    │   └─ ← ()
    ├─ [33087] → new SenderLogger@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   └─ ← 165 bytes of code
    ├─ [55705] → new Contract@0x2e234DAe75C793f67A35089C9d99245E1C58470b
    │   └─ ← 278 bytes of code
    ├─ [1451] SenderLogger::log() 
    │   ├─ emit Log(: ContractTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], : DefaultSender: [0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38])
    │   └─ ← ()
    ├─ [0] VM::startPrank(player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C], player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C]) 
    │   └─ ← ()
    ├─ [1451] SenderLogger::log() 
    │   ├─ emit Log(: player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C], : player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C])
    │   └─ ← ()
    ├─ [493] Contract::f() 
    │   ├─ [0] VM::prank(player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C], player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C]) 
    │   │   └─ ← ()
    │   └─ ← ()
    ├─ [1451] SenderLogger::log() 
    │   ├─ emit Log(: ContractTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], : player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C])
    │   └─ ← ()
    ├─ [1451] SenderLogger::log() 
    │   ├─ emit Log(: ContractTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], : player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C])
    │   └─ ← ()
    ├─ [0] VM::stopPrank() 
    │   └─ ← "No prank in progress to stop"
    └─ ← "No prank in progress to stop"

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 1.13ms
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/Counter.t.sol:ContractTest
[FAIL. Reason: No prank in progress to stop] test() (gas: 166169)

Encountered a total of 1 failing tests, 0 tests succeeded
```

As can see from the wrong log after calling `Contract::f()`

```
    ├─ [1451] SenderLogger::log() 
    │   ├─ emit Log(: ContractTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], : player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C])
    │   └─ ← ()
    ├─ [1451] SenderLogger::log() 
    │   ├─ emit Log(: ContractTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], : player: [0x44E97aF4418b7a17AABD8090bEA0A471a366305C])
    │   └─ ← ()
```

I think the trigger is to call `vm.prank` in another contract.
In the above code, the contract is `Contract`.

Full source: https://github.com/minaminao/foundry-bug-reports/tree/main/2023-08-broken-prank

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

Closes #5515 . This problem (`tx.origin` not being updated correctly after doing `vm.prank` after a `vm.startPrank`) is introduced in part due to https://github.com/foundry-rs/foundry/pull/4884 — we now have certain rules to override pranks that weren't explicit enough in the code. You should probably not be able to call `vm.prank` after a `vm.startPrank`, as `vm.startPrank` is "multi-use" and must be stopped, while `vm.prank` is "single use", and one should not overlap the other, as you can use `vm.startPrank` again after having used the first startPrank. This is made a little confusing as we don't have a `changePrank` cheatcode, but rather re-use `vm.startPrank` for this.

We could probably make a case for allowing this, but this feels like a hard-to-explain possible footgun and I'd rather disallow it entirely.

## Solution

Disallow calling `vm.prank` after a `vm.startPrank`.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
this sounds reasonable to me,

pending @mds1

File: evm/src/executor/inspector/cheatcodes/env.rs [hunk 1]
```diff
@@ -161,8 +161,11 @@ fn prank(
 ) -> Result {
     let prank = Prank::new(prank_caller, prank_origin, new_caller, new_origin, depth, single_call);
 
-    if let Some(Prank { used, .. }) = state.prank {
+    if let Some(Prank { used, single_call, .. }) = state.prank {
         ensure!(used, "You cannot overwrite `prank` until it is applied at least once");
+        // This case can only fail if the user calls `vm.startPrank` and then `vm.prank` later on.
+        // This should not be possible.
```
Comment (mds1) [inline evm/src/executor/inspector/cheatcodes/env.rs:167]: nit
```suggestion
        // This should not be possible without first calling `stopPrank`
```

File: evm/src/executor/inspector/cheatcodes/env.rs [hunk 2]
```diff
@@ -161,8 +161,11 @@ fn prank(
...
+        ensure!(single_call == single_call, "You cannot override an ongoing prank with a single vm.prank. Use vm.startPrank to override the current prank.");
```
Comment (mds1) [inline evm/src/executor/inspector/cheatcodes/env.rs:168]: is this correct? `single_call == single_call` seems like no-op that will always evaluate to true?

Comment (Evalir) [reply evm/src/executor/inspector/cheatcodes/env.rs:168]: yep seems like a no-op haha, but actually, this will evaluate to false if you use `vm.startPrank`, and then use `vm.prank` (which is what surfaced this bug/unintended feature)

Comment (mattsse) [reply evm/src/executor/inspector/cheatcodes/env.rs:168]: oh right, I misread that, this indeed looks like a noop

Comment (Evalir) [reply evm/src/executor/inspector/cheatcodes/env.rs:168]: yep it's a no-op actually—it's being shadowed by the other `single_call`

Comment (Evalir) [reply evm/src/executor/inspector/cheatcodes/env.rs]: fixed in https://github.com/foundry-rs/foundry/pull/5520/commits/1c5375e85e898c6ba542bb5868b846a46b147e41

**Comment by Evalir** [comment]
alright, should be good now @mds1 !

**Review by mds1 — APPROVED** [review]
LGTM!
