### PR TITLE
fix: estimate gas if missing for eth_sendTransaction

### LINKED ISSUE #6931: regression(anvil): can't process more than one tx on the same block
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.2.0 (caef136 2024-01-29T00:23:41.917496000Z)

### What command(s) is the bug in?

anvil

### Operating System

None

### Describe the bug

Upgrading [Viem](https://github.com/wevm/viem) to use the latest Anvil, and seem to be running into a regression where more than one transaction cannot be mined on the same block. This seemed to work before. 

#### 1. Start up Anvil

Start an Anvil instance w/ fork url and automining disabled.

```bash
anvil --fork-url https://cloudflare-eth.com --no-mining
```

#### 2. Send some transactions

```bash
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1,"method":"eth_sendTransaction","params":[{"from":"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"}]}' http://127.0.0.1:8545
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":2,"method":"eth_sendTransaction","params":[{"from":"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"}]}' http://127.0.0.1:8545
```

#### 3. Mine block

```bash
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":3,"method":"anvil_mine","params":["0x1","0x0"]}' http://127.0.0.1:8545
```

#### 4. Get transaction receipts

```bash
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":6,"method":"eth_getTransactionReceipt","params":["TX_HASH_1"]}' http://127.0.0.1:8545
# ✅ first transaction is successfully mined, and we get a receipt
# > {"jsonrpc":"2.0","id":6,"result":{ ... }}

curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":6,"method":"eth_getTransactionReceipt","params":["TX_HASH_2"]}' http://127.0.0.1:8545
# ❌ second transaction still in txpool. get `null` as the receipt. expected an obj like above.
# > {"jsonrpc":"2.0","id":6,"result":null}
```

### PR DESCRIPTION
**Pull request by mattsse**
Closes #6931

if gas is missing estimate the appropriate value

see also 

https://github.com/ethereum/go-ethereum/blob/bc0b87ca196f92e5af49bd33cc190ef0ec32b197/internal/ethapi/transaction_args.go#L111-L132

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]

File: crates/anvil/src/eth/api.rs [hunk 1]
```diff
@@ -885,7 +900,9 @@ impl EthApi {
             trace!(target : "node", ?from, "eth_sendTransaction: impersonating");
             PendingTransaction::with_impersonated(transaction, from)
         } else {
+            dbg!(&request);
             let transaction = self.sign_request(&from, request)?;
+            dbg!(&transaction);
```
Comment (DaniPopes) [inline crates/anvil/src/eth/api.rs:905]: use tracing or remove

**Review by DaniPopes — CHANGES_REQUESTED** [review]
