### PR TITLE
fix(forge): fix nonce for tx with 7702 auth

### LINKED ISSUE #10461: Forge script run has authorization and transaction nonce reversed
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.1.0-nightly 
Commit SHA: a34f4c989b94f572497631ff5c85909d674c23a6

### What version of Foundryup are you on?

foundryup: 1.1.0

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

This bug may be upstream in revm, but thought I would open here first, though I am happy to re-open there.

I've produced a MRE: https://github.com/SanLeo461/mre-7702-nonce-bug
To run: `forge script script/Counter.s.sol -vvvvv --rpc-url <RPC_URL>`

Essentially, when running a script that signs and attaches a 7702 authorization, foundry is meant to set the nonce of the authorization at (`currentNonce + 1`), or higher depending on if there are more authorizations behind in the current list.

Instead, the authorization gets set at `currentNonce`, and the transaction gets set at `currentNonce + 1`
This can manifest in bugs such as foundry believing the provider nonce is behind the current intended nonce.

Foundry when it checks its internal simulations gets what should be the correct simulation:
```
Traces:
  [121] CounterScript::setUp()
    └─ ← [Stop]

  [169287] CounterScript::run()
    ├─ [0] VM::startBroadcast(<pk>)
    │   └─ ← [Return]
    ├─ [107551] → new Counter@0x00Df3E91238EB91192D60e01E73D661Be87d52A9
    │   └─ ← [Return] 537 bytes of code
    ├─ [0] VM::signAndAttachDelegation(0x00Df3E91238EB91192D60e01E73D661Be87d52A9, "<pk>")
    │   └─ ← [Return] (1, 0xbc9c8cc66abb2c8700cc262c65993b5bae43a8627c2365c5f61a2ab5d14510e3, 0x08484ef8a3bfce668299ee5443bc3e37a38e40013a3cbb60e90820be4a63e764, 1, 0x00Df3E91238EB91192D60e01E73D661Be87d52A9)
    ├─ [23705] 0x8D726E3092E7F92234f8463e8Bf3ddFde7d89341::increment()
    │   ├─ emit Incremented(newValue: 1)
    │   └─ ← [Stop]
    ├─ [0] VM::stopBroadcast()
    │   └─ ← [Return]
    └─ ← [Stop]


Script ran successfully.
```

But when simulating on chain, since any incorrect authorization nonces do not halt exceptionally but are instead skipped, it simply behaves as if there is no delegation at the address.

```
## Setting up 1 EVM.
==========================
Simulated On-chain Traces:

  [107551] → new Counter@0x00Df3E91238EB91192D60e01E73D661Be87d52A9
    └─ ← [Return] 537 bytes of code

  [0] 0x8D726E3092E7F92234f8463e8Bf3ddFde7d89341::increment()
    └─ ← [Stop]

Warning: Script contains a transaction to 0x8D726E3092E7F92234f8463e8Bf3ddFde7d89341 which does not contain any code.
```

You can see the transaction nonces being incorrect @ https://github.com/SanLeo461/mre-7702-nonce-bug/blob/master/broadcast/Counter.s.sol/1/dry-run/run-latest.json
```json
    {
      "hash": null,
      "transactionType": "CALL",
      "contractName": null,
      "contractAddress": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
      "function": "increment()",
      "arguments": [],
      "transaction": {
        "from": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
        "to": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
        "gas": "0xf889",
        "value": "0x0",
        "input": "0xd09de08a",
        "nonce": "0x2",
        "chainId": "0x1",
        "authorizationList": [
          {
            "chainId": "0x1",
            "address": "0x00df3e91238eb91192d60e01e73d661be87d52a9",
            "nonce": "0x1",
            "yParity": "0x1",
            "r": "0xbc9c8cc66abb2c8700cc262c65993b5bae43a8627c2365c5f61a2ab5d14510e3",
            "s": "0x8484ef8a3bfce668299ee5443bc3e37a38e40013a3cbb60e90820be4a63e764"
          }
        ]
      },
      "additionalContracts": [],
      "isFixedGasLimit": false
    }
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #10461 #10470 
- do not increment account nonce when attaching delegation
- increment nonce when custom nonce is not provided, reset authority nonce after attaching
- test added, failing with `After 5 attempts, provider nonce (3) is still behind expected nonce (4).` in master

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/cheatcodes/src/script.rs [hunk 1]
```diff
@@ -125,12 +126,19 @@ fn sign_delegation(
...
         return Err("invalid nonce".into());
     }
-    authority_acc.data.info.nonce += 1;
+
     let bytecode = Bytecode::new_eip7702(*auth.address());
     ccx.ecx.journaled_state.set_code(authority, bytecode);
+
+    // Reset authority nonce.
+    let authority_acc = ccx.ecx.journaled_state.load_account(authority, &mut ccx.ecx.db)?;
+    authority_acc.data.info.nonce -= 1;
```
[the remark this answers is not in the document]
Comment (grandizzy) [reply crates/cheatcodes/src/script.rs:141]: yeah, so when we sign the auth we artificially increment the nonce amd here is the part where we attach the sig generated with incremented nonce. Mind that the tx is not executed here, but on the next call which should use the current nonce, not the one incremented for the sig. We want to avoid setting higher nonce in auth list than tx itself as in https://github.com/foundry-rs/foundry/issues/10461#issue-3047870942
```json
    {
      "hash": null,
      "transactionType": "CALL",
      "contractName": null,
      "contractAddress": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
      "function": "increment()",
      "arguments": [],
      "transaction": {
        "from": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
        "to": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
        "gas": "0xf889",
        "value": "0x0",
        "input": "0xd09de08a",
        "nonce": "0x2",
        "chainId": "0x1",
        "authorizationList": [
          {
            "chainId": "0x1",
            "address": "0x00df3e91238eb91192d60e01e73d661be87d52a9",
            "nonce": "0x1",
            "yParity": "0x1",
            "r": "0xbc9c8cc66abb2c8700cc262c65993b5bae43a8627c2365c5f61a2ab5d14510e3",
            "s": "0x8484ef8a3bfce668299ee5443bc3e37a38e40013a3cbb60e90820be4a63e764"
          }
        ]
      },
      "additionalContracts": [],
      "isFixedGasLimit": false
    }
```

[the remark this answers is not in the document]
Comment (grandizzy) [reply crates/cheatcodes/src/script.rs:141]: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7702.md#behavior

**Review by zerosnacks — DISMISSED** [review]

File: crates/cheatcodes/src/script.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (grandizzy) [reply crates/cheatcodes/src/script.rs:141]: Just to make sure nothing missed @klkvr or @onbjerg could you pls validate the approach 🙏

File: crates/cheatcodes/src/inspector.rs [hunk 2]
```diff
@@ -1152,6 +1152,9 @@ where {
                         (Some(auth_list), None) => {
                             tx_req.authorization_list = Some(vec![auth_list]);
                             tx_req.sidecar = None;
+
+                            // Increment nonce to reflect the signed authorization.
+                            account.info.nonce += 1;
```
Comment (klkvr) [inline crates/cheatcodes/src/inspector.rs:1157]: I think we should only increment nonce if the delegation was actually applied. It is still possible to attach delefation with invalid nonce manually

this is kind of part of a reason why I'm feeling we should find a way to route this logic through revm code paths (e.g reuse validation/nonce increment logic here). we're basically re-implementing part of the EVM logic here in an incomplete way

File: crates/cheatcodes/src/script.rs [hunk 3]
```diff
@@ -98,7 +98,8 @@ fn sign_delegation(
     } else {
         let authority_acc =
             ccx.ecx.journaled_state.load_account(signer.address(), &mut ccx.ecx.db)?;
-        authority_acc.data.info.nonce
+        // If we don't have a nonce then use next auth account nonce.
+        authority_acc.data.info.nonce + 1
```
Comment (klkvr) [inline crates/cheatcodes/src/script.rs:102]: hmm, not sure we want to increment the nonce in the journal when signing delegations?

File: crates/cheatcodes/src/script.rs [hunk 4]
```diff
@@ -125,12 +126,19 @@ fn sign_delegation(
 fn write_delegation(ccx: &mut CheatsCtxt, auth: SignedAuthorization) -> Result<()> {
     let authority = auth.recover_authority().map_err(|e| format!("{e}"))?;
     let authority_acc = ccx.ecx.journaled_state.load_account(authority, &mut ccx.ecx.db)?;
+
+    // Create and set bytecode with incremented nonce.
+    authority_acc.data.info.nonce += 1;
```
Comment (klkvr) [inline crates/cheatcodes/src/script.rs:131]: don't think I follow why we need to do this here. why do we need to do anything besides the `set_code` call?

Comment (klkvr) [reply crates/cheatcodes/src/script.rs:131]: actually why are we even doing the `write_delegation` call before delegation tx was even sent? shouldn't it happen here instead? https://github.com/foundry-rs/foundry/blob/cc3a3f8ced82ff2df8317592b8c016bf8759d592/crates/cheatcodes/src/inspector.rs#L1152-L1155

Comment (grandizzy) [reply crates/cheatcodes/src/script.rs]: > don't think I follow why we need to do this here. why do we need to do anything besides the `set_code` call?

indeed, incrementing in cheatcode is not needed but only `set_code` changed in https://github.com/foundry-rs/foundry/pull/10464/commits/7988e9747a710aaef2496b9fbaf09a9764132c58

File: crates/cheatcodes/src/script.rs (hunk 3 above)
Comment (grandizzy) [reply crates/cheatcodes/src/script.rs:102]: here's my understanding and why's needed to be done before, so for a script like
```Solidity
        Vm.SignedDelegation memory signedDelegation = vm.signDelegation(address(counter), PRIVATE_KEY);
        vm.attachDelegation(signedDelegation);
        Counter(SENDER).increment();
```
or directly using sign and attach
```Solidity
        vm.signAndAttachDelegation(address(counter), PRIVATE_KEY);
        Counter(SENDER).increment();
```
steps are
- when sign & attach delegation call to cheatcode we create the delegation with current nonce. The issue is that since here we have access to nonce before actual tx we need to increment it in order to avoid tx nonce being lower than auth one (see in example below "nonce": "0x2" vs "nonce": "0x1")
```json
    {
      "hash": null,
      "transactionType": "CALL",
      "contractName": null,
      "contractAddress": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
      "function": "increment()",
      "arguments": [],
      "transaction": {
        "from": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
        "to": "0x8d726e3092e7f92234f8463e8bf3ddfde7d89341",
        "gas": "0xf889",
        "value": "0x0",
        "input": "0xd09de08a",
        "nonce": "0x2",
        "chainId": "0x1",
        "authorizationList": [
          {
            "chainId": "0x1",
            "address": "0x00df3e91238eb91192d60e01e73d661be87d52a9",
            "nonce": "0x1",
            "yParity": "0x1",
            "r": "0xbc9c8cc66abb2c8700cc262c65993b5bae43a8627c2365c5f61a2ab5d14510e3",
            "s": "0x8484ef8a3bfce668299ee5443bc3e37a38e40013a3cbb60e90820be4a63e764"
          }
        ]
      },
      "additionalContracts": [],
      "isFixedGasLimit": false
    }
```
- when we actually simulate / broadcast txes, we need to account the auth nonce, otherwise next tx (if one) will have same nonce as the one within auth

File: crates/cheatcodes/src/inspector.rs (hunk 2 above)
Comment (grandizzy) [reply crates/cheatcodes/src/inspector.rs:1157]: > It is still possible to attach delegation with invalid nonce manually
that would fail the verification in cheatcode that requires auth nonce to be equal with account nonce + 1

> this is kind of part of a reason why I'm feeling we should find a way to route this logic through revm code paths 
this is the part where we craft the `TransactionRequest`/`BroadcastableTransaction` so not sure how we could do that :thinking:

File: crates/cheatcodes/src/script.rs (hunk 4 above)
Comment (grandizzy) [reply crates/cheatcodes/src/script.rs]: > actually why are we even doing the `write_delegation` call before delegation tx was even sent? shouldn't it happen here instead?

pls see https://github.com/foundry-rs/foundry/pull/10464#discussion_r2081054577 above

File: crates/cheatcodes/src/script.rs (hunk 3 above)
Comment (klkvr) [reply crates/cheatcodes/src/script.rs:102]: why can't we sugn and save delegation with higher nonce without actually incrementing the sender nonce?

it just doesn't make sense to me that signing delegation reaults in increased nonce

**Comment by grandizzy** [comment]
@klkvr as discussed I performed additional testing and didn't hit any nonce out of sync issue with this fix for sign and attach 7702, would like to move forward with the approach and improve in follow-ups (move write delegation from cheatcode call to inspector itself) if that's fine. Thank you!

**Review by klkvr — APPROVED** [review]
lgtm!
