### PR TITLE
fix(forge): init errors

### LINKED ISSUE #4214: forge init circular dependency issue
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge init hello_foundry

### Operating System

Linux

### Describe the bug

There seems to be a circular dependency issue with `forge init hello_foundry` in an existing and empty git repo.

# Background

Most of my crypto work is anon, so I don't globally set my git credentials. I set them up per repo using scripts.

This is the reason why I'm running the above command in an empty folder that has already been initialised as a repo (an setup with correct user config). 

# Steps to replicate

> must make sure that git credentials are not set globally by running `git config --list | grep 'user.'`

1. Create a new folder 

2. Initialise that new folder as a git repo

3. Run `forge init hello_foundry` 

# Behaviour

Running the command ends in this error:

```
Installing forge-std in "/home/USER/foundry/hello_foundry/lib/forge-std" (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
Error: 
This command requires clean working and staging areas, including no untracked files. Modify .gitignore and/or add/commit first, or add the --no-commit option.

```

Quite a strange error as you can see: why would we get an unclean working area within an empty git repo?

After doing an ls in the repo it becomes clear what is happening.

```
hello_foundry

```

The folder for the project has been created and a downstream command has a clean repo requirement that is not satified.

But I'm also betting that the folder is required for upcoming steps, hence why I titled this - circular dependency.

# Workarounds

Trying to commit the newly created folder and then rerunning the `init` command does not work, resulting in: 

```
error: `forge init` cannot be run on a non-empty directory.

```

Running `forge init hello_foundry --force` also does not work, resulting in: 

```
Installing forge-std in "/home/USER/foundry/hello_foundry/lib/forge-std" (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
Error: 
fatal: pathspec '.gitmodules' did not match any files

```

# Outcome

Was not able to install the `hello-world` example because of the above issues

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Fixes #4214

If the folder is already initialized to a git repo (and using `--force`), we're creating all the necessary files, except for workflow, .gitignore and the initial commit (`init_git_repo` doesn't run), so when git status is checked later during forge-std installation, it fails with that message because the initialized files didnt get committed

## Solution

make `if !is_git` block only apply to `git init` itself
do not overwrite `.gitignore` and `.github/workflows`

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
this is great, tysm.
would appreciate a `forgetest!` similar to the ones in https://github.com/foundry-rs/foundry/blob/master/cli/tests/it/cmd.rs

**Comment by DaniPopes** [comment]
I feel like this is in the top 5 questions asked in the telegram chat, so tried to add even more information to the error message

File: cli/src/cmd/forge/install.rs [hunk 1]
```diff
@@ -305,7 +305,18 @@ fn commit_after_install(libs: &Path, target_dir: &str, tag: Option<&str>) -> eyr
...
+This command's target directory is, or is in an already initialized git repository,
+and it requires clean working and staging areas, including no untracked files.
+
+Check the current git repository's status with `git status`.
+Then, you can track files with `git add ...` and then commit them with `git commit`,
+ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.
+
+If none of the previous steps worked, please open an issue at:
+https://github.com/foundry-rs/foundry/issues/new/choose"
+        )
```
Comment (DaniPopes) [inline cli/src/cmd/forge/install.rs:319]: I feel like this is in the top 5 questions asked in the telegram chat, so tried to add even more information to the error message

File: cli/src/cmd/forge/install.rs [hunk 2]
```diff
@@ -306,8 +306,16 @@ fn commit_after_install(libs: &Path, target_dir: &str, tag: Option<&str>) -> eyr
...
+            "\
+This command's target directory is, or is in an already initialized git repository,
+and it requires clean working and staging areas, including no untracked files.
+
+Check the current git repository's status with `git status`.
+Then, you can track files with `git add ...` and then commit them with `git commit`,
+ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.
+
+If none of the previous steps worked, please open an issue at:
+https://github.com/foundry-rs/foundry/issues/new/choose"
```
Comment (mattsse) [inline cli/src/cmd/forge/install.rs:318]: while this explains it perfectly, I think this is perhaps a bit too verbose, but not sure.

maybe we add this separately? would like to hear some additional feedback on this first.

happy to merge the rest of this PR

Comment (DaniPopes) [reply cli/src/cmd/forge/install.rs:318]: I'll move it to a second PR

**Review by mattsse — APPROVED** [review]
