### PR TITLE
fix: Respect `--override-*` flags on `cast call` with `--trace` flag

### LINKED ISSUE #10720: bug(`cast call`): `--override-*` flags not respected with `--trace`
### Component

Cast

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.2.2-stable Commit SHA: 73ac79f0679f93c78353d7ea4303e3f8bc4ab7cd Build Timestamp: 2025-06-01T14:56:44.649397717Z (1748789804) Build Profile: maxperf

### What version of Foundryup are you on?

foundryup: 1.0.1

### What command(s) is the bug in?

cast call

### Operating System

Linux

### Describe the bug

`cast call` `--override` flags added in #10255 do not apply when used with `--trace`.

Works (no `--trace`):
```
cast call -r https://mainnet.base.org --override-balance 0xFFFFFFFFFFAAAAAAAAAAFFFFFFFFFFAAAAAAAAAA:500 --from 0xFFFFFFFFFFAAAAAAAAAAFFFFFFFFFFAAAAAAAAAA --value 500 0x4200000000000000000000000000000000000006 "deposit()"
```

EVM error (with `--trace`):
```sh
cast call -r https://mainnet.base.org --override-balance 0xFFFFFFFFFFAAAAAAAAAAFFFFFFFFFFAAAAAAAAAA:500 --from 0xFFFFFFFFFFAAAAAAAAAAFFFFFFFFFFAAAAAAAAAA --value 500 0x4200000000000000000000000000000000000006 "deposit()" --trace
```

### PR DESCRIPTION
**Pull request by Yen**
Fixes #10720

### CODE REVIEW

**Comment by Yen** [comment]
I have looked at the existing tests for `--override` and they use the `stderr_eq` check to ensure the output is expected. If I add additional tests in the case of `--trace` this output is more complex and I assume it will change more often. Is it ok for the tests to fail when the format of the trace changes in the future, would the expectation be that the tests are updated to reflect this?

**Comment by Yen** [comment]
Ah, actually I did not see the `SNAPSHOTS=overwrite` functionality which I assume is meant to assist in this case. I will add equivalent tests to the existing `--override` tests with the `--trace` flag enabled.

**Comment by Yen** [comment]
I have added tests and rebased onto the latest master. Thanks

**Comment by grandizzy** [comment]
@Yen `cast call` accepts now  block.time and block.number overrides (as of https://github.com/foundry-rs/foundry/pull/10727) mind to add those to work with --trace as well? thank you

**Comment by Yen** [comment]
I have rebased and added the block overrides to work with `--trace`. The changes were minor. 👍

**Comment by Yen** [comment]
Tests in CI are failing after the rebase but not sure what the reason is as these tests don't use `--trace`. Can a maintainer confirm these are caused by the changes here as I can't understand what change causes them.

**Comment by grandizzy** [comment]
yeah, not related, looks like a contract we use in a test was upgraded and returns different now

File: crates/evm/evm/src/executors/trace.rs [hunk 1]
```diff
@@ -23,18 +25,48 @@ impl TracingExecutor {
...
+        // tracing will be enabled only for the targeted transaction
+        let mut executor = ExecutorBuilder::new()
+            .inspectors(|stack| {
+                stack.trace_mode(trace_mode).odyssey(odyssey).create2_deployer(create2_deployer)
+            })
+            .spec_id(evm_spec_id(version.unwrap_or_default(), odyssey))
+            .build(env, db);
+
+        // Apply the state overrides.
+        if let Some(state_overrides) = state_overrides {
```
Comment (mattsse) [inline crates/evm/evm/src/executors/trace.rs:41]: making a note here that after the next alloy-evm bump we have utils for this

**Review by mattsse — APPROVED** [review]
