### PR TITLE
fix(forge): show lcov hits for do while statements

### LINKED ISSUE #10422: No coverage report inside do...while loops
> The bug was re-introduced by https://github.com/foundry-rs/foundry/commit/5b8416363c7c1aab6d3cda0da6e7c65594ad8a12 (regression). @onbjerg or @grandizzy can you re-open the issue? 

 _Originally posted by @beeb in [#6968](https://github.com/foundry-rs/foundry/issues/6968#issuecomment-2844214791)_

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #10422 
- https://github.com/foundry-rs/foundry/commit/5b8416363c7c1aab6d3cda0da6e7c65594ad8a12 fixed an issue where lcov reports were doubled due to adding them both as lines and as statements, by not accounting statement hits
- turns out this breaks do / while report for block statements
- added back the DA line from statement if it wasn't already generated as line statement - this prevents doubling it but also properly generate lcov report if only statements recorded
- added test to prevent regression
image

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/forge/src/coverage.rs [hunk 1]
```diff
@@ -140,8 +142,12 @@ impl CoverageReporter for LcovReporter {
                             writeln!(out, "FNDA:{hits},{name}")?;
                         }
                     }
-                    CoverageItemKind::Line => {
-                        writeln!(out, "DA:{line},{hits}")?;
+                    // Add lines / statement hits only once.
+                    CoverageItemKind::Line | CoverageItemKind::Statement => {
+                        if !recorded_lines.contains(&line) {
```
Comment (DaniPopes) [inline crates/forge/src/coverage.rs:147]: if insert() directly

**Review by DaniPopes — CHANGES_REQUESTED** [review]

File: crates/forge/src/coverage.rs (hunk 1 above)
Comment (grandizzy) [reply crates/forge/src/coverage.rs]: yep, simplified in https://github.com/foundry-rs/foundry/pull/10423/commits/7c58c573813af991b3001c832d3250481966dd71

**Review by DaniPopes — APPROVED** [review]
