### PR TITLE
fix(`chisel`): Override set solc and Install post-merge solc version if needed

### LINKED ISSUE #4888: chisel 0.1.1 is broken: can't run any command
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3092735 2023-05-06T00:10:49.805815000Z)

### What command(s) is the bug in?

chisel

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
chisel
Welcome to Chisel! Type `!help` to show available commands.
➜ 1+1
Compiler errors:
Error: Invalid EVM version requested.
```

I didn't find any exmple on how to specify custom EVM version or what that is. tried `0.8.0` didn't work.

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

Closes #4888 .

Seems people still are having issues with the issue linked above. It's caused by a mismatch between the used solc and evm version required.

## Solution

Introduces a check to ensure that the user is using/installing an solc version that is compatible the merge onwards if the evm version is higher or equal to Paris. This overrides the solc option set by the user if it's not recent enough, but it will *not* override a local solc path.

cc @clabby looping you in! this should hopefully fix this—lmk if i missed any other solc checks elsewhere

### CODE REVIEW

File: chisel/src/session_source.rs [hunk 1]
```diff
@@ -100,6 +100,22 @@ impl SessionSourceConfig {
...
+                // solc that is supported by the evm version.
+                // 1. Do we need solc 0.8.18 or higher?
+                let needs_post_merge_solc = self.foundry_config.evm_version >= EvmVersion::Paris;
+                // 2. Check if the version provided is less than 0.8.18 and override it,
+                // or leave it as-is if we don't need a post merge solc version or the version we
+                // have is good enough.
+                if let v = needs_solc_18 && version < Version::new(0, 8, 18) {
+                    // If we do need a new version, install 0.8.19 (Paris)
+                    // NOTE: This needs to be bumped to 0.8.20 once we upgrade all tooling to Shanghai.
+                   Version::new(0, 8, 19)
```
Comment (Evalir) [inline chisel/src/session_source.rs:114]: Could also probably also add a shell warning here saying that the provide solc version has been overriden

File: chisel/src/session_source.rs [hunk 2]
```diff
@@ -100,8 +100,25 @@ impl SessionSourceConfig {
...
+                // 1. Do we need solc 0.8.18 or higher?
+                let needs_post_merge_solc = self.foundry_config.evm_version >= EvmVersion::Paris;
+                // 2. Check if the version provided is less than 0.8.18 and override it,
+                // or leave it as-is if we don't need a post merge solc version or the version we
+                // have is good enough.
+                let v = if needs_post_merge_solc && version < Version::new(0, 8, 18) {
+                    // If we do need a new version, install 0.8.19 (Paris)
+                    // NOTE: This needs to be bumped to 0.8.20 once we upgrade all tooling to
+                    // Shanghai.
+                    Version::new(0, 8, 19).to_string()
```
Comment (mattsse) [inline chisel/src/session_source.rs:115]: does this mean, once we have 0.8.20?

**Review by mattsse — APPROVED** [review]

File: chisel/src/session_source.rs (hunk 2 above)
Comment (Evalir) [reply chisel/src/session_source.rs:115]: yup, once svm and ethers all get bumped

File: chisel/src/session_source.rs (hunk 1 above)
Comment (mattsse) [reply chisel/src/session_source.rs]: yeh, user input should take precedence, would even prefer an error if conflicting user input is provided.

Comment (clabby) [reply chisel/src/session_source.rs]: ^ agree

**Review by clabby — APPROVED** [review]

File: chisel/src/session_source.rs (hunk 1 above)
Comment (Evalir) [reply chisel/src/session_source.rs]: aight, changed this to instead bail if the version provided is not recent enough: https://github.com/foundry-rs/foundry/pull/4949/commits/0eda884a042befca1aa5fd484ddf36cc2cce2d4f

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by Evalir** [comment]
hmm i think it's trying to install a pre 0.8.18 solidity version in tests and it's failing because of that—how can we force it to install something newer?

**Comment by mattsse** [comment]
this doesn't seem to happen on master, so looks like this is introduced here

looks like it fails to create a chisel session now, likely because of failed installation, which has to do with changed version

**Comment by Evalir** [comment]
Aight, so the cause of this is that solc 0.8.13 gets installed due to some old tests requiring it. This then (correctly) triggers the error we've set as the solc version is incompatible with the EVM version set. The fix is just force 0.8.19 to be installed on each chisel test.

Now, this is actually a symptom of a larger issue—we seem to be accepting incompatible solc & EVM Version combinations. I consider this a bug, but we'll fix this in another issue—we'll probably have to modify / upgrade the solc version of quite a few tests to properly fix this.
