### PR TITLE
fix: gas report threshold

### LINKED ISSUE #6019: Gas report unexpectedly omits some tests
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0722a1 2023-10-10T00:25:42.578508482Z)

### What command(s) is the bug in?

forge test --gas-report

### Operating System

Linux

### Describe the bug

The issue happens when running `forge test --gas-report` on the following file:
https://gist.github.com/QGarchery/b4399a96db810e95453713fca2d816e2

This produces the following ouput:
Screenshot from 2023-10-10 15-22-25

Notice the number of calls: only 1 call.

The gas report does not seem to take into account the test `testAggregateTwice`, which can be shown by running the same command again after having deleted this test (which produces the same output).

### PR DESCRIPTION
**Pull request by mattsse**
Closes #6019

ref #6129

refactors the gas reporter slightly.

also increases the diff matching used for matching contract codes

cc @mds1

### CODE REVIEW

File: crates/evm/traces/src/identifier/local.rs [hunk 1]
```diff
@@ -34,7 +34,10 @@ impl TraceIdentifier for LocalTraceIdentifier<'_> {
                     .iter()
                     .filter_map(|(id, (abi, known_code))| {
                         let score = diff_score(known_code, code);
-                        if score < 0.1 {
+                        // Note: the diff score can be inaccurate for small contracts so we're using
+                        // a relatively high threshold here to avoid filtering out too many
+                        // contracts.
+                        if score < 0.85 {
```
Comment (Evalir) [inline crates/evm/traces/src/identifier/local.rs:40]: super small nit, but maybe we can lift this to a constant and document it?

**Review by Evalir — APPROVED** [review]
nice! lgtm bar comment / mds testing!

File: crates/evm/traces/src/identifier/local.rs (hunk 1 above)
Comment (mattsse) [reply crates/evm/traces/src/identifier/local.rs:40]: I think that's fine here, I also think this entire logic deserves another look because we only do this to filter out candidates for decoding matches, the better approach would be to just get __all__ function selectors
