### PR TITLE
fix(fork): preserve block number and timestamp when changing fork

### LINKED ISSUE #8168: bug(`forge`): warp effect is reversed when switching back to original fork
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6179312 2024-06-10T00:18:46.177980000Z)

### What command(s) is the bug in?

forge script / forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

**Scenario**: two or more forks created using `vm.createFork` cheatcode
**Bug**: Use the `warp` cheatcode on fork `1` to move to a future timestamp, then switch to fork `2`, and finally switch back to fork `1`. The `block.timestamp` on fork `1` will be the block just before the warp. 

**Reproducing**: 

```solidity
pragma solidity 0.8.19;

import {console} from "@forge-std/console.sol";
import {Script} from "@forge-std/Script.sol";

import "@forge-std/Test.sol";

contract MultipleForksWarp is Script, Test {
    /// @notice fork ID for moonbeam
    uint256 public moonbeamForkId =
        vm.createFork(vm.envString("MOONBEAM_RPC_URL"));

    /// @notice fork ID for base
    uint256 public baseForkId = vm.createFork(vm.envString("BASE_RPC_URL"));

    function run() public {
        console.log("Moonbeam fork selected");
        vm.selectFork(moonbeamForkId);
        console.log("Timestamp: ", block.timestamp);

        vm.warp(block.timestamp + 1000);
        console.log("Timestamp after warp: ", block.timestamp);

        console.log("Switching to base fork");
        vm.selectFork(baseForkId);

        console.log("Back to moonbeam fork");
        vm.selectFork(moonbeamForkId);

        console.log("Timestamp: ", block.timestamp);
    }
}
```

```bash
Script ran successfully.
Gas used: 36285

== Logs ==
  Moonbeam fork selected
  Timestamp:  1718386092
  Timestamp after warp:  1718387092
  Switching to base fork
  Back to moonbeam fork
  Timestamp:  1718386092
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #8168 

Fork's block number and timestamp can be changed using `vm.warp` and `vm.roll` but they're not preserved in a multifork setup when a different fork is selected.

## Solution

- save current env block number and ts in active fork env

### CODE REVIEW

File: crates/evm/core/src/fork/multi.rs [hunk 1]
```diff
@@ -282,14 +294,23 @@ impl MultiForkHandler {
...
     }
 
+    /// Update fork block number and timestamp. Used to preserve values set by `roll` and `warp`
+    /// cheatcodes when new fork selected.
+    fn update_block(&mut self, fork_id: ForkId, block_number: U256, block_timestamp: U256) {
+        if let Some(fork) = self.forks.get_mut(&fork_id) {
+            fork.opts.env.block.number = block_number;
+            fork.opts.env.block.timestamp = block_timestamp;
+        }
+    }
```
Comment (mattsse) [inline crates/evm/core/src/fork/multi.rs:312]: I see, makes sense

**Review by mattsse — APPROVED** [review]
lgtm!
