### PR TITLE
fix(invariants): support `vm.assume` in invariant tests

### LINKED ISSUE #4190: feat: `vm.assume` support in invariant tests
### Component

Forge

### Describe the feature you would like

Invariant tests support this cheat, which I believe is because `assume` was added before invariant tests. There are two ways we should support:
- `vm.assume` directly in a `function invariant_MyInvariantTest()` method. Currently a failed assume here fails the test with `[FAIL. Reason: Assertion failed.]`. To be fair this usage is a bit limited since you can't make assumptions on fuzzed inputs, but still seems worthwhile to support
- `vm.assume` in a handler contract. This lets you reject e.g. owner addresses from a fuzzed owner input. I tried putting a quick test together and it seems these are just ignored since the cheat isn't being called in a test method

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

Closes #4190 

## Solution

Catch reverts with `MAGIC_ASSUME`, regenerate latest calldata and increase `assume_rejects_counter`. Once counter goes beyond configured `max_assume_rejects`, test fails.

I've changed `InvariantFuzzError` to be an enum, because we don't need data it holds right now for `MaxAssumeRejects` failures.

Also changed `invariant_strat` a bit, currently it always returns Vec with one element, it seemed a bit confusing at first glance, so I changed it to return just a single input.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm

File: crates/forge/src/runner.rs [hunk 1]
```diff
@@ -513,26 +513,28 @@ impl<'a> ContractRunner<'a> {
...
+                        &mut logs,
+                        &mut traces,
+                    ) {
+                        Ok(c) => counterexample = c,
+                        Err(err) => {
+                            error!(%err, "Failed to replay invariant error");
+                        }
+                    };
+                }
+                _ => {}
```
Comment (DaniPopes) [inline crates/forge/src/runner.rs:536]: Let's make this exhaustive

**Review by DaniPopes — APPROVED** [review]
