### PR TITLE
fix(test): make sure that tests are run by the same `setUp` caller

### LINKED ISSUE #3661: `msg.sender` different in setUp and tests
### Component

Forge, Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8b0af47 2022-11-05T15:13:14.009577258Z)

### What command(s) is the bug in?

forge test --match-test testSameSender -vv

### Operating System

_No response_

### Describe the bug

`msg.sender` value differs between the `setUp` function and the unit tests. Here is a minimal code to reproduce the issue:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import "forge-std/Test.sol";

contract TestMe is Test {
    address sender;

    function setUp() public {
        sender = msg.sender;
    }

    function testSameSender() public {
        assertEq(sender, msg.sender);
    }
}
```

### PR DESCRIPTION
**Pull request by joshieDo**
## Motivation

closes #3661

For `setUp` we're using `CALLER` but for calling the test function we're using `DEFAULT_SENDER` if the user hasn't provided a `FROM`.

## Solution
Make sure that the sender for the test function is the same as the one set here https://github.com/foundry-rs/foundry/pull/2084

Now, going out on a limb and I'm merging `CALLER` and `DEFAULT_SENDER` into one. Seems confusing having two default senders across contexts. Ended up choosing the one which has no transactions on any chain, but it breaks compatibility with dapptools...

### CODE REVIEW

**Comment by mds1** [comment]
> Seems confusing having two default senders across contexts. Ended up choosing the one which has no transactions on any chain, but it breaks compatibility with dapptools...

This seems reasonable to me. I think at this point it's probably ok to break compatibility with dapptools, but cc'ing @hexonaut to confirm first

**Comment by hexonaut** [comment]
I didn't even realize `msg.sender` was different between these. Maker doesn't use this anywhere to the best of my knowledge.

**Comment by gakonst** [comment]
@joshieDo Just need to fix tests, lgtm otherwise

**Review by mattsse — APPROVED** [review]
lgtm, 

need to add this to the book as well.

File: forge/tests/it/repros.rs [hunk 1]
```diff
@@ -183,12 +183,6 @@ fn test_issue_3347() {
     );
 }
 
-// <https://github.com/foundry-rs/foundry/issues/3616>
-#[test]
-fn test_issue_3616() {
-    test_repro!("Issue3616");
-}
-
```
Comment (joshieDo) [inline forge/tests/it/repros.rs:191]: no longer applicable since the test contract address is now different with no balance in any chain (0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f)
