### PR TITLE
fix: add safety check for auto-detected remappings

### LINKED ISSUE #1797: weird remapping `lib/=lib/` required in some codebases
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (54ec8e3 2022-05-31T00:04:13.132504939Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

In some codebases, an extra `lib/=lib/` remapping is required to overwrite what seems to be a wrong remapping introduced by forge

Example repo for reproduction: 
https://github.com/timeless-fi/swapper
Remove `lib/=lib/` from foundry.toml and run `forge build` to reproduce the error

**Initial investigation (by myself, may be off here)**

In the above example repo `forge remappings` will show `lib/=lib/timeless/src/lib/`, which seems to be the cause of the compilation issues.
Forge them seems to merge these default remappings with the ones from `remappings.txt`, which is why adding a weird `lib/=lib/` fixes the compilation, since it overwrites the default one

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #1797
Ref https://github.com/gakonst/ethers-rs/pull/1335

## Solution
prevents weird autodetected remappings named `lib` or `src`

### CODE REVIEW

File: config/src/lib.rs [hunk 1]
```diff
@@ -1771,6 +1771,10 @@ impl<'a> RemappingsProvider<'a> {
         // use auto detection for all libs
         for r in self.lib_paths.iter().map(|lib| self.root.join(lib)).flat_map(Remapping::find_many)
         {
+            // this is an additional safety check for weird auto-detected remappings
+            if ["lib/", "src/"].contains(&r.name.as_str()) {
```
Comment (naps62) [inline config/src/lib.rs:1775]: shouldn't it include `"contracts/" as well?

In the timeless-fi sample repo, `src/lib` existed. In my own private repo, I actually had `contracts/lib`

Comment (mattsse) [reply config/src/lib.rs:1775]: good point, adding `contracts/` as well

**Review by gakonst — APPROVED** [review]
Let's see how this goes - I think we're at the point where we should write up the algorithm for how we do everything: caching, relative/absolute path detection, remappings, filtering of the tree based on match test etc
