### PR TITLE
fix(evm): refactor executor & detect `setUp` assertion failures

### LINKED ISSUE #1291: failed assertions in `setUp` do not fail the test, even if the test fails
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (64087b5 2022-04-13T00:05:01.629608+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (amd)

### Describe the bug

The below test should fail for two reasons: First because the assertions in setup fail, and again because the assertion in `testSetUpFailure` fails. However `forge test -m testSetUpFailure` shows this test as passing

```solidity
contract SetUpFailureTest is DSTest {
  function setUp() public {
    assertTrue(false);
  }

  function testSetUpFailure() public {
    assertTrue(false);
  }
}

```

Below is a table of what currently happens for the four combinations you can have above, vs. what I'd expect to happen. You can see the problems are from when assertions in `setUp` fail. 

| setUp             | testSetUpFailure  | Current Test Result | Expected Test Result | Summary |
| ----------------- | ----------------- | ------------------- | -------------------- | ------- |
| `assertTrue(true)`  | `assertTrue(true) ` | PASS                | PASS                 | ✅       |
| `assertTrue(true)`  | `assertTrue(false)` | FAIL                | FAIL                 | ✅       |
| `assertTrue(false)` | `assertTrue(true)`  | PASS                | FAIL                 | ❌       |
| `assertTrue(false)` | `assertTrue(false)` | PASS                | FAIL                 | ❌       |

### PR DESCRIPTION
**Pull request by rkrasiuk**
close #1291

Refactoring according to @onbjerg's comment

> We can refactor Executor such that we only really have the call_raw/call variants that return state changesets - call_committing/call_raw_committing would then just be very thin wrappers around these that also call db.commit(changeset). This cleans up the executor code a bit, and seems like the right path forward. I think I did attempt this at some point, but there was some annoyances in some other parts of the code so I shelved it to get REVM over the line.

### CODE REVIEW

File: evm/src/executor/mod.rs [hunk 1]
```diff
@@ -385,26 +295,11 @@ impl Executor {
...
-            out,
-            gas_used,
-            gas_refunded,
-            state_changeset,
-            logs,
-            stipend,
-            env,
-        };
-        let call_result = convert_executed_call(inspector, executed_call)?;
+        // TODO: not used let logs = self.backend.merged_logs(logs);
```
Comment (rkrasiuk) [inline evm/src/executor/mod.rs:302]: @mattsse currently this call to `merged_logs` does nothing because the `logs` field is omitted in `convert_executed_result`. is that expected behavior and we can remove this call or should it be fixed?

**Comment by rkrasiuk** [comment]
rfr pending `merged_logs` resolution above

File: evm/src/executor/mod.rs (hunk 1 above)
Comment (mattsse) [reply evm/src/executor/mod.rs:302]: ah right, that makes sense, since we get the logs from the log inspector directly, so not required here and can be removed

File: evm/src/executor/mod.rs [hunk 2]
```diff
@@ -784,6 +701,10 @@ pub struct RawCallResult {
     pub script_wallets: Vec<LocalWallet>,
     /// The `revm::Env` after the call
     pub env: Env,
+    /// The cheatcode states after execution
+    pub cheatcodes: Option<Cheatcodes>,
```
Comment (mattsse) [inline evm/src/executor/mod.rs:705]: this is useful

File: evm/src/executor/mod.rs [hunk 3]
```diff
@@ -219,7 +219,32 @@ impl Executor {
...
+                        traces: res.traces.clone(),
+                        gas_used: res.gas_used,
+                        gas_refunded: res.gas_refunded,
+                        stipend: res.stipend,
+                        logs: res.logs.clone(),
+                        debug: res.debug.clone(),
+                        labels: res.labels.clone(),
+                        state_changeset: None,
+                        transactions: None,
+                        script_wallets: res.script_wallets.clone(),
```
Comment (mattsse) [inline evm/src/executor/mod.rs:242]: why do we need to clone everything here?

can't we just return here?

**Review by mattsse — CHANGES_REQUESTED** [review]
great changes,

smol question re error case

File: evm/src/executor/mod.rs (hunk 3 above)
Comment (rkrasiuk) [reply evm/src/executor/mod.rs:242]: yup, sry, was debugging smth and forgot to clean up

**Review by mattsse — APPROVED** [review]

**Review by gakonst — APPROVED** [review]
