### PR TITLE
fix: better artifacts management for `getCode`

### LINKED ISSUE #4876: Coverage report inconsistent
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e807429 2023-05-04T00:04:41.301525000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

## Description
- `forge coverage` report shows seemingly-accurate percentages of tested functions for some contract files, but 0% for one that clearly has functions tested: `src/ParachainRegistry.sol`. The relevant test file is `test/testParachainRegistry.t.sol`.
- To reproduce, run `forge coverage` for this repo [here](https://github.com/tellor-io/tellor-parachain-contracts).
- Example output that shows the behavior:
```console
>>> forge coverage
[⠆] Compiling...
[⠰] Compiling 30 files with 0.8.3
[⠑] Compiling 28 files with 0.8.17
[⠰] Solc 0.8.17 finished in 2.27s
[⠒] Solc 0.8.3 finished in 4.94s
Compiler run successful
Analysing contracts...
Running tests...
| File                        | % Lines           | % Statements      | % Branches       | % Funcs         |
|-----------------------------|-------------------|-------------------|------------------|-----------------|
| src/Parachain.sol           | 50.00% (44/88)    | 50.00% (64/128)   | 100.00% (0/0)    | 50.00% (12/24)  |
| src/ParachainGovernance.sol | 100.00% (114/114) | 100.00% (121/121) | 88.16% (67/76)   | 100.00% (10/10) |
| src/ParachainRegistry.sol   | 0.00% (0/28)      | 0.00% (0/30)      | 0.00% (0/4)      | 0.00% (0/12)    |
| src/ParachainStaking.sol    | 100.00% (89/89)   | 100.00% (95/95)   | 90.00% (45/50)   | 100.00% (11/11) |
| Total                       | 77.43% (247/319)  | 74.87% (280/374)  | 86.15% (112/130) | 57.89% (33/57)  |
```

Apologies if this is a duplicate issue, but I didn't see the specific case searching, or [here](https://github.com/foundry-rs/foundry/issues/1961#issuecomment-1427113699), but maybe related to [this one](https://github.com/foundry-rs/foundry/issues/3900).

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

Follow-up to #7661 extending usage of `ContractsByArtifact`

Closes #4876

## Solution

Rewrite `getCode` logic to directly use compilation artifacts instead of reading them from filesystem. This makes it possible to use `getCode` in tests which were compiled without writing artifacts (which is happening in coverage for example).

This also separates `known_contracts` per each test contract. This is needed because different test contracts might be linked with different libraries, thus having a single `known_contracts` object is incorrect and might result in invalid `getCode` output or identifiers failing to identify contracts. This introduces overhead of cloning compiler output for each running test which shouldn't affect performance much I believe.

Related to #1161 and #4049 but not resolves in full because `getCode` will now only work for linked contracts which only depend on subset of test contract libraries.

### CODE REVIEW

File: crates/forge/bin/cmd/coverage.rs [hunk 1]
```diff
@@ -313,22 +312,13 @@ impl CoverageArgs {
...
             .evm_spec(config.evm_spec_id())
             .sender(evm_opts.sender)
             .with_fork(evm_opts.get_fork(&config, env.clone()))
-            .with_cheats_config(CheatsConfig::new(
-                &config,
-                evm_opts.clone(),
-                Some(artifact_ids),
-                None,
-                None,
-            ))
```
Comment (mattsse) [inline crates/forge/bin/cmd/coverage.rs:331]: I see, this makes cheatsconfig redundant here

File: crates/forge/src/multi_runner.rs [hunk 2]
```diff
@@ -233,8 +241,8 @@ pub struct MultiContractRunnerBuilder {
     pub evm_spec: Option<SpecId>,
     /// The fork to use at launch
     pub fork: Option<CreateFork>,
-    /// Additional cheatcode inspector related settings derived from the `Config`
-    pub cheats_config: Option<CheatsConfig>,
+    /// Project config.
+    pub config: Config,
```
Comment (mattsse) [inline crates/forge/src/multi_runner.rs:245]: should this also be an Arc?

**Review by mattsse — APPROVED** [review]
> This also separates known_contracts per each test contract. This is needed because different test contracts might be linked with different libraries, thus having a single known_contracts object is incorrect and might result in invalid getCode output or identifiers failing to identify contracts. 

I see, this makes sense

> This introduces overhead of cloning compiler output for each running test which shouldn't affect performance much I believe.

this should be ok.

removing the cheatsconfig also makes sense to me


reasonable, I think artifact mgmt is a lot better now,

pending @DaniPopes

File: crates/common/src/contracts.rs [hunk 3]
```diff
@@ -32,6 +32,26 @@ type ArtifactWithContractRef<'a> = (&'a ArtifactId, &'a ContractData);
...
+                    let bytecode = artifact.bytecode.and_then(|b| b.into_bytes())?;
+                    let deployed_bytecode =
+                        artifact.deployed_bytecode.and_then(|b| b.into_bytes())?;
+                    let abi = artifact.abi?;
+
+                    Some((id, ContractData { name, abi, bytecode, deployed_bytecode }))
+                })
+                .collect(),
+        )
+    }
```
Comment (DaniPopes) [inline crates/common/src/contracts.rs:54]:
```suggestion
    }

```

**Review by DaniPopes — APPROVED** [review]
