### PR TITLE
fix(`anvil`): handle OP deposit txs in `TypedTransaction` and `PoolTransaction` conversion

### LINKED ISSUE #8940: Error using Anvil "--fork-transaction-hash" argument with Base chain
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a592f7a 2024-09-23T00:23:27.691802000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

Using anvil along with the "--fork-transaction-hash" argument for transactions on Base chain is failing. This is in contrast to "--fork-block-number" which works fine. 

Here is an example of the command with a sample Base transaction, assuming FORK_URL is a valid Base node:
```
TRANSACTION_HASH=0x969d8e40260a84ecbc65658772bc80bcea2a84e7c386fe636a9f171c1bd04c90
anvil --fork-url $FORK_URL --fork-transaction-hash $TRANSACTION_HASH
```

The output received is:
```
thread 'main' panicked at /Users/runner/work/foundry/foundry/crates/anvil/src/config.rs:1091:77:
Failed to derive fork block number and force transactions from fork choice: Unexpected type flag. Got 126.

Caused by:
    Unexpected type flag. Got 126.

Location:
    crates/anvil/src/eth/pool/transactions.rs:122:33
```

The transaction forked from is a type 2 transaction, not type 126, however the first transaction in every Base block is a system transaction of type 126. For example, for the sample transaction used above from block 20142328, the system transaction from this block is https://basescan.org/tx/0x054a5a5c33d73422605ea96da29f9e23dfbdfacbd707a1a88cdd8753d471f30b. It seems that there is an issue during forking with the replay of the system transactions.

Note that the transaction used here is just an example, and that the fork fails for any chosen Base transaction as well.

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Fixes #8940 

## Solution

Change `TryFrom` implementations of `PoolTransaction` and `TypedTransaction` to use `WithOtherFields<RpcTransaction>` instead of `RpcTransaction`

### CODE REVIEW

File: crates/anvil/core/src/eth/transaction/mod.rs [hunk 1]
```diff
@@ -1003,11 +1003,48 @@ impl TypedTransaction {
...
+        if tx.transaction_type.is_some_and(|t| t == 0x7E) {
+            let mint = tx
+                .other
+                .get("mint")
+                .ok_or(ConversionError::Custom("MissingMint".to_string()))
+                .cloned()
+                .map(|v| {
+                    serde_json::from_value::<U256>(v)
+                        .map_err(|_| ConversionError::Custom("Cannot deserialize mint".to_string()))
+                })?;
```
Comment (mattsse) [inline crates/anvil/core/src/eth/transaction/mod.rs:1019]: this is just get_deserialized ?

File: crates/anvil/core/src/eth/transaction/mod.rs [hunk 2]
```diff
@@ -1003,11 +1003,48 @@ impl TypedTransaction {
...
+            let source_hash = tx
+                .other
+                .get("sourceHash")
+                .ok_or(ConversionError::Custom("MissingSourceHash".to_string()))
+                .cloned()
+                .map(|v| {
+                    serde_json::from_value::<B256>(v).map_err(|_| {
+                        ConversionError::Custom("Cannot deserialize source hash".to_string())
+                    })
+                })?;
```
Comment (mattsse) [inline crates/anvil/core/src/eth/transaction/mod.rs:1030]: same

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
unrelated error
