### PR TITLE
fix(doc): reuse solar sema compiler

### LINKED ISSUE #11966: Last couple of weeks we have seen a litany of forge issues in our ci pipeline
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

1.4.0-nightly

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

forge lint, forge fmt --check, forge doc --build

### Operating System

Linux

### Describe the bug

3 bugs in last 2 weeks:
- `forge lint`: https://github.com/foundry-rs/foundry/issues/11668
- `forge fmt --check`: not using foundry.toml settings
- `forge doc --build`: 
```
thread '<unknown>' has overflowed its stack
fatal runtime error: stack overflow, aborting
```

These checks have been running for months without issues. Now they are failing from some recent foundry updates.

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #11966 
- include only fn sig in doc (`func.loc_prototype` no body) + add `;` at the end of sig to match prev behavior
- remove extra indent of 4 spaces to fix format issue as

image
image

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/doc/src/parser/item.rs [hunk 1]
```diff
@@ -81,7 +81,20 @@ impl ParseItem {
...
+        if let ParseSource::Function(_) = self.source {
+            code.push(';');
+        }
+
+        // Remove extra indent from docs.
+        self.code = code
+            .lines()
+            .map(|line| line.strip_prefix("    ").unwrap_or(line))
+            .collect::<Vec<_>>()
+            .join("\n");
```
Comment (0xrusowsky) [inline crates/doc/src/parser/item.rs]: i think that we should make this more robust.

what i'd like to see is the following logic:
1. get the source code from beginning of line to `self.source.range().start`
2. strip the indentation of this source code (should be an empty string or just indentation) from all lines


```solidity
function topLevel() public {
	// this needs 1 indentation level, none should be removed
}

contract TopLevel {
	function innerLevel() public {
		// this has 2 ind, 1 needs to be removed
	}
}
```

Comment (grandizzy) [reply crates/doc/src/parser/item.rs]: I changed the logic to remove only if starts with > 4 whitespaces (that is to proper format the free functions as in prev version), since we're going to remove solang anyways not sure if should spend more time on this, wdyt?

Comment (0xrusowsky) [reply crates/doc/src/parser/item.rs]: i think it is fine as a temp workaround as we need to drop the solang dep anyways.
once we do that, we can do it properly

**Review by 0xrusowsky — APPROVED** [review]

**Comment by 0xrusowsky** [comment]
let's wait for @DaniPopes to have a look before we merge

File: crates/doc/src/builder.rs [hunk 2]
```diff
@@ -124,135 +125,153 @@ impl DocBuilder {
...
+            let documents = combined_sources
+                .par_iter()
+                .enumerate()
+                .map(|(i, (path, from_library))| {
+                    let path = *path;
+                    let from_library = *from_library;
+                    let mut files = vec![];
+
+                    // Read and parse source file
+                    if let Some(ast) = gcx.sources.iter().find(|source| {
```
Comment (DaniPopes) [inline crates/doc/src/builder.rs]: gcx.get_ast_source

File: crates/doc/src/parser/item.rs [hunk 3]
```diff
@@ -81,7 +81,25 @@ impl ParseItem {
...
+        // Special function case, add `;` at the end of definition.
+        if let ParseSource::Function(_) = self.source {
+            code.push(';');
+        }
+
+        // Remove extra indent from source lines.
+        self.code = code
+            .lines()
+            .map(|line| {
+                if line.chars().take_while(|c| c.is_whitespace()).count() > 4 {
```
Comment (DaniPopes) [inline crates/doc/src/parser/item.rs]: I think you can just trim_start always

Comment (0xrusowsky) [reply crates/doc/src/parser/item.rs]: this is what he did initially, but that's inaccurate.

see the reasoning here: https://github.com/foundry-rs/foundry/pull/11980#discussion_r2405211333

Comment (grandizzy) [reply crates/doc/src/parser/item.rs]: indeed, however I just realized the count check should have been >= 4 so it didn't apply format properly, hence I am in favour of `trim_start` always, this affects only free functions which will be displayed as below but I don't think it's a biggie

image

Comment (grandizzy) [reply crates/doc/src/parser/item.rs]: https://github.com/foundry-rs/foundry/pull/11980/commits/e7aa1627e873b1e3c4ce42ed00f8a41bda1aaba3

File: crates/doc/src/builder.rs (hunk 2 above)
Comment (grandizzy) [reply crates/doc/src/builder.rs]: https://github.com/foundry-rs/foundry/pull/11980/commits/e7aa1627e873b1e3c4ce42ed00f8a41bda1aaba3

**Review by DaniPopes — APPROVED** [review]
