### PR TITLE
fix(cast): sign erc20 transactions locally before broadcast

### LINKED ISSUE #12368: `cast erc20 transfer` does not sign the tx
### Component

Cast

### Describe the bug

Using `cast erc20 transfer` the tx is not signed, instead it defers to the node, which is incorrect.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

closes #12368

## Solution

note: i moved the `sol!` macro with ERC20 out of cast + added a new helper `fn signing_provider` so that we can keep things organized if we add more token subcommands down the line.

## PR Checklist

- [ ] Added Tests
- [X] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/cast/src/cmd/erc20.rs [hunk 1]
```diff
@@ -112,60 +117,79 @@ pub enum Erc20Subcommand {
 }
 
 impl Erc20Subcommand {
-    pub async fn run(self) -> eyre::Result<()> {
+    // Helper to get the rpc and be able to de-duplicate code.
+    // Acceptable to match twice as performance is not critical in cast + there are few commands.
```
Comment (DaniPopes) [inline crates/cast/src/cmd/erc20.rs]: pls remove comment
