### PR TITLE
fix(chisel): Map PCs correctly if `run()` ends in a scoped block

### LINKED ISSUE #3964: bug(chisel): ending with an assembly block breaks (stack|mem)dump
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e9f274d 2022-12-12T00:04:24.380051Z)

### What command(s) is the bug in?

chisel

### Operating System

macOS (Apple Silicon)

### Describe the bug

If the last command is an assembly block, !sd/!md break with the error "Run function is empty."

Here's a simple repro case:

```solidity
λ chisel
Welcome to Chisel! Type `!help` to show available commands.
➜ uint test = 1;
➜ !sd
[0]: 0x01
[1]: 0x33
[2]: 0xc0406226
➜ assembly { test := 2 }
➜ !sd
⚒️ Chisel Error: Run function is empty.
➜ !source
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import {Cheats} from "forge-std/Vm.sol";

contract REPL {
    Cheats internal constant vm = Cheats(address(uint160(uint256(keccak256("hevm cheat code")))));

    /// @notice REPL contract entry point
    function run() public {
        uint256 test = 1;
        assembly {
            test := 2
        }
    }
}
```

### PR DESCRIPTION
**Pull request by clabby**
# Overview

Fixes an issue where chisel would not map the final statement's program counter correctly if the `run()` function ended in a scoped block (`assembly`, `unchecked`, or a regular `{}`)

## Motivation

@transmissions11 pointed out this bug in #3964 

## Solution

Chisel's `executor` uses solc's source map to map the REPL contract's source code to program counters within the deployed runtime code. Adds some extra logic that checks if the final statement of `run()` is a block of some kind, finds its last statement, and uses its source location to determine the program counter that the `ChiselInspector` should take a state snapshot at.

Screenshot from 2022-12-27 11-36-15

#### Meta

closes #3964

### CODE REVIEW

File: chisel/src/executor.rs [hunk 1]
```diff
@@ -40,8 +40,45 @@ impl SessionSource {
...
+                        if let Some(statement) = statements.last() {
+                            statement.loc()
+                        } else {
+                            // In the case where the block is empty, attempt to grab the statement
+                            // before the block. Because we use saturating sub to get the second to
+                            // last index, this can always be safely unwrapped.
+                            run_func_statements
+                                .get(run_func_statements.len().saturating_sub(2))
+                                .unwrap()
+                                .loc()
```
Comment (mattsse) [inline chisel/src/executor.rs:73]: duplication is fine here

**Review by mattsse — APPROVED** [review]
nice catch!
