### PR TITLE
fix: canonicalize script contract path

### LINKED ISSUE #2092: forge test --debug crashes: "Target not found?"
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7b9d3ad 2022-06-17T21:57:41.4016897Z)

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

I'm trying to debug a test for a contract using `forge test` but i can't do so for some reason, `forge debug` runs just fine:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Contract {
    uint256 public count = 0;

    function plus() public {
        count += 1;
    }
}
```

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import "src/Contract.sol";


contract ContractTest is Test {
    Contract c;
    
    function setUp() public {
        c = new Contract();
    }

    function testCount() public {
        assertEq(c.count(), 0);
        c.plus();
        assertEq(c.count(), 1);
    }
}
```

Trying to run: `forge test --debug "testCount"` gives me this:

```
C:\Users\proto\Desktop\foundry-play>forge test --debug testCount
[⠔] Compiling...
[⠊] Compiling 1 files with 0.8.15
[⠒] Solc 0.8.15 finished in 1.49s
Compiler run successful
[⠔] Compiling...
Nothing to compile
The application panicked (crashed).
Message:  Target not found?
Location: cli\src\cmd\forge\script\build.rs:163

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

while using `forge debug --debug test/Contract.t.sol --sig "testCount()"` works just fine, not sure if i am missing something here?

### PR DESCRIPTION
**Pull request by onbjerg**
Attempting to fix #2092 and #2085

### CODE REVIEW

**Comment by onbjerg** [comment]
@mattsse My best guess is that this is the issue, but I'm not sure how we test this. I don't have a Windows computer

File: cli/src/cmd/forge/script/build.rs [hunk 1]
```diff
@@ -135,7 +135,10 @@ impl ScriptArgs {
 
                 // if it's the target contract, grab the info
                 if extra.no_target_name {
-                    if id.source == std::path::Path::new(&extra.target_fname) {
+                    if id.source ==
+                        dunce::canonicalize(&extra.target_fname)
+                            .expect("Could not canonicalize target path")
```
Comment (mattsse) [inline cli/src/cmd/forge/script/build.rs:140]: looking at where this is originally created, looks like this is already `canonicalized`?

**Review by mattsse — COMMENTED** [review]
since this is a windows issue we probably compare paths but canonicalized windows paths are super annoying and don't necessarily match the solc output so we probably fail a comparison that would be true on UNIX...

on another note, this linking code is so horrendous, I would have rewritten this already if I understood what this even does lol
