### PR TITLE
fix: don't leak env parser error

### LINKED ISSUE #6374: forge dumps full private key out into the terminal if it can't parse it properly
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (529559c 2023-11-13T00:19:35.957961000Z)

### What command(s) is the bug in?

`forge script` etc.

### Operating System

macOS (Apple Silicon)

### Describe the bug

Would be nice if the private key was at least masked a little bit. I know there are probably times where it doesn't know what it's parsing, but when the env variable is called `PRIVATE_KEY` maybe there's a way.

### PR DESCRIPTION
**Pull request by mattsse**
Closes #6374

prevents leaking env value via `alloy::parser::Error`

### CODE REVIEW

**Review by Evalir — APPROVED** [review]

File: crates/cheatcodes/src/env.rs [hunk 1]
```diff
@@ -274,6 +277,26 @@ fn map_env_err(key: &str) -> impl FnOnce(Error) -> Error + '_ {
         } else {
             ": "
         };
+        // ensure we're also removing the value from the underlying alloy parser error message, See
+        // [alloy_dyn_abi::parser::Error::parser]
+        let e = e.replacen(&format!("\n{value}\n"), &format!("${key}"), 1);
```
Comment (DaniPopes) [inline crates/cheatcodes/src/env.rs:282]: Or remove from lhs

```suggestion
        let e = e.replacen(&format!("\n{value}\n"), &format!("\n${key}\n"), 1);
```

**Review by DaniPopes — CHANGES_REQUESTED** [review]
