### PR TITLE
[wip] feat: provider alloy migration

### LINKED ISSUE #5709: Gas estimation message for EIP1559 txs is extremely misleading
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1143e57 2023-08-24T00:28:32.561836000Z)

### What command(s) is the bug in?

forge script

### Operating System

None

### Describe the bug

--priority-gas-price was implemented in #5281 

My version of foundry is up to date. 

Expected behavior: when I use --priority-gas-price, it lowers my gas fee on deployment and doesn't use foundry's default 3 gwei tip. 

To reproduce, create a fresh repository and deploy. I ran the following command:

`forge script script/Counter.s.sol:CounterScript --priority-gas-price 100 --broadcast --slow --rpc-url optimism -vvvv`

This is the output:

```
Estimated gas price: 3.0000001 gwei

Estimated total gas used for script: 138734

Estimated amount required: 0.0004162020138734 ETH
```

Following the suggestion in #5281, I use `--legacy --with-gas-price`:

`forge script script/Counter.s.sol:CounterScript --legacy --with-gas-price 100 --broadcast --slow --rpc-url optimism -vvvv`

This is the output:

```
Chain 420

Estimated gas price: 0.0000001 gwei

Estimated total gas used for script: 138734

Estimated amount required: 0.0000000000138734 ETH
```

I have also tried by using the environment variable alias, it also doesn't work.

### LINKED ISSUE #7089: Overestimated gas prices for cheap chains
### Component

Forge

### Describe the bug

Mentioned in https://github.com/foundry-rs/foundry/issues/6503#issuecomment-1837648597 and https://github.com/foundry-rs/foundry/issues/4903#issuecomment-1620446076.

Currently, due to ethers internals being oriented on Mainnet, gas prices for scripts are often over-estimated to be around 3 gwei when the actually needed gas price might be  less than 1 gwei.

It can be reproduced by dry-running any script on any L2 via `forge script <SCRIPT_CONTRACT> --rpc-url <RPC_OF_L2>`

For Arbitrum the output will include
```
Estimated gas price: 3.2 gwei
```
And the estimation of required funds for execution will be calculated considering gas price being 3.2 as well, which is much higher than is actually needed and can result in script failing due to sender not having enough funds.

This is reproducible on Optimism, Base, Arbitrum and any other cheap chain I believe. Currently common workaround is to add `--legacy` flag to the command which helps avoiding priority fee calculation.

I am not sure what's the best way to fix this as it is possible that we might break some scenarios as for some L2s this overestimation helped avoiding situations when script sender does not have enough funds to cover additional L2 fees. For example, the actuall gas price on Base is around `0.000000315`, but usually most of tx cost is coming from L1 fees which are not included in the estimation currently

### LINKED ISSUE #7400: massive gas estimation when running `forge script` on base
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (545cd0b 2024-03-14T00:20:00.210934000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Blob storage was released today on Base, and I am using `forge script` to run a transaction through a new contract.

- [The forge-based tx](https://basescan.org/tx/0x607518b4a7ff312c17160e23a554aed3ee6920619e4e7009b7a571c54df7ad28)
- [What the tx should've cost](https://basescan.org/tx/0x879ed42f97027a78ad789be0d6bb02b455f370a95a6f4093209b303d6d891d59)

## Repro steps:
1. clone the repo off this pr / branch https://github.com/0xmetropolis/erc20/pull/3
2. run `export OWNER=rando_addr`
3. run `forge script script/DeployToken.s.sol --rpc-url https://mainnet.base.org`

### LINKED ISSUE #7486: Max Priority gas price does not work
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7545c7a2 2024-03-12T03:19:04.521042379Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

I use `forge script -v --priority-gas-price 0.05gwei --with-gas-price 20gwei`,  but the transaction will set the priority gas to 20GWEI. 

```
Gas Fees:
Base: 15.038300915 Gwei |Max: 20 Gwei |Max Priority: 20 Gwei
```

### PR DESCRIPTION
**Pull request by Evalir**
## Motivation

This migrates anvil, cast and most of the forge to use alloy providers and primitive types on all methods.

Closes #7486 
Closes #7400
Closes #5709
Closes #7089 

## Solution

- [x] `NameOrAddress` ENS support with CLI utility (#7122)

### CODE REVIEW

File: crates/cast/src/lib.rs [hunk 1]
```diff
@@ -759,9 +762,10 @@ where
     /// ```
     pub async fn rpc<T>(&self, method: &str, params: T) -> Result<String>
     where
-        T: std::fmt::Debug + serde::Serialize + Send + Sync,
+        T: std::fmt::Debug + serde::Serialize + Send + Sync + Clone,
     {
-        let res = self.provider.provider().request::<T, serde_json::Value>(method, params).await?;
+        let method = Box::new(method.to_string()).leak();
+        let res = self.alloy_provider.raw_request::<T, serde_json::Value>(method, params).await?;
```
Comment (gakonst) [inline crates/cast/src/lib.rs:768]: this seems weird, why are we box/leaking here?

File: crates/common/src/ens.rs [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+            NameOrAddress::Address(addr) => return Ok(*addr),
+        };
+        let node = namehash(&name);
+        let registry = EnsRegistry::new(ENS_ADDRESS, provider);
+        let resolver = registry
+            .resolver(node)
+            .call()
+            .await
+            .map_err(|err| EnsResolutionError::EnsRegistryResolutionFailed(err.to_string()))?
+            ._0;
```
Comment (gakonst) [inline crates/common/src/ens.rs:54]: why the `._0`? cc @DaniPopes

**Comment by klkvr** [comment]
Cast now compiles and ethers is almost gone.

We are still using it in 2 places:
1. [crates/cast/bin/cmd/logs.rs](https://github.com/foundry-rs/foundry/blob/evalir/cast-provider-mig/crates/cast/bin/cmd/logs.rs) - this still uses ethers types to prepare event filters from user-entered event signature and arguments. @DaniPopes does current state of alloy-json-abi and alloy-dyn-abi allow this?

     The flow is basically like this:
     1. Parse signature to extract types
     2. Parse entered values as extracted types (`DynSolValue`?)
     3. Encode and obtain hashes of indexed fields for filter (not sure if we have that)
2. [crates/cast/bin/cmd/bind.rs](https://github.com/foundry-rs/foundry/blob/evalir/cast-provider-mig/crates/cast/bin/cmd/bind.rs) - `cast bind` and `forge bind` should probably be deprecated?

There are still a lot of errors coming from various places. At the first glance most of them are coming from anvil due to alloy bump and changed transaction types. Will work on that next

cc @mattsse

**Comment by klkvr** [comment]
We now don't use ethers in anvil code except for tests.

Also its removed from foundry-wallets, forge-script and forge (except for `forge bind`).

Currently blocked by https://github.com/alloy-rs/alloy/pull/381 and https://github.com/alloy-rs/alloy/pull/361, will need bump of alloy in revm-inspectors once those are merged

**Comment by klkvr** [comment]
This mostly just changes types/trait bounds, but there are two flow changes:
1. Anvil now uses `Encodable2718` and `Decodable2718` for typed transactions.
2. Cast no more uses `TxBuilder` and instead uses alloy `TransactionRequest` which has `TransactionBuilder` trait implemented.

ethers and alloy now also use incompatible reqwest versions, so I've aliased ethers version as `reqwest_ethers` for `foundry-common` as a workaround for now

**Comment by klkvr** [comment]
revm 7.2 changed default used `HashMap` impl to the std `HashMap`: https://github.com/bluealloy/revm/pull/1042

This resuts in `CacheDb::accounts` not having deterministic order and breaks fuzz failure persistence (example CI run: https://github.com/foundry-rs/foundry/actions/runs/8452372534/job/23152599290)

For now I've implemented [this](https://github.com/foundry-rs/foundry/pull/7106/commits/c8781e5fc995833664c92645bf30fec44ed68b91) workaround which sorts addresses from db before adding them to dictionary  but not sure if this is the best approach here or if something else could break because of `HashMap` change

cc @mattsse @DaniPopes

File: crates/anvil/tests/it/fork.rs
Comment (mattsse) [inline crates/anvil/tests/it/fork.rs:1]: all of these tests can be migrated seprately

File: crates/cast/bin/cmd/access_list.rs [hunk 3]
```diff
@@ -59,54 +62,76 @@ impl AccessListArgs {
...
+            sender,
+            to,
+            sig,
+            args,
+            data,
+            tx,
+            chain,
+            block,
+            to_json,
+        )
```
Comment (mattsse) [inline crates/cast/bin/cmd/access_list.rs:87]: we also need to clean this up separetely

File: crates/cast/bin/opts.rs [hunk 4]
```diff
@@ -524,11 +525,11 @@ pub enum CastSubcommand {
         /// The block height to query at.
         ///
         /// Can also be the tags earliest, finalized, safe, latest, or pending.
-        #[arg(long, short = 'B')]
+        #[clap(long, short = 'B')]
```
Comment (mattsse) [inline crates/cast/bin/opts.rs:528]: these should be `arg(`

File: crates/common/src/ens.rs [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+        .resolver(node)
+        .call()
+        .await
+        .map_err(|err| EnsResolutionError::EnsRegistryResolutionFailed(err.to_string()))?
+        ._0;
+
+    Ok(EnsResolver::new(address, provider))
+}
+
+pub async fn resolve_name<N: Network, T: Transport + Clone, P: Provider<N, T>>(
```
Comment (mattsse) [inline crates/common/src/ens.rs:134]: can we use an extension trait for all these ens functions?

then we could move this to alloy in a followup

File: crates/common/src/provider/alloy.rs [hunk 6]
```diff
@@ -250,10 +255,10 @@ impl ProviderBuilder {
 ///   - polygon
 ///
 /// Fallback is the default [`Provider::estimate_eip1559_fees`] implementation
-pub async fn estimate_eip1559_fees<P: TempProvider>(
+pub async fn estimate_eip1559_fees<P: Provider<Ethereum, T>, T: Transport + Clone>(
```
Comment (mattsse) [inline crates/common/src/provider/alloy.rs:258]: I think we could solve this with a layer as well, but can simplify it separately.

**Review by mattsse — CHANGES_REQUESTED** [review]
hell yeah, one more milestone

only have a few suggestions,
this has potential for more small scope followups

File: clippy.toml [hunk 7]
```diff
@@ -1 +1,2 @@
 msrv = "1.76"
+ignore-interior-mutability = ["bytes::Bytes", "alloy_primitives::Bytes"]
```
Comment (DaniPopes) [inline clippy.toml:2]: Where is this used? You should use `static` instead of `const` to silence this warning

File: Cargo.toml [hunk 8]
```diff
@@ -28,7 +28,7 @@ resolver = "2"
 [workspace.package]
 version = "0.2.0"
 edition = "2021"
-rust-version = "1.76" # Remember to update clippy.toml as well
+rust-version = "1.76"                                       # Remember to update clippy.toml as well
```
Comment (DaniPopes) [inline Cargo.toml:31]: rm

File: crates/cast/bin/cmd/storage.rs [hunk 9]
```diff
@@ -226,18 +221,17 @@ async fn fetch_and_print_storage(
     }
 }
 
-async fn fetch_storage_slots(
-    provider: RetryProvider,
-    address: NameOrAddress,
+async fn fetch_storage_slots<P: Provider<Ethereum, T>, T: Transport + Clone>(
+    provider: P,
```
Comment (DaniPopes) [inline crates/cast/bin/cmd/storage.rs:225]: why don't we use a concrete provider type anymore?

File: crates/cast/bin/opts.rs (hunk 4 above)
Comment (DaniPopes) [reply crates/cast/bin/opts.rs:528]: Yeah, run `cargo check --features clap/deprecated`

File: crates/cheatcodes/src/fs.rs [hunk 10]
```diff
@@ -422,6 +422,8 @@ fn prompt(
 
 #[cfg(test)]
 mod tests {
+    use alloy_primitives::Bytes;
+
```
Comment (DaniPopes) [inline crates/cheatcodes/src/fs.rs:426]:
```suggestion
```

File: crates/cast/bin/cmd/storage.rs (hunk 9 above)
Comment (klkvr) [reply crates/cast/bin/cmd/storage.rs:225]: we can, this was already generic when I started working on this PR, should I change it back?

Comment (DaniPopes) [reply crates/cast/bin/cmd/storage.rs:225]: I see, that's fine then

File: crates/anvil/core/src/eth/transaction/mod.rs [hunk 11]
```diff
@@ -97,10 +98,10 @@ pub fn transaction_request_to_typed(tx: TransactionRequest) -> Option<TypedTrans
             }))
         }
         // EIP2930
-        (Some(1), _, None, None, _, None, None, None) |
-        (None, _, None, None, Some(_), None, None, None) => {
+        (Some(1), _, None, None, _, None, None, None, _) |
+        (None, _, None, None, Some(_), None, None, None, _) => {
```
Comment (DaniPopes) [inline crates/anvil/core/src/eth/transaction/mod.rs:102]: Can we reuse logic from alloy here somehow?

Comment (klkvr) [reply crates/anvil/core/src/eth/transaction/mod.rs:102]: We can probably, but we'd still have to treat `Deposit` tx case separately. In Reth we also have this logic duplicated I believe.

It's basically similar to `TransactionRequest` -> `TypedTransaction` conversion but here we're doing `unwrap_or_default` instead of throwing errors on missing fields, not sure why

Comment (mattsse) [reply crates/anvil/core/src/eth/transaction/mod.rs:102]: yeah this logic is very cursed -.-

we could use the TransactionRequest::build_signed here I think, if we use alloy-consensus types, we can check for OP deposit seperately

**Comment by klkvr** [comment]
Bumped alloy and changed Anvil receipt handling a bit to avoid operating on catch-all fields for them.

We now have concrete `DepositReceipt` struct for optimism deposit receipt which is used for encoding/decoding: https://github.com/foundry-rs/foundry/blob/879153abe777d0f7989ea5a5afff7cbac561ab3f/crates/anvil/core/src/eth/transaction/mod.rs#L996-L1001

The new `ReceiptResponse` alias for `TransactionReceipt<TypedReceipt>` is used where we need an receipt in RPC format:  https://github.com/foundry-rs/foundry/blob/879153abe777d0f7989ea5a5afff7cbac561ab3f/crates/anvil/core/src/eth/transaction/mod.rs#L1228

Currently anvil will fail to process external deposit receipts fetched from forked endpoint, this should be fixed with https://github.com/alloy-rs/alloy/pull/457 and after that we can switch `RetryProvider` to using `AnyNetwork` and decoding additional fields manually.

**Comment by bernard-wagner** [comment]
> Cast now compiles and ethers is almost gone.
> 
> We are still using it in 2 places:
> 
> 1. [crates/cast/bin/cmd/logs.rs](https://github.com/foundry-rs/foundry/blob/evalir/cast-provider-mig/crates/cast/bin/cmd/logs.rs) - this still uses ethers types to prepare event filters from user-entered event signature and arguments. @DaniPopes does current state of alloy-json-abi and alloy-dyn-abi allow this?
>    The flow is basically like this:
>    
>    1. Parse signature to extract types
>    2. Parse entered values as extracted types (`DynSolValue`?)
>    3. Encode and obtain hashes of indexed fields for filter (not sure if we have that)
> 2. [crates/cast/bin/cmd/bind.rs](https://github.com/foundry-rs/foundry/blob/evalir/cast-provider-mig/crates/cast/bin/cmd/bind.rs) - `cast bind` and `forge bind` should probably be deprecated?
> 
> There are still a lot of errors coming from various places. At the first glance most of them are coming from anvil due to alloy bump and changed transaction types. Will work on that next
> 
> cc @mattsse

I took a stab at migrating `cast logs` this is still very WIP but it seems feasible given the current state of `alloy`: 

https://github.com/bernard-wagner/foundry/commit/c9abc5c3d1d055e75885b7169f808e072c7e8862

I need to cover a bit more error handling. `foundry_common::abi::get_event` doesn't seem to be very strict and can contain invalid argument types.

Let me know if I should continue or if the team wants to take another approach.

File: clippy.toml (hunk 7 above)
Comment (DaniPopes) [reply clippy.toml:2]: This shouldn't be allowed in clippy, please use Vec<u8> instead then

Comment (DaniPopes) [reply clippy.toml:2]: Actually this is fine, bytes::Bytes is ignored by default as internal mutability is not exposed. Please add a note for this

Comment (klkvr) [reply clippy.toml:2]: discussed internally and keeping this as this lint is a false positive for `bytes::Bytes` and therefore alloy wrapper as well

per clippy doc:
> It’s correct to use a struct that contains interior mutability as a key, when its implementation of Hash or Ord doesn’t access any of the interior mutable types. However, this lint is unable to recognize this, so it will often cause false positives in theses cases. The bytes crate is a great example of this.

> `ignore-interior-mutability`: A list of paths to types that should be treated like Arc, i.e. ignored but for the generic parameters for determining interior mutability (default: ["bytes::Bytes"])

**Comment by klkvr** [comment]
blocked by deser issues, should be fixed by https://github.com/alloy-rs/alloy/pull/474

**Comment by DaniPopes** [comment]
https://github.com/alloy-rs/alloy/pull/474 is merged

File: crates/anvil/core/src/eth/transaction/mod.rs (hunk 11 above)
Comment (mattsse) [reply crates/anvil/core/src/eth/transaction/mod.rs:109]: we can do this but separately

**Review by mattsse — APPROVED** [review]
let's send it and do more incremental followups

**Comment by klkvr** [comment]
failing test unrelated I believe

**Comment by Evalir** [comment]
https://github.com/foundry-rs/foundry/pull/7594 needs to be merged into this before we merge this PR
