### PR TITLE
fix(cast): return logs in all cases

### LINKED ISSUE #7729: cast returns no log if block numbers are not provided or only a to-block is provided
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (79dd88c 2024-04-19T00:21:49.496222000Z)

### What command(s) is the bug in?

cast logs

### Operating System

None

## Current behavior

```bash
# Provide a from block AND a to block, logs are returned
cast logs 0x7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb3847402498 \
  --address 0x034edD2A225f7f429A63E0f1D2084B9E0A93b538 \
  --from-block 0 --to-block latest -r $SEPOLIA_RPC_URL

# Provide only a from block, logs are returned
cast logs 0x7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb3847402498 \
  --address 0x034edD2A225f7f429A63E0f1D2084B9E0A93b538 \
  --from-block 0 -r $SEPOLIA_RPC_URL

# Provide only a to block, no logs are returned
cast logs 0x7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb3847402498 \
  --address 0x034edD2A225f7f429A63E0f1D2084B9E0A93b538 \
  --to-block latest -r $SEPOLIA_RPC_URL

# Provide no from or to block, no logs are returned
cast logs 0x7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb3847402498 \
  --address 0x034edD2A225f7f429A63E0f1D2084B9E0A93b538 \
  -r $SEPOLIA_RPC_URL
```

## Expected Behavior

All cases should return the same set of logs, by defaulting to block 0 if no from block is provided, and defaulting to latest when no to block is provided

### PR DESCRIPTION
**Pull request by kamuik16**
Closes #7729

### CODE REVIEW

File: crates/cast/bin/cmd/logs.rs [hunk 1]
```diff
@@ -81,8 +81,17 @@ impl LogsArgs {
             None => None,
         };
 
-        let from_block = cast.convert_block_number(from_block).await?;
-        let to_block = cast.convert_block_number(to_block).await?;
+        let from_block = if let Some(_) = from_block {
```
Comment (DaniPopes) [inline crates/cast/bin/cmd/logs.rs:84]:
```rust
let from_block = cast. ... (Some(from_block.unwrap_or_else(BlockId::earliest)));
let to_block = cast. ... (Some(to_block.unwrap_or_else(BlockId::latest)));
```

Comment (kamuik16) [reply crates/cast/bin/cmd/logs.rs]: > ```rust
> let from_block = cast. ... (Some(from_block.unwrap_or_else(BlockId::earliest)));
> let to_block = cast. ... (Some(to_block.unwrap_or_else(BlockId::latest)));
> ```

done!

**Review by mattsse — APPROVED** [review]
