### PR TITLE
fix(cast): auto fetch chain id in cast call

### LINKED ISSUE #1522: `cast call` does not automatically use correct chain id
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8478c08 2022-05-05T00:11:43.429171710+00:00)

### What command(s) is the bug in?

cast call

### Operating System

Linux

### Describe the bug

`cast call` does not automatically fetch chain id. When creating an instance of `TxBuilder` on line 200 of `cli/src/cast.rs`, the chain is passed in from the environment variable. This means if you want to use etherscan to infer the function signature and haven't explicitly set the chain, it will fail due to it using the wrong etherscan endpoint.

`cast send` doesn't even bother to allow the chain to be passed in via env variable, and simply calls the provider to get this information. I think this is probably the better behavior since it reduces the amount of configuration required.

I'm working on a fix now for this now, but please let me know if there is a better solution, and I'd be happy to adjust.

### PR DESCRIPTION
**Pull request by ncitron**
## Motivation
Fixes #1522 

## Solution
Automatically fetch the chain id in `cast call` instead of relying on an environment variable.

### CODE REVIEW

File: cli/src/cast.rs [hunk 1]
```diff
@@ -195,8 +195,11 @@ async fn main() -> eyre::Result<()> {
                 config.eth_rpc_url.unwrap_or_else(|| "http://localhost:8545".to_string()),
             )?;
 
+            let chain_id = provider.get_chainid().await?;
+            let chain = Chain::try_from(chain_id.as_u64())?;
+
             let mut builder =
-                TxBuilder::new(&provider, config.sender, address, eth.chain, false).await?;
+                TxBuilder::new(&provider, config.sender, address, chain, false).await?;
```
Comment (onbjerg) [inline cli/src/cast.rs:202]: Maybe instead of failing here we should turn it into an `Option` and fall back on `eth.chain`?

Comment (ncitron) [reply cli/src/cast.rs:202]: Fall back in case of what? All providers must implement `eth_chainId` so that shouldn't fail. Or are you thinking that `Chain::try_from` could fail?

Comment (onbjerg) [reply cli/src/cast.rs:202]: Yeah, I think `Chain::try_from` could fail

Comment (ncitron) [reply cli/src/cast.rs]: Yeah I think your right. Someone might be using a chain that isn't yet in the mapping, and we wouldn't want that to brick it. Just pushed a change.

**Review by mattsse — APPROVED** [review]
thanks
