### PR TITLE
fix(anvil): keep local changes separate when flushing forked state

### LINKED ISSUE #1531: Anvil: Fork cache is dirtied by local state changes
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (bab38d6 2022-05-06T00:07:49.001076+00:00)

### What command(s) is the bug in?

anvil

### Operating System

macOS (amd)

### Describe the bug

When running `anvil` in forking mode, the ForkCache persists local state changes. 

Although this is an awesome feature on its own and I would really like to see this behaviour maintained as a flag, this behaviour is not what is expected when starting and stopping the node in fork mode. Only the remote state should be cached.

# Steps to reproduce

### Start Anvil

```
anvil --fork-url $ALCHEMY_URL --fork-block-number 14723772 -vvvvv
```

### Query Balance

```
cast balance 0x000000000000000000000000000000000000dEaD
12556104082473169733500
```

### Modify state

```
cast send --rpc-url http://localhost:8545 -f 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 0x000000000000000000000000000000000000dEaD --value 123456789012345

blockHash               0xd2e1ed0dca82c62676e84336ecb6e70e52ef05b8ab96ca714deb078be8384919
blockNumber             14723773
contractAddress         
cumulativeGasUsed       0
effectiveGasPrice       4000000000
gasUsed                 21000
logs                    []
logsBloom               0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root                    
status                  1
transactionHash         0xb69864e7a741807a8ce3da0c34d7b91338a7d0e4708b5f4f1dcf1964d76e7963
transactionIndex        0
type         
```

### Query Balance (Updated)

```
cast balance 0x000000000000000000000000000000000000dEaD
12556104205929958745845
```

### Restart Anvil

```
anvil --fork-url $ALCHEMY_URL --fork-block-number 14723772 -vvvvv
```

### Query Balance (change persisted)
```
cast balance 0x000000000000000000000000000000000000dEaD
12556104205929958745845
```

### Wipe cache
```
rm -rf ~/.foundry/cache/mainnet/14723772
```

### Start Anvil

```
anvil --fork-url $ALCHEMY_URL --fork-block-number 14723772 -vvvvv
```

### Query Balance (Reverted)
```
cast balance 0x000000000000000000000000000000000000dEaD
12556104082473169733500
```

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #1531

## Solution
* separate local and remote state
* don't commit changes to db that holds remote state
* only flush remote change

### CODE REVIEW

File: anvil/src/eth/backend/mem/fork_db.rs [hunk 1]
```diff
@@ -118,49 +137,50 @@ impl ForkedDatabase {
 
 impl Database for ForkedDatabase {
     fn basic(&mut self, address: Address) -> AccountInfo {
-        self.backend.basic(address)
+        self.cache_db.basic(address)
```
Comment (gakonst) [inline anvil/src/eth/backend/mem/fork_db.rs:140]: Should we add a test to ensure this is implemented correctly? Eg same one as the one in the issue?

**Review by gakonst — APPROVED** [review]

File: anvil/src/eth/backend/mem/fork_db.rs (hunk 1 above)
Comment (mattsse) [reply anvil/src/eth/backend/mem/fork_db.rs:145]: added test for scenario #1531 which ensures that modifications don't end up in the database that will be flushed to cache file
