### PR TITLE
fix(cast): apply contract code size limit in cast run

### LINKED ISSUE #11365: Transaction failed but cast run shows it succeeds
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

1.2.3-stable

### What version of Foundryup are you on?

1.3.0

### What command(s) is the bug in?

forge script script/DeployVaultOnly.s.sol:DeployVaultOnly   --rpc-url http://localhost:8545   --private-key $PRIVATE_KEY  --code-size-limit 100000 --broadcast -vvvv

### Operating System

Linux

### Describe the bug

I have a fork branch of gmx: 

`git clone https://github.com/sdajklfw389/my-gmx-fork.git` 

I wanted to make a local gmx chain and do some testing. But there is one failure when trying to deploy the Vault contract, which is relatively big, so i set the code size limit to a large number.

The script I run are:

`source scripts/setup_local.sh`

and

```
forge script script/DeployVaultOnly.s.sol:DeployVaultOnly   --rpc-url http://localhost:8545   --private-key $PRIVATE_KEY  --code-size-limit 100000 --broadcast -vvvv
```
DeployVaultOnly.s.sol is a file where I deploy the Vault contract only, in order to analyze why this specific contract failed to deploy.

so the output of forge script command is here:

```
forge script script/DeployVaultOnly.s.sol:DeployVaultOnly   --rpc-url http://localhost:8545   --private-key $PRIVATE_KEY  --code-size-limit 100000 --broadcast -vvvv
[⠊] Compiling...
No files changed, compilation skipped
Warning: Detected artifacts built from source files that no longer exist. Run `forge clean` to make sure builds are in sync with project files.
 - /home/jls/Documents/LMU_SS25/BugHunt/GMX/gmx-contracts/test/Counter.t.sol
Traces:
  [5286859] DeployVaultOnly::run()
    ├─ [0] VM::startBroadcast(<pk>)
    │   └─ ← [Return]
    ├─ [0] console::log("=== Deploying Vault Contract Only ===") [staticcall]
    │   └─ ← [Stop]
    ├─ [5238883] → new Vault@0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
    │   └─ ← [Return] 24827 bytes of code
    ├─ [0] console::log("Vault deployed at:", Vault: [0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512]) [staticcall]
    │   └─ ← [Stop]
    ├─ [0] VM::stopBroadcast()
    │   └─ ← [Return]
    ├─ [0] console::log("=== Vault Deployment Complete ===") [staticcall]
    │   └─ ← [Stop]
    └─ ← [Stop]


Script ran successfully.

== Logs ==
  === Deploying Vault Contract Only ===
  Vault deployed at: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
  === Vault Deployment Complete ===

## Setting up 1 EVM.
==========================
Simulated On-chain Traces:

  [5238883] → new Vault@0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
    └─ ← [Return] 24827 bytes of code


==========================

Chain 31337

Estimated gas price: 2.000000001 gwei

Estimated total gas used for script: 7390230

Estimated amount required: 0.01478046000739023 ETH

==========================

##### anvil-hardhat
❌  [Failed] Hash: 0xb4cd54d0e4c549e2ee899a6f8aef88e4bb55be58ee34fe1f4f8606ffc0286bee
Block: 2
Paid: 0.0064664513978046 ETH (7390230 gas * 0.87500002 gwei)


Transactions saved to: /home/jls/Documents/LMU_SS25/BugHunt/GMX/gmx-contracts/broadcast/DeployVaultOnly.s.sol/31337/run-latest.json

Sensitive values saved to: /home/jls/Documents/LMU_SS25/BugHunt/GMX/gmx-contracts/cache/DeployVaultOnly.s.sol/31337/run-latest.json

Error: Transaction Failure: 0xb4cd54d0e4c549e2ee899a6f8aef88e4bb55be58ee34fe1f4f8606ffc0286bee
```

In order to incept the exact error, I run:

```
cast run 0xb4cd54d0e4c549e2ee899a6f8aef88e4bb55be58ee34fe1f4f8606ffc0286bee
Executing previous transactions from the block.
Traces:
  [5238883] → new <unknown>@0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
    └─ ← [Return] 24827 bytes of code


Transaction successfully executed.
Gas used: 5684793
```

So it shows that the transaction is actually successful.

Then I run another command:

```
cast receipt 0xb4cd54d0e4c549e
2ee899a6f8aef88e4bb55be58ee34fe1f4f8606ffc0286bee

blockHash            0xd7fb80670e02a4f1b08238caf7c2a48c9372a588d12cc038538c3dc82a7f7af1
blockNumber          2
contractAddress      
cumulativeGasUsed    7390230
effectiveGasPrice    875000020
from                 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
gasUsed              7390230
logs                 []
logsBloom            0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root                 
status               0 (failed)
transactionHash      0xb4cd54d0e4c549e2ee899a6f8aef88e4bb55be58ee34fe1f4f8606ffc0286bee
transactionIndex     0
type                 2
blobGasPrice         1
blobGasUsed   
```

which shows the status is "failed".

So I am actually very confused. But it looks like there are two "GasUsed": 
one is "Gas used: 5684793" from cast run
the other one is "gasUsed              7390230" from cast receipt.

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #11365 
- `cast run` use `usize::MAX` as contract limit, hence a failed tx will pass when replayed (https://github.com/foundry-rs/foundry/issues/11365#issuecomment-3212997422)
- fixed by resetting contract code size for `cast run`

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/cast/src/cmd/run.rs [hunk 1]
```diff
@@ -162,6 +162,7 @@ impl RunArgs {
         let mut evm_version = self.evm_version;
 
         env.evm_env.cfg_env.disable_block_gas_limit = self.disable_block_gas_limit;
+        env.evm_env.cfg_env.limit_contract_code_size = None;
```
Comment (grandizzy) [inline crates/cast/src/cmd/run.rs:165]: unclear if we should do this for cast run only here or in `configure_env` here
https://github.com/foundry-rs/foundry/blob/6071d59dc5b1d9d411822fe92f4182d204a10e00/crates/evm/core/src/fork/init.rs#L88
CC @zerosnacks

**Review by mattsse — APPROVED** [review]
here definitely, because I think these are initialized differently

this is fine here because we need to enforce the actual rules when replaying blocks, this could perhaps be an issue on networks that dont enforce this but we can relax once that gets reported
