### PR TITLE
fix(fmt): filter libs when recursing

### LINKED ISSUE #12118: bug(fmt): fmt should not format lib srcs
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

v1.4.1

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

forge fmt .

### Operating System

None

### Describe the bug

ref https://t.me/foundry_support/65117 `forge fmt .` should not recurse in lib src

```bash
~/work/foundry-issues$ forge init fmt-lib --commit
~/work/foundry-issues$ cd fmt-lib
~/work/foundry-issues/fmt-lib$ forge fmt .
Formatted ~/work/foundry-issues/fmt-lib/lib/forge-std/src/interfaces/IERC7540.sol
Formatted ~/work//foundry-issues/fmt-lib/lib/forge-std/src/StdJson.sol
Formatted ~/work//foundry-issues/fmt-lib/lib/forge-std/src/interfaces/IMulticall3.sol
Formatted ~/work//foundry-issues/fmt-lib/lib/forge-std/src/StdToml.sol
Formatted ~/work//foundry-issues/fmt-lib/lib/forge-std/src/StdAssertions.sol
Formatted ~/work//foundry-issues/fmt-lib/lib/forge-std/test/StdStorage.t.sol
Formatted ~/work//foundry-issues/fmt-lib/lib/forge-std/src/Vm.sol
Formatted ~/work/foundry-issues/fmt-lib/lib/forge-std/src/StdConfig.sol
Formatted ~/work//foundry-issues/fmt-lib/lib/forge-std/src/console.sol
```

### PR DESCRIPTION
**Pull request by 0xrusowsky**
## Motivation

closes #12118

## Solution

when the input path requires discovery (i.e. `.`, or `lib/.`) check if it is a lib path. If it is not, ignore libs.

## PR Checklist

- [X] Added Tests
- [X] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/forge/tests/cli/fmt.rs [hunk 1]
```diff
@@ -24,6 +24,16 @@ contract Test {
 }
 "#;
 
+forgetest_init!(fmt_exclude_libs_in_recursion, |prj, cmd| {
+    prj.wipe_contracts();
```
Comment (grandizzy) [inline crates/forge/tests/cli/fmt.rs:28]: can we add a test for a `src/ignored` dir too?

**Review by grandizzy — APPROVED** [review]
lgtm
