### PR TITLE
fix(forge): enable fail fast flag

### LINKED ISSUE #6529: bug: `--fail-fast` flag does not work
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (13af418 2023-12-05T00:21:30.568484000Z)

### What command(s) is the bug in?

forge test --fail-fast

### Operating System

None

### Describe the bug

Running `FOUNDRY_FUZZ_RUNS=100000 forge test --fail-fast` on the below code should run `test_Increment` and `testFuzz_SetNumber` in parallel, and fail `test_Increment` should fail immediately. However, `forge test` does not fail and exist until all 100,000 fuzz runs complete

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console2} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";

contract CounterTest is Test {
    Counter public counter;

    function setUp() public {
        counter = new Counter();
        counter.setNumber(0);
    }

    function test_Increment() public {
        assertTrue(false);
    }

    function testFuzz_SetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
}
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #6529 

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

File: crates/forge/src/runner.rs [hunk 1]
```diff
@@ -279,7 +279,7 @@ impl<'a> ContractRunner<'a> {
     }
 
     /// Runs all tests for a contract whose names match the provided regular expression
-    pub fn run_tests(mut self, filter: &dyn TestFilter) -> SuiteResult {
+    pub fn run_tests(mut self, filter: &dyn TestFilter, fail_fast: &FailFast) -> SuiteResult {
```
Comment (DaniPopes) [inline crates/forge/src/runner.rs]: can we set this in self? it can also be cloned just fine

File: crates/forge/src/multi_runner.rs [hunk 2]
```diff
@@ -168,6 +168,7 @@ impl MultiContractRunner {
         filter: &dyn TestFilter,
         tx: mpsc::Sender<(String, SuiteResult)>,
         show_progress: bool,
+        fail_fast: bool,
```
Comment (DaniPopes) [inline crates/forge/src/multi_runner.rs]: set in self / tcfg instead?

Comment (grandizzy) [reply crates/forge/src/multi_runner.rs]: set in https://github.com/foundry-rs/foundry/pull/11328/commits/9d610914bdd40910671ac591a53083022f5dc322

File: crates/forge/src/runner.rs (hunk 1 above)
Comment (grandizzy) [reply crates/forge/src/runner.rs]: set in https://github.com/foundry-rs/foundry/pull/11328/commits/9d610914bdd40910671ac591a53083022f5dc322
