### PR TITLE
Fix mean on empty arrays

### LINKED ISSUE #2611: Mean is panicking on empty arrays
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b0575e 2022-08-04T00:04:01.463358166Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

In [calc.rs#L12](/foundry-rs/foundry/tree/master/common/src/calc.rs#L12), this fix should be applied:

```diff
pub fn mean<T>(values: &[T]) -> U256
where
    T: Into<U256> + Copy,
{
-    values.iter().copied().fold(U256::zero(), |sum, val| sum + val.into()) / values.len();
+    let len = values.len();
+    if len > 0 {
+        values.iter().copied().fold(U256::zero(), |sum, val| sum + val.into()) / len
+    } else {
+        U256::zero()
+    }
}
```

### PR DESCRIPTION
**Pull request by Rubilmax**
## Motivation

The gas report of my test suite is panicking when providing `FOUNDRY_FUZZ_RUNS=0`, because it's computing the mean of an empty array (`&func.calls`)

## Solution

Check if the array is empty in `calc::mean`

- Closes #2611

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
lgtm :smile: let's add a small test to ensure we don't break it?

also welcome to github, thanks for submitting your first pr ever to foundry :partying_face:

File: common/src/calc.rs [hunk 1]
```diff
@@ -9,7 +9,12 @@ pub fn mean<T>(values: &[T]) -> U256
 where
     T: Into<U256> + Copy,
 {
-    values.iter().copied().fold(U256::zero(), |sum, val| sum + val.into()) / values.len()
+    let len = values.len();
+    if len > 0 {
+        values.iter().copied().fold(U256::zero(), |sum, val| sum + val.into()) / len
+    } else {
+        U256::zero()
+    }
```
Comment (mattsse) [inline common/src/calc.rs:17]: I'd prefer 

```rust
if values.is_empty() {
  return U256::zero()
}

```

here

**Review by mattsse — CHANGES_REQUESTED** [review]
thanks,

smol style nit

**Comment by Rubilmax** [comment]
> lgtm 😄 let's add a small test to ensure we don't break it?
> 
> also welcome to github, thanks for submitting your first pr ever to foundry 🥳

Ahah, I'm learning Rust
Currently it seems there are no tests for calc (or I can't find them?)
It may take me a while before adding such a test, but I may succeed

**Comment by onbjerg** [comment]
@Rubilmax the tests are in the `test` module in the file itself at the bottom:

https://github.com/foundry-rs/foundry/blob/50d73f75cf554cdd86913602697e05a9201e534f/common/src/calc.rs#L38-L64

The `#[cfg(test)]` attribute means that the module is only compiled during tests - the `#[test]` attribute on each function in there marks the function as a test :smile: Let me know if you need some help building the test

More in the Rust book: https://doc.rust-lang.org/book/ch11-01-writing-tests.html

**Comment by Rubilmax** [comment]
> @Rubilmax the tests are in the `test` module in the file itself at the bottom:
> 
> https://github.com/foundry-rs/foundry/blob/50d73f75cf554cdd86913602697e05a9201e534f/common/src/calc.rs#L38-L64
> 
> The `#[cfg(test)]` attribute means that the module is only compiled during tests - the `#[test]` attribute on each function in there marks the function as a test 😄 Let me know if you need some help building the test
> 
> More in the Rust book: https://doc.rust-lang.org/book/ch11-01-writing-tests.html
> 
> Edit: You can basically just copy one of the tests and pass in an empty array

Thank you, done!

**Review by gakonst — APPROVED** [review]
