### PR TITLE
fix(`anvil`): set `storage.best_number` correctly

### LINKED ISSUE #9053: bug(`anvil`): `nonce too low` after anvil restarts with state
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8905af3 2024-10-07T03:18:50.978938000Z)

### What command(s) is the bug in?

_No response_

### Operating System

macOS (Apple Silicon)

### Describe the bug

Steps to reproduce the bug:

1. `anvil  -f https://eth.llamarpc.com  --chain-id 31337 --state anvil-state` where `anvil-state` is an empty directory.
2. `cast send 0x9276449EaC5b4f7Bc17cFC6700f7BeeB86F9bCd0 --value "1 ether" --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://127.0.0.1:8545`
3. `cast balance 0x9276449EaC5b4f7Bc17cFC6700f7BeeB86F9bCd0 --rpc-url http://127.0.0.1:8545` shows corect balance

Now restart anvil with the same command.

5. `cast balance 0x9276449EaC5b4f7Bc17cFC6700f7BeeB86F9bCd0 --rpc-url http://127.0.0.1:8545` shows 0 balance. **This should show the same balance as before** since it loads the dumped state.
6. `cast send 0x9276449EaC5b4f7Bc17cFC6700f7BeeB86F9bCd0 --value "1 ether" --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://127.0.0.1:8545` says:

`server returned an error response: error code -32003: nonce too low`

### PR DESCRIPTION
**Pull request by yash-atreya**
## Motivation

Closes #9053 + Closes https://github.com/foundry-rs/foundry/issues/8493

This arises when `--fork-url` and `--load-state` are used together.

## Solution

- ~Introduce `account_at` in `ForkedStorage` which stores the state of accounts at specific block numbers.~
- ~Populate `account_at` using the provided state file.~ 

Solution is a lot simpler.

- We are correctly loading the data to the db: https://github.com/foundry-rs/foundry/blob/4012adefd376bd618d1348398c1da07224d2dace/crates/anvil/src/eth/backend/mem/mod.rs#L925
- However, the `storage.best_number` i.e head of the chain is not correctly set when `--load-state` is used with `--fork-url`. We continue to set `storage.best_number = state.block.number` which is incorrect as the `best_number` should be `fork_block_number`. 
- This issue is observed when `fork_block_number` > `state.block_number`. In this case while all state data has been correctly loaded to the db, we fetch via the provider due to this check. https://github.com/foundry-rs/foundry/blob/4012adefd376bd618d1348398c1da07224d2dace/crates/anvil/src/eth/api.rs#L683
- Setting `storage.best_number = fork_block_number` fixes this

- [x] Test

### CODE REVIEW

**Comment by grandizzy** [comment]
@yash-atreya I added a test here, basically dumping state from gh issue and reloading / make sure balance properly retrieved, feel free to include in PR if OK

https://github.com/foundry-rs/foundry/compare/yash/load-forked-state...grandizzy:test-for-9215

**Comment by yash-atreya** [comment]
> @yash-atreya I added a test here, basically dumping state locally from gh issue recreate and reloading / make sure balance properly retrieved, feel free to include in PR if OK
> 
> [yash/load-forked-state...grandizzy:test-for-9215](https://github.com/foundry-rs/foundry/compare/yash/load-forked-state...grandizzy:test-for-9215)

@grandizzy thanks for this. 

I've added a more comprehensive test. ptal.

**Comment by grandizzy** [comment]
@yash-atreya I suspect this is supposed to close https://github.com/foundry-rs/foundry/issues/8493 too? If so, could you please update description to include it? thank you

File: crates/anvil/src/eth/backend/mem/mod.rs [hunk 1]
```diff
@@ -907,19 +907,27 @@ impl Backend {
...
-                self.blockchain.storage.read().hash(best_number.into()).ok_or_else(|| {
-                    BlockchainError::RpcError(RpcError::internal_error_with(format!(
-                        "Best hash not found for best number {best_number}",
-                    )))
-                })?;
-
-            self.blockchain.storage.write().best_hash = best_hash;
+            if let Some((number, hash)) = fork_num_and_hash {
+                // If loading state file on a fork, set best number to the fork block number.
+                // Ref:
```
Comment (grandizzy) [inline crates/anvil/src/eth/backend/mem/mod.rs:914]: did you want to include ref to a gh issue here?

**Review by grandizzy — APPROVED** [review]
lgtm!

**Review by mattsse — APPROVED** [review]

**Review by zerosnacks — APPROVED** [review]
