### PR TITLE
fix/refactor(cast): strip struct prefix and make interface a cmd

### LINKED ISSUE #2722: `cast interface` from ABI doubles the `struct` keyword in output file from './out/' input file
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e71033d 2022-08-11T13:39:22.281674Z)

### What command(s) is the bug in?

cast interface -n IMyfile -o contracts/interfaces/IMyfile.sol ./out/Myfile.sol/Myfile.json

### Operating System

macOS (Apple Silicon)

### Describe the bug

```sol
struct Bid {
    address a;
    address b;
    address c;
    address d;
    uint256 e;
}
```
in the main contract `MyFile.sol` becomes in the interface

fe6f5bf1aa4185e069dc7b612d206eb6

after I `cast interface` on the ABI of `'./out/Myfile.sol/Myfile.json`

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #2722

## Solution
* turn `Interface` variant into a standalone command
* fix duplicate `struct ` prefix

### CODE REVIEW

File: utils/src/lib.rs [hunk 1]
```diff
@@ -632,7 +634,7 @@ pub fn abi_to_solidity(contract_abi: &Abi, mut contract_name: &str) -> Result<St
     };
 
     // instantiate an array of all ABI Encoder v2 structs
-    let mut structs = HashSet::new();
+    let mut structs = BTreeSet::new();
```
Comment (gakonst) [inline utils/src/lib.rs:637]: Do we do btreeset so that order is preserved?

**Review by gakonst — APPROVED** [review]

File: utils/src/lib.rs (hunk 1 above)
Comment (mattsse) [reply utils/src/lib.rs:637]: yes, so structs are also sorted

https://github.com/foundry-rs/foundry/blob/9fb4450a6d8f056f32b68a8153c6e7f0e0dbd45a/testdata/fixtures/SolidityGeneration/WithStructs.sol#L24-L27
