### PR TITLE
fix(fmt): correct indentation for closing brace in empty contracts with comments

### LINKED ISSUE #13315: forge fmt: block with comment + empty line triggers extra indentation
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.5.1-stable Commit SHA: b0a9dd9ceda36f63e2326ce530c10e6916f4b8a2 Build Timestamp: 2025-12-22T11:41:09.812070000Z (1766403669) Build Profile: maxperf

### What version of Foundryup are you on?

foundryup: 1.5.0

### What command(s) is the bug in?

forge fmt

### Operating System

MacOS

### Describe the bug

If you have a block with a comment + empty line it causes subsequent lines to be indented incorrectly:

```solidity
pragma solidity ^0.8.0;

contract ProofOfConcept {
    // some comment

    }
```

### PR DESCRIPTION
**Pull request by Himess**
- Added `CommentEmptyLine` test case in testdata
- Added unit test `test_comment_empty_line_bug`
- All existing formatter tests pass

Fixes #13315

### CODE REVIEW

File: crates/fmt/src/state/sol.rs [hunk 1]
```diff
@@ -406,8 +406,11 @@ impl<'ast> State<'_, 'ast> {
             // restore block depth
             self.block_depth -= 1;
         } else {
-            if self.print_comments(span.hi(), CommentConfig::skip_ws()).is_some() {
```
Comment (onbjerg) [inline crates/fmt/src/state/sol.rs:409]: nit: no need to split this out into a variable

**Comment by Himess** [comment]
@onbjerg Done.
Could you re-run CI ?
