### PR TITLE
fix(inspect): add flag to strip ir comments

### LINKED ISSUE #9822: bug: `forge inspect` output broken for `ir` and `irOptimized`
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge Version: 1.0.0-nightly Commit SHA: 60f0b692acae47a4933bb4a0bc4a29cab8831ba1 Build Timestamp: 2025-02-02T00:22:16.408407000Z (1738455736) Build Profile: maxperf

### What version of Foundryup are you on?

_No response_

### What command(s) is the bug in?

forge inspect .. irOptimized

### Operating System

None

### Describe the bug

output of "forge inspect" is broken - lines seem to be broken, with unaligned parenthesis.
also, all comments were stripped off

```
$ forge clone 0x0000000071727de22e5e9d8baf0edac6f37da032 .
$ forge inspect EntryPoint irOptimized |grep -C 2  let._14.:=.64
                    if iszero(_13)
                    {
                        let _14 := 64)
                        mstore(_14, 15382879430798280032274949015962546692963007421274584931219521726781440655360)
                        mstore( var_opIndex)
```

(this is just one example - there is a huge # of those in the generated output)

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- closes #9822 
- regression introduced when `--pretty` flag was removed
- added flag `-s/--strip-yul-comments` to strip comments from `inspect ir / irMinimum` output

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by zerosnacks — APPROVED** [review]

**Comment by DaniPopes** [comment]
There's a reason for it to exist: https://github.com/foundry-rs/foundry/pull/8272
So I would try to fix it instead of removing it.

**Comment by grandizzy** [comment]
> There's a reason for it to exist: #8272 So I would try to fix it instead of removing it.
> 

Thanks, wasn't aware. There's not a fix per se but the expectation to preserve comments if no flag passed (not valid since pretty output was made default).

> Also why I don't understand the --pretty removal considering not all "ugly" output is JSON

Yep, not sure what would be the best way to handle it, should we add a new flag to preserve comments and keep default abd json as it is (and was for `--pretty`)? Wdyt? Cc @zerosnacks @yash-atreya

**Comment by grandizzy** [comment]
I added the new flag `-s/--strip-yul-comments` to strip comments from `inspect ir / irMinimum` output please rereview. thank you!

File: crates/forge/bin/cmd/inspect.rs [hunk 1]
```diff
@@ -532,15 +536,19 @@ fn print_json_str(obj: &impl serde::Serialize, key: Option<&str>) -> Result<()>
...
 }
 
-fn print_yul(yul: Option<&str>) -> Result<()> {
+fn print_yul(yul: Option<&str>, strip_comments: bool) -> Result<()> {
     let Some(yul) = yul else {
         eyre::bail!("Could not get IR output");
     };
 
     static YUL_COMMENTS: LazyLock<Regex> =
         LazyLock::new(|| Regex::new(r"(///.*\n\s*)|(\s*/\*\*.*\*/)").unwrap());
```
Comment (DaniPopes) [inline crates/forge/bin/cmd/inspect.rs:545]: This should also fix the regex

```suggestion
        LazyLock::new(|| Regex::new(r"(///.*\n\s*)|(\s*/\*\*.*?\*/)").unwrap());
```

**Review by DaniPopes — APPROVED** [review]
