### PR TITLE
fix(cast): block opt

### LINKED ISSUE #4584: `cast age` shouldn't require `--block` option
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

cast age

### Operating System

Linux

### Describe the bug

As per https://github.com/foundry-rs/book/pull/851, the documentation in the foundry book provides examples for `cast age` where the `--block` option is omitted:

```
$ cast age latest
```
or
```
$ cast age 1
```

This is not actually working at the moment as `cast age` requires the `--block` argument.
I decided to fix the docs accordingly, @mattsse confirmed this is rather a bug in `cast age` command (https://github.com/foundry-rs/book/pull/851#discussion_r1139371890).

`cast age` should work without the `--block` option as shown in the examples above.

### PR DESCRIPTION
**Pull request by 0xYYY**
## Motivation
1. Remove the requirement to specify `--block` for `cast basefee` and `case age`. (Both only depend on the block argument besides rpc opts). Closes #4584.
2. Unify and improve help text for the `block` argument. Add `finalized` and `safe` tag in help text.
3. Make `block` argument optional for `cast block` and default to `latest` following other commands.

### CODE REVIEW

File: common/src/selectors.rs [hunk 1]
```diff
@@ -333,7 +333,7 @@ impl fmt::Display for PossibleSigs {
         writeln!(f, " ------------")?;
         for (i, row) in self.data.iter().enumerate() {
             let row_label_decimal = i * 32;
-            let row_label_hex = format!("{:03x}", row_label_decimal);
+            let row_label_hex = format!("{row_label_decimal:03x}");
```
Comment (0xYYY) [inline common/src/selectors.rs:336]: clippy

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
there's a failing `cast block` test.

**Comment by 0xYYY** [comment]
> there's a failing `cast block` test.
looking into it

File: cli/src/opts/cast.rs [hunk 2]
```diff
@@ -285,12 +285,14 @@ Examples:
...
-            long_help = "The block height you want to query at. Can also be the tags earliest, latest, or pending.",
+            long_help = "The block height you want to query at. Can also be the tags earliest, finalized, safe, latest, or pending.",
             value_name = "BLOCK"
         )]
-        block: BlockId,
+        block: Option<BlockId>,
 
         #[clap(
+            long,
+            short = 'f',
```
Comment (mattsse) [inline cli/src/opts/cast.rs:295]: this is a breaking change.

is this necessary for this PR?

**Review by mattsse — CHANGES_REQUESTED** [review]

File: cli/src/opts/cast.rs (hunk 2 above)
Comment (0xYYY) [reply cli/src/opts/cast.rs:295]: based on my understanding of the [comment](https://github.com/foundry-rs/book/pull/851#discussion_r1139371477) that started the original issue, commands that query the info of the block itself (which requires only the `BlockId` as input) should take `block` as an (optional) argument, instead of an option, and default to `latest` if not specified, e.g. `cast age` and `cast basefee`

imho, `cast block` also falls in that category (querying the info of the block itself), so we should follow those 2 commands and make `block` an optional argument. but then changing `field` to be an option is required to avoid ambiguity (having 2 optional arguments, `block` and `field`). (also, "semantic" wise, `cast block [BLOCK] -f <FIELD>`  seems more reasonable to me then the current `cast block <BLOCK> [FIELD]`, since `field`  is just for filtering the block info output)

please let me know what you think and your suggestion on this

Comment (mattsse) [reply cli/src/opts/cast.rs:295]: thank you for this,

this makes sense. 

so this is now necessary because block is now optional and defaults to latest?

I agree

> cast block [BLOCK] -f <FIELD>

is the best syntax, do we need to update the book reference?

Comment (0xYYY) [reply cli/src/opts/cast.rs:295]: > so this is now necessary because block is now optional and defaults to latest?

yes

> do we need to update the book reference?

i'll update the book reference accordingly once this pr is set to be merged

**Review by mattsse — APPROVED** [review]
